vector/build.gradle
vector/src/main/java/im/vector/riotredesign/core/utils/DebouncedClickListener.kt
vector/src/main/java/im/vector/riotredesign/core/utils/DimensionUtils.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/BaseEventItem.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/MessageInformationData.kt
vector/src/main/java/im/vector/riotredesign/features/media/ImageContentRenderer.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/widget/CircleView.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/widget/DotsView.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/widget/ReactionButton.kt
vector/src/main/res/drawable/rounded_rect_shape.xml
vector/src/main/res/drawable/rounded_rect_shape_off.xml
vector/src/main/res/layout/item_timeline_event_base.xml
vector/src/main/res/layout/reaction_button.xml
vector/src/main/res/values/styles_riot.xml
vector/src/main/res/values/values.xml

Fixes #115
- Reaction Button Bellow the message
- Upgrade to constraint layout 2.0.0 beta (for Constraint Helpers / Flow)
- Added tap on member name action
- Cleaning
Known Limitations: As per phase 1, only support 8 reactions maximum below cell

Reactions: Display existing reactions below the message

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/SendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/SendRelationWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimeline.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailActions.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageActionsBottomSheet.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/QuickReactionFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/QuickReactionViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/EmojiChooserViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/EmojiReactionPickerActivity.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/EmojiRecyclerAdapter.kt
vector/src/main/java/im/vector/riotredesign/features/reactions/ReactionClickListener.kt

Fixes #114 
Fixes #116 
Adding Ability to send reaction via quick react and picker + increment existing
Known Limitations:
- Can only add reaction (not possible to undo/remove existing)
- Quick reaction is only adding (e.g. if you disagree a previously agreed event, app will not undo old and add new)
- Not using the new send_relation API as not available (code created but not tested), uses the regular send event
- No Optimistic update. Intermediate states e.g. currently sending reaction not handled perfectly (might experience delay) -> Optimistic send in phase 2
+ fix / Error when to many reactions in cells (more than placeholders -8-)
+ fix / DefaultTimeline quick map access was not shifted when items inserted at given index (reaction was added to wrong message)

Send reaction view quick react and picker

---

matrix-sdk-android/build.gradle
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/session/room/timeline/TimelineTest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/EditAggregatedSummary.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/ReactionAggregatedSummary.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/EventAnnotationsSummaryMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/EditAggregatedSummaryEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/ReactionAggregatedSummaryEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/EventEntityQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/EventRelationsAggregationTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/EventRelationsAggregationUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/prune/EventsPruner.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/prune/PruneEventTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/SendRelationWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/RedactEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/SendEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TimelineSendEventWorkCommon.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TokenChunkEventPersistor.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncModule.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/MessageInformationData.kt

Fixes #149
New reactions are immediately reflected in the UI, the created summary keeps track of 'unsynced' events used to build the summary (updated on reception of remote echo). UX use this information to disable the correct reaction button while not synced.
Same for edits. Edits can be stacked (even in offline mode), they will be sent one by one as soon as network is back.
Redacts are reflected as soon as done thanks to local echo (No detection of local vs remote echo, the remote echo will also prune the event, but it's ok)
+ Refactoring: Aggregation Update is implemented as a live event listener (using DB as SSoT)

Local echo for reactions/edits/redacts

---

vector/src/main/java/im/vector/riotredesign/VectorApplication.kt
vector/src/main/java/im/vector/riotredesign/core/utils/Emoji.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/ViewReactionViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/util/MessageInformationDataFactory.kt

Fixes #191 
Existing regex used by riot (from legacy riot android) are incomplete. 
Haven't found some easy way to detect if a string is exactly an emoji.
But as we already have a dictionary of emoji, the json source file of emoji picker, i have been able to use it

Only show reactions with an emoji key

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/SecretStoringUtils.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/AuthModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/Helper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/RealmKeysUtils.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/Hash.kt
vector/src/main/java/im/vector/riotredesign/features/notifications/NotificationDrawerManager.kt

Add encryption for realm databases (auth / session / crypto).
On creation a random key is generated, this key is then encrypted using the system KeyStore.
The encrypted key is stored in shared preferences.
When the database is opened again, the encrypted key is taken from the shared pref, then the Keystore is used to decrypt the key. The decrypted key is passed to the RealConfiguration.
On android >=M, the KeyStore generates an AES key to encrypt/decrypt the database key, and the encrypted key is stored with the initialization vector in base64 in the shared pref.
On android <M, the KeyStore cannot create AES keys, so a public/private key pair is generated, then we generate a random secret key. The database key is encrypted with the secret key; The secret key is encrypted with the public …

Encrypt Realm databases

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/CryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/timeline/TimelineEvent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/NewSessionListener.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/RoomDecryptorProvider.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/IMXCryptoStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimeline.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimelineService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TimelineEventFactory.kt

Added mechanism to detect when a new key is received in order to refresh current timeline.
How to:
Enter encrypted room on phone, go to other account where a key share popup appears then verify device 
-> Before: you had to exit then enter the room to see devcrypted event
-> Now: Timeline will be refreshed with clear content

Update timeline on new session

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/read/DefaultReadService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/read/SetReadMarkersTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/helper/TimelineEventVisibilityStateChangedListener.kt

Send read markers for collapsed events (rooms ending with unread collapsed state events will always stays on home)
Remove un-needed check on eventID format when sending read receipt. 
Added warning log when event is a local echo
Fixes #181

Fix / send read marker for collapsed items

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/EventRelationsAggregationTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/EventRelationsAggregationUpdater.kt

Regression due to update of event state to sending. Reaction updated was only checking that state was UNSENT to see if event is local echo.
-> Now we just check the eventID to see if local echo instead of checking state
Example log with bug:
```
DefaultEventRelationsAggregationTask: Reaction local.352593da-d636-4aa2-96e0-3da1ccbd721b relates to $15620633861083705gPnpk:matrix.org
DefaultEventRelationsAggregationTask: Adding synced reaction 😢
```

Fix / sometime sent reaction is count twice

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/CryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
vector/src/main/java/im/vector/riotx/core/di/ActiveSessionHolder.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysrequest/KeyRequestHandler.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt

Moved management of incoming Verification / Key  Requests to the active session holder.
Fix cases when incoming verification was not coming on first launch, and also delayed room.key ?

Moved incoming key/verif to active session holder

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncResponseHandler.kt

The crypto manager was started after room sync was handled, causing the start command to be far away in the queue of commands in the crypto thread

Start crypto manager before handling first sync events

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncResponseHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncThread.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncWorker.kt

Fix / Concurrent syncs
Start initial sync then enters foreground, if a push is received the SyncWorker is started and will start another initial sync (token null)
-> Now worker use the same sync task as sync thread on the task executor queue

Fix / Push worker could launch concurrent syncs

---

CHANGES.md
vector/src/main/res/values/theme_black.xml
vector/src/main/res/values/theme_dark.xml

Fix / composer separator color was using a clear theme color

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/Session.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncThread.kt
vector/src/main/java/im/vector/riotx/core/extensions/Session.kt

Fixes #376
Upon reception of a push, if the session is instantiated the sync thread was starting to loop (causing the app to permanently sync in background -until eventually killed by system-)

Fix / SyncThread was started in background

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultSasVerificationService.kt

I have mostly changed `CoroutineScope(coroutineDispatchers.*).launch` to `GlobalScope.launch(coroutineDispatchers.*)`, they effectively do the same thing but the latter uses one less allocation and is a bit clearer imo. (`CoroutineScope`s should not be manually constructed if they are not going to be explicitly cancelled or joined, `GlobalScope` was made for this).
Changed a *private* callback function to a suspend function.
Also, replaced some `TextUtils` usages with the Kotlin equivalents as the Kotlin equivalents support contracts and reduce the need for `!!`s.

Some more kotlinification.

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt

Plain text reply fallback should be prefixed with "> " not ">" (as per spec).
I am just doing this blind off github, I thought it was more useful to open a PR for a single character change than an issue!
Signed Off By Stuart Mumford <stuart@cadair.com>

Fix reply fallback prefix

---

vector/build.gradle

- Automatic "-dev" suffix to version name for non-master branch.
- VersionCode is now based on timestamp only for develop branch. For other branches, it's based on application version.

Automatic "-dev" version suffix on non master branch

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomMessageTouchHelperCallback.kt

Slide-in reply icon is distorted

---

CHANGES.md
vector/build.gradle
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ReactionInfoSimpleItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ViewReactionBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ViewReactionViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ViewReactionsEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/util/MessageInformationDataFactory.kt
vector/src/main/java/im/vector/riotx/features/reactions/widget/ReactionButton.kt
vector/src/main/res/layout/reaction_button.xml

Fixes #307 
There is still an issue due to font & compatibility
As the reactions widget was supposed to display only reaction, they use the emoji font, but this font displays spaces in a strange way (like 3 times bigger in some devices, and 0 in others)
-> We probably need to move to EmojiCompat (will replace emojis with Spans inside the text), but it's a bigger task (side effects on emoji picker?)

Accept non unicode reactions

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/media/VideoContentRenderer.kt
vector/src/main/res/layout/activity_video_media_viewer.xml

VideoView fails to play some remote uri video on some device. For now video is downloaded locally in internal cache then played. 
This offers basic support before full media preview implementation

Some video won't play

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/readreceipts/DisplayReadReceiptsBottomSheet.kt
vector/src/main/res/drawable/pill_receipt_black.xml
vector/src/main/res/drawable/pill_receipt_dark.xml
vector/src/main/res/drawable/pill_receipt_light.xml
vector/src/main/res/layout/item_display_read_receipt.xml
vector/src/main/res/layout/item_simple_reaction_info.xml
vector/src/main/res/layout/view_read_receipts.xml
vector/src/main/res/values/attrs.xml
vector/src/main/res/values/strings_riotX.xml
vector/src/main/res/values/styles_riot.xml
vector/src/main/res/values/theme_black.xml
vector/src/main/res/values/theme_dark.xml
vector/src/main/res/values/theme_light.xml

Improve read receipt design

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/NoticeEventFormatter.kt

Before:
After:
Riot-Android uses the stateKey first, but I think it's better to use the mxid.

Fix rendering issue of accepted third party invitation event

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/timeline/TimelineEvent.kt
vector/src/gplay/java/im/vector/riotx/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/riotx/features/notifications/InviteNotifiableEvent.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableEvent.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableEventResolver.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableMessageEvent.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/riotx/features/notifications/SimpleNotifiableEvent.kt

Edition of an event will replace the notification, if it is still displayed in the notification drawer.
Test with 2 successive edition below:
Before the code change:
After the code change:
Edition of an event not displayed in the notification drawer does not display a new notification.
Fixes #128

Message Editing: Update notifications (#128)

---

CHANGES.md
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxRoom.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/Room.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/RoomSummary.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/DraftService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/UserDraft.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/DraftMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/RoomSummaryMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/DraftEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/RoomSummaryEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/SessionRealmModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/UserDraftsEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/UserDraftsEntityQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoom.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/draft/DefaultDraftService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
vector/build.gradle
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailActions.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListDisplayModeFilter.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryItemFactory.kt
vector/src/main/res/layout/item_room.xml

Fixes #329 
Feature: save the composer content as a draft, for each room.
The implementation is indeed a persistence of the SendMode in DB, with some specific rules. A new DraftService is added to the SDK.
Draft are saved each time the composer text is updating (to be robust to random crash), with a 100ms debouncing.
When editing an event, a new draft is created, which means we can start editing multiple event without loosing anything. When editing, close the edit composer cancel the draft and the previous draft is restored.
Reply/Quote/Regular move shares the same draft, which means user can start typing text, then choose to quote another message or reply to another message with keeping the text entered in the composer.
Also, the room list displays a badge for rooms containing some draft …

Save draft of a message when exiting a room with non empty composer (#329)

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/group/model/GroupSummary.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/GroupSummaryMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/GroupEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/GroupSummaryEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/GroupEntityQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/GroupSummaryEntityQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/group/DefaultGetGroupDataTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/group/GroupSummaryUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/GroupSyncHandler.kt
vector/src/fdroid/java/im/vector/riotx/fdroid/service/VectorSyncService.kt
vector/src/main/java/im/vector/riotx/features/home/group/GroupListViewModel.kt

Fixes #497 
When a user leave a group (from another client), the group is removed from the list of group. Tested OK.
Also hide group invitations, they are not managed for the moment (so -2 TODOs and #569).
Also add a few documentation on the group management by the SDK

Handle left group from sync

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/ui/views/ReadReceiptsView.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginFragment.kt
vector/src/main/java/im/vector/riotx/features/reactions/EmojiReactionPickerActivity.kt
vector/src/main/java/im/vector/riotx/features/reactions/EmojiRecyclerAdapter.kt
vector/src/main/res/layout/fragment_login.xml
vector/src/main/res/layout/fragment_room_detail.xml
vector/src/main/res/layout/merge_composer_layout.xml
vector/src/main/res/layout/view_read_receipts.xml
vector/src/main/res/values/strings_riotX.xml

I'm using RiotX with a screen reader for a few months and I'm tweaking it a bit to make it more accessible to screen reader users.
I have noticed you have added some accessibility related improvements recently too. In fact I did some things very similar to you.
By knowing this I have rebased my stuff over your recent accessibility related work and here is the result.
The big features for screen reader users are better accessibility of read receipts and access to reactions emoji chooser.

more a11y tweaks

---

matrix-sdk-android/build.gradle
vector/build.gradle

As reported in RiotX room: https://matrix.to/#/!tTIucwUZLRtKnXeurb:matrix.org/$157064645582hLwbg:pvagner.tk?via=matrix.org&via=feneas.org&via=privacytools.io
Unfortunately, it does not fix the issue of reading only the date on a message cell. We have to investigate more on this one. FTR, room cells are correctly read (title, date, and last message).
Also minor upgrade of some other libs

Upgrade RecyclerView version to fix issues with a11y.

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/helper/ChunkEntityHelper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/EventMapper.kt

Fix bug when some messages in encrypted rooms appears as malformed events
(rageshake 6356)
The issue is that the event mapper persists the clear type as the type in DB, leading to an event with a clear type m.room.message but with an encrypted content.
Not sure what lead to this case as the sync handler does not decrypt before persisting, but it might be possible that the in memory event is modified by another 'task' before the persisting occurs?(Event is not immutable)

Fix / event mapper persist the clear type in type

---

vector/src/main/java/im/vector/riotx/AppStateHandler.kt
vector/src/main/java/im/vector/riotx/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListModule.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewModelFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/riotx/features/share/IncomingShareActivity.kt
vector/src/main/java/im/vector/riotx/features/share/IncomingShareViewModel.kt
vector/src/main/java/im/vector/riotx/features/share/ShareRoomListObservableStore.kt

The filter was not working.
The room list displayed was depending on the current selected community. In the future we may add a way to change community, but for now we display the full room list.

Fix 2 issues with share Activity: filter and room lists

---

CHANGES.md
vector/src/main/res/layout/view_attachment_type_selector.xml

better presentation for file type selector buttons to screen reader users
It would be even better if we could add on click handler and contentDescription to the parent linear layout encapsulating both image and text. But I'd rather did minimal changes as I can't predict visual appearance changing it that way.
Signed-off-by: Peter Vágner <pvdeejay@gmail.com>

a11y: file type selector

---

tools/import_from_riot.sh
vector/src/main/java/im/vector/riotx/features/settings/VectorLocale.kt
vector/src/main/res/values-sr/strings.xml

There is no possibility to switch language from RiotX yet, but this PR ensure that the code is up to date with Riot-android code.
Mainly importing change from https://github.com/vector-im/riot-android/pull/3364
Also add missing language.

Support Cyrillic script

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/utils/UrlUtils.kt
vector/src/main/java/im/vector/riotx/features/command/Command.kt
vector/src/main/java/im/vector/riotx/features/command/CommandParser.kt
vector/src/main/java/im/vector/riotx/features/command/ParsedCommand.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt
vector/src/main/java/im/vector/riotx/features/html/EventHtmlRenderer.kt
vector/src/main/java/im/vector/riotx/features/html/SpanHandler.kt
vector/src/main/java/im/vector/riotx/features/html/SpoilerSpan.kt
vector/src/main/res/values/attrs.xml
vector/src/main/res/values/strings.xml
vector/src/main/res/values/theme_dark.xml
vector/src/main/res/values/theme_light.xml

Supports custom html spoiler tag
https://github.com/matrix-org/matrix-doc/pull/2010
```
"content": {
"body": "Hey [Spoiler for movie](mxc://someserver/somefile)",
"format": "org.matrix.custom.html",
"formatted_body": “Also, <span data-mx-spoiler=\"movie\">Dumbledore dies, not only that, but Snape killed him! And they had planned the whole thing! </span>",
"msgtype": "m.text"
}
```

Support spoilers in messages

---

vector/src/main/java/im/vector/riotx/core/epoxy/HelpFooterItem.kt
vector/src/main/java/im/vector/riotx/core/resources/UserPreferencesProvider.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/res/drawable/ic_idea.xml
vector/src/main/res/layout/item_help_footer.xml
vector/src/main/res/values/strings_riotX.xml

Display a small help, at the bottom of the list.
The help is not displayed anymore once the user has perform a long click on a room

Add help to reveal the long click on a room

---

.idea/dictionaries/bmarty.xml
CHANGES.md
vector/src/main/java/im/vector/riotx/core/error/ErrorFormatter.kt
vector/src/main/res/values/strings_riotX.xml

Fixes #754 
Authorize email domain list cannot be retrieved from config.json file

Email domain can be limited on some homeserver, i18n of the displayed error (#754)

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/Room.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/RoomSummary.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/typing/TypingService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/RoomSummaryMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/RoomSummaryEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoom.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomSummaryUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/typing/DefaultTypingService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/typing/SendTypingTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/typing/TypingBody.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/typing/TypingEventContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomSyncHandler.kt
vector/src/main/java/im/vector/riotx/features/home/room/breadcrumbs/BreadcrumbsController.kt
vector/src/main/java/im/vector/riotx/features/home/room/breadcrumbs/BreadcrumbsItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/typing/TypingHelper.kt
vector/src/main/res/drawable/bg_breadcrumbs_typing.xml
vector/src/main/res/layout/item_breadcrumbs.xml
vector/src/main/res/layout/item_room.xml
vector/src/main/res/values/donottranslate.xml
vector/src/main/res/xml/vector_settings_preferences.xml

This is a first proposal to render typing information.
In the room:
In the room list:
In the breadcrumbs:
It also send the typing events, if the user allow it from the settings, and following the [spec](https://matrix.org/docs/spec/client_server/latest#id51).

Send and render typing events (#564)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultFileService.kt

NOTE: this hasn't really gone through any testing.
It's a possible solution. @bmarty please take a look.
DefaultFileService - code was passing the inputStream to the decryption method
but not storing the output of the method anywhere
then it was writing inputStream to file and returning that file handle
changed inputStream to var and used it to store output of decryption method
Signed-off-by: David Hyman dghyman@gmail.com

File decryption path was writing incorrect stream to file 

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
CONTRIBUTING.md

Specific rules:
- disable using * in import
- align `->` in when block
- remove blank lines before `}` (so that `ktlint` will complain less)
This ensure the future PRs be polluting by formatting change, if every developer share the same rules.
Global formatting has not been done thought, it will come file by file for the moment.
Also import * can be checked by `ktlint`, but this is not enabled for the moment, because we have several branches.

Share the same code formatting rules

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomSummaryUpdater.kt
matrix-sdk-android/src/main/res/values/strings_RiotX.xml
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/NoticeEventFormatter.kt

Fixes #897
Also ensure encryption is enabled only if the algorithm is "m.megolm.v1.aes-sha2" (MXCRYPTO_ALGORITHM_MEGOLM)

Modify encryption notice

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/common/CryptoTestHelper.kt
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/verification/SASTest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/extensions/Booleans.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/sas/VerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/sas/VerificationTxState.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/create/CreateRoomParams.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DeviceListManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultIncomingSASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultOutgoingSASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/SASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/DefaultQrCodeVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/task/CoroutineSequencersTest.kt
vector/src/main/java/im/vector/riotx/features/MainActivity.kt
vector/src/main/java/im/vector/riotx/features/createdirect/CreateDirectRoomViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/emoji/VerificationEmojiCodeViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomViewModel.kt

Closes #907: Tested OK with regular user (so e2e on by default) and @riot-bot:matrix.org (so e2e off by default)
Also:
- Convert VerificationTxState to a sealed class
- Make CreateRoomParams a regular data class
- Cleanup

Negotiate E2E by default for DMs (#907)

---

README.md

RiotX is on F-Droid now
Signed-off-by: Christopher Rossbach <public.cr@protonmail.ch>

Add "get it on F-Droid"

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DeviceListManager.kt
vector/src/main/java/im/vector/riotx/core/dialogs/ExportKeysDialog.kt
vector/src/main/java/im/vector/riotx/core/dialogs/PromptPasswordDialog.kt
vector/src/main/java/im/vector/riotx/features/settings/crosssigning/CrossSigningSettingsFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/VectorSettingsDevicesFragment.kt
vector/src/main/res/layout/dialog_prompt_password.xml

Reveal password, inline error when empty
Before:
After (empty error case):

Improve prompt password dialog

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/verification/SASTest.kt
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/verification/qrcode/VerificationTest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/sas/VerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/PendingVerificationRequest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransport.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransportRoomMessage.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransportToDevice.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysrequest/KeyRequestHandler.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/choose/VerificationChooseMethodViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/emoji/VerificationEmojiCodeViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/VerificationRequestItem.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewModel.kt

Fixes #988
Tested ok with a hacked client which declare supported only show Qr code
Also all the tests pass:
This PR also contain some cleanup and some update in the Javadoc

Fix issue with verification when other client declares it can only show QR code (#988)

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/roomdirectory/PublicRoomsResponse.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/MatrixItem.kt
vector/src/main/java/im/vector/riotx/core/platform/EllipsizingTextView.kt

Fixes #1023 
Also use room alias when room name is not available, ex:

Fix crash in the room directory, when public room has no name (#1023)

---

CHANGES.md
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/MatrixPatterns.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/RoomDirectoryService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/RoomService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/create/CreateRoomResponse.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/roomdirectory/PublicRoom.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/tombstone/RoomTombstoneContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/MatrixItem.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoomDirectoryService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoomService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/membership/joining/JoinRoomTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/tombstone/RoomTombstoneEventLiveObserver.kt
vector/src/main/java/im/vector/riotx/core/platform/EllipsizingTextView.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewEvents.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsController.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/RoomDirectoryAction.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/RoomDirectoryViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/roompreview/RoomPreviewAction.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/roompreview/RoomPreviewActivity.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/roompreview/RoomPreviewNoPreviewFragment.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/roompreview/RoomPreviewViewModel.kt

Fixes #808 
Fixes #1041 
the room `#voice:matrix.org` has no name and no canonical alias, so is a good candidate to test robustness of the app.
To test #808, you have to be on another home server. I reproduced the bug using a modular homerver, so I can confirm that the issue is fixed by this PR.
@onurays you should just do a static review of the code

Fix join room over federation

---

vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileController.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileFragment.kt

Display internal id of a room section in room profile, with copy to clipboard action, only in developer mode
French screenshot:

Display internal id of a room section in room profile

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/user/model/User.kt
vector/src/main/java/im/vector/riotx/features/createdirect/CreateDirectRoomKnownUsersFragment.kt
vector/src/main/java/im/vector/riotx/features/createdirect/CreateDirectRoomViewEvents.kt
vector/src/main/java/im/vector/riotx/features/createdirect/CreateDirectRoomViewModel.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationDrawerManager.kt

A race condition was sometimes adding twice the first chip (#1032) 
This PR also fixes the fact that adding from userId was not working well if there was already a user selected.

Fix dm chips

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/IMXDecrypting.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/olm/MXOlmDecryption.kt

un needed runblocking, and dangerous (should not be used from a coroutine):
````
* Runs a new coroutine and **blocks** the current thread _interruptibly_ until its completion.
* This function should not be used from a coroutine. It is designed to bridge regular blocking code
* to libraries that are written in suspending style, to be used in `main` functions and in tests.

Remove dangerous runBlocking (and un-needed)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/EncryptEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomSyncHandler.kt

Fixes #518
Immediatly decrypt remote echo of encrypted messages to avoid annoying transition

Fix Message transitions in encrypted rooms

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/ui/views/KeysBackupBanner.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/settings/KeysBackupSettingsRecyclerViewController.kt
vector/src/main/res/values/strings.xml

Fix / When there are locally unknown keys available on the backup the banner is not clickable

QuickFix / key banner not clickable

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt

Fixes #841
Missing avatar/displayname after verification request message 
After a verificati
Before:
After:

Fixes #841

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/secrets/DefaultSharedSecretStorageService.kt

Fix / Since migration to symetric SSSS RiotX can't restore cross signing keys saved by web in SSSS

Fixes #1174

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomSummaryUpdater.kt

Fixes #963 
> (Added 2020-02-24) The set of “all users” depends on the type of room:
For regular / topic rooms, all users including yourself, are considered when decorating a room
For 1:1 and group DM rooms, all other users (i.e. excluding yourself) are considered when decorating a room

Update shield logic for DM

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimeline.kt

Local echo in timeline was not anymore following database changes (encrypting, failed to send..)
It's because timeline has now 'inMemory' sending events for snappiness, but they were not synced with DB until sync

Fix / sending event not always updating

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/di/NetworkModule.kt

Increase default timeout to match old riot
https://github.com/matrix-org/matrix-android-sdk/blob/3427bf4d96fb707e4d5429b8739af6aa4cbcc179/matrix-sdk-core/src/main/java/org/matrix/androidsdk/RestClientHttpClientFactory.kt#L35
-> helps for verification with toDevice on mx
Ideally we should do dynamic timeouts based on connection type like former SDK was doing

Increase default timeout to match old riot

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/DefaultKeysBackupService.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreActivity.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromKeyFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromKeyViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromPassphraseFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromPassphraseViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreSharedViewModel.kt

Fixes #1163
Keybackup created by bootstrapping could not be restored from riotX.
With this PR, on tapping restore backup, we will check:
- If the secret has been gossiped, and in this case automatically load keys
- If the secret is in SSSS, in this case ask for the 4S passphrase to get backup key and restore
- if none of above, ask directly for the backup passphrase/key
=> We need to open issues for when user tries to delete backup (to clean 4S), as well as when user creates a backup when SSSS is enabled

KeyBackup / Use 4S if key in quadS

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/secrets/DefaultSharedSecretStorageService.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/request/VerificationRequestController.kt

Fixes #1007 Cross-Signing | Hide Use recovery key when 4S is not setup

 Hide Use recovery key when 4S is not setup

---

vector/src/main/java/im/vector/riotx/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/UnknwonDeviceDetectorSharedViewModel.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt

Currently 'unknown device security notice' will keep poping up even if you dismissed it.
This PR will fix that, once dismissed it wont show + it will remember it also for next login.
-> Now users have to go to Security&Privacy to verify a session if the alert was dismissed
-- This will need some re-work, and a cross platform strategy. This PR is a quick change to avoid annoying users indefinitly (also given that some clients -old riot- cannot complete this flow)

Remember ignored unknown sessions

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncTask.kt

Get HS capabilities was called before notifying ux of initial sync, thus the app stays in blank state (empty home, drawer) several seconds before sync started
Also, should we do that at every sync?

Fix / ensure ux aware of wait

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/ComputeTrustTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/SessionToCryptoRoomMembersUpdate.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/ShieldTrustUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomSummaryUpdater.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DeviceVerificationInfoBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewModel.kt

Fixes #963 
The issue has been re-open because sometimes the shield for DM was not following the right rules.
ComputeTrustTask is called at two points, on room membership change, and on crypto device changes (user adding/removing devices), but the DM rules was only applied in one case.
On room member change, the correct rule was applied (ignore yourself in shield trust computation), but on crypto device change it was not done.
=> Refactored so that the specific rule is applied directly by the task

Fix / Move DM shield rules to task

---

matrix-sdk-android/src/main/res/values/strings.xml
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MergedRoomCreationItem.kt

#1309
- do not collapse room member events
- collapse other type of event: topic, alias, canonical alias, powel level
- Use correct user name for collapsed version (should be fixed twice due to the previous change of excluding some room member events)
- align "join" and "left" string with Riot-Web
With encryption:

Several fixes on room creation collpasing events (Fixes #1309)

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/AvatarRenderer.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/ShortcutsHandler.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailActivity.kt

👋 Hello! I started using Riot recently and found myself missing having direct shortcuts, so I added them. Fixes #652.
I kept it simple and just allow creating shortcuts from rooms which have been favourited. Android restricts the number of shortcuts you can have to 4, so this seemed like a reasonable thing to do!
I wasn't sure the best place to trigger the creation of the shortcuts - so I decided to do so in home. So when the user opens the app, we'll subscribe and start listening for room changes, and update the available shortcuts as needed. 
Tested on a Pixel 1 running Android 9.x. I've tried to get it going on an Android 6.x or 7.x emulators, but I couldn't get the app installing. Hardware acceleration isn't available on the older emulators, and installing the app just times out 😭. …

Add direct shortcuts

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/utils/SystemUtils.kt
vector/src/main/java/im/vector/riotx/features/sync/widget/SyncStateView.kt
vector/src/main/res/layout/view_sync_state.xml
vector/src/main/res/values/strings.xml

Make the message more specific when airplane mode is on (and less 'red' because it's a user decision).
A request has been done to the design team to get an icon, but we can merge this small PR befoer waiting for it.
So when visible, the three possible renderings are (copy pasted from layout preview):
This PR is a quick improvement, it does not handle the case were airplane is set to On, and connectivity to the server was already lost, or airplane mode set to Off, but connectivity to the server cannot be retrieved. The last state will be displayed.

Better connectivity lost indicator when airplane mode is on

---

CHANGES.md
vector/src/main/res/menu/home.xml

Fixes #1384 
The filtering icon was not clear for some users.
Use the regular magnifying icon
Before:
After:
We may in the future have unified search so the icon will be replaced anyway
Note: I keep the filter icon on the other screens, for instance:

Change icon to magnifying-glass to filter room (#1384)

---

CHANGES.md
matrix-sdk-android/src/main/res/values/strings.xml
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/NoticeEventFormatter.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MergedRoomCreationItem.kt
vector/src/main/res/values/strings.xml

It's worth noting that historically notice string were located in the SDK. Now a few of them are in the app.
This PR does not change anything about this, but maybe on day we should clarify this point.

Use "you" instead of your display name for notice events you have sent

---

.idea/codeStyles/Project.xml
CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/signout/SignOutTask.kt
vector/src/main/java/im/vector/riotx/features/login/LoginFragment.kt

Temporary fix to show error when user is creating an account on matrix.org with userId containing only digits (#1410)

---

CHANGES.md
vector/src/main/res/values-v21/theme_light.xml
vector/src/main/res/values-v21/theme_status.xml
vector/src/main/res/values-v23/theme_light.xml
vector/src/main/res/values-v23/theme_status.xml
vector/src/main/res/values-v27/theme_light.xml
vector/src/main/res/values-v27/theme_status.xml

Fixes #1342
(Note, this is an old version with old filter icon)

Fix bad color contrast for navigation and status bar

---

CHANGES.md
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/RoomService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoomService.kt
vector/src/main/java/im/vector/riotx/features/home/room/breadcrumbs/BreadcrumbsViewModel.kt

User get confused to see left rooms in the breadcrumbs.
I decided to filter them out.
Note that they are still present in the breadcrumbs account data, but should naturally be excluded once the user has navigated to any 20 other rooms.
If the user joins the room again, it may appear in its current breadcrumb index, which is OK I think.

Hide left rooms in breadcrumbs (#766)

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/KeysQueryBody.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/DownloadKeysForUsersTask.kt

Fixes #1444 
RiotX now sends empty lists instead of empty JsonObjects (= maps)

Wrong /query request (#1444)

---

CHANGES.md
matrix-sdk-android-rx/build.gradle
matrix-sdk-android/build.gradle
vector/build.gradle

Fixes #405 
The decision has been taken to set min level API to 21. Several reasons for that have been provided in #405.
It's still possible for anyone to create a fork to support previous versions of Android OS if they want to.

Min SDK level set to 21 (#405)

---

CONTRIBUTING.md
tools/templates/configure.sh

tools/templates/configure only worked for Mac OSX. I added an optional variable to set the location for Android Studio when using other OSes.
Signed-off-by: Fabian Ulbricht <fabianu@student.ethz.ch>
#648 # Pull Request Checklist

Minor dev setup improvement for Linux/Windows.

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/Request.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/RetrofitExtensions.kt

+ This extension is identical to the one used in this project and is available since Retrofit 2.6.0.
See https://github.com/square/retrofit/commit/b761518aa174c7b0512b73f2fe70e2e908f24081.
Signed-off-by: Tobias Preuss <tobias.preuss@googlemail.com>

Use retrofit2.Call.awaitResponse extension provided by Retrofit 2.

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/events/model/RelationType.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/TimelineEventFilter.kt

Fixes #1537 
It has been forgotten in 32c4ad9ecba32e111aff9a7e98f2f6c76b6ea36a

Use vendor prefix for non merged MSC (#1537)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/EventMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/membership/LoadRoomMembersTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoRepository.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TokenChunkEventPersistor.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomSyncHandler.kt

Call events from back pagination can trigger the call UX (notification, then call activity)
Looks like the ageLocalTS check is failing; because ageLocalTS was not correctly set when paginating

Pagination do not set ageLocalTs

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewState.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListDisplayModeFilter.kt
vector/src/main/java/im/vector/riotx/features/themes/ThemeUtils.kt
vector/src/main/java/im/vector/riotx/features/ui/SharedPreferencesUiStateRepository.kt
vector/src/main/res/menu/home_bottom_navigation.xml

Invites are displayed in the corresponding DM or Room tab
Fixes #1565

Catchup tab is removed temporarily (#1565)

---

vector/src/main/java/im/vector/riotx/features/MainActivity.kt
vector/src/main/java/im/vector/riotx/features/home/ShortcutsHandler.kt

This PR fixes a crash observed when user create shortcut and then sign out.
We cannot do better than disabling the shortcut (we cannot remove the shortcut).

Clear dynamic shortcuts when user logs out

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/login/DirectLoginTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/wellknown/GetWellknownTask.kt
vector/src/main/java/im/vector/riotx/core/utils/UrlUtils.kt
vector/src/main/java/im/vector/riotx/features/login/AbstractLoginFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginActivity.kt
vector/src/main/java/im/vector/riotx/features/login/LoginFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginServerSelectionFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginServerUrlFormFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginSignUpSignInSelectionFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewEvents.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewModel.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewState.kt
vector/src/main/java/im/vector/riotx/features/login/ServerType.kt
vector/src/main/java/im/vector/riotx/features/signout/soft/SoftLogoutFragment.kt
vector/src/main/res/drawable/bg_login_server_selector.xml
vector/src/main/res/layout/fragment_login.xml
vector/src/main/res/layout/fragment_login_server_selection.xml
vector/src/main/res/values/strings.xml

Figma: https://www.figma.com/file/S6e3YKA1OB7lWGYrOLEZBq/.well-known-quick-wins
Fixes #1614 
New screen:
The "continue" button as been removed, for a straight forward navigation. It was strange to be able to click twice on the element to validate the choice.
Also now, when selecting "modular" or "other" and typing "matrix.org" as the homeserver url, RiotX will display the matrix.org form
Tested OK: 
- Account creation on matrix.org
- login on matrix.org
- direct login on matrix.org account

Re-activate Wellknown support with updated UI (#1614)

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/animations/behavior/PercentViewBehavior.kt
vector/src/main/java/im/vector/riotx/core/platform/EllipsizingTextView.kt
vector/src/main/java/im/vector/riotx/core/platform/MaxHeightScrollView.kt
vector/src/main/java/im/vector/riotx/core/ui/views/BottomSheetActionButton.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/PollResultLineView.kt
vector/src/main/java/im/vector/riotx/features/reactions/widget/ReactionButton.kt

+ This function is more concise and ensures `recycle()` is always invoked.
+ Sources: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-preference-release/core/core-ktx/src/main/java/androidx/core/content/Context.kt#52
Signed-off-by: Tobias Preuss tobias.preuss@googlemail.com

Use Context#withStyledAttributes extension function.

---

vector/src/main/java/im/vector/riotx/features/media/ImageContentRenderer.kt
vector/src/main/java/im/vector/riotx/features/media/VectorAttachmentViewerActivity.kt

Fix a crash when images have a very thin ration, e.g 10px*500px , due to bad resize policy, the height was trying match target height leading to a big multiplicator, that when applied to the width would cause OOM
https://github.com/matrix-org/riot-android-rageshakes/issues/12383
Fix, delay or freeze (when offline) when opening image viewer pager -> updated glide to only take image from cache to avoid delaying shared element transition for too long

Fix / view attachment crash + freeze when offline

---

vector/src/main/res/values-v21/theme_common.xml
vector/src/main/res/values/theme_common.xml

Use accent color to tint status and navigation bar, on devices which support it.
Before:
After:

Improve splash screen

---

docs/signin.md
vector/src/main/AndroidManifest.xml
vector/src/main/assets/open_source_licenses.html
vector/src/main/java/im/vector/riotx/core/resources/AppNameProvider.kt
vector/src/main/java/im/vector/riotx/features/call/telecom/VectorConnectionService.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewState.kt
vector/src/main/java/im/vector/riotx/features/rageshake/VectorUncaughtExceptionHandler.kt
vector/src/main/res/values/donottranslate.xml

Change all visible in the app mention of "RiotX" to "Element".
There are still lots of mention of RiotX in comments, and internal files, as well as in some of .md file, which will be updated later.
Login with SSO tested OK

RiotX -> Element

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/RoomSummary.kt
vector/src/main/res/xml/vector_settings_root.xml

Show VOIP call icons for all 2 participants room (even if not DM)
+ Hide for now the VOIP settings category until implemented Fixes #1733

Allow call in all 2 participants rooms

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimeline.kt
vector/src/main/java/im/vector/riotx/core/epoxy/LoadingItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/res/layout/item_loading.xml

Fix loading of timeline items when there are only filtered events

Fix timeline non loading when there are lots of filtered events

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/crypto/quads/SharedSecureStorageViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivityViewModel.kt

We got several reports from store of an Illegal argument exception while getting view model
It's a bit defensive code, not sure how this could be called without proper args
````
Caused by: java.lang.IllegalArgumentException: 
at com.airbnb.mvrx.MvRxFactory.create (MvRxFactory.kt:23)
at com.airbnb.mvrx.MvRxViewModelProvider.get (MvRxViewModelProvider.kt:27)
at com.airbnb.mvrx.MvRxViewModelProvider.get$default (MvRxViewModelProvider.kt:2)
at im.vector.riotx.features.home.HomeActivity$$special$$inlined$viewModel$1.invoke (MvRxExtensions.kt:6)
at im.vector.riotx.features.home.HomeActivity$$special$$inlined$viewModel$1.invoke (Unknown Source)
at com.airbnb.mvrx.lifecycleAwareLazy.getValue (lifecycleAwareLazy.kt:6)
at im.vector.riotx.features.home.HomeActivity.getHomeActivityViewModel (Unknown …
```

Fix IllegalArgumentException reported from store on HomeActivity aunch

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/NetworkCallbackStrategy.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/NetworkInfoReceiver.kt
vector/src/debug/java/im/vector/app/features/debug/DebugMenuActivity.kt
vector/src/fdroid/java/im/vector/app/fdroid/features/settings/troubleshoot/TestBackgroundRestrictions.kt
vector/src/fdroid/java/im/vector/app/fdroid/receiver/AlarmSyncBroadcastReceiver.kt
vector/src/main/java/im/vector/app/core/extensions/View.kt
vector/src/main/java/im/vector/app/core/files/FileSaver.kt
vector/src/main/java/im/vector/app/core/hardware/HardwareInfo.kt
vector/src/main/java/im/vector/app/core/hardware/vibrator.kt
vector/src/main/java/im/vector/app/core/services/CallRingPlayer.kt
vector/src/main/java/im/vector/app/core/services/VectorSyncService.kt
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt
vector/src/main/java/im/vector/app/core/utils/SystemUtils.kt
vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt
vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
vector/src/main/java/im/vector/app/features/call/WebRtcPeerConnectionManager.kt
vector/src/main/java/im/vector/app/features/call/telecom/TelecomUtils.kt
vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
vector/src/main/java/im/vector/app/features/rageshake/RageShake.kt

- Here the `Context#getSystemService` extension function is used which is provided by the `core-ktx` artifact.
- Sources: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/core/core-ktx/src/main/java/androidx/core/content/Context.kt#30
Signed-off-by: Tobias Preuss tobias.preuss@googlemail.com
---
_Feel free to rebase the branch before merging it to facilitate a linear history. Let me know if I should do this._

Use Context#getSystemService extension function provided by core-ktx.

---

CHANGES.md
vector/src/main/java/im/vector/app/core/date/VectorDateFormatter.kt

This fixes #822. 
The problem was that the transitionResolution parameter has to go back to the beginning of the day. In general, going back 24h is not enough.
I tried to write some tests but had difficulty to set localization, timezones and time for the test to make the tests deterministic. Anybody experience with doing that?

Relative date time formatter #822

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
vector/src/main/res/values/strings.xml
vector/src/main/res/xml/vector_settings_root.xml
vector/src/main/res/xml/vector_settings_voice_video.xml

Fixes #1869 
A new setting (disabled by default) allow to show a confirmation dialog before starting a call

Give user the possibility to prevent accidental call (#1869)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/accountdata/UpdateIgnoredUserIdsTask.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/res/values/strings.xml

Fixes #1890 
The confirmation dialog already exist when ignoring user from the room member detail.
I just add the confirmation dialog when ignoring from the message bottom sheet.

Ensure users do not accidentally ignore other users (#1890)

---

CHANGES.md
matrix-sdk-android-rx/src/main/java/org/matrix/android/sdk/rx/RxSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/rest/UploadSignatureQueryBuilder.kt
vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapAccountPasswordFragment.kt
vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt
vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt
vector/src/main/java/im/vector/app/features/settings/crosssigning/CrossSigningSettingsViewModel.kt
vector/src/main/java/im/vector/app/features/settings/devices/DeviceVerificationInfoBottomSheetViewModel.kt
vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt

When another session was remotely deleted (i.e. signed out), the session list was not updating correctly.
Fix other RX similar issues.
First commit is just a renaming

Live sessions list

---

CHANGES.md
vector/src/main/java/im/vector/app/core/date/VectorDateFormatter.kt

With DateFormat.getBestDateTimePattern to generate best localized pattern.
Signed-off-by: Yihong Gao <yihong.ui@gmail.com>
Locale | EN | JP | zh_CN 
--- | --- | --- | ---
Screen Shot With Fix | ![en_US](https://user-images.githubusercontent.com/7749575/90324463-0d1c5a00-df24-11ea-89ca-645706df7774.png) | ![JP](https://user-images.githubusercontent.com/7749575/90324464-0db4f080-df24-11ea-9797-0535f18b71ec.png) | ![zh_CN](https://user-images.githubusercontent.com/7749575/90324465-0e4d8700-df24-11ea-86ad-aac9050fb830.png)

Fix date format for some Asian languages (#1928)

---

.idea/codeStyles/Project.xml
CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/failure/CreateRoomFailure.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomTask.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/res/values/strings.xml

When creating a DM and inviting a user whose account is on a HomeServer which is not federated, we get an error, but the room is actually created.
This PR inform the user about that and avoid the user to click again on "Create", which will create many rooms.
Here is the displayed dialog:
Clicking on OK close the room creation screen.
Note: As we do not know the created roomId, we cannot add it to the DM list.

DM creation: handled denied federation error

---

build.gradle
vector/build.gradle
vector/src/main/assets/open_source_licenses.html
vector/src/main/java/im/vector/app/features/pin/PinCodeStore.kt
vector/src/main/java/im/vector/app/features/pin/PinFragment.kt
vector/src/main/res/values/strings.xml

This PR add supports for biometrics to unlock the app.
It also limit the number of wrong PIN code to 3 before automatically log the user out.

Improve PIN code feature

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/NetworkCallbackStrategy.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/NetworkConnectivityChecker.kt

SyncThread is calling unregister before registration completed.
Fixes #1960.

Fix IllegalArgumentException: Receiver not registered: NetworkInfoReceiver

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/AttachmentEncryptionTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/attachments/MXEncryptedAttachments.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/Helper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/securestorage/SecretStoringUtils.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/FileSaver.kt
vector/src/main/java/im/vector/app/core/glide/VectorGlideModelLoader.kt
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt

+ This change replaces a few usages of `ByteArrayInputStream`, `FileInputStream`, `FileOutputStream` with their equivalent Kotlin extension functions.
Signed-off-by: Tobias Preuss tobias.preuss@googlemail.com
---
_Feel free to rebase the branch before merging it to facilitate a linear history. Let me know if I should do this._

Use File extension functions to make code more concise.

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/call/CallSignalingService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/call/ActiveCallHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/call/DefaultCallSignalingService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt

Since the app is not getting any push notification for `m.call.answer` and `m.call.hangup` events we can't handle these events when the app is in the background.

Don't pause the sync thread if there is an active or pending call.

---

CHANGES.md
vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt

Fix: Loudspeaker is always used

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/wellknown/WellknownResult.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/wellknown/GetWellknownTask.kt
vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt

Fixes #2027
Align with web and relax IS discovery for login with matrix id.
See https://github.com/vector-im/element-web/issues/11102
I hesitated to create a FailPromptInvalidateIS data class (would be cleaner), but maybe it's better to stick with types defined in spec?

Relax IS dicovery

---

CHANGES.md
attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/AnimatedImageViewHolder.kt
attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/ImageLoaderTarget.kt
attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoLoaderTarget.kt
attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoViewHolder.kt
attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/ZoomableImageViewHolder.kt

Fixes  #2034
Some cleaning. Can't reproduce crash after those changes

Crash / Attachment viewer: Cannot draw a recycled Bitmap

---

CHANGES.md
vector/src/main/java/im/vector/app/features/html/FontTagHandler.kt

Pretty much what it says on the can :-) As outlined [in the spec](https://matrix.org/docs/spec/client_server/r0.6.1#m-room-message-msgtypes), `<font>` tags can have the `data-mx-bg-color` attribute attached to indicate that text should have a different background colour. While this is somewhat counter to things like good readability in many instances with e.g. dark or light themes, only supporting the foreground colour also renders some text unreadable for some messages that change both.
First time writing Kotlin, so I'm sure the styling could be improved :-)

Support data-mx-[bg-]color attribute on <font> tags in formatted messages.

---

CHANGES.md
vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt
vector/src/main/java/im/vector/app/features/call/WebRtcPeerConnectionManager.kt

Always use loudspeaker while ringing and a headset is not connected

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/actions/MegolmSessionDataImporter.kt
vector/src/main/java/im/vector/app/core/ui/list/GenericItemWithValue.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt
vector/src/main/java/im/vector/app/features/settings/devtools/AccountDataAction.kt
vector/src/main/java/im/vector/app/features/settings/devtools/AccountDataEpoxyController.kt
vector/src/main/java/im/vector/app/features/settings/devtools/AccountDataFragment.kt
vector/src/main/java/im/vector/app/features/settings/devtools/AccountDataViewModel.kt
vector/src/main/res/layout/dialog_import_e2e_keys.xml
vector/src/main/res/values/strings.xml

- Add possibility to delete account data by type (advanced setting screen)
- Improve import Megolm key dialog (add show password as for other password input)
- After importing Megolm keys from manual backup, upload keys to the key backup if it exists.

Add possibility to delete account data and fix bug

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/res/values/strings.xml

Visually disables call buttons when either
- the room has only one member
- in rooms with 2 participants you have no permission to send `m.call.invite` events
- in rooms with 3 or more participants you don't have permission to manage widgets.
Click/select handlers are still attached.
This is just a suggestion on how to handle #2112 but I am of course open for better ways to deal with call permissions.

Visually disable call buttons/prohibit calling on insufficient permissions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/CancelGossipRequestWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/SendGossipRequestWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/SendGossipWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/SendVerificationMessageWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportRoomMessage.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/group/GetGroupDataWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/AddHttpPusherWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/SendRelationWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/EncryptEventWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/MultipleEventSendingDispatcherWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/RedactEventWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/SendEventWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/SessionSafeCoroutineWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/worker/WorkerParamsFactory.kt

Trying to normalize the way we use worker, and also try to catch all possible Exception to avoid breaking worker chains.
Parsing Exception is dealt in @ganfra 's PR #2129 
This is really dirty, I cannot to parsing and buildErrorResult() in the parent class, so many duplicated code... Not very proud of it.

Create parent class for all MatrixWorker

---

CHANGES.md
vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
vector/src/main/res/layout/fragment_login_splash.xml
vector/src/main/res/values/styles_login.xml

Rely only on ConstraintLayout (no more scroll view) for the first displayed screen of the app.
Before <img width="239" alt="Screenshot 2020-09-25 at 06 29 03" src="https://user-images.githubusercontent.com/3940906/94231238-e29ac500-ff03-11ea-9bbe-b9475bcd9078.png"> After <img width="242" alt="image" src="https://user-images.githubusercontent.com/3940906/94231284-f6462b80-ff03-11ea-9e94-101f03606e0f.png">
Before <img width="250" alt="Screenshot 2020-09-25 at 07 28 29" src="https://user-images.githubusercontent.com/3940906/94231418-46bd8900-ff04-11ea-8ef6-1a4325351ecc.png"> After <img width="250" alt="image" src="https://user-images.githubusercontent.com/3940906/94231371-28f02400-ff04-11ea-888c-797375fedf19.png">

Fix Splash screen layout, especially on small screens

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/read/ReadService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/read/DefaultReadService.kt
vector/src/main/java/im/vector/app/core/di/VectorComponent.kt
vector/src/main/java/im/vector/app/core/utils/TemporaryStore.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailPendingAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailPendingActionStore.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileController.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewState.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileActivity.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListFragment.kt

Using a trick to avoid messing up with ActivityResult: we store the pending action in a singleton.
Also I created https://github.com/vector-im/element-web/issues/15380

Add "jump to read receipt" and "mention" actions from room member detail screen

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DeviceListManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt
vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt

Properly detect when cross signing keys are reseted.
-> currently on reset, we were not cleaning the known private keys (as they are now irrelevant)
-> On my cross signing keys change, we also clear now any trust of my sessions (including local)
-> When cross signing keys has changed, we detect it and add a new alert to ask to re-verify

Fix / reset cross signing not well supported

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/res/xml/vector_settings_preferences.xml

- Add preference settings to send message by pressing the soft keyboard enter key (instead of new line)
- Add support for external keyboard send (currently can only break line)
=> I imported back the old app code https://github.com/vector-im/riot-android/blob/af848a04704b8a286c39ce75b23894f63de53cfa/vector/src/main/java/im/vector/activity/VectorRoomActivity.java#L733
Fixes #1195
Fixes #1881
Fixes #1440

Add preference to send with enter

---

CHANGES.md
vector/src/main/res/menu/vector_attachments_preview.xml

The remove and edit icons were black on a black background on the attachments preview screen so were invisible.
Icon tint was added to the menu xml file for the appropriate menu to make the icons visible

Make edit and remove image icons visible in attachments preview screen

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt

Fix issues with ui local echo (introduced with send re-work), visible when adding a reaction that would be counted twice
We had several issues with UI echos
- We were listening only to filtered sending events, which is annoying as relations events filtered but their updates are needed to update ui echo. Changed this and delayed the filtering at the time of event building
- There was an issue with update of reaction (was looking at reference event instead of local id of the reaction)
- We also had an issue in the event filtering that was not checking on clear type , clear content (for sending event post encrypt)

Fix ui echo isues

---

AUTHORS.md
CHANGES.md
vector/src/main/java/im/vector/app/core/qrcode/QrCode.kt

Directly assign colours to a colour buffer then use that buffer to
generate the bitmap. This is much faster than using Bitmap.setPixel for
every pixel.
Roughly 100x speed increase with a sample QR-code when tested on a Motorola G4

Considerably faster QR-code bitmap generation

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/ChangePasswordTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/DeactivateAccountTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/account/AccountService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/account/DefaultAccountService.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
vector/src/main/java/im/vector/app/features/settings/account/deactivation/DeactivateAccountViewModel.kt

Would do a big PR but this will be easier to review.
Also each endpoint needs to be checked to see which dispatchers it should use so it's best to keep it small.

Convert `AccountService` to suspend functions

---

CHANGES.md
vector/src/main/java/im/vector/app/features/login/AbstractLoginFragment.kt
vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt

Fixes #2391 
Not sure from where this regression comes from.
Actually those are the other resumed Fragment (ex: `LoginCaptchaFragment`) which show the error dialog by mistake, because they are still listening to the ViewEvents. The (sort of expected) 401 error is correctly ignored by `LoginWaitForEmailFragment`
@ganfra do you have an idea

Registration: annoying error message scares every new user when they add an email (#2391)

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/raw/RawService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/raw/DefaultRawService.kt
vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnownExt.kt

Convert RawService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/DraftService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/draft/DefaultDraftService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt

Convert DraftService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/group/Group.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/group/DefaultGroup.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/group/GroupFactory.kt
vector/src/main/java/im/vector/app/features/grouplist/GroupListViewModel.kt

Convert Group to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/PushRuleService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/DefaultPushRuleService.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsAdvancedNotificationPreferenceFragment.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsNotificationPreferenceFragment.kt
vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestAccountSettings.kt

Convert PushRuleService to suspend functions

---

CHANGES.md
vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt

Native dialler integration breaks the jitsi widget for those of us with non-vanilla telephony frameworks.
Disabling this integration (as is default on the Jitsi Meet Android app) allows us to also join conference calls, with no adverse effect on those for whom it already works.
Signed-off-by: Ed Geraghty <ed@geraghty.london>

Disable native dialler integration on jitsi widget

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/EventDecryptor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/IncomingGossipingRequestManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/MXOlmDevice.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/SendGossipWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/actions/EnsureOlmSessionsForDevicesAction.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/CryptoSyncHandler.kt

Globally raise crypto log levels so they are in rageshakes (a lot are verbose only)
Better log for failed to decrypt ToDevice (print sender info)
Check that key share and unwedge flows are correctly logged
Check that key re-share flows are correctly logged

Better e2e log reporting

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/UserStore.kt

Update profile has no effect if user is in zero rooms (as nothing comes back from sync?)
-> propose to update user store after update call

Fix / update profile when no rooms

---

CHANGES.md
vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
vector/src/main/java/im/vector/app/features/crypto/verification/QuadSLoadingFragment.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationAction.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/res/layout/fragment_progress.xml

When verifying with passphrase, after entering correct passpharse you go back to the bottom sheet, and it's displaying again the options to verify with pass / skip ...
- > actually some secret extraction is going on in background and you have to wait a few seconds for the conclusion fragment to appear
=> Fixed by introducing a new waiting fragment during this process
Also the keybackup import was done in viewmodel scope, moved it to global scope for better reliability

Fix / double bottomsheet effect

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/Constants.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
vector/src/main/java/im/vector/app/features/login/LoginViewState.kt

See https://github.com/matrix-org/matrix-doc/pull/2858/files#r543567196
Original implementation in https://github.com/vector-im/element-android/pull/2484
I have not tested this, but have no reason to believe it needs to be.

Make MSC2858 implementation match the unstable policy of the spec

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt

Notices and formatted messages don't have imageContentRenderer and
previewUrlRetriever set.
Accordingly, when recycling messages that previously had an URL preview,
we do not want to keep that preview, but actually hide it, instead of
returning early (without rendering any update).
~~- [ ] UI change has been tested on both light and dark themes~~
~~- [ ] Pull request includes screenshots or videos if containing UI changes~~

Properly hide preview URLs for messages that don't support previews

---

vector/src/main/java/im/vector/app/core/platform/VectorBaseBottomSheetDialogFragment.kt

Set `_bindings` in VectorBaseBottomSheetDialogFragment to null when view destroyed, as done in VectorBaseFragment and [suggested by View Binding migration guide](https://developer.android.com/topic/libraries/view-binding#fragments) _(minor oversight in ViewBindings migration PR https://github.com/vector-im/element-android/pull/2542)_

Release VectorBaseBottomSheetDialogFragment bindings when view destroyed

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/Constants.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/UrlExtensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/Constants.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt
vector/src/main/java/im/vector/app/features/login/AbstractSSOLoginFragment.kt
vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt
vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
vector/src/main/java/im/vector/app/features/login/LoginViewState.kt
vector/src/main/java/im/vector/app/features/login/LoginWebFragment.kt

When releasing the SDK 1.0.13, I realized that the auth URLs should be computed by the SDK, and not by the app.
This PR moves those computation SDK side.

Let the SDK compute the URLs

---

CHANGES.md
vector/src/main/java/im/vector/app/features/themes/ThemeUtils.kt
vector/src/main/res/values/array.xml
vector/src/main/res/values/strings.xml
vector/src/main/res/xml/vector_settings_preferences.xml

This adds an option to use the system theme as the app theme. It is enabled by default and works on API 21+. 
Login screen with system theme option (dark theme as system default)
Settings dialog to choose themes
Signed-off-by: Tigermouthbear <tigermouthbear@tigr.dev>

Add System theme option and set as default

---

docs/ui-tests.md

I think I removed a typo. You probably don't want a new virtualenv every time you start a homeserver?

Typo in the set-up instructions for the test homeserver

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/state/StateServiceExtension.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
vector/src/main/res/values/strings.xml

Fix #1460 
Add an extra warning, and color the button in red in case of not public room
Applies when leaving room from rooms list or from room profile

Warn user when he is leaving a not public room (#1460)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/SenderNotificationPermissionCondition.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/PowerLevelsContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/powerlevels/PowerLevelsHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/SafePowerLevelContent.kt
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/powerlevel/EditPowerLevelDialogs.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileActivity.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileSharedAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/EditablePermission.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsViewEvents.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsViewState.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsFragment.kt
vector/src/main/res/values/strings.xml

Fixes #2471
It was already possible to edit the power level event to update the power level of users, but this PR add the possibility to edit the configuration of the room itself. I am reusing the same dialog to edit the level though, I just added a dynamic title.
Expanded:
Updating something
(also possible to show advanced part)

Edit power level

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/joining/JoinRoomTask.kt
vector/src/main/java/im/vector/app/features/roomdirectory/roompreview/RoomPreviewViewModel.kt

This PR fix the pb of using too many servers when joining a room.
By default we now use what was provided in the permalink (via parameter).
Also the SDK enforces that there is no more than 3 servers in the join request
You can reproduce the current problem with this permalink: https://matrix.to/#/#matrix:matrix.org?via=matrix.org&via=t2bot.io&via=gnome.org

Fix request too large Uri error when joining a room

---

CHANGES.md
vector/src/main/res/layout/activity_home.xml
vector/src/main/res/values-sw600dp/dimens.xml
vector/src/main/res/values/dimens.xml

Drawer layout width limit for landscape and tablets

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/IdentityBulkLookupTask.kt

When a new pepper is retrieved after an M_INVALID_PEPPER response,
recompute hashes with that pepper, and send those new hashes in the next
lookup attempt instead of reusing the original hashes.

Identity: Recompute hashes after M_INVALID_PEPPER

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/EventContextResponse.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/PaginationResponse.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEventPersistor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/uploads/GetUploadsTask.kt

Fixes issues when syncing and back paginating with Dendrite:
EA didn't support null event list (dendrite behavior) , expected it to be an empty array (synapse behavior)
Back pagination depends on this dendrite fix https://github.com/matrix-org/dendrite/pull/1708

Fix Dendrite sync response support

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/widgets/WidgetService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/UrlExtensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/DefaultWidgetURLFormatter.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/helper/WidgetFactory.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiCallViewModel.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiWidgetProperties.kt
vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/widgets/WidgetArgsBuilder.kt
vector/src/main/res/layout/item_timeline_event_base_state.xml

Especially joining a Jitsi conf created by ElementWeb does not work since the Jitsi URL does not contain the `confId` parameter, it's only in the fragment.
Also properly encode (and decode) parameters in the fragment.
Support for `$theme` template

Fix a bunch of bugs and feature parity for Widget

---

CHANGES.md
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsFragment.kt

A few changes and improvements in the UX for room settings
- Move "Room addresses" and "Room permissions" entry point from the screen where user can update basic states of the room to the advanced section of the room profile. This is mainly because it's better for non-tech user, and also the room setting screen is a form where all changes are committed at once, so, for the UX it was not ideal to have entry point for other screens here.
- Add some click listener to open specific screens from the settings.

Room settings ux

---

CHANGES.md
tools/install/androidSelectDevice.sh
tools/install/installFromBuildkite.sh
tools/release/download_buildkite_artifacts.py

Make developers (and power users) happy: install APK from any branches since Buildkite has built it.
It will prompt for the device to install the APK if several device are available. Also will download the correct APK depending on the device architecture.

Add a script to download and install APK from Buildkite

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/sync/FilterService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/MoshiProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/filter/FilterFactory.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/filter/SaveFilterTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/ProcessEventForPushTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/InitialSyncStrategy.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/model/LazyRoomSyncEphemeral.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/model/RoomSync.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/model/RoomsSyncResponse.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/parsing/DefaultLazyRoomSyncEphemeralJsonAdapter.kt
vector/src/main/java/im/vector/app/core/extensions/Session.kt

This PR reduce the delay to see the room list and be able to open a room and send a message to it.
On my account (about 300 rooms) I can see the room list after 55 seconds. With this PR, it is reduced to 35 seconds, including 12 seconds to let the server compute the response and the client to download the data.

Improve init sync performance

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomDirectoryService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomDirectoryService.kt
vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsViewState.kt
vector/src/main/java/im/vector/app/features/roomdirectory/RoomDirectoryViewModel.kt
vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
vector/src/main/res/values/strings.xml
vector/src/main/res/xml/vector_settings_preferences.xml

New settings, in Settings/Preferences screen, off by default:
(Edit: wording has been updated, see new screenshot below)
Filtering room directory
Also migrate RoomDirectoryService to coroutines (#2449)

Basic filtering for "nsfw" keyword

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoRepository.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/Extensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/ReactionUiEchoData.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineState.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/UIEchoManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt

There was an issue on the local echo, especially the update of the sent state. Message can stay in gray, whereas they are already sent to the server.
This is more visible if the database is blocked in a long transaction.
This PR also contain a rework (in a dedicated commit), to split DefaultTimeline into several smaller files.

Snappier local echo

---

vector/src/main/res/layout/item_room_widget.xml

Add arrows to room widget items

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/CryptoSessionInfoProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DeviceListManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/MXOlmDevice.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/olm/MXOlmDecryption.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/IMXCryptoStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/LoadRoomMembersTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/LogUtil.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt

- Hide the shield from the room list (part of #2991)
- Stop loading room members of e2e just after an init sync.
- Also fix "Encrypted message" displayed on the room list
- Rework UpdateTrustWorker (should not introduce change)
- limit the size of logged data.
In the future we may want to compute the room shields for room on demand. For now we keep computing it but in a lazy way, since we do not load all the members at once.

Shields optimization

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DeviceListManager.kt

Server names are allowed to contain ':' to specify a port, see https://matrix.org/docs/spec/appendices#server-name
User ids on the other hand are not allowed to contain ':', even
historical user ids, see https://matrix.org/docs/spec/appendices#historical-user-ids
Therefore we can use the first instance of ':' to split the user
localpart from the server name.
Note: I could not test it yet
Signed-off-by: Timo Kösters <timo@koesters.xyz>

fix: make cross signing work with server names containing :

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt

Quick work around to remove stuck messages at the bottom of timeline.
Currently only choice is to clear cache and do a full initial sync.
This PR is just adding an option to cancel sent but not synced message, only effect is that it will delete the local echo.
This does not fix the root issues, See:
https://github.com/vector-im/element-android/issues/516
https://github.com/matrix-org/synapse/issues/9424
https://github.com/matrix-org/synapse/issues/9624

Quick Work around to remove stuck messages

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGES.md

Bugged me for a while, 4-deep headers are equivalent, but they look nicer when editing the pull request itself, and they shift the lines on the PR a tiny bit to make it more readable.
- (sidenote; do I really need to add meta changes such as this to `CHANGES.md`?)
`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

Change ISSUE_TEMPLATE bold lines to proper headers

---

CHANGES.md
vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerActivity.kt

Fixes #2928 (Regression: Video will not play upon tap, but only after swipe)

Regression: Video will not play upon tap

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt

NO_OLM withheld code were sent one by one during keyshare process.
In big room this can be a common scenario (people running out of OTK), this change simply send all the NO_OLM in a single toDevice event.
With a test account in Megolm Test room, this tear down the number of needed requests to 15 instead of 835

Send several NO_OLM in one request

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/DownloadKeysForUsersTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/MathUtils.kt
matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/util/MathUtilTest.kt

Fixes #2925
Limit the number of user to max 250 per request.
If there is 251 users, the request will be cut into 2 requests, one with 125 users and one with 126 users

Split key request

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relationship/RoomChildRelationInfo.kt
vector/src/main/java/im/vector/app/AppStateHandler.kt
vector/src/main/java/im/vector/app/core/ui/list/GenericFooterItem.kt
vector/src/main/java/im/vector/app/core/ui/list/GenericItem.kt
vector/src/main/java/im/vector/app/features/form/FormMultiLineEditTextItem.kt
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModelFactory.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewState.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/app/features/spaces/ShareSpaceBottomSheet.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceCreationActivity.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceSettingsMenuBottomSheet.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceSummaryController.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceDefaultRoomsFragment.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceDetailsFragment.kt
vector/src/main/java/im/vector/app/features/spaces/create/SpaceDefaultRoomEpoxyController.kt
vector/src/main/java/im/vector/app/features/spaces/create/SpaceDetailEpoxyController.kt
vector/src/main/java/im/vector/app/features/spaces/create/WizardButtonView.kt
vector/src/main/res/drawable/rounded_rect_shape_16.xml
vector/src/main/res/layout/bottom_sheet_space_invite.xml
vector/src/main/res/layout/fragment_space_create_choose_type.xml
vector/src/main/res/layout/fragment_space_create_generic_epoxy_form.xml
vector/src/main/res/layout/item_editable_square_avatar.xml
vector/src/main/res/layout/view_space_type_button.xml
vector/src/main/res/values/strings.xml

Spaces | Design review changes

---

vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt

A small change to make sure that files downloaded on devices with API level below 29 end up in the directory they are meant to end up in. I've previously submitted this as a path traversal vulnerability just in case, but it was not accepted, so I'm submitting it as a public PR instead.
Replacing dangerous path elements with underscores matches the behaviour on devices above API level 29, although this is done implicitly for those.
NOTE: This is a small change, so I didn't modify CHANGES.md, which is why CI is failing. If I should still do that, lmk.
`Signed-off-by: TR_SLimey <tr_slimey@protonmail.com>`

When downloading a file in <= API 29, replace dangerous characters with underscores

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/identity/IdentityService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/DefaultIdentityService.kt
vector/src/main/java/im/vector/app/features/contactsbook/ContactsBookViewModel.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsViewModel.kt
vector/src/main/java/im/vector/app/features/discovery/change/SetIdentityServerViewModel.kt

Convert IdentityService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/read/ReadService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/read/DefaultReadService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt

Convert ReadService to suspend functions

---

matrix-sdk-android-rx/src/main/java/org/matrix/android/sdk/rx/RxRoom.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/KeyShareTests.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/MembershipService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/DefaultMembershipService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedMemberListViewModel.kt
vector/src/main/java/im/vector/app/features/widgets/WidgetPostAPIHandler.kt

Convert MembershipService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/pushers/PushersService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/DefaultPushersService.kt
vector/src/gplay/java/im/vector/app/gplay/features/settings/troubleshoot/TestPushFromPushGateway.kt
vector/src/main/java/im/vector/app/core/pushers/PushersManager.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsNotificationPreferenceFragment.kt

Convert PushersService to suspend functions

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/RoomSummaryEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAvatarResolver.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/UserAccountDataSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/model/accountdata/DirectMessagesContent.kt

Also better handling of previous DMs management
Fixes #2693 (I think)
Tested OK when playing with account data to switch room between DM to room with devtools on EW

Fix avatar rendering for DMs, after initial sync (#2693)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/read/SetReadMarkersTask.kt

Fixes #3065.
Use another request when "m.fully_read" does not have to be updated.

Fix mandatory parameter in API (#3065)

---

CHANGES.md
vector/build.gradle

Previously jitsi only had optional dependencies being disabled by the
LIBRE build flag but a while ago they introduced optional exclusion
rules which don't transitively propagate to consumers of the library, so
instead we need to mirror the exclusion rules from the jitsi gradle file:
See: https://github.com/jitsi/jitsi-meet/blob/7a64bf006ea027b77564d8847570e1ac46ff0ec0/android/sdk/build.gradle#L53

propagate jitsi LIBRE_BUILD exclusion rules to not pull in gms libs

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/Request.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/SendEventWorker.kt
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt

Fixes #1300
I think it also fixes #2240

Generic hanlding of rate limit eror by the SDK

---

CHANGES.md
tools/import_emojis.py

Follow up to PR #2998 to make sure that the emoji import script does not shuffle keywords between runs.

Update import_emojis.py to retain keyword order

---

vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt

The recent EW [rework](https://github.com/matrix-org/matrix-react-sdk/pull/5727) on verification flow are not compatible with mobile implementation.
Two main issues:
- When login a new web session and trying to verify with EA:
When you type on 'Use anothe login' on web, nothing appears on mobile; And if from EA you type 'verify the new login' you will have a infinite loading
- When login in a new EA and trying to verify with EW:
EA is waiting for an incoming verification request, and this will never happen with EW recent re-work
Quick Fix
For 1: Actually the EA alert for the request from EW is there but under the 'verify this new login' green popup. to fix it EA will dismiss the green alert so that the user can see the verification request alert
For 2: EA now always send a verification …

Fix EW-EA compatibility for verification

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/registration/RegistrationWizard.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/DefaultRegistrationWizard.kt

Following Matrix spec (Fixes #3205)

RegistrationWizard.createAccount() parameters are now all optional

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/pushers/PushersService.kt
vector/src/gplay/java/im/vector/app/gplay/features/settings/troubleshoot/TestPushFromPushGateway.kt

Push can be received before the Gateway API returns, which lead to infinite loading in the notification troubleshoot screen.

Fix a race condition

---

CHANGES.md
vector/src/main/res/xml/network_security_config.xml

This functionality exists in the desktop client, so hoping to mirror that. 
This addresses a number of the use cases touched on in #1793. `localdomain` is a conventional domain that is an equivalent of the `localhost` host. Enabling clear text to `*.localdomain` means it's easier to develop the Android application, as a Matrix server can be deployed locally without much fuss anywhere on the developer's LAN. This can reduce the reliance on a DNS or SSL certificates when neither are really relevant to the interaction of the client/server. In particular, managing SSL certs without a public domain is a pain in the butt.
At the same time, this does not significantly diminish the security of Element Android, as `*.localdomain` is not a TLD so any "real" deployment still needs SSL. …

Related to #1793, allow cleartext to LAN domains

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt

Note: I'm not too familiar with kotlin coroutines yet, however, using the NonCancellable dispatcher for setting the read marker seems to fix updating the read marker automatically upon exiting the room.

Fix updating read marker automatically

---

vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
vector/src/main/java/im/vector/app/core/di/ViewModelModule.kt
vector/src/main/java/im/vector/app/core/epoxy/profiles/BaseProfileMatrixItem.kt
vector/src/main/java/im/vector/app/core/epoxy/profiles/ProfileMatrixItemWithPowerLevel.kt
vector/src/main/java/im/vector/app/core/platform/GenericIdArgs.kt
vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewState.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberSummaryFilter.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleActivity.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleFragment.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleListController.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleSharedAction.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleSharedActionViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleViewAction.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleViewEvents.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleViewState.kt
vector/src/main/res/layout/activity_simple_loading.xml
vector/src/main/res/layout/fragment_recyclerview_with_search.xml
vector/src/main/res/layout/item_profile_matrix_item.xml
vector/src/main/res/layout/item_profile_matrix_item_progress.xml
vector/src/main/res/values/strings.xml

Fixes #2970
As part of the space beta, when a user taps on the FAB of the DM tab, we will now show a new screen listing the members of that space; on select it will start a DM 
As for now it is not using directly the CreateDM activity, instead it's a new screen reusing view models as much as possible. It is also less powerfull than createDm activity (no multi select group dm creation)

Spaces | beta Browsing Member Directory In Space

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/CreateRoomParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/RoomCreateContent.kt

Use stable prefixes as msc1772 has been merged
Proposed final identifier       | Purpose | Development identifier
------------------------------- | ------- | ----
`type` | property in `m.room.create` | `org.matrix.msc1772.type`
`m.space` | value of `type` in `m.room.create` | `org.matrix.msc1772.space`
`m.space.child` | event type | `org.matrix.msc1772.space.child`
`m.space.parent` | event type | `org.matrix.msc1772.space.parent`

stable prefix for msc1772

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt
newsfragment/3396.feature

Fix #3396 
Quality 100: 1_032_382 bytes
Quality 80: 134_085
File size is 7 times smaller.

Compress thumbnail: change Jpeg quality from 100 to 80 (#3396)

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/SsoIdentityProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/Constants.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
newsfragment/3442.bugfix

stable ids for MSC 2858

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/CryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/typing/DefaultTypingService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/typing/SendTypingTask.kt
newsfragment/2449.feature
vector/src/main/java/im/vector/app/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/app/features/crypto/keys/KeysExporter.kt
vector/src/main/java/im/vector/app/features/crypto/keys/KeysImporter.kt
vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupActivity.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt
vector/src/main/java/im/vector/app/features/workers/signout/SignOutBottomSheetDialogFragment.kt
vector/src/main/java/im/vector/app/features/workers/signout/SignoutCheckViewModel.kt

Part of #2449: migrate DefaultTypingService, KeysImporter and KeysExporter to coroutines

Migration to coroutines

---

vector/src/main/res/layout/fragment_keys_backup_setup_step1.xml

Got a crash when trying to setup keybackup on logout
````
Thread: main, Exception: android.view.InflateException: Binary XML file line #97 in im.vector.app.debug:layout/fragment_keys_backup_setup_step1: Binary XML file line #97: You must supply a layout_width attribute.
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #97: You must supply a layout_width attribute.
at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:829)
at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7932)
at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8130)
at androidx.constraintlayout.widget.ConstraintLayout$LayoutParams.<init>(ConstraintLayout.java:2691)

Fix crash when setting up key backup

---

newsfragment/3207.bugfix
vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/list/SpaceChildInfoItem.kt
vector/src/main/java/im/vector/app/features/spaces/explore/SpaceDirectoryController.kt
vector/src/main/java/im/vector/app/features/spaces/explore/SpaceDirectoryViewModel.kt
vector/src/main/res/layout/item_suggested_room.xml
vector/src/main/res/values/strings.xml

Add error feedback when joining space rooms

---

changelog.d/3577.bugfix
vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt

Fix https://github.com/vector-im/element-android/issues/3577

Fix crash after video call

---

changelog.d/3605.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/SessionRealmConfigurationFactory.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/legacy/DefaultLegacySessionImporter.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/IdentityModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/db/RealmIdentityStoreMigration.kt

Thread: main, Exception: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. The most likely cause is that equals() and hashCode() are not overridden in the migration class: org.matrix.android.sdk.internal.database.RealmSessionStoreMigration
Should fix #3605

CryptoStore migration has to be object to avoid crash

---

vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt

This is useful for the P2P demo as we need to subscribe to configuration changes from a background service. The `Service` can implement `SharedPreferences.OnSharedPreferenceChangeListener` and override `onSharedPreferenceChanged` to receive notifications.

Add subscribeToChanges/unsubscribeToChanges to VectorPreferences

---

changelog.d/3624.bugfix
vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodController.kt
vector/src/main/res/values/strings.xml

The copy all refers to 'their' device for when you're verifying
someone else. Update it to refer to your own devices in the case
where you're verifying one of your own devices.
Equivalent for iOS: https://github.com/vector-im/element-ios/pull/4525

Use different copy for self verification

---

changelog.d/3634.bugfix
changelog.d/3635.feature
vector/src/main/java/im/vector/app/features/roomprofile/alias/RoomAliasAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/alias/RoomAliasController.kt
vector/src/main/java/im/vector/app/features/roomprofile/alias/RoomAliasFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/alias/RoomAliasViewModel.kt

- Fixes #3634 
- Also add retry support

Fix crash in room aliases

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/InitializeCrossSigningTask.kt

Typo in comment. Was "userSigningKey" instead of "selfSigningKey".

Typo in InitializeCrossSigningTask.kt

---

changelog.d/3655.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineControllerInterceptorHelper.kt

Scenario: the last read event in a chat is a membership change. After
that, at least two new membership changes were added, followed by normal
messages. Due to the membership changes being collapsed by default, in
this scenario the read marker would not show, since in the loop, we
would overwrite the appendReadMarker with the value for the last eventId
of the merged item, instead of showing it if any of the items matched.

Fix unread messages marker being hidden in collapsed membership item

---

changelog.d/3661.bugfix
vector/src/main/res/layout/activity_emoji_reaction_picker.xml

Emojis were not showing if not enough space, so allow scrolling there.
Before:
After:

Fix top row of emoji reaction picker on small displays

---

changelog.d/3667.feature
vector/src/debug/AndroidManifest.xml
vector/src/debug/java/im/vector/app/features/debug/DebugMenuActivity.kt
vector/src/debug/java/im/vector/app/features/debug/DebugPermissionActivity.kt
vector/src/debug/res/layout/activity_debug_menu.xml
vector/src/debug/res/layout/activity_debug_permission.xml
vector/src/debug/res/values/strings.xml
vector/src/main/java/im/vector/app/core/dialogs/GalleryOrCameraDialogHelper.kt
vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/app/core/utils/PermissionsTools.kt
vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorView.kt
vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomByQrCodeFragment.kt
vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomActivity.kt
vector/src/main/java/im/vector/app/features/usercode/ScanUserCodeFragment.kt
vector/src/main/java/im/vector/app/features/usercode/ShowUserCodeFragment.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeActions.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeActivity.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeShareViewEvents.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt
vector/src/main/res/values/strings.xml

Especially better handling of the "denied forever" permission user story.
Add a new debug screen to play with permission request from the application.
so now when requesting permissions:
- already granted: sync call (no change on this part)
- not yet granted:
- user give permission: async success
- user denies: no more thing to do, the action is not performed
- user denies and check `do not ask again`: no more thing to do, the action is not performed
- not yet granted, user has previously checked `do not ask again`:
- a dialog or a snackbar is displayed to ask the user to open the system settings to grant the permission
https://user-images.githubusercontent.com/3940906/125365236-2caa4580-e374-11eb-9cf6-3d84c2f54885.mp4

Permission rework

---

changelog.d/3656.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt

Previously, when a download was aborted (e.g. due to a bad internet
connection), a partly downloaded file was remaining in cache, which
would then be delivered upon later requests.
This can lead e.g. to chats where images aren't loading.
To avoid this, first download files to a temporary file that is not the
final cache file, and only rename/move it on finish.

Avoid incomplete downloads in cache

---

vector/src/main/res/values/strings.xml

Fixes vector-im/element-android#491
This PR standardises the spelling and casing of the following terms:
- homeserver
- identity server
- integration manager
This is a follow-up to #3680, which erroneously did not fix source translation strings.

Standardise casing of terms in source strings

---

changelog.d/3656.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/file/AtomicFileCreator.kt

Complement for #3656

---

changelog.d/3589.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportToDevice.kt

Verification flows have something called a transaction id. This is a client-set custom ID that identifies the flow and is established by the first message that gets sent out. This transaction ID needs to be kept the
same and be part of all events that are sent during the verification flow.
To-device requests have something called a transaction id. This is a client-set custom ID that identifies a given request. It is used to ensure idempotency of requests, i.e. retrying to send a request won't result in two events being sent as long as the transaction id is kept the same.
This patch removes usage of the first type of transaction ID for the second use-case.
Before:
After:
To be honest, I have no idea how that ever worked.
This closes: #3589.
Signed-off-by: Damir Jelić poljar@termina.org.uk

crypto: Don't use the transaction ID of the verification for the request

---

changelog.d/3720.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DeviceListManager.kt

The crypto DB has been deleted, and the key download request is cancelled, but in the catch block we tried to write to the deleted DB.
Tested OK on my device.

Fix a crash which can happen when user signs out.

---

changelog.d/3713.removal
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/CreateRoomParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/CreateRoomStateEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBodyBuilder.kt

Fixes #3713
Usage, for instance to set the room name (which can be done normally more simplier):
```kotlin
CreateRoomParams().apply {
initialStates.add(CreateRoomStateEvent(
EventType.STATE_ROOM_NAME,
content = RoomNameContent(
name = state.roomName
).toContent()
))
}
```
Tested OK on my side, with temporary code. There is no dedicated test for room creation yet...

Add initialState support to CreateRoomParams

---

changelog.d/3724.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/OneTimeKeysUploader.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/IMXCryptoStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt

The sync response can omit the field `device_one_time_keys_count.signed_curve25519` and the SDK was waiting to know this value to eventually upload some OTKs, even after a session creation.
Now the SDK uploads the OTK when it uploads the device keys.
This is due to recent change on Synapse sync response: https://github.com/matrix-org/synapse/pull/10214/files/7978990f5139067e1868d100d223e28e4447d2fb#diff-70f29654c1c37fb886340dc6f22a99571503f4a54dc46942ca6028b8896b00b7L254

Ensure OTKs are uploaded when the session is created

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/CryptoDeviceInfo.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/CryptoMapper.kt

This PR try to avoid creating new orphan TrustLevelEntities.
Migrate the database to delete the existing onces
On a test account, I get:
```
RealmCryptoStoreMigration: Migrating Realm Crypto from 12 to 13
RealmCryptoStoreMigration: Step 12 -> 13
RealmCryptoStoreMigration: TrustLevelEntity cleanup: 93 entities
RealmCryptoStoreMigration: TrustLevelEntity cleanup: 11 entities referenced in DeviceInfoEntities
RealmCryptoStoreMigration: TrustLevelEntity cleanup: 10 entities referenced in KeyInfoEntity
RealmCryptoStoreMigration: TrustLevelEntity cleanup: 72 entities deleted!
```
Related to #2759

Cleanup TrustLevelEntity

---

changelog.d/3793.bugfix
vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorView.kt

Tested on device with Android 11, shouldn't matter (assuming it worked before 😉)
This PR changes the order in which the items in the attachement menu appear. Currently, the ones on the right are faster than the ones on the left. Because the '+'-Button to trigger the menu is on the left, this doesn't make sense.
This behavior is more noticable if animations are disabled, because the menu doesn't have the circular mask animation. That's why the videos are recorded with animations disabled.
https://user-images.githubusercontent.com/37022952/128323836-4de37c81-6fd0-44d8-bd67-09713c635942.mp4
https://user-images.githubusercontent.com/37022952/129963137-51ae4628-c16f-44e9-9ff9-2be4550c058a.mp4

Fix attachment menu animation order

---

changelog.d/3243.bugfix
vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt

On receiving of push notifications we do a background sync to fill in missing information in the push content.
Previously we would update the notification with a call to notify but with the sound disabled in an attempt to update the notification and avoid a second notify sound.
Depending on on the time it would take to do the background sync you would sometimes see different behaviours:
- The first sound would play, the sync would complete after it had finished and the the push would be updated silently.
- The first sound would start to play,  the sync would complete during it playing and the, second call to notify would cut off the sound playing.
- The sync would complete before the sound played, the second call to notify would in effect silence the sound.
I am removing the modification …

Fix missing sounds on room notifications (messages, invitations, etc).

---

changelog.d/3743.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/RoomMemberEventHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponsePostTreatmentAggregator.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponsePostTreatmentAggregatorHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/UserAccountDataSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/model/accountdata/DirectMessagesContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/accountdata/DirectChatsHelper.kt

Fixes #3643 
Update the Account Data when an user has been invited to a DM by email (which is not bound to an existing account).
The DM is initially populated with the invited user email and stuck with this email when the user has joined Element by creating an account. Therefore, the `RoomSummary.directUserId` is also stuck on the email and does not match the otherUserId which has been updated with the user matrix id.
To handle the user registration, we catch the `m.room.member` event which contains the matrix id as part of the third_party_invite content. Then, we check the account data dictionary and update the entries matching the roomId attached to the event, and where the user id does not match the matrix id pattern.
Update the account data will then cause the update of the …

Update Account Data with user matrix id for invited user by email

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/verification/VerificationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/CancelGossipRequestWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/IncomingGossipingRequestManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/OutgoingGossipingRequestManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/SendGossipRequestWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/SendGossipWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/SendToDeviceTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/util/RequestIdHelper.kt

Complement to #3707 
Ensure that txnId is the same if the request is retried.
Also improve the value of generated requestId. We now use UUIDs

 Ensure that txnId is the same if the request is retried

---

changelog.d/1809.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSortOrder.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/query/QueryRoomOrderProcessor.kt
vector/src/main/java/im/vector/app/features/home/AvatarRenderer.kt
vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt
vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt

Resolves the first item in #1722 
Screenshots:
Signed-off-by: David Teresi <dkteresi@gmail.com>

Support Android 11 Conversation features

---

changelog.d/3927.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/MatrixError.kt

Add password matrix errors

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomJoinRulesAllowEntry.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomJoinRulesContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/ViaParameterFinder.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpace.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/joinrule/advanced/RoomJoinRuleChooseRestrictedViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt

EA was using an old format of restriced join rule
````
"join_rule": restricted
"allow" : [
{
"space" : "!mods:example.org",
"via": ["m.org","ex.org"]
}
]
````
instead of
````
"join_rule": "restricted",
"allow": [
{
"type": "m.room_membership",
"room_id": "!mods:example.org"
}
]
````

FIx / bad format of restricted join rule

---

vector/src/main/res/layout/merge_overlay_waiting_view.xml

It was causing crash with `Missing required view with ID: im.vector.app.debug:id/waiting_view`, probably due to a recent change in AGP 7.X.X. Not sure what is exactly the root cause of this crash though.
Anyway this `merge` tag was a bit useless IMHO
Fixes #3961

Remove the useless merge tag

---

changelog.d/3965.bugfix
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt

Use `ShareCompat.IntentBuilder` for sharing images. `ShareCompat` does the right thing with URI permissions so image previews show up in the Share sheet of Android 11.
Before and after:
Signed-off-by: cketti <ck@cketti.de>

Use ShareCompat.IntentBuilder for sharing images

---

changelog.d/3959.feature
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MergedRoomCreationItem.kt

This PR fixes #3959 
User power-level is now checked before showing action as set a topic or invite people to a room.
Previously, an error dialog was shown **after** the forbidden action, making a bad user experience.

Room details: check power level before displaying actions in the timeline

---

changelog.d/3956.bugfix
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileController.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewState.kt
vector/src/main/res/values/strings.xml

Fixes #3956 
Change copy to room when it's a room and space when it's a space, and remove un-needed action (jump to read receipt, mention,  secruity section..)

Fix /  Kick user dialog for spaces talks about rooms

---

changelog.d/3946.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomStrippedState.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/GetRoomSummaryTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/peeking/PeekRoomTask.kt

Fixes #3946 
Implements [MSC 3266](https://github.com/matrix-org/matrix-doc/pull/3266)
Improve Room preview by using the new Room Summary API (stripped state). This allows you to get minimum information on a room (name/topic/avatar/type/member count...) even if you cannot peek state or if it's not in public directory.
Basically if you can join the room you will get a summary.

Better room preview, use room Summary API if available

---

changelog.d/3951.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/EditablePermission.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsController.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManageActivity.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManageSharedViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedAction.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedViewEvents.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceSettingsController.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceSettingsFragment.kt
vector/src/main/res/values/strings.xml

Fixes #3951 
Change default power level to invite in private room to 50 (Moderator)
Also adding settings UX to change it

Change default power to invite in private space + setting

---

changelog.d/3947.bugfix
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/space/SpaceService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpace.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt
vector/src/main/java/im/vector/app/features/command/Command.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManageRoomsViewModel.kt
vector/src/main/res/values/strings.xml

Fixes #3947 
Handle properly m.space.parent.
Consider a m.space.parent as valid if and only if:
- There is a corresponding m.space.child the overway around
- If the m.space.parent sender is also able to send m.space.child in the parent (kind of secret sub room)
Also when removing a room from a space, if there is a pending m.space.parent relation clean it.

Fix parent relation handling

---

changelog.d/4043.bugfix
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt

Fixes #4043 
Tapping on a space invite notification, was only opening the app in the home screen.
Was acceptable for rooms as the invite would show up on top of the roomlist.
But now with spaces we need to do more (the space invite will only appear in the left drawer).
So with this PR, on notification tap a bottomsheet will appear with preview and join button:
Will work also for rooms

Show mxto bottom sheet when tapping invite notification

---

changelog.d/4011.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/InboundGroupSessionStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/MXOlmDevice.kt

Use in memory cache when adding inBoundGroupSession

---

dependencies.gradle
matrix-sdk-android/build.gradle
vector/build.gradle
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt

Adds missing orchestrator test util, this was being set in the `matrix-android-sdk` module but not in `vector`.
This should hopefully get the CI sanity test step completing again
caught by @onurays  :pray:

Fixing no tests found when running vector:connectedAndroidTest

---

changelog.d/4059.bugfix
vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt

Fix notif badge for space invite

---

changelog.d/4042.bugfix
matrix-sdk-android-rx/src/main/java/org/matrix/android/sdk/rx/RxSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/DefaultIdentityService.kt
vector/src/main/java/im/vector/app/core/utils/Dialogs.kt
vector/src/main/java/im/vector/app/features/contactsbook/ContactsBookFragment.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsFragment.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/share/ShareSpaceBottomSheet.kt
vector/src/main/java/im/vector/app/features/userdirectory/FoundThreePidItem.kt
vector/src/main/java/im/vector/app/features/userdirectory/InviteByEmailItem.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListAction.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListController.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListFragment.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewState.kt
vector/src/main/res/layout/bottom_sheet_space_invite.xml
vector/src/main/res/layout/item_invite_by_mail.xml
vector/src/main/res/values/strings.xml

This PR adds support to invite by mail from the user invite dialog.
If the search term is an email, then the app will try to lookup this email from the configured identity server. If a match is found the result will appear with some profile information, if no match it is still possible to tap the raw email and send the invite.
For now only email 3pid is supported (not phone numbers)
If there is no Identity Server the user will see a call to action to set it up
If the Identity server is setup but user didn't consent to use it, then a dedicated call to action is added:
Fixes #4042

Support entering mail in user invite screen

---

.gitignore
tools/benchmark/benchmark.profile
tools/benchmark/run_benchmark.sh

Adds a script to run the [gradle-profiler](https://github.com/gradle/gradle-profiler) so that we can start monitoring and quantifying build time improvements  
- Requires the gradle-profile to be installed
- running from the root of the repository `./tools/benchmark/run-benchmark "comma separated scenario names or blank to run all"`
The warm up and run iterations have been reduced from the defaults, makes the overall suite take less time but at the cost some reliability
Here's some early results...
```
assemble {
tasks = [":vector:assembleGPlayDebug"]
}
```
recompiling without any changes takes 1 second~ it's almost entirely gradle configuration, it shows our gradle setup isn't invaliding the configuration and causing extra processing
assemble clean builds with and without the build …

Adding benchmarking script to start monitoring build times

---

changelog.d/4057.feature
vector/src/main/java/im/vector/app/features/spaces/invite/SpaceInviteBottomSheetViewModel.kt

Quick improvement of invite bottomsheet:
Whe showing an invite we try in background to query the room Summary API to get a bit more information (like the number of members). Also it could get a more up to date strippedState than the one in the room invite sync.

Improve invite bottom sheet

---

changelog.d/4082.bugfix
vector/build.gradle
vector/src/main/java/im/vector/app/core/di/VectorComponent.kt
vector/src/main/java/im/vector/app/core/di/VectorModule.kt
vector/src/main/java/im/vector/app/core/dispatchers/CoroutineDispatchers.kt
vector/src/main/java/im/vector/app/features/crypto/keys/KeysExporter.kt
vector/src/test/java/im/vector/app/features/crypto/keys/KeysExporterTest.kt
vector/src/test/java/im/vector/app/test/fakes/FakeContext.kt
vector/src/test/java/im/vector/app/test/fakes/FakeCryptoService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt

Whilst looking into #4082 (missing content in the exported room keys) there were no obvious issues with the packing algorithm that would cause appending the trailer line to fail without the entire packing failing. 
```kotlin
outStream.write("\n".toByteArray())
outStream.write(TRAILER_LINE.toByteArray())
outStream.write("\n".toByteArray())
```
There are some stylistic differences in the packing but their logic is the same. 
```
// android
val nLines = (data.size + LINE_LENGTH - 1) / LINE_LENGTH
// web
const nLines = Math.ceil(data.length / LINE_LENGTH)
```
I suspect an error occurred on the filesystem which meant the output wasn't correctly written to disk.
This PR adds a naive file size verification after writing the exported E2E keys, this attempts to catch any file system abnormalities …

Verify exported keys output

---

changelog.d/3833.bugfix
changelog.d/4110.bugfix
vector/src/main/res/layout/fragment_room_detail.xml

Fix crash to render failed message warning stub

---

changelog.d/3898.bugfix
vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModel.kt
vector/src/test/java/androidx/lifecycle/LifecycleRegistry.kt
vector/src/test/java/im/vector/app/features/crypto/keys/KeysExporterTest.kt
vector/src/test/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModelTest.kt
vector/src/test/java/im/vector/app/test/Extensions.kt
vector/src/test/java/im/vector/app/test/InstantRxRule.kt
vector/src/test/java/im/vector/app/test/fakes/FakeCryptoService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeSharedSecretStorageService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeStringProvider.kt

Fixes #3898
When an key info response doesn't contain a passphrase the login verification flow would still attempt to visit the passphrase screen when _going back_
Fixed by simply checking if a passphrase is available when _going back_ and dismissing if no passphrase is available
- Adds a suite of tests around the `SharedSecureStorageViewModelTest`, these tests also found an issue where we're posting `ViewEvents` as part of the `ViewModel` init flow, this is problematic because we're unable to register an observer before `init` is called (will raise a separate issue)
| --- | --- |
|![before-no-passphrase](https://user-images.githubusercontent.com/1848238/135267396-2352fbc0-7bcf-4315-aec5-88ff775449e9.gif)|![after-no-passphrase](https://user-images.githubusercontent.com/1 …

Skipping passphrase screen when no passphrase is available

---

changelog.d/3935.bugfix
vector/src/main/res/layout/fragment_space_add_rooms.xml

Fixes #3935 
We should not hide the toolbar on scroll as it can have the save button

Fix do not hide toolbar on scroll

---

changelog.d/240.feature
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
vector/src/main/res/xml/automotive_app_desc.xml

Add Android Auto notification support

---

changelog.d/983.bugfix
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt

Add robustness, if Idle state is lost for any reason, the dialog will be hidden also on incr sync Events.
It does not fix the pb with foreground service notification not displayed.

Ensure initial sync progress dialog is hidden when the initial sync is over

---

changelog.d/4045.bugfix
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt

Fixes #4045 
Align default encrypted for restricted room as web is doing it, i.e use what is in well-known (default e2e).
Private and restricted encrypted switch is on if well-known e2e is by default.
=> Also if the user did manually change the encrypted toggled then always take that value and not the default.
Additional Fix:
When no space was selected, the option to set the room to restricted was visible, that would create a room restricted to nothing. So now if no space selected you'll only have a choice between Private or Public

Fix default encrypted for restricted

---

changelog.d/3347.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt

Fixes #3347 and #523 
Our notification dismissing works by matching the currently held notification events to the latest timeline chunk for the room, this presents a problem when the next chunk is created which doesn't reference those original notification events, which then presents itself as notifications not being dismissed when read from other sessions.
The fix is to check the existence of missing events against the entire chunk history if there's also a read receipt event in the latest chunk.
- I was able to to reproduce the issue by spamming messages to force the timeline to create a new chunk
Here's the worlds least exciting gif... notice the element icon in the top
| |
| --- |
|![after-new-chunk](https://user-images.githubusercontent.com/1848238/135493519-80b872e1-06cd-4b15-a364-00 …

Fixing notifications not being dismissed when read from other devices

---

changelog.d/1673.bugfix
vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt

Resending the notification here can trigger other system components or
apps that listen to new notifications, such as connected smart watches
or automation tools.
Fixes https://github.com/vector-im/element-android/issues/1673

Do not notify again for old events

---

changelog.d/4157.feature
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomAction.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomByQrCodeFragment.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt
vector/src/main/java/im/vector/app/features/userdirectory/PendingSelection.kt

In previous implementation, existing DM was checked only for QR code invites.
This PR moves this check in the ViewModel side (which makes more sense) and applies it for 1:1 in both cases (QR and user invites).

Load existing DM instead of creating a new one

---

.github/ISSUE_TEMPLATE/bug.yml
changelog.d/4076.misc

The issue form currently generates a bug report that contains the "What happened?" heading twice. See https://github.com/vector-im/element-android/issues/4047#issue-1001300890.
This PR edits the culprit heading and its subheadings to remove the redundancy and clarify what is meant.

Remove redundancy in heading in bug report issue form 

---

changelog.d/4369.bugfix
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt

The whole link base url (eg. `https://develop.element.io`) was compared to the supported hosts list instead of the host part only (`develop.element.io`), causing the link not handled anymore (displaying a malformed link dialog, which was not true...)

Fix permalink handling

---

changelog.d/4277.feature
vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt

Fixes #4277 
Orders the SSO providers by the priority in [SsoIdentityProvider](https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/SsoIdentityProvider.kt#L66)
| --- | --- |
|![before-sso](https://user-images.githubusercontent.com/1848238/139669788-1fb45561-9f55-4bf5-910d-8395a64342c8.png)|![after-sso](https://user-images.githubusercontent.com/1848238/139669785-1a4432dd-a8e6-4c7b-9deb-91ee73f440f3.png)

Sorting social providers by priority

---

changelog.d/4047.bugfix
vector/src/main/java/im/vector/app/core/services/CallRingPlayer.kt

Fixes #4047 
Out of the box android is relying on audio file metadata to determine if the ringtone should loop
- Android 9.0 introduced an api to programmatically enable looping https://developer.android.com/reference/android/media/Ringtone#setLooping(boolean)
- Users below Android 9.0 will need to select other ringtones or edit them to include a `ANDROID_LOOP true` tag

Force call ringtones to loop

---

changelog.d/4353.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/VideoCompressor.kt

Library issue: https://github.com/natario1/Transcoder/issues/154
Possibly fixes
https://github.com/vector-im/element-android/issues/4337
Also add some logging for failures.

Fix broken video compression due to NPE in library

---

changelog.d/3674.bugfix
vector/src/main/res/menu/menu_devtools.xml

Fixes #3674 Missing send icon in the light mode dev tools send event screens
Reusing the existing tint colour from the theme (matches the home screen search) 
| BEFORE LIGHT | AFTER LIGHT |
| --- | --- |
|![Screenshot_20211103_160921](https://user-images.githubusercontent.com/1848238/140099325-026a28c3-4206-4cf1-873f-6e486add5e5f.png)|![after-light](https://user-images.githubusercontent.com/1848238/140099722-61e7312e-d047-44f0-8b68-8d7dbd3fc894.png)
| BEFORE DARK | AFTER DARK |
| --- | --- |
|![Screenshot_20211103_160909](https://user-images.githubusercontent.com/1848238/140099327-5e500c59-19b4-4ea8-acce-a53ed19c61e8.png)|![after-dark](https://user-images.githubusercontent.com/1848238/140099322-fa02aa5e-e853-48ba-b202-02022cde13da.png)

Fixing missing dev tools light mode send button 

---

changelog.d/4401.removal
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/PushEvents.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/PushRuleService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/DefaultPushRuleService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/ProcessEventForPushTask.kt
vector/src/gplay/java/im/vector/app/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt
vector/src/main/java/im/vector/app/features/notifications/PushRuleTriggerListener.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsPinFragment.kt
vector/src/test/java/im/vector/app/features/notifications/NotifiableEventProcessorTest.kt
vector/src/test/java/im/vector/app/features/notifications/NotificationEventQueueTest.kt
vector/src/test/java/im/vector/app/features/notifications/NotificationFactoryTest.kt
vector/src/test/java/im/vector/app/test/fixtures/NotifiableEventFixture.kt

Some preparation/refactors around the `Push triggers` in order to support _suspending_ `NotifiableEventResolver.resolveEvent` which is required for including images in the notifications
*points to a feature branch
- `PushRuleListener` functions are replaced with a single `onEvents(PushEvents)` in order to allow any logic within the implementation to be asynchronous 
- All notification event changes are handled via the `notificationDrawerManager.updateEvents`, this ensures a single point of synchronisation and notification render pass (reduces the amount of render passes and synchronisation locks)
- Notification queue mutations are extracted to a dedicated class along with unit tests 
- Lifts the `NotifiableEvent` fixtures to a dedicated fixtures test package

Single `PushTriggerListener` dispatch

---

changelog.d/4402.feature
vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableMessageEvent.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/app/features/notifications/PushRuleTriggerListener.kt
vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt
vector/src/test/java/im/vector/app/test/fixtures/NotifiableEventFixture.kt

Fixes #1697, relies on #4401 refactor 
Adds image support to the message notifications
- Downloads the image as part of the notification event resolving chain
- Temporarily exposes the image via `FileProvider Uri` in order to allow the notifications to read and display the image
| EXPANDED GROUP WITH TEXT | EXPANDED GROUP | GROUP COLLAPSED  |  GROUP SUMMARY | SINGLE | ROOM LIST |
| --- | --- | --- | --- | --- | --- |
|![Screenshot_20211103_154653](https://user-images.githubusercontent.com/1848238/140094474-5906eaf3-7055-4fc4-8ac2-9c46d5156b96.png)|![Screenshot_20211103_154629](https://user-images.githubusercontent.com/1848238/140094480-1e42dd01-7a72-4ec5-b0fc-95928fc659ab.png)|![Screenshot_20211103_154620](https://user-images.githubusercontent.com/1848238/140094484-dafa73b1-ea77-4eb1-881d- …

Supporting images in notifications 

---

vector/src/main/java/im/vector/app/core/utils/Dialogs.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsController.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListAction.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListController.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListFragment.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
vector/src/main/res/values/strings.xml

Fixes the email invites not being available when searching for users #4297
- `onIdentityServerChange` is using exceptions to control the flow so we can't use `tryEmit` in this case. This caused the identity server steps to be missed
- `MutableStateFlow` automatically deduplicates emissions so we have to provide some more data in order to re-emit identical search terms (which the identity server steps rely on in order to refresh the page and move to the next step) 
| BEFORE | AFTER | GIF |
| --- | --- | --- | 
Copy updates 
| --- | --- |

Missing ability to invite users by email

---

changelog.d/4428.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/accountdata/RoomAccountDataDataSource.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/accountdata/UserAccountDataDataSource.kt

`toOptional()` function was safe called (prefixed by `?.`) causing the resulting Optional object to be null instead of encapsulating the null value inside the Optional object (which is the purpose of this object).

Fix potential NPE on Optional objects

---

.github/workflows/sanity_test.yml
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/SessionManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/account/DeactivateAccountTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/cleanup/CleanupSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/signout/SignOutTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt

- Reintroduces the sign out/re-signin flow to the sanity tests 
- Fixes multiple sign outs occurring whilst signing out during a sync task execution 
- Changes the Sanity check to execute on a nightly basis instead of on each pull request push
- Updates the action runner to the use hardware accelerated OSX runner 
- Fixes bad argument placement for the `--no-rate-limit` option
| GIF | 
| --- | 
|![after-sanity-2](https://user-images.githubusercontent.com/1848238/140768328-d25ce38b-f401-4a31-86fd-5ee81ce241a1.gif)

Sign out - Sign in sanity check & nightly sanity check

---

vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt
vector/src/main/res/values/strings.xml

Also prefer using ShortcutManagerCompat to disable shortcuts
After a room for which a shortcut has been pinned is left, when clicking on the disabled shortcut, we can see a Toast with:
Default message from the system
Explicit message

Add an explicit reason when shortcut are disabled.

---

.github/workflows/sanity_test.yml
vector/src/androidTest/java/im/vector/app/EspressoExt.kt
vector/src/androidTest/java/im/vector/app/espresso/tools/ScreenshotFailureRule.kt
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/MessageMenuRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/RoomListRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/settings/SettingsAdvancedRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/settings/SettingsRobot.kt

- Adds the sanity check for the developer mode options, fixes #4308 
```
- Advanced Settings 
- Account Data
- Key Requests
- Message Actions
- View Source      
```
- Improved bottomsheet waiting 
- Updates the emulator options to use the recommended optimisations https://github.com/marketplace/actions/android-emulator-runner
- Captures screenshots on sanity failure and uploads as action artifacts

Developer mode sanity check & failure screenshots

---

changelog.d/4446.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/MXKey.kt

Fix fallback otk support

---

changelog.d/4401.removal
changelog.d/4402.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/PushEvents.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/PushRuleService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/DefaultPushRuleService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/ProcessEventForPushTask.kt
vector/src/gplay/java/im/vector/app/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableMessageEvent.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt
vector/src/main/java/im/vector/app/features/notifications/PushRuleTriggerListener.kt
vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsPinFragment.kt
vector/src/test/java/im/vector/app/features/notifications/NotifiableEventProcessorTest.kt
vector/src/test/java/im/vector/app/features/notifications/NotificationEventQueueTest.kt
vector/src/test/java/im/vector/app/features/notifications/NotificationFactoryTest.kt
vector/src/test/java/im/vector/app/test/fixtures/NotifiableEventFixture.kt

Feature PR containing 
#4401 Single notification update point of entry
#4402 Supporting images in notifications
Adds image support to the message notifications
- Downloads the image as part of the notification event resolving chain
- Temporarily exposes the image via `FileProvider Uri` in order to allow the notifications to read and display the image
| EXPANDED GROUP WITH TEXT | EXPANDED GROUP | GROUP COLLAPSED  |  GROUP SUMMARY | SINGLE | ROOM LIST |
| --- | --- | --- | --- | --- | --- |
|![Screenshot_20211103_154653](https://user-images.githubusercontent.com/1848238/140094474-5906eaf3-7055-4fc4-8ac2-9c46d5156b96.png)|![Screenshot_20211103_154629](https://user-images.githubusercontent.com/1848238/140094480-1e42dd01-7a72-4ec5-b0fc-95928fc659ab.png)|![Screenshot_20211103_154620](https://use …

Notification images

---

.github/ISSUE_TEMPLATE/enhancement.yml
changelog.d/4257.misc

This is a similar PR to #4076. It removes a redundant sentence.

Remove redundant text in feature request issue form

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt

Render markdown in room list

---

changelog.d/4480.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionListeners.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt

Fixes an intermittent crash on sign out caused by a race condition where we attempt to access an already closed session causing it to be recreated which in turn causes realm to crash because the new session is slightly different.
the race condition boils down to...
```kotlin
sessionComponents.remove(sessionId)
runOnUiThread {
if (sessionParamsStore[sessionId] != null) {
val session = sessionComponents.getOrCreate(sessionId).session()
onStopped(session)
}
} 
sessionParamsStore.delete(sessionId)
```
- The solution is to avoid using the `SessionManager` within the `SessionListeners` and instead pass the current session directly (to avoid creating a new one), which we were already doing in most cases
| --- | --- |
|![before-signout](https://user-images.githubusercontent.com/ …

Sign out crash - Realm configuration mismatch 

---

changelog.d/3477.feature
changelog.d/452.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/ContentUtils.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/TextComposerViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt

Replacement for #4426 and #2694

Markdown and sploiler in roomlist + spoiler in notifications

---

.github/workflows/sanity_test.yml
vector/src/androidTest/java/im/vector/app/EspressoExt.kt
vector/src/androidTest/java/im/vector/app/espresso/tools/WaitActivity.kt
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/MessageMenuRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/RoomSettingsRobot.kt

- Makes the Sanity github action fail on error and use a Pixel 5 profile
- Adds waits for bottom sheets and dialogs
- Increases default espresso timeouts from 60 seconds to 120
- Increases text length in the edit text check as the runner tends to tap the "(edited)" part which opens a different bottom sheet

UI test CI tweaks

---

vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/features/MainActivity.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationEventPersistence.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationEventQueue.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationState.kt
vector/src/test/java/im/vector/app/features/notifications/NotificationEventQueueTest.kt

Fixes #4505 Notifications not automatically dismissing, this is caused by the in memory tracking being out of sync.
The most likely trigger of this issue is the android OS reclaiming memory and killing the Element app whilst it's idle in the background (which is perfectly normal)  
- The loading of the persisted events was happening before the current session was active which meant we weren't able to read any previously persisted events.
- Preloads the in memory cache of rendered events with the last known persisted events (this fixes the original issue)
- Persists the event queue every time we receive a new event instead of when the app moves to the background, this allows us to handle crash cashes where the app doesn't gracefully move to the background 
- Also extracts out the …

Non dismissing notifications

---

vector/lint.xml
vector/src/fdroid/java/im/vector/app/di/FlavorModule.kt
vector/src/gplay/java/im/vector/app/di/FlavorModule.kt
vector/src/main/java/im/vector/app/core/di/HomeModule.kt
vector/src/main/java/im/vector/app/core/di/ScreenModule.kt
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/main/java/im/vector/app/features/home/HomeModule.kt

See https://github.com/google/dagger/releases/tag/dagger-2.25.2 point 2.ii. : @Module object classes no longer need @JvmStatic on the provides methods.
Ensure this warning does not appear again.

Fix "@JvmStatic used for @Provides function in an object class" Lint warning

---

changelog.d/3833.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageHelper.kt
vector/src/main/java/im/vector/app/features/voice/AbstractVoiceRecorder.kt

Breaking down #4527 into smaller PRs
- Fixes https://github.com/vector-im/element-android/issues/3833
- Makes each voice message file unique to avoid us deleting or overwriting any pending files
- Provides a human readable name via the ContentResolver  
- Fixes edits not working (broken on develop only)
| BEFORE EDIT | AFTER EDIT |
| --- | --- |
|![before-edit-message](https://user-images.githubusercontent.com/1848238/143080543-30a8dbb1-946e-4bcf-b7fb-6478d8976d9c.png)|![after-edit-message](https://user-images.githubusercontent.com/1848238/143079954-82ba36c7-30cb-4709-960a-96d5771764ac.png)
| BEFORE PENDING OFFLINE | AFTER PENDING OFFLINE |
| --- | --- |
|![before-offline-vm](https://user-images.githubusercontent.com/1848238/143080582-b2a4f159-13b2-46f1-82e9-edbfbdb11eec.gif)|![after-offli …

Timeline editing and offline voice message fixes

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/UserDraft.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/DraftMapper.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt

Extracted from #4527 
- Renames the `UserDraft` and `SendMode` child class names to `CamelCase`
- Removes unused base properties from the sealed classes
- Switches sealed classes to interfaces to help enforce no base properties

Voice related sealed class cleanup

---

changelog.d/4552.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/content/ContentAttachmentData.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt
vector/src/main/java/im/vector/app/features/attachments/AttachmentsMapper.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/voice/AbstractVoiceRecorder.kt

Fixes #4552 .ogg files failing to upload
- We were inferring that uploaded `.ogg` audio files were our temporary voice messages and attempting to delete, android throws a security exception as we open external files as read only which caused the upload to fail entirely.
- Adds a dedicated `VOICE_MESSAGE` type in order to only delete the files which we control
| PENDING VOICE MESSAGE | FILE EXISTS | VOICE MESSAGE SENT | FILE DELETED |
|![Screenshot_20211124_103538](https://user-images.githubusercontent.com/1848238/143222863-993dc393-d2fa-40bc-8744-2afe6327348a.png)|![2021-11-24T10:36:15,422339591+00:00](https://user-images.githubusercontent.com/1848238/143222871-22af5a9e-ceb2-4b9d-ab64-a29608db24ee.png)|![Screenshot_20211124_103640](https://user-images.githubuserco …

Unable to upload .ogg to rooms

---

changelog.d/3449.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/AutoCompleter.kt

Fixes #3449 Leftover characters when inserting emojis by text.
This was a really strange issue, it seemed to only affect single character look ups eg `:a` but didn't affect all emojis equally, `:z` worked without issue. There's no obvious place where we're incorrectly manipulating the message text content and replacing the `replace` with a `delete + insert` also fixed the issue... perhaps some lingering spans in some cases?  
- Also fixed the emoji replacement always using the last `:` by taking into account the current cursor position
| BEFORE INSERT EMOJI | AFTER INSERT EMOJI |
| --- | --- |
|![before-emoji-text](https://user-images.githubusercontent.com/1848238/143578862-3884250b-ea91-4315-96f6-61cec3b0da6b.gif)|![after-emoji-text](https://user-images.githubusercontent.com/1848238/14357 …

Emoji insertion leftover characters 

---

changelog.d/4488.bugfix
vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt

Fixes https://github.com/vector-im/element-android/issues/4488
- Stops the guard service on clearActiveSession (sign out), the service is already tied to `setActiveSession` 
| --- | --- |
|![before-signout-notifications](https://user-images.githubusercontent.com/1848238/143559769-e49a27c1-7f55-4c16-b87b-bb0cfc6046bf.gif)|![after-signout-notification](https://user-images.githubusercontent.com/1848238/143559787-89967a33-27c2-490c-a0c8-e45104b8d601.gif)

Dismissing Fdroid variant `Listening for notifications` on sign out

---

changelog.d/4067.bugfix
vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/main/java/im/vector/app/core/time/Clock.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceMessageRecorderView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceMessageViews.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt

Fixes #4067 Allows the device to rotate whilst recording a voice message
- Makes the `VoiceMessagePlaybackTracker` a singleton to avoid losing any state on activity destruction (means we need to be extra careful with releasing the listeners)
- Holds onto the recording start time in order to maintain the current recording length after rotation
- Checks if the device is actively recording a voice message and going through a configuration change, if so we don't stop the recording or save any drafts
| --- | --- |
|![before-vm-rotation](https://user-images.githubusercontent.com/1848238/143258150-e0b802fd-7666-40af-a387-3677e8ad73da.gif)|![after-vm-rotation](https://user-images.githubusercontent.com/1848238/143258145-25006a9e-2eff-4b14-95ad-8c47f60103a5.gif)

Supporting rotation during voice recordings

---

changelog.d/4022.bugfix
vector/src/main/java/im/vector/app/core/extensions/Activity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageHelper.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/VoiceMessagePlaybackTracker.kt

Fixes #4022 Forces the device screen to stay awake during voice message playback and recording, this state is only active for the room details activity.
No gifs this time as it requires unplugging the device

Keep device screen on during voice message playback and recording

---

changelog.d/4144.bugfix
vector/src/main/java/im/vector/app/features/call/CallControlsView.kt

Fixes the symptom of #4144 
- Updates the `VectorCallActivity` to always show the hang up button during the initial phases of a VOIP call (`Idle, Create Offer`, matching the `Dialing` behaviour) 
At least from the logs submitted in #4144 there was a native media player error which we're not able to propagate up to our `CallActivity` which means we end up stuck in the `Idle` call state. I can't seem to find a way to hook into player errors via the `RemoteAudioTrack` :thinking:  
The only way I've been able to reproduce this issue is by instantly recreating the call (`Activity.recreate`) when it starts. 
| --- | --- |
|![before-stuck-voip](https://user-images.githubusercontent.com/1848238/143611425-4fe8cc97-b2a9-4f31-8c41-17211f06f0eb.gif)|![after-stuck-voip](https://user- …

Always showing hang up button in VOIP calls

---

changelog.d/4577.feature
vector/src/main/java/im/vector/app/core/utils/Dialogs.kt
vector/src/main/java/im/vector/app/features/contactsbook/ContactsBookFragment.kt
vector/src/main/java/im/vector/app/features/contactsbook/ContactsBookViewEvents.kt
vector/src/main/java/im/vector/app/features/contactsbook/ContactsBookViewModel.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsFragment.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsViewModel.kt
vector/src/main/java/im/vector/app/features/discovery/Extensions.kt
vector/src/main/java/im/vector/app/features/discovery/IdentityServerWithTerms.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListAction.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListFragment.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewEvents.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
vector/src/main/res/values/strings.xml

Implements #4577 
New dialogs: https://github.com/vector-im/element-android/issues/4577#issuecomment-982701319
We need to retrieved the T&C, that's why many changes are necessary. Sadly there is some code duplication between the ViewModels, we may find a way to reduce that later.

Iterate on user consent dialog for identity server

---

changelog.d/3922.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/content/ContentAttachmentData.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/UserDraft.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/DraftMapper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/DraftEntity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageHelper.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceMessageRecorderView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceMessageViews.kt
vector/src/main/java/im/vector/app/features/voice/AbstractVoiceRecorder.kt
vector/src/main/java/im/vector/app/features/voice/VoiceRecorder.kt

Fixes #3922 Continuation of @onurays #4237 rebased and squashed with all of the refactors around the `VoiceMessageRecorderView` and `MessageComposerViewModel` refactors (and also #4527)
- Introduces a `UserDraft.Voice` and `SendMode.Voice` in order to differentiate between audio messages
- Handles drafts as part of the moving to background flow (when not rotating) 
- Adds an initialisation step to preload the voice recorder
- Simplifies the `VoiceRecordingView` callbacks to have explicit actions instead of exposing internal `RecordingUiStates`
| --- | --- |
|![before-voice-draft](https://user-images.githubusercontent.com/1848238/142663244-14d8db9d-86bb-45b3-93d2-f5c8da426562.gif)|![after-voice-draft](https://user-images.githubusercontent.com/1848238/143283384-660b978b-1 …

Adding support for voice drafts

---

vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageHelper.kt

- Fixing voice messages from _erroring_ on android 28 and below due to attempting to convert already converted audio files. This was caused by the draft flow converting the audio files to `.ogg` but expecting them to still be `.mp4` 
Fixed by only converting to .ogg as part of the sending process
*nexus 4 5.1.1
| AFTER DRAFT | AFTER PLAYBACK |
| --- | --- | 
|![Screenshot_20211201_152808](https://user-images.githubusercontent.com/1848238/144263158-17274b5c-3579-43b8-b6ce-e29999121e28.png)|![Screenshot_20211201_152823](https://user-images.githubusercontent.com/1848238/144263155-69a0bdc5-aa0b-41be-ae4f-30653c11b923.png)

Fixed voice messages on Android 28 and below

---

changelog.d/4605.bugfix
multipicker/src/main/java/im/vector/lib/multipicker/ContactPicker.kt
multipicker/src/main/java/im/vector/lib/multipicker/FilePicker.kt
multipicker/src/main/java/im/vector/lib/multipicker/utils/ContentResolverUtil.kt
vector/src/main/java/im/vector/app/core/contacts/ContactsDataSource.kt
vector/src/main/java/im/vector/app/core/intent/Filename.kt

Use androidx.core.database extension for better nullability check, and ignore uncomplete data.
Regression from 1.3.7, 1.3.8 not released, so let's merge this PR before release 1.3.9
Fixes #4605

Add robustness when getting data from cursors.

---

changelog.d/4324.bugfix
vector/src/main/java/im/vector/app/core/epoxy/Listener.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt

Fixes #4324 URL long presses opening menu and copying
- Infers that a Clickable span has been pressed by the presence of a selection (from this handy SO https://stackoverflow.com/a/35696744)
| --- | --- |
|![before](https://user-images.githubusercontent.com/1848238/144444423-7b29209b-179d-4171-bca7-265eaf40b4c8.gif)|![after](https://user-images.githubusercontent.com/1848238/144444404-46664802-5f8c-486b-81e9-cde60afd2ad4.gif)
This does pose the question of whether we should have link copying at all as the message menu already contains a `Copy` item cc @daniellekirkwood

Avoiding duplicate message long press events 

---

build.gradle
changelog.d/4647.misc
matrix-sdk-android/build.gradle

Get OLM library from our maven repository, and upgrade it from 3.2.4 to 3.2.7
Related: https://gitlab.matrix.org/matrix-org/olm/-/issues/5 and following instruction from https://gitlab.matrix.org/matrix-org/olm/-/packages/43 .
Issue like that should not happen anymore #3150 #4271
Dependabot should be able to create PR for automatic update of the lib 🤞

Upgrade OLM to v3.2.7 and get it from our maven repository.

---

changelog.d/4278.feature
library/ui-styles/src/main/res/values/dimens.xml
vector/src/main/java/im/vector/app/core/ui/views/SendStateImageView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/BaseEventItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/url/PreviewUrlView.kt
vector/src/main/res/drawable/ic_close_with_circular_bg.xml
vector/src/main/res/layout/item_timeline_event_base.xml
vector/src/main/res/layout/item_timeline_event_text_message_stub.xml
vector/src/main/res/layout/view_url_preview.xml

Fixes #4278 Url preview design updates
- Updates the send status icon to force all message types to include a right gutter, fixes inconsistent message sizes when the send status is present
| BEFORE LIGHT | AFTER LIGHT
| --- | --- |
|![Screenshot_20211201_172552](https://user-images.githubusercontent.com/1848238/144283166-7ec7f30f-bbf6-4225-b5f9-7282309e83ad.png)|![Screenshot_20211202_101758](https://user-images.githubusercontent.com/1848238/144402942-c823795c-5937-47b6-898f-0fb3b197eeae.png)
| BEFORE DARK | AFTER DARK |
| --- | --- |
|![Screenshot_20211201_172540](https://user-images.githubusercontent.com/1848238/144283192-d9c561c0-57b4-40f9-8955-66fed9cde8fe.png)|![Screenshot_20211202_101810](https://user-images.githubusercontent.com/1848238/144402960-58955345-a1d3-4b36-ad43-e99473f4aa1b. …

Updating URL preview design

---

changelog.d/4693.bugfix
vector/src/main/java/im/vector/app/features/spaces/SpaceSummaryController.kt

When you have two root spaces with the same space as subspace, and you expand both root spaces, you end up with two times the same id in the list. This has two problems:
- The expand animation is slightly broken, if you expand the second root space first and then the first one
- If you select one of these items with same id, the app crashes:
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
As solution, just prefix the epoxy item ids with the parent spaces.

Fix possible crash when having identical subspaces in multiple root spaces

---

changelog.d/4600.misc
vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchResultController.kt
vector/src/main/java/im/vector/app/features/roomprofile/alias/RoomAliasController.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedMemberListController.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListController.kt
vector/src/main/java/im/vector/app/features/roomprofile/notifications/RoomNotificationSettingsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/files/UploadsFileController.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/media/UploadsMediaController.kt
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleListController.kt

Fix issue 4600 that search results sometimes are not displayed properly

---

changelog.d/3473.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/sync/model/SyncResponse.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/MXOlmDevice.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/OneTimeKeysUploader.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/rest/KeysUploadBody.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/UploadKeysTask.kt

Olm uses a set of one-time keys when initializing a session between two devices: Alice uploads one-time keys to her homeserver, and Bob claims one of them to perform a Diffie-Hellman to generate a shared key. As implied by the name, a one-time key is only to be used once. However, if all of Alice's one-time keys are claimed, Bob will not be able to create a session with Alice.
A new response parameter, `device_unused_fallback_key_types` is added to /sync. If the client wants the server to have a fallback key for a given key algorithm, but that algorithm is not listed in `device_unused_fallback_key_types`, the client will upload a new key.
Here is the proposed logic to decide whether we need to generate a new fallback keys or not:
```
// The presence of device_unused_fallback_key_types …
```

Fallback keys implementation

---

changelog.d/4559.feature
vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt

Still possible to opt-in from the settings.
Also add changelog for the previous PR.
Tested OK using the Analytics debug screen.

Disable automatic opt-in screen display

---

changelog.d/2467.bugfix
vector/src/main/java/im/vector/app/features/call/CallProximityManager.kt

Fixes #2467 Proximity sensor not releasing
Wake locks are reference counted which means we would need to release as many times as we acquire in order to full release the proximity sensor. It's possible that the `onProximityNear` / `onProximityFar` may not trigger as cleanly as we expect on some devices which can cause multiple wakelock acquires 
- Guards the proximity wake lock acquiring by checking if we already have one active.
----
was able to reproduce the original issue by commenting out the `onProximityFar` and triggering the proximity sensor multiple times whilst in a call

Proximity sensor not releasing

---

changelog.d/4710.bugfix
vector/src/main/res/layout/view_current_calls.xml

Fix #4710 
|Before|After|
|-|-|
|<img width="484" alt="image" src="https://user-images.githubusercontent.com/3940906/145999272-fb8144fd-b235-41dc-9db3-e7f9922ba1fb.png">|<img width="311" alt="image" src="https://user-images.githubusercontent.com/3940906/146267065-471d90ec-39cb-4317-8d10-382e5707b5b5.png">|

Call banner: center text vertically

---

changelog.d/4713.misc
vector/src/main/java/im/vector/app/core/platform/VectorBaseFragment.kt

Fixes #4713 leaking activity windows
Currently when we display loading dialogs we don't take into account if they're still displaying when destroying the associated fragment, dismissing them when destroying them avoids leaking the parent activity window

Avoid leaking Activity Window when showing loading dialog

---

changelog.d/4700.bugfix
vector/src/main/res/layout/view_stub_room_member_profile_header.xml

In the room member profile header, when the name is too long the name and the shield are not completely visible.
Screen after the fix:

Small UI fix in room member profile hearder

---

changelog.d/4743.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt

Fixes #4743 
A follow up to the original emoji fix #4698, we had a missing case (the emote section eg `/me :tada:`) 
| --- | --- |
|![before-emoji-crash](https://user-images.githubusercontent.com/1848238/146430061-2d209831-7d68-4ffb-9f6c-6727941d46bf.gif)|![after-emoji-crash](https://user-images.githubusercontent.com/1848238/146430064-b7194ff7-c092-4d5e-b284-3142657115f2.gif)

Emojis in emotes causing crashes on Android 12+

---

changelog.d/4733.bugfix
vector/src/androidTest/java/im/vector/app/features/html/SpanUtilsTest.kt
vector/src/main/java/im/vector/app/EmojiCompatWrapper.kt
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/reactions/ViewReactionsEpoxyController.kt
vector/src/main/java/im/vector/app/features/html/SpanUtils.kt
vector/src/main/java/im/vector/app/features/reactions/widget/ReactionButton.kt

Fixes #4733 
The timeline is failing to render whilst the emoji library is initialising. Fixed by using our safe wrapper which we already use in other places with emoji capabilities 
```
E/ /Tag: failed to create message item
java.lang.IllegalStateException: Not initialized yet
at androidx.core.util.Preconditions.checkState(Preconditions.java:1)
at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:3)
at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:2)
at im.vector.app.features.html.SpanUtils.getBindingOptions(SpanUtils.kt:1)
at im.vector.app.features.home.room.detail.timeline.factory.MessageItemFactory.buildMessageTextItem(MessageItemFactory.kt:1)
at im.vector.app.features.home.room.detail.timeline.factory.MessageItemFactory.buildItemForTextContent(MessageItemFactory.kt …
```

Unable to render messages

---

changelog.d/4742.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/tools/EventRenderingTools.kt

This PR fixes the long press crash on a reply event on develop branch. Somehow in production works.

Fix crash ImmutableModelException

---

changelog.d/4769.bugfix
vector/src/main/java/im/vector/app/features/html/SpanUtils.kt

Fixes #4769 emojis still crashing on android 8.1.1 and below
From the user rageshake reports we can still see emoji crashes in 1.3.11, the original fix #4698 is still valid, we were however bypassing it for android versions 8.1.1 android below
*an 8.1.1 emulator with google play services
| --- | --- |
|![Screenshot_1639994544](https://user-images.githubusercontent.com/1848238/146750919-c7b7bb2a-4c04-415f-b41e-353d84370bda.png)|![Screenshot_1639994587](https://user-images.githubusercontent.com/1848238/146750916-637f623e-6757-4e16-abd2-cd2668026bd5.png)

Fixing Android 8.1.1 / 27 and below emoji crash

---

changelog.d/4612.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncWorker.kt

Workaround to fetch all the pending toDevice events from a Synapse homeserver

---

changelog.d/4756.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/composer/ComposerEditText.kt

Fixes #4756 Inconsistent emoji input in the composer view
- Switches the `ComposeEditText` base view to the `AppCompatEditText` which now supports emojis out of the box
| --- | --- |
|![before-new-emoji](https://user-images.githubusercontent.com/1848238/146574235-85f09a53-e200-4a9e-a52a-1f4817b664d8.gif)|![after-new-emoji](https://user-images.githubusercontent.com/1848238/146574229-8984f4bb-8653-4418-b596-52872af650fe.gif)

Wrong emojis in composer

---

changelog.d/4804.bugfix
vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt

Fixes #4804 mute events displaying blank notifications
- It turns out the app was assuming all encrypted events were messages, which meant we were showing invalid notifications
- The fix is to only create `NotifiableMessageEvent` when the decrypted or clear content type is a `message`
- This also ends up fixing the debug and duplicated VOIP notifications appearing as w were using the same filtering logic for the timeline as the notifications
| --- | --- |
|![before-muting](https://user-images.githubusercontent.com/1848238/147348731-ca400f69-e4d2-4a0e-baad-ff7a1f3c2f54.gif)|![Screenshot_20211224_111636](https://user-images.githubusercontent.com/1848238/147348734-0e69407b-52ae-4672-a3ba-311360889297.png)

Fixing duplicated/empty notifications when joining/muting/leaving a VOIP call

---

changelog.d/4767.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/FileUploader.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt

Fixes #4767 Unable to change avatar
We had a report of `NetworkOnMainThread` whilst changing avatar, I've been unable to reproduce the issue but did notice we have an unnecessary main thread dispatcher being used (looks like it was introduced as part of the suspend migration).
- Switches the `main` dispatcher to `io`, the user has also confirmed this fixed their issue
- Bundles the file reading + temp file creation into the same io context 
| |
| --- |
|![changing-avatar](https://user-images.githubusercontent.com/1848238/146909084-71fde02c-2517-42a5-93f2-f7402537ed24.gif)

Unable to change avatar due to `NetworkOnMainThread`

---

changelog.d/4745.misc
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt

- The implementation of **sharing text** and **sharing media** is updated to use the `ShareCompat.IntentBuilder` API.
- The UI does not change.
- Screenshot of the system share chooser UI for sharing a file.
- Screenshot of the system share chooser UI for sharing an image.
- Screenshot of the system share chooser UI for sharing plain text.

Use ShareCompat.IntentBuilder for sharing content

---

changelog.d/4847.bugfix
vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
vector/src/main/res/values/strings.xml

Update error message when joining room

---

changelog.d/4749.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt

If there are no messages in a room lastPreviewableEvent will be null. We should not indicate there is an unread if we don't have a lastPreviewableEvent.
Fixes #4749

Fix unread messages indicator on room list if no messages

---

vector/build.gradle

Dependabot does not care about this dependency, I do not know why.

Manual upgrade of the emoji2 lib

---

vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt
vector/src/main/java/im/vector/app/core/utils/SystemUtils.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt

Remove unused methods.
Following change from PR #4745

Small cleanup

---

changelog.d/4719.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
vector/src/main/java/im/vector/app/features/analytics/DecryptionFailureTracker.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt

Fixes #4719
Track and report failure to decrypt errors

Track decryption failures

---

changelog.d/4781.bugfix
vector/src/main/java/im/vector/app/core/services/CallRingPlayer.kt
vector/src/main/java/im/vector/app/core/services/CallService.kt

Tentatively fixes #4781 wrong audio device being used for outgoing call ringtone
- In #4781 it's reported that the correct audio device is used when the call starts, the attempted fix is to use the same audio device configuration for the outgoing ringtone as we do for the call itself. 
I haven't been able to reproduce this locally, I'm assuming it's something related to LineageOS

Outgoing call ringtone using wrong audio device

---

changelog.d/4789.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt

Tentatively fixes #4789 Timeline crashes when quickly scrolling or restoring state.
I was unable to reproduce this crash locally, the stack trace looks to be the same as when a `TextView` is modified after setting a `TextFuture`
```
Thread: main, Exception: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.
at android.widget.TextView.setText(TextView.java:6206)
at android.widget.TextView.setText(TextView.java:6124)
at android.widget.TextView.setText(TextView.java:6076)
at androidx.core.widget.TextViewCompat.setPrecomputedText(TextViewCompat.java:907)
at androidx.appcompat.widget.AppCompatTextView.consumeTextFutureAndSetBlocking(AppCompatTextView.java:542)
at androidx.appcompat.widget.AppCompatTextView.getText(AppCompatTextView.java …
```

Timeline recycling crash

---

changelog.d/4644.misc
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomByQrCodeFragment.kt
vector/src/main/java/im/vector/app/features/qrcode/QrCodeScannerFragment.kt
vector/src/main/java/im/vector/app/features/usercode/ScanUserCodeFragment.kt
vector/src/main/res/layout/fragment_qr_code_scanner.xml
vector/src/main/res/layout/fragment_qr_code_scanner_with_button.xml

Toolbar is added to screens with QR code scanner. 
| CreateDirectRoomByQrCodeFragment | ScanUserCodeFragment | QrCodeScannerFragment |
| ------------- | ------------- | ------------- |
| ![photo_2022-01-06_17-14-41](https://user-images.githubusercontent.com/66663241/148414360-912d3306-7fcf-40fe-bf3a-63049d80e472.jpg) | ![photo_2022-01-06_17-15-07](https://user-images.githubusercontent.com/66663241/148414379-5bfc7019-fb8f-43b1-b9d6-4029a9d5064d.jpg)| ![photo_2022-01-06_17-15-11](https://user-images.githubusercontent.com/66663241/148414394-bcc9d11d-d512-4cb0-b0d4-34594cc48560.jpg)|
fixes #4644

Toolbar is added to a views with QR code scan

---

changelog.d/4872.misc
vector/build.gradle

Switches the build config to point to the `FTUE_AUTH` onboarding variant, this variant is a copy of the current (legacy login) with separate feature flags for future changes, eg  #4727 and #4585 
- The `FTUE_AUTH` flow also includes #4668  
| BEFORE SPLASH | AFTER SPLASH | 
| --- | --- |
|![Screenshot_20220106_172749](https://user-images.githubusercontent.com/1848238/148425932-e74c0d5d-afd4-43af-9f3b-b184c2dae7e5.png)|![Screenshot_20220106_173520](https://user-images.githubusercontent.com/1848238/148425830-b6d901ae-5bf2-42d0-a1cd-fac87cbfd4fa.png)
| BEFORE FEATURES | AFTER FEATURES |
| --- | --- |
|![Screenshot_20220106_172757](https://user-images.githubusercontent.com/1848238/148425930-764a631f-4483-45c2-b070-ee4f3bf97bcb.png)|![Screenshot_20220106_173528](https://user-images.githubuserco …

Enabling FTUE_AUTH onboarding variant

---

.github/workflows/quality.yml
changelog.d/4864.misc
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/LiveDataTestObserver.java

Improve Github Actions Linter reports:
- Add **ktlint** Artifact report
- **kotlint reports will be also added as comment in the PR**
- It will print exactly the lines that have problem
- It will trim the output so the developer will be able to immediately find the class with the error
- Support for all the different modules along with tests 
- The same comment will be reused
- It is also able to identify the success and print the result appropriately

Enhance Linter Github Actions Reporting

---

.github/workflows/quality.yml

While `lintOptions {
abortOnError true
}` 
lets always run the artifact uploading step

Minor lint fix

---

.github/workflows/quality.yml
changelog.d/4888.misc

This PR will contain the following changes:
- Do not add GitHub comments on successful `ktlint` runs
- Remove already existing comments when `ktlint` succeed

Add comment only on ktlint fail

---

.idea/dictionaries/bmarty.xml
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/EventStreamService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/LiveEventListener.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/ToDeviceService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmDecryptionFactory.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultEventStreamService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultToDeviceService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/StreamEventsManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEventPersistor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomSyncHandler.kt
tools/check/forbidden_strings_in_code.txt
vector/src/main/java/im/vector/app/AutoRageShaker.kt
vector/src/main/java/im/vector/app/UISIDetector.kt
vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReportActivity.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
vector/src/main/java/im/vector/app/features/rageshake/ReportType.kt
vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
vector/src/main/res/values/strings.xml
vector/src/main/res/xml/vector_settings_labs.xml

Fixes #4263
Adds a new lab option to enable auto reporting of fail to decrypt errors. When detected the device will send a rageshake and then send a toDevice message to the other participant to request him to also upload a RS.
The AutoRageShake and UISIs detection part has been put in the app side, and in order to do that I added to new services in the SDK:
- SendToDeviceService: A service that allows to send to device messages (needed by AutoRageshaker in order to ask for the matching rageshake)
- EventStreamService: Provides entry points needed by the UISI detector (could not be done by listening at the db events..)
@ganfra / @bmarty  If you could have a quick look on the SDK part and give some feedbaks
Sample report 
https://github.com/matrix-org/element-android-rageshakes/issues/27579

Auto report unable to decrypt errors via lab option

---

changelog.d/4892.feature
vector/src/androidTest/java/im/vector/app/espresso/tools/WaitActivity.kt
vector/src/androidTest/java/im/vector/app/ui/robot/AnalyticsRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt

Enable automatic display of opt-in screen.
This reverts commit 08def813cc8e0dcadb68330692e358c5dea7a71a.
Also update the test so that it handles the new opt-in screen and the new FTUE flow.
Fixes #4875

Revert "Disable automatic opt-in screen display."

---

build.gradle
changelog.d/4882.misc
dependencies_groups.gradle
matrix-sdk-android/build.gradle

And upgrade to Olm <del>3.2.9</del> **3.2.10**
Sanity test pass.

Olm lib is now hosted in MavenCentral

---

changelog.d/4735.bugfix
vector/src/main/java/im/vector/app/features/poll/create/CreatePollFragment.kt
vector/src/main/java/im/vector/app/features/poll/create/CreatePollViewModel.kt

Workaround to not to reuse poll option cells

---

library/ui-styles/src/main/res/drawable/bg_carousel_page_1.xml
library/ui-styles/src/main/res/drawable/bg_carousel_page_2.xml
library/ui-styles/src/main/res/drawable/bg_carousel_page_3.xml
library/ui-styles/src/main/res/drawable/bg_carousel_page_4.xml
vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
vector/src/main/java/im/vector/app/core/extensions/Integer.kt
vector/src/main/java/im/vector/app/core/extensions/ViewPager2.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashCarouselFragment.kt

Part of #4584
- Adds automatic 5 second rotation to the Ftue auth carousel
- Also included a super handy extension from [SO](https://stackoverflow.com/questions/57505875/change-viewpager2-scroll-speed-when-sliding-programmatically/59235979#59235979) to control the view pager page transition speed as it's too fast out of the box
- Fixes the carousel direction for RTL locales
| GIF | RTL
| --- | --- |
|![device-2021-12-16-144427](https://user-images.githubusercontent.com/1848238/146399095-f75eb89d-bf78-419c-8f3a-2c6a49c25e0c.gif)|![after-rtl](https://user-images.githubusercontent.com/1848238/148559619-10ff05ce-fdc6-40bd-b202-fe75ffa5ad0a.gif)

Automatic carousel rotation

---

vector/src/main/res/values/strings.xml

Fixes #4903 
Haven't created a changelog entry as the feature isn't enabled/live yet

Typo in carousel title

---

changelog.d/4924.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/TimelineEventEntityHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomGetter.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt

Ensure that algorithm instance is created and cached when setEncryptionInRoom is called even if no alg change

Ensure algorithm instance is created and stored

---

changelog.d/4926.misc
gradle.properties
vector/build.gradle

To be able to test the release build sooner during the release process.

Add signing config for the release. No secret added

---

changelog.d/4895.removal
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/encryption/EncryptionTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/state/StateService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoom.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/SendStateTask.kt
vector/src/main/java/im/vector/app/features/devtools/RoomDevToolViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/permissions/RoomPermissionsViewModel.kt
vector/src/main/java/im/vector/app/features/widgets/WidgetPostAPIHandler.kt

Should always be an empty String according to the Matrix specification.
There is no functional change, just a change in the SDK API for clarity regarding the Matrix specs.

Avoid allowing null String for state_key.

---

vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashCarouselFragment.kt

Part of #4584
- Disables the automatic carousel transitions once the user interacts with the carousel
| --- | --- |

Disabling automatic carousel transitions on user interaction

---

library/ui-styles/src/main/res/values-sw600dp/tablet.xml
library/ui-styles/src/main/res/values/tablet.xml
vector/src/main/java/im/vector/app/core/platform/ScreenOrientationLocker.kt
vector/src/main/java/im/vector/app/features/analytics/ui/consent/AnalyticsOptInActivity.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingVariantFactory.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt

Part of #4584 
- Makes use of a resource bucket flag to determine if the device is big enough to be considered a tablet and in turn, enable a landscape experience in the FTUE auth onboarding flow
| BEFORE PHONE | AFTER PHONE | AFTER LOGIN | AFTER TABLET |
|![before-rotation](https://user-images.githubusercontent.com/1848238/148992078-02c1ea01-beeb-47b5-8eab-ad55a5487409.gif)|![after-rotation](https://user-images.githubusercontent.com/1848238/148992075-61403f61-d115-4786-9080-7f061b5f0ac0.gif)|![after-login](https://user-images.githubusercontent.com/1848238/148994843-a093db96-7cea-45ed-baf4-cd5c8b95928d.gif)|![tablet-rotation](https://user-images.githubusercontent.com/1848238/148996853-5e48c536-ca24-405e-8ae9-64802319d897.gif)

Locking phones to portrait during FTUE onboarding

---

changelog.d/4811.feature
vector/src/main/AndroidManifest.xml

Aims to fix #4811 
Enables resizable activities for the entire application https://developer.android.com/guide/topics/manifest/activity-element#resizeableActivity
This _should_ :crossed_fingers: allow desktop android to resize/maximise windows without needing the device OEM to force the behaviour (like Samsung Dex)

Enable activity resizing

---

changelog.d/4669.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/NetworkModule.kt

Quite frequently when I am on mobile data I will experience #4669. The incremental sync state will be idle, but the progress bar will be visible for one minute before throwing a timeout exception and displaying a connectivity error bar
I found some open OkHttp issues that were possibly related (3146, 3278 and 4455). I didn't drop links because I don't know if they're the cause, but these led me to disabling HTTP/2 which seems to resolve the issue.
I have attached a recording with the following setup:
- Phone1 as a mobile hotspot
- Phone2 in airplane mode connected to hotspot, proxying connections through a laptop to record traffic
I'm running two builds of element in split screen on phone2. The top app (dark mode) is this PR, the bottom app (light mode) is v1.3.14 from the Play Store. The …

Force HTTP/1.1

---

changelog.d/4969.bugfix
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt

Fixes #4969 
The crash occurs because the updated login flow attempts to forward the user to the sign in or sign up pages after fetching the homeserver login configuration, this is only correct for the `matrix.org` server.
- Only applies the sign in/up forwarding if the current server selection is `matrix.org`, for other server types we instead allow the `OnLoginFlowRetrieved` event to continue the flow (this is what the `LoginViewModel` [originally did](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt#L819) 
| OTHER BEFORE | OTHER AFTER |
| --- | --- |
|![before-sso-crash](https://user-images.githubusercontent.com/1848238/149921059-414e83ad-79d2-4ed0-bbba-be8a84202b80.gif)|![after-sso-fix](https://user-images.git …

Fixing onboarding crash when signing in/up on non `matrix.org` server with SSO

---

.github/workflows/triage-labelled.yml
.github/workflows/triage-move-review-requests.yml
.github/workflows/triage-priority-bugs.yml
.github/workflows/triage-unlabelled.yml
changelog.d/4949.misc

Add automation for
* labelling Labs issues
* moving design and product PRs
* moving product PRs to board
* move UISI issues to Crypto team
Fixes issue #4949
I think we have a repository conditional `github.repository == 'vector-im/element-android'` in all the places that need it. Worth double checking.

Sync issue automation with element-web

---

.github/dependabot.yml
changelog.d/4988.misc

Closes #4988 issue to disable @github-script@v3 updates

Ignore dependabot upgrade for @github-script@v3

---

changelog.d/4991.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt

Fix #4991 
Signed-off-by: Tiago Loureiro tiago@beeper.com

Fix EmojiPopupDismissListener not being triggered after dismissing the EmojiPopup

---

changelog.d/4998.misc
vector/src/main/java/im/vector/app/features/command/CommandParser.kt
vector/src/main/java/im/vector/app/features/command/ParsedCommand.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/test/java/im/vector/app/features/command/CommandParserTest.kt

Small cleanup on this part of the code + add some unit tests.

Small iteration on command parser

---

changelog.d/4997.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/res/values/strings.xml

Fix an error in string resource (#4997)

---

changelog.d/4995.removal
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/Request.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorCoroutine.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorThread.kt
vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt

Replace #4950 
Propagate the M_LIMIT_EXCEEDED error when the provided delay is too long (exceeds 32 seconds, eg. after three failed login attempts).

Do not auto-retry on 429 in case of too long retry delay

---

changelog.d/5003.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncWorker.kt

Fixes #5003 Fdroid notifications no longer working.
The workaround is to switch the background mode to `optimised for realtime` 
- We've had a small regression in the automatic background sync worker where the `periodic` flag was no longer being set and instead using the default value of `false`
- The named arguments should help combat this in the future!
https://github.com/vector-im/element-android/pull/4614/files#diff-0b0656b4f8d1f73f2a4d5844acec8bf35b732e315e5355800f74145c7fc82fa1L117

Missing fdroid notifications

---

tools/check/forbidden_strings_in_code.txt
vector/src/main/java/im/vector/app/features/invite/InviteButtonStateBinder.kt
vector/src/main/res/layout/vector_invite_view.xml

2 tiny things:
- CI: Disable the check on `enum class`
- Center horizontally the loading wheel when accepting (or rejecting) an invitation
|Before|After|
|-|-|
|<img width="460" alt="image" src="https://user-images.githubusercontent.com/3940906/150837106-e02161d3-5c1b-4086-877e-f8f3e0e7c7d3.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/3940906/150838566-d9753af8-09a7-48b1-805c-44ecb2e77cb3.png">|

Small layout issues

---

changelog.d/5008.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/EventMatchCondition.kt

`regex.containsMatchIn()` for `.*@room.*` can take significantly longer
than checking for `@room` (some real-world events I was getting took
around 15 seconds with this, significantly slowing down the sync
parsing).
Checking `containsMatchIn()` does not lead to different results when
having leading and trailing stars however, it will match in the same
cases as when these are omitted.
For testing purposes, I sent myself some Lorem Ipsum with 5000 words
(not containing any `@room`).
Without this change, the regex evaluation takes about 16 seconds.
With this change, the regex evaluation now takes significantly less then
a second.

Speed up event match regex evaluation for big messages

---

vector/src/androidTest/java/im/vector/app/EspressoExt.kt

We're seeing concurrent modification exceptions within the sanity test suite when using the `waitForActivity` idling resource.
This is caused by `waitForActivity` not taking into account instantly idle activities eg already in a resumed state, combined with our activity matching being `Class` type based rather than instance it means we end up registering callbacks which are leaked and unexpectedly trigger throughout the rest of the test run (ultimately causing concurrent modification exceptions)
We haven't been seeing this with the current test suite due to few usages of `waitForActivity` and rarely revisiting screens after destroying them

Fixing concurrent modification espresso errors 

---

changelog.d/5062.bugfix
vector/src/main/res/layout/fragment_location_sharing.xml

We should not hide the legal mention at bottom left of the map.
|Before|After|
|-|-|
|<img width="480" alt="image" src="https://user-images.githubusercontent.com/3940906/151076672-b47d7ad3-0191-490d-85af-b25f58e4f430.png">|<img width="479" alt="image" src="https://user-images.githubusercontent.com/3940906/151076803-2e1225ef-ba9b-42ed-ade0-86df51a75021.png">|
Note: The legal mention is correctly displayed in the timeline, in the message bottom sheet and in the location message detail.

Ensure mapbox legal mention are displayed on the map

---

vector/src/androidTest/java/im/vector/app/EspressoExt.kt
vector/src/androidTest/java/im/vector/app/ui/robot/MessageMenuRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt

Ui test cleanups 
- Fixes the missing `when` cases when compiling the UI tests with warnings enabled
- Replaces hardcoded timeout for the reaction picker with `waitUntil*`, some times the CI tests fail because the emojis aren't loaded in time
- Replaces `Barista.longClickOn` with the stock espresso long click which we're also using to open the reaction menu, the UI tests have been failing on the CI at the point of long clicking a previously added reaction
- Adds a wait for ensure the message reaction is present before attempting to long click it

UI test clean ups

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/notification/ProcessEventForPushTask.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableEventProcessor.kt
vector/src/main/java/im/vector/app/features/notifications/PushRuleTriggerListener.kt

An attempt to help confirm the cause of #5038 
- Adds extra logging around the push rules and promotes some existing logs to `debug` from `verbose` to allow them to be included in rage shakes without having to enable verbose developer logs
output
```
[PushRules] Found 3 out of 3 to check for push rules with 17 rules
[PushRules] matched 3 out of 3
```

Increased push rules logging

---

build.gradle

From the dependabot logs we've noticed we're mainly scanning jitpack for dependency updates, it appears that dependabot is only scanning the first 2 defined maven repositories.
- Moving maven central to the first position in an attempt to use the broadest scope first
```
updater | INFO <job_273791762> Checking if com.google.android.material:material 1.4.0 needs updating
proxy | 2022/01/31 15:21:28 [046] GET https://jitpack.io:443/com/google/android/material/material/maven-metadata.xml
proxy | 2022/01/31 15:21:28 [046] 404 https://jitpack.io:443/com/google/android/material/material/maven-metadata.xml
proxy | 2022/01/31 15:21:28 [048] GET https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-3.10.0/com/google/android/material/material/maven-metadata.xml
proxy | 2022/01/31 …
```

Attempting to fix missing dependabot updates

---

.github/workflows/integration_tests.yml
.github/workflows/quality.yml
changelog.d/5118.misc

This PR will fix some errors after merging branches to develop or master.  Closes #5118

Fix CI/CD errors after merges

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXOutboundSessionInfo.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt

Quick fix for a crash reported in the rageshake, I did not try to repro the issue.
I have checked that there is no other occurrence of `Timber.\w\(".*",.*\)`

Fix timber crash

---

changelog.d/4295.misc
vector/src/main/java/im/vector/app/features/spaces/share/ShareSpaceBottomSheet.kt

"Invite users to space" dialog now closed when user choose invite method

---

changelog.d/3907.bugfix
library/ui-styles/src/main/res/values/theme_dark.xml
library/ui-styles/src/main/res/values/theme_light.xml

Fixes #3907 Ignored font weights
We're setting a global typeface in our application theme which is overriding our manually set `fontFamily` styles  
| --- | --- |
|![before-font-weights](https://user-images.githubusercontent.com/1848238/152200870-6428880b-1ba7-447a-a3a2-4d7b617a2142.png)|![after-without-font-limit](https://user-images.githubusercontent.com/1848238/152200873-19f0dabe-3744-4724-b825-b5f22e8cdfc7.png)

Fixing ignored font weights 

---

changelog.d/5038.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt

Fixes #5038 Missing google play variant push notifications
**tl;dr** The _not so ideal workaround_ is to disable wifi, as we only run the fast lane pipeline whilst the device is on a wifi connection.
The bug -
Push messages received whilst your own message is the latest in a room whilst a background sync is occurring are skipped until the background sync completes.
The conditions to encounter this bug are:
- a message from yourself is the latest local message in the room
- the device is on wifi
- the app is in the background
- receive a push notification from FCM (google play variant only)
- the fast lane `getEvent` responds faster than the scheduled `/sync`  
- any further pushes received whilst the `/sync` is running are skipped
- after the sync completes the latest message in the room …

Fixing google play variant push notifications being skipped

---

vector/src/main/java/im/vector/app/core/datastore/DataStoreProvider.kt
vector/src/main/java/im/vector/app/core/extensions/Context.kt
vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt
vector/src/main/java/im/vector/app/features/analytics/itf/VectorAnalyticsEvent.kt
vector/src/main/java/im/vector/app/features/analytics/plan/Identity.kt
vector/src/main/java/im/vector/app/features/session/VectorSessionStore.kt

Whilst fixing the sanity tests after enabling the use case screen, 2 crashes were found
- Multiple `VectorSessionStore` instances were attempting to create separate dataStore instances which then throw because the same backing file was being accessed, fixed by introducing a thread safe lazy provider `(String) -> DataStore<Preferences>` to allow for dynamic created stores to be cached and reused   
- Posthog doesn't support sending empty properties and a blank analytics id when identifying a user/session. This was caused by the analytics models filtering out null properties https://github.com/matrix-org/matrix-analytics-events/pull/20, I've manually merged in the changes for the identity model.
*note 
- I haven't created a changelog entry as the feature hasn't been enabled yet, are the …

Handling use case screen in sanity tests 

---

changelog.d/4641.misc
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
vector/src/main/res/values/strings.xml

Enhancement.
In a room timeline screen, removing the search option from the options menu when the search is not available (i.e. when the room is encrypted).
See #4641 
- Go to an encrypted room screen
- Press the options menu
- Check search option is not displayed in the menu
- Go to a non encrypted room screen
- Press the options menu
- Check "Search" option is displayed in the menu
- Press "Search" option
- Check the search screen is displayed

Issue-4641: Show search menu item only if available

---

vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
vector/src/main/java/im/vector/app/features/VectorFeatures.kt
vector/src/main/res/layout/fragment_ftue_auth_use_case.xml
vector/src/main/res/values/donottranslate.xml
vector/src/main/res/values/strings.xml

#4585 Enables the FTUE Use case screen by default
| LIGHT | DARK | 
| --- | --- |
| SMALL DEVICE TOP | SMALL DEVICE BOTTOM | TABLET PORTRAIT | TABLET LANDSCAPE |

Enabling FTUE Use Case

---

dependencies.gradle
dependencies_groups.gradle
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncWorker.kt
vector/build.gradle
vector/lint.xml

Reverts vector-im/element-android#5082.
There are reported problems in unit tests along with hilt.
Integration tests cannot run neither in local builds nor in the CI

Revert "AGP 7.1.0"

---

changelog.d/5142.bugfix
vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt

Aligning use case user property tracking with iOS
- Filters out null user properties as we want to avoid 1 device resetting values for others, we allow new non absent values to be set
- Delays applying the use case property until the point of account creation to avoid needing to reset the value.

Aligning use case tracking with iOS

---

changelog.d/5175.feature
vector/src/main/java/im/vector/app/features/location/LocationPreviewFragment.kt
vector/src/main/java/im/vector/app/features/location/LocationSharingFragment.kt
vector/src/main/java/im/vector/app/features/location/UrlMapProvider.kt
vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnown.kt

Fixes #5175.
[MSC](https://github.com/matrix-org/matrix-doc/blob/matthew/location/proposals/3488-location.md#well-known-configuration)

Retrieve map style url from .well-known

---

changelog.d/5209.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/cleanup/CleanupSession.kt

Debug logging for CleanupSession has been combined into a single log line.
When reading the logs from some of the integration tests, there were periods of up to 10s of these logs being generated, which was a lot to scroll through.
Currently we wait up to 10s for this operation to complete.
Replacing the two log lines with three, lets us halve the number of logs printed every 10ms,
but always print exactly one log line each iteration of the loop. Rather than:
```
02-10 19:58:48.880  3140  3140 D CleanupSession: Wait for all Realm instance to be closed (29 - 0)
02-10 19:58:48.880  3140  3140 D CleanupSession: Waiting 10ms
02-10 19:58:48.890  3140  3140 D CleanupSession: Wait for all Realm instance to be closed (29 - 0)
02-10 19:58:48.890  3140  3140 D CleanupSession: Waiting 10ms
02-10 …
```

Reduce verbosity of CleanupSession debug logs.

---

.github/workflows/sanity_test.yml
changelog.d/5210.misc

This makes it easier to reason about emulator failures.
Update sanity_test.yml to use same configuration options when running an emulator as integration_test.yml
We've had issues with the emulator not starting; using the same options in both places will make it easier to reason about
N/A
https://github.com/vector-im/element-android/pull/5193 contains some experiments - the build there is currently passing.
I'm aware that the builds may be fragile at present, and merging this PR is not guaranteed to fix the UiSanityTests 
N/A

Standardise configuration options for emulators in GHA integration tests

---

gradle.properties

The F-Droid build ran OOM during R8 shrinking with 3GB, but worked fine with 4GB. The failure didn't seem F-Droid-specific, so I'm upstreaming this patch. Do with it what you want :)
- Try to build Element 1.4.0 for F-Droid
- See the build fail
- [Increase the max heap size to 4GB](https://gitlab.com/fdroid/fdroiddata/-/commit/fed4824ecc6b657ca01e3250efc6f5d4ccc32eb1)
- [See the build succeed](https://monitor.f-droid.org/builds/log/im.vector.app/40104000#site-footer)

Increase max heap size for build

---

changelog.d/5201.bugfix
vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
vector/src/main/java/im/vector/app/features/call/VectorCallViewActions.kt
vector/src/main/java/im/vector/app/features/call/VectorCallViewEvents.kt
vector/src/main/java/im/vector/app/features/call/VectorCallViewModel.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferActivity.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferResult.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferViewEvents.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferViewModel.kt

Fixes https://github.com/vector-im/element-android/issues/5201
Intent information(`EXTRA_MODE`) that is pass to attachViewRenderers  [here](https://github.com/vector-im/element-android/blob/11986ec9ef508b93be68860e5eb28460535592ce/vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt#L505) is not present on intent when `onNewIntent` is called, so the outgoing call is never placed. Fix is to set the intent [here](https://github.com/vector-im/element-android/pull/5203/files#diff-7ccb9f5a9496cb142b284f942f64646e7e3580890854d161ab4e7bdaeca74ec2R170).
A follow on issue was related to a recent [PR](https://github.com/vector-im/element-android/pull/5083) that puts other caller on hold when going to the transfer selection and off hold [when they …

Call transfer with consult fails to make outgoing consultation call.

---

changelog.d/5243.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt

Increments the session store database schema version in order to take into account the `HomeServerCapabilitiesEntity` migration.
Crash on launch due to missing migration #5243, this crash isn't live and only affects the pre-release/dev users
N/A
- Installed 1.4.0
- Installed develop on top

Incrementing schema version - fixes pre-release launch crash

---

changelog.d/5185.sdk
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/Matrix.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncService.kt
vector/src/androidTest/java/im/vector/app/SecurityBootstrapTest.kt
vector/src/androidTest/java/im/vector/app/VerifySessionInteractiveTest.kt
vector/src/androidTest/java/im/vector/app/VerifySessionPassphraseTest.kt
vector/src/androidTest/java/im/vector/app/core/utils/TestMatrixHelper.kt
vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/main/java/im/vector/app/core/services/VectorSyncService.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
vector/src/main/java/im/vector/app/features/room/VectorRoomDisplayNameFallbackProvider.kt

Decouples the creation of our `Matrix` instance from the application by using the DI factory instead.
This has the benefit of allowing the `MatrixConfiguration` to use injectable dependencies.
However, it means the `Matrix.getInstance` will throw if we attempt to access a non injected instance before an injected instance as it'll attempt to read the configuration from the application which no longer implements the provider interface  (maybe a good thing for consistency?)

Decoupling Matrix creation from Application

---

changelog.d/5234.bugfix
vector/src/main/java/im/vector/app/core/di/NamedGlobalScope.kt
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt
vector/src/main/java/im/vector/app/features/analytics/impl/LateInitUserPropertiesFactory.kt
vector/src/main/java/im/vector/app/features/analytics/impl/PostHogFactory.kt
vector/src/test/java/im/vector/app/features/analytics/impl/DefaultVectorAnalyticsTest.kt
vector/src/test/java/im/vector/app/features/analytics/impl/LateInitUserPropertiesFactoryTest.kt
vector/src/test/java/im/vector/app/test/fakes/FakeActiveSessionDataSource.kt
vector/src/test/java/im/vector/app/test/fakes/FakeAnalyticsStore.kt
vector/src/test/java/im/vector/app/test/fakes/FakeLateInitUserPropertiesFactory.kt
vector/src/test/java/im/vector/app/test/fakes/FakePostHog.kt
vector/src/test/java/im/vector/app/test/fakes/FakePostHogFactory.kt
vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt
vector/src/test/java/im/vector/app/test/fakes/FakeVectorStore.kt
vector/src/test/java/im/vector/app/test/fixtures/AnalyticsConfigFixture.kt
vector/src/test/java/im/vector/app/test/fixtures/UserPropertiesFixture.kt
vector/src/test/java/im/vector/app/test/fixtures/VectorAnalyticsFixture.kt

- Re-applies specified `UserProperties` each time the client does an initial `identify` (cold launches and on providing tracking consent)   
- Lifts the `GlobalScope` and `PostHog` creation to dagger providers for testability
- Adds unit tests around the `DefaultVectorAnalytics` and  `LateInitUserPropertiesFactory` which involves creating a bunch of fakes to enable testing
Fixes #5234 
Fixes the missing identity properties from within the onboarding flow (pre consent) specifically the onboarding use case. This was caused by `posthog.identify` being called whilst the client was opt'd out which unfortunately doesn't send the cached properties once consent is given, the fix is for us to manually send the stored properties as part of the initial identify which occurs after the user has …

Fixing missing identify properties 

---

changelog.d/4643.misc
vector/src/main/res/menu/home.xml

Replacing the search icon in the home menu by a filter icon to be more consistent.
See #4643 
- Go to home screen
- Check a filter icon is displayed in the top right menu
- Click on the filter icon
- Check the filter screen is opened

#4643: Home screen: replacing the search icon by a filter icon in the menu

---

changelog.d/2782.misc
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/DefaultMergedEventsItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MergedSimilarEventsItem.kt
vector/src/main/res/values/strings.xml

Merge of multiple successive received server ACLs updates in a room into a single collapsable/expandable item.
See #2782 
<image src="https://user-images.githubusercontent.com/46314705/154494015-91455bbc-f160-48ab-9adf-6d2b4bfb5007.png" width=300><image src="https://user-images.githubusercontent.com/46314705/154494047-cd6a8212-fbec-4043-abfe-0bc1bf541274.png" width=300>
<image src="https://user-images.githubusercontent.com/46314705/154496905-80147a28-0bae-4e32-9755-933188d0a416.png" width=300><image src="https://user-images.githubusercontent.com/46314705/154496929-6e38d7f6-d150-44ad-bf29-4e16e1c72326.png" width=300>
- Go to a room where there are many successive ACLs events
- Check the events are merged together
- Click on "expand" button
- Check all corresponding events are listed
- …

#2782: Collapse server ACLs update events

---

changelog.d/5225.misc
library/ui-styles/src/main/res/values/colors.xml
library/ui-styles/src/main/res/values/theme_black.xml
library/ui-styles/src/main/res/values/theme_dark.xml
library/ui-styles/src/main/res/values/theme_light.xml
vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
vector/src/main/res/drawable/bg_unread_notification.xml

Replacing the color attribute `vctr_unread_room_badge` by `vctr_content_secondary` since it is relying on the same color number.
See #5225 
- Launch the application
- Check notification badge is well displayed in home screen

#5225 Replace color "vctr_unread_room_badge" by "vctr_content_secondary"

---

.github/workflows/sanity_test.yml
vector/src/androidTest/java/im/vector/app/espresso/tools/ScreenshotFailureRule.kt
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt

Ensure UI tests have permission to write screenshots on failure.
Ensure UI test screenshots have a suitable name for upload
Always upload even if the tests fails
Improve the usefulness of the `sanity_test.yml` tests by making them reliable

Improve reliability of sanity tests.

---

changelog.d/5099.misc
changelog.d/5104.misc
vector/src/main/res/layout/fragment_space_create_choose_private_model.xml
vector/src/main/res/layout/fragment_space_create_choose_type.xml
vector/src/main/res/values/strings.xml

Changed the UI as described in #3942:
- Gave titles the same font size
- Removed the duplicate "Spaces are a new way [...]"
- Have "You can change this later" on both screens
- Have title and description on top of each screen
I did not center the header title ("Create a space" / "Your private space") as suggested since the header titles are usually left aligned throughout the app if I am not mistaken.
See:
**EDIT from bmarty: adding a table to wrap the screenshots**
|Create space|Create private space|
|-|-|
|![Screenshot_20220131_134640](https://user-images.githubusercontent.com/39308834/151798264-3dff2fff-c347-4fc3-8082-6af6fec4d8a7.png)|![Screenshot_20220131_134841](https://user-images.githubusercontent.com/39308834/151798270-8d2647d2-65a2-4cbc-b9d6-fc4c4a9087b9.png)|
- ~~[ ] If you …

Make Space creation screens more consistent

---

changelog.d/5290.feature
vector/src/main/java/im/vector/app/features/poll/create/CreatePollController.kt

Allow creating disclosed polls

---

changelog.d/5295.bugfix
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/app/features/qrcode/QrCodeScannerFragment.kt

Adds missing `QrScannerFragment` arguments when scanning a QR code accept accepting the camera permission for the first time 
Fixes #5295
| --- | --- |
|![before-add-room-qr](https://user-images.githubusercontent.com/1848238/155127171-efac1bf8-b1cf-4aa1-8cd4-8ea24acfe488.gif)|![after-add-room-qa](https://user-images.githubusercontent.com/1848238/155127169-f64dc3df-fb97-4aa3-a4a9-a2422ec482ed.gif)
- With a fresh install
- Attempt to add a room by qr code

Fixing crash adding room by QR code

---

changelog.d/5294.misc
vector/src/main/res/layout/item_room.xml

- Unread marker colour changed from colorSecondary (green) to vctr_content_secondary (grey)
iOS already uses this grey colour and we want to have parity with them
|       | Before | After |
|-------|--------|-------|
| Light | ![beforelight](https://user-images.githubusercontent.com/20701752/155114396-6d5d092f-8495-4864-9c23-271d15b8aa9f.jpg) | ![afterlight](https://user-images.githubusercontent.com/20701752/155114609-8d322543-8aa8-4512-b5b4-72e5991c6d67.jpg)|
| Dark | ![beforedark](https://user-images.githubusercontent.com/20701752/155114766-c66d1789-b3e6-4d57-a2fa-0033a100bcd9.jpg) | ![afterdark](https://user-images.githubusercontent.com/20701752/155114823-2784f490-4f4b-44ae-9308-63ecfe905340.jpg) |
Go to Rooms tab
See that marker for rooms with unread messages is grey …

Changes unread marker in item_room.xml

---

changelog.d/5297.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/ReadReceipt.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/AsyncTransaction.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/ReadReceiptsSummaryMapper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/TimelineEventMapper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/joining/JoinRoomTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/ReadReceiptsItemFactory.kt

This PR removes usage of frozen RealmResults in the timeline, as it wasn't necessary (not switch of threads)
Also uses Realm.WRITE_EXECUTOR for awaitTransaction.
Last, not really related to realm but took the opportunity to replace ReadReceipt.User by ReadReceipt.RoomMember as we are in a room.
Improves performance of realm, and reduce the consumption of disk space (before compacting) and probably ram usage.
- Open timeline
- Close timeline
- Check number of Realm.globalInstanceCount
- Repeat
- [ X] Physical : Pixel 3

Improve usage of realm 

---

changelog.d/5218.bugfix
vector/src/main/java/im/vector/app/features/login/LoginWebFragment.kt
vector/src/main/java/im/vector/app/features/login2/LoginWebFragment2.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWebFragment.kt
vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt

- Removing usage of `SoftLogoutViewModel` in `FtueAuthWebFragment` since it seems the code which is using it cannot be reached.
- Changing the way we retrieve the current active `Session` to initialize the `ViewState` used in `SoftLogoutViewModel`: there is no more reference to the `Activity` using the `ViewModel` which caused the crash (ClassCastException).
See #5218.
- Edit temporarily the code to reproduce the flow leading to web view redirection as explained in [this comment](https://github.com/vector-im/element-android/issues/5218#issuecomment-1042746067).
- Start onboarding
- Choose to create a new account on "Matrix.org" server for example
- Wait to see the redirection dialog
- Choose "yes" to be redirected to web view
- Check the app does not crash and displays the registration …

#5218: Fix crash at registration when redirecting to Web View

---

changelog.d/5158.wip
vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
vector/src/main/java/im/vector/app/features/VectorFeatures.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
vector/src/main/res/layout/fragment_ftue_account_created.xml
vector/src/main/res/values/donottranslate.xml

Part of #4586 https://github.com/vector-im/element-meta/issues/132
- Adds an account created screen behind a feature flag
- The `personalise profile` button TODO is handled by https://github.com/vector-im/element-android/pull/5211
| SCREEN | FEATURE FLAG | SYSTEM BACK | TAKE ME HOME | 
|![Screenshot_20220204_171024](https://user-images.githubusercontent.com/1848238/152572204-f214a9c9-7f80-4dc5-82cf-31c8d985ca92.png)|![Screenshot_20220204_172701](https://user-images.githubusercontent.com/1848238/152574874-cd07afe9-f9e2-429d-92ca-fbd15919a69e.png)|![after-system-back](https://user-images.githubusercontent.com/1848238/152574721-9560b2b7-3499-48b4-920a-a35e0efb601c.gif)|![after-take-me-home](https://user-images.githubusercontent.com/1848238/152574726-8adb9fa4-837d-415 …

FTUE - Account created screen

---

changelog.d/5312.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt

This aids debugging when `/sync` does something weird server side. Since we already log a line each time we do an incremental sync this shouldn't cause a problem.
---
I haven't tested this in any shape or form, nor do I know if this is *actually* where we want to add this log line. Sorry for the drive by PR, but found myself wanting this when investigating https://github.com/matrix-org/synapse/issues/11916.

Log `since` token when doing an incremental sync

---

changelog.d/5269.misc
vector/src/androidTest/java/im/vector/app/EspressoExt.kt
vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceMenuRobot.kt

Adds a separate `clickOn` helper for interacting with dialog bottom sheets, it seems the space menu sheet lives in a separate root to the rest of the suite (could be the fast switching of activities highlighting existing issues)
To fix the UI sanity tests failing when attempting to interact with the spaces menu #5269 
| --- | --- |
|![before-space-test](https://user-images.githubusercontent.com/1848238/155317042-b59e8dc4-e75d-410b-a981-de6f3f5651f9.gif)|![after-spaces-test](https://user-images.githubusercontent.com/1848238/155317032-4995893a-0f70-4b5b-8852-7938a26bb577.gif)
Run the UI sanity tests on a Pixel 5x (Sv2) emulator.
- OS version(s): Sv2 (31)

Tentatively fixing space menu items not being clicked on during sanity test

---

.github/workflows/integration_tests.yml

Move from `continue_on_error` to `if: always()`.
This will allow previous steps to explicitly fail and be marked as failed
but later steps will continue to run in order to display the outcomes.
(there's probably a better way to do this, but this will at least start
to expose the errors in the UI)
- Step 1
- Step 2
- Step ...

Allow integration tasks to fail, but use if: always() to allow the next step to continue anyway.

---

changelog.d/5326.misc
vector/src/main/java/im/vector/app/core/extensions/Fragment.kt

- [] Bugfix
Use the appName instead of the string "element" in the filename.
In forked application like Tchap, we have "element" in the name of the file.
For element debug
- Step 1
- Step 2
- Step ...
- OS version(s): 30

[Export e2ee keys] use appName instead of element

---

.github/workflows/nightly.yml

Moved sanity test and integration test into a single workflow, triggering that workflow nightly at 8pm, and also on `synchronize` of any branch called `release/*`.
Integration tests are taking > 2h to run, and we are not taking them on board when merging PRs.
Moving to a nightly run reduces wasted work (freeing up CI resources to do other tasks, faster) and will stand as a place to run the tests until we have them running reliably and quickly, and can re-introduce them to the PR flow.
Hard to test: on purpose this PR does NOT run the tests :)
After merging to develop, trigger a nightly test run manually and check ~3h later if the notification arrives.
GHA

Run integration tests nightly

---

build.gradle
changelog.d/5379.misc
matrix-sdk-android/build.gradle
vector/build.gradle

Removed unused threads **buildConfig** configurations. Enable/Disable threads can be performed from lab settings

Cleanup enabling threads from buildConfig

---

changelog.d/4319.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailPendingAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileAction.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewEvents.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt

Moving the navigation handling to open direct message from `TimelineFragment` to `RoomMemberProfileFragment`.
Closes #4319 
- Open drawer menu
- Click on a space menu
- Click on "List members" button
- Click on a member
- Click on "Direct message"
- Check the screen with corresponding direct message room is displayed
- Go to a room where there are different members
- Click on a member in the timeline
- Click on "Direct message"
- Check the screen with corresponding direct message room is displayed 

#4319: Fix DM navigation in member profile screen

---

changelog.d/5394.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/file/FileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt
vector/src/main/java/im/vector/app/core/utils/FileUtils.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt

Fix https://github.com/vector-im/element-android/issues/5394
Negative media cache sizes due to Int overflow.
Signed-off-by: Tiago Loureiro [tiago@beeper.com](mailto:tiago@beeper.com)

Fix Media cache size with negative values in the General Settings screen 

---

changelog.d/5392.misc
dependencies.gradle

Upgrading the material library dependency from 1.4.0 > 1.5.0 without any other changes
[There's another PR up](https://github.com/vector-im/element-android/pull/5359) that implements a design change to upgrade our material components themselves to the new Material You design scheme.
This however is a decision that design needs to make and may take a while.
So while I continue to maintain that PR in the midst of that decision, this PR simply serves as an upgrade to keep our dependencies up-to-date without any user-facing changes.
This being merge would thus close [Issue 5291](https://github.com/vector-im/element-android/issues/5291). I would however recommend a new issue be raised for the upgrade of the app's look to Material You
**I'm currently testing that this indeed doesn't change …

Upgrades to Material 1.5.0 (dependency only)

---

changelog.d/5361.misc
vector/src/debug/java/im/vector/app/features/debug/di/FeaturesModule.kt
vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorOverrides.kt
vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsFragment.kt
vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewModel.kt
vector/src/main/java/im/vector/app/features/DefaultVectorOverrides.kt
vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/settings/VectorDataStore.kt
vector/src/release/java/im/vector/app/core/di/FeaturesModule.kt

Lifts the debug only options to their own `VectorOverrides` class, this class is explicitly for overriding behaviour for testing and is not meant to be user facing. The `release` build type will use the interface defaults, effectively the same as `VectorFeatures`.
To avoid leaking debug only content within the `VectorDataStore` and provide a single point of reference for adding feature overrides for testing
No UI changes
- Open the debug menu -> private settings 
- enable force dial pad tab
- see the dial pad tab in the home activity
- OS version(s): Sv2 (31)

Lifting debug overrides to their own abstraction

---

vector/src/main/java/im/vector/app/core/di/FragmentModule.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingVariant.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthChooseDisplayNameFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
vector/src/main/res/layout/activity_login.xml
vector/src/main/res/layout/fragment_ftue_display_name.xml
vector/src/main/res/values/donottranslate.xml
vector/src/test/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModelTest.kt
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
vector/src/test/java/im/vector/app/test/Extensions.kt
vector/src/test/java/im/vector/app/test/fakes/FakeActiveSessionHolder.kt
vector/src/test/java/im/vector/app/test/fakes/FakeAnalyticsTracker.kt
vector/src/test/java/im/vector/app/test/fakes/FakeAuthenticationService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerConnectionConfigFactory.kt
vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerHistoryService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeProfileService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt
vector/src/test/java/im/vector/app/test/fakes/FakeVectorFeatures.kt

Depends on #5158 Part of #5200
Adds a `Choose a display name` screen to the onboarding personalisation flow, sits behind the FTUE personailzation feature flag.
To allow the user to personalise their account during the account creation process
*the gif animations are odd because the emulator has them turned off
| EMPTY | WITH CONTENT | WITH CONTENT AND KEYBOARD |
| --- | --- | --- |
| GIF | 
| --- |
|![after-update-name](https://user-images.githubusercontent.com/1848238/153624671-2ec06f28-33d4-42fa-94db-e83c86361f00.gif)
- Adds unit tests around the `OnboardingViewModel` (along with the fakes needed to setup the class) to ensure the display name is updated and errors are handled
- OS version(s): 32 / Sv2

FTUE - Choose a display name

---

vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt

Adds missing `VectorOverride` instance in test, temporarily uses the `Default` instance as it's replaced by a Fake in [#5375](https://github.com/vector-im/element-android/pull/5375/files#diff-05c6932fe7e57fc02d437f108829986761ec74e6e15b916f853f28c56ad3202aR22)
Fixes test compilation error caused by git's automerge with develop
No app changes
The CI!
N/A

Fixing unit test compilation error

---

changelog.d/5418.feature
vector/src/main/java/im/vector/app/features/settings/VectorSettingsBaseFragment.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt

Reuses the error dialog logic which translates exceptions to human readable strings in the settings screen
Fixes #5418 - The error messages for display name/avatar changing are making use of the raw exception instead of the nicely formatted message included within the exception
| --- | --- |
|![Screenshot_20220303_155653](https://user-images.githubusercontent.com/1848238/156605690-ff085582-ce5a-4240-9fd4-fb813d1fafb2.png)|![Screenshot_20220303_160945](https://user-images.githubusercontent.com/1848238/156605688-3b9a8d45-3c30-42e9-b53a-81958f3d5cb1.png)
- Via the settings
- Attempt to change the display name to one longer than 256 characters
- OS version(s): 31 (Sv2)

Giving avatar/display name error dialogs human readable error messages

---

changelog.d/5402.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/FileUploader.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBodyBuilder.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt

Upload image in thread io instead of mainThread
Closes #5402 
- Step 1
- Step 2
- Step ...

[Create private room] Picture doesn't not displayed 

---

.github/workflows/nightly.yml
build.gradle

Nightly runs of sonarqube code quality checks
Requires @bmarty to add a secret to github for this project called "SONAR_TOKEN", which can be done at any time.
Automate away our sonarqube runs. An extension to this will be adding jacoco support and reporting code coverage metrics to sonarqube as well.
Code coverage could be implemented by codecov instead of sonarqube, and is done so by other element client implementations; so this PR may not be the end result.

Run sonarqube as part of nightly build

---

changelog.d/4642.bugfix
library/ui-styles/src/main/res/values/style_action_button.xml
library/ui-styles/src/main/res/values/theme_common.xml
library/ui-styles/src/main/res/values/theme_dark.xml
library/ui-styles/src/main/res/values/theme_light.xml
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/res/layout/view_room_detail_toolbar.xml

- Update the Shield and the ON/OFF notification within the Room toolbar image. 
- Remove the subtitle
- reduce extra padding for the menu item icons. 
Dark | Light
--- | --- 
- Access to a timeline and check the toolbar. 

#4642 Update the top bar in a room

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/threads/ThreadMessagingTest.kt

at-Ignored the ThreadMessagingTest , as it seemed to trigger the remaining integration tests to fail.
I want the build to go green.
BEFORE:
AFTER:

Ignore ThreadMessagingTest as it seems to cause other integration tests to fail

---

.github/workflows/nightly.yml
.github/workflows/tests.yml
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/TestMatrix.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/signout/SignOutTask.kt

This exception is printed in the logs on every sign-out that did not have an identity server configured:
```
2022-03-08 10:02:48.129 14210-14267/? I/System.out: W/DefaultSignOutTask: Unable to disconnect identity server
2022-03-08 10:02:48.129 14210-14267/? I/System.out: org.matrix.android.sdk.api.session.identity.IdentityServiceError$NoIdentityServerConfigured
2022-03-08 10:02:48.129 14210-14267/? I/System.out:     at org.matrix.android.sdk.internal.session.identity.DefaultIdentityDisconnectTask.execute(IdentityDisconnectTask.kt:36)
2022-03-08 10:02:48.129 14210-14267/? I/System.out:     at org.matrix.android.sdk.internal.session.identity.DefaultIdentityDisconnectTask.execute(IdentityDisconnectTask.kt:29)
2022-03-08 10:02:48.129 14210-14267/? I/System.out:     at …
```

Remove deprecated warning in TestMatrix, and reduce severity of identity server error

---

changelog.d/5456.misc
library/ui-styles/src/main/res/values/colors.xml
library/ui-styles/src/main/res/values/theme_dark.xml
library/ui-styles/src/main/res/values/theme_light.xml
vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
vector/src/main/res/drawable/bg_unread_notification.xml
vector/src/main/res/layout/item_room.xml

Fixes #5332 .
|Light|Dark|
|-|-|
|<img width="483" alt="image" src="https://user-images.githubusercontent.com/3940906/155490792-65bae4b6-c10a-41d7-bf87-4a654f8cd97c.png">|<img width="483" alt="image" src="https://user-images.githubusercontent.com/3940906/155490738-2a99b13c-617b-4174-bd02-0144288978e5.png">|
|Light|Dark|
|-|-|
|<img width="437" alt="image" src="https://user-images.githubusercontent.com/3940906/157251782-7c03f2a7-19a9-49a7-a86f-c150c0c38985.png">|<img width="437" alt="image" src="https://user-images.githubusercontent.com/3940906/157251721-49c7a793-e875-4302-98e6-d1e4532993c1.png">|

Iterate on badge / unread indicator color (#5332)

---

changelog.d/5468.bugfix
vector/src/main/res/layout/view_room_detail_toolbar.xml

Fixes #5468 
Introduces a barrier which contains all the possible leading icons, allowing us to be sure the text is always aligned to the right of whichever icon is currently present. 
The room toolbar title is overlapping image due to missing constraints when the badge icon is not present
| --- | --- |
|![before-rt](https://user-images.githubusercontent.com/1848238/157414031-3a154080-3d20-4121-ac9d-8021727186c0.png)|![after-rt](https://user-images.githubusercontent.com/1848238/157414041-a7002dd4-74e3-43a8-b39a-135135f8b155.png)
|![before-rt2](https://user-images.githubusercontent.com/1848238/157414029-b6acf30a-2183-4105-b8f3-8c76ba9ce04b.png)|![after-rt2](https://user-images.githubusercontent.com/1848238/157414037-e8e2dbf9-0b09-49a8-8268-6a2f2ebb788d.png) …

Fixing overlapping room image and title

---

changelog.d/5260.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt

include dms number in space unread number badge

---

changelog.d/5463.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/CallItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptedItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptionItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactoryParams.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VerificationItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/WidgetItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageItemAttributesFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/ReactionsSummaryFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsBaseMessageItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/CallTileTimelineItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/StatusTileTimelineItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/VerificationRequestItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/WidgetTileTimelineItem.kt

Fixing `NotSerializableException` crash on reactions summary
Closes #5463

Fix reactions summary crash

---

.github/workflows/nightly.yml

Rather than use a shell script to start and stop synapse, use a github action instead
The synapse demo script changed which caused CI to fail, so fixing it up so it's internal to GHA rather than re-using a script not quite designed for this purpose.
Additional benefits is that this should retain the configuration and logs of the synapse homeserver for analysis after the run.
Tested by manual runs

Swap to using github action to configure synapse server in CI builds

---

changelog.d/5384.misc
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayout.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayoutFactory.kt
vector/src/main/res/layout/view_message_bubble.xml

Add a padding before the first message send by ourselves. It is the same size than a displayed name.
It is easier to view our messages from others if the padding is a bit bigger.
|Before|After|
|-|-|
|![Capture d’écran de 2022-03-01 00-39-42](https://user-images.githubusercontent.com/31284753/156077863-b2a889a2-00b0-4bdc-9b9a-a36ee9833132.png)|![Capture d’écran de 2022-03-01 00-35-07](https://user-images.githubusercontent.com/31284753/156077885-b726fdf8-2ff7-4a4c-a89b-eed9754f1a34.png)|
**Edit**: adding a table for better comparison of screnshoots
- OS version(s): 9

Add padding before first own message

---

changelog.d/5501.misc
vector/src/main/res/layout/view_attachment_type_selector.xml

In view_attachment_type_selector.xml, for the icon: attchmentGalleryButton a tint is not set.
For the forked projet like Tchap, we prefer use colorPrimary for the tint.
- Step 1
- Step 2
- Step ...
- OS version(s): Pixel 4 API 30

Use ColorPrimary for attachmentGalleryButton tint

---

changelog.d/5448.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt

- offsets() was not limiting in the right direction when loading
messages forwards
- after fixing offsets(), more recent messages would not be loaded due
to the isLastForward() check, so better prioritize the SUCCESS
LoadMoreResult over the REACHED_END here
Fixes https://github.com/vector-im/element-android/issues/5448
1. Permalink the latest message in a room
2. Go back to room list
3. Receive lots of new messages in that room (e.g. 100)
4. Open the room from the permalink
5. Check if all messages are shown

Fix missing messages when forward paging with chunks > 50 messages

---

.github/workflows/tests.yml

Also remove extra space for the text_template
I hope this will change
🔴Build Android Tests failure at 2022-03-11T09:23:50Z [[details]](https://github.com/vector-im/element-android/runs/5508653758?check_suite_focus=true)
🟢Run Unit Tests success at 2022-03-11T10:03:38Z [[details]](https://github.com/vector-im/element-android/runs/5508654026?check_suite_focus=true)
To 
🔴 Build Android Tests failure at 2022-03-11T09:23:50Z [[details]](https://github.com/vector-im/element-android/runs/5508653758?check_suite_focus=true)
🟢 Run Unit Tests success at 2022-03-11T10:03:38Z [[details]](https://github.com/vector-im/element-android/runs/5508654026?check_suite_focus=true)

Add space between icon and name

---

changelog.d/5443.misc
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/NetworkConstants.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/ResolveSpaceInfoTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/SpaceApi.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/SpaceChildSummaryResponse.kt
matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/space/DefaultResolveSpaceInfoTaskTest.kt
matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeSpaceApi.kt
matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fixtures/ResolveSpaceInfoTaskParamsFixture.kt
matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fixtures/SpacesResponseFixture.kt

Adds stable room hierarchy endpoint with a fallback to the unstable one
Closes https://github.com/vector-im/element-android/issues/4462
N/A
**Testing Normal Functionality**
1. Login with any account belonging to spaces, preferrably one with subspaces too
2. Open the home navigation drawer and see that you can see your spaces and subspaces as normal
**Testing Fallback**
- Set debug points in ResolveSpaceInfoTask lines 49 and 51
- Force a fail on the stable request (either via code or via a network interceptor) and see that it falls back to the unstable API

Changes room hierarchy endpoint to stable

---

.github/workflows/tests.yml

Otherwise we will cancel one in favour of the other.
see eg https://github.com/vector-im/element-android/runs/5513822281?check_suite_focus=true

Use different tags for unit tests and android test compilation.

---

changelog.d/5375.wip
vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorOverrides.kt
vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsFragment.kt
vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewActions.kt
vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewModel.kt
vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewState.kt
vector/src/debug/java/im/vector/app/features/debug/settings/OverrideDropdownView.kt
vector/src/debug/java/im/vector/app/features/debug/settings/PrivateSettingOverrides.kt
vector/src/debug/res/layout/fragment_debug_private_settings.xml
vector/src/debug/res/layout/view_boolean_dropdown.xml
vector/src/main/java/im/vector/app/features/DefaultVectorOverrides.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingVariant.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthChooseProfilePictureFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
vector/src/main/res/layout/fragment_ftue_account_created.xml
vector/src/main/res/layout/fragment_ftue_profile_picture.xml
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
vector/src/test/java/im/vector/app/test/Extensions.kt
vector/src/test/java/im/vector/app/test/fakes/FakeAuthenticationService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerCapabilitiesService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt
vector/src/test/java/im/vector/app/test/fakes/FakeVectorOverrides.kt

Draft PR, relies on #5361  #5323 
Dynamically shows/hides the personalisation onboarding screen based on the homeservers capabilities.
when display name and profile picture are not supported
- Account created only offers the `Take me home` button
when only changing display name is supported
- Account created personalisation is enabled but only shows the display name step 
when only changing profile picture is supported
- Account created personalisation is enabled but only change profile picture step, removing the toolbar back to the match the display name flow
Also introduces debug overrides for the homeserver capabilities to make testing the different options easier.
To only show personalisation options to users on homeservers which support them. Part of #5200 
| ALL OPTIONS DISABLED | …

FTUE - Capability based personalisation flow

---

changelog.d/5514.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/ReadReceiptsItemFactory.kt

Update read receipt order in the factory.
#5514 
Open ready receipt details on a message (especially if there is some events hidden before it)

Read receipt in wrong order

---

changelog.d/5534.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayout.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/view/MessageBubbleView.kt

Fixes a crash due to a view with id R.id.additionalTopSpace not being found in the base timeline view. This is a view that's only being used in bubbles
Closes https://github.com/vector-im/element-android/issues/5535 and https://github.com/matrix-org/element-android-rageshakes/issues/35624
The additionalTopSpace view is only being used in bubbles so I reduced its scope to only the bubbles view rather than the base timeline view.
I also included some slight refactoring of the bubbles view class for readability
No UI changes but simple confirmation that top space above bubbles works as expected
- Open timeline. Observe no crash
- Observe top margin behaviour added [in this PR](https://github.com/vector-im/element-android/pull/5384) is still present

Fixes timeline crash due to additionalTopSpace

---

changelog.d/5521.bugfix
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/session/room/send/MarkdownParserTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/session/room/send/TestPermalinkService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/PermalinkService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/DefaultPermalinkService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/PermalinkFactory.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/pills/TextPillsUtils.kt

Mentions permalinks are now based on the client defined permalink base url if available rather than using matrix.to (default).
Fixes #5521 
- Step 1: Define clientPermalinkBaseUrl in MatrixConfiguration (don't forget to add it to permalink_supported_hosts as well)
- Step 2: Test communication with another client with the same configuration and the usability of created permalinks (ideally with iOS and/or Web)

Fix mentions using matrix.to rather than client defined permalink base url

---

changelog.d/5547.bugfix
vector/src/main/java/im/vector/app/features/roomprofile/notifications/RoomNotificationSettingsViewState.kt

Use none in android application when all messages or mentions only is selected in the web application.
https://github.com/tchapgouv/tchap-android-v2/issues/464
Android:
Web:
- Update Notification settings in web application to mention only
- Check if in Android application the notifications preference is equal to None.

[Notification mode] Wrong mode is displayed when the mention only is selected on the web client

---

changelog.d/5540.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt

Fixes the wrong `setArguments`  being called when triggering the verification bottom sheet
Fixes a crash when tapping the item area instead of the buttons #5540 
| --- | --- |
|![crash](https://user-images.githubusercontent.com/1848238/158636672-ad0056e2-7f0d-4384-be79-16c476412537.gif)|![after-verify](https://user-images.githubusercontent.com/1848238/158637187-6c26c21b-8050-416c-bd34-d168f4f24de3.gif)
- From web, verify another user
- On mobile as the other user, tap the area surrounding the verification buttons
- OS version(s): 31 Sv2

Fixing crash when tapping timeline verification item

---

changelog.d/5552.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineEventDecryptor.kt

Catch the `InterrutedException` produced by `runBlocking`
When shutting down the executor, the app crashes if we don't catch that exception for an ongoing `runBlocking`.
Open the room and close it again.
Can insert a `Thread.sleep(1000)` into the `runBlocking` to ensure it is still running.

Fix crash when closing room during timeline decryption

---

changelog.d/5571.feature
library/ui-styles/src/main/res/values/styles_location.xml
vector/src/main/java/im/vector/app/features/location/live/LocationLiveStatusView.kt
vector/src/main/res/layout/fragment_timeline.xml
vector/src/main/res/layout/view_location_live_status.xml
vector/src/main/res/values/strings.xml

Adding a custom view inside the room timeline screen to show a status bar when the live location will be enabled in a room. For now, it is always hidden.
Closes #5571 
When the user will share its live location in a room, the app will show a status bar saying the live location is enabled in the room. A "stop" button enables the user to stop sharing its live location.
Note: I have decided to use upper case for the "Stop" button since I think it is more suitable for this type of button (it is in lower case in Figma): this change will be confirmed and can be modified later if needed.
If you want to test, you can add this piece of code at the end of the `onViewCreated` method in the `TimelineFragment`:
```kotlin
private fun testLocationLiveStatusIndicator() { …
```

#5571: Live location status bar indicator

---

changelog.d/5408.misc
vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/RegistrationActionHandler.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthGenericTextInputFormFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWaitForEmailFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/terms/FtueAuthTermsFragment.kt
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
vector/src/test/java/im/vector/app/features/onboarding/RegistrationActionHandlerTest.kt
vector/src/test/java/im/vector/app/test/Extensions.kt
vector/src/test/java/im/vector/app/test/fakes/FakeAuthenticationService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeRegisterActionHandler.kt
vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
vector/src/test/java/im/vector/app/test/fakes/FakeVectorFeatures.kt
vector/src/test/java/im/vector/app/test/fixtures/HomeserverCapabilityFixture.kt

Marked as draft as this relies on #5389
Adds unit tests around the Registration steps within the `OnboardingViewModel`
- Extracts out the `RegistrationWizard` action interactions to it's own class to make testing the view model easier
- Converts the `RegisterAction` to sealed interface to allow for compile time type checking 
To improve the test coverage around the authentication flows. Could be considered part of #5200 
No UI changes

FTUE - Onboarding registration steps unit tests

---

changelog.d/5513.misc
library/ui-styles/src/main/res/values/colors.xml
library/ui-styles/src/main/res/values/palette_mobile.xml
library/ui-styles/src/main/res/values/theme_dark.xml
library/ui-styles/src/main/res/values/theme_light.xml
vector/src/main/res/drawable/ic_presence_online.xml

A proxy of #5513 with a small change 4a7646a7ba7fcf4896c50645038e3c5ba6019ee6 to keep the color definitions consistent

Presence indicator theme attribute

---

changelog.d/5572.misc
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/app/features/media/RoomEventsAttachmentProvider.kt

Open stickers and play animated sticker
Fix https://github.com/vector-im/element-android/issues/2668
Stickers can be clicked to show their content.
Some stickers need to be opened to be seen (too small) or to be played (GIF) but it wasn't possible.
- Send a playable sticker on a room (For instance with https://duckchi.github.io/stickerpicker/web/)
- Click on it
- OS version(s): 9, 11

Show stickers on click

---

.github/workflows/nightly.yml
tools/ci/render_test_output.py

If a test fails to run, ensure the renderer prints a suitable message
Format nightly run data in colour to be more obvious when failures occur.
~~Upload synapse homeserver log after run for diagnosis.~~
Add names to all runs
General improvement to the test scripts to make it easier to understand what's going on.
Synapse homeserver logging has been removed in favour of 
- Step 1
- Step 2
- Step ...

CI Script improvements

---

changelog.d/5551.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/SendingEventsDataSource.kt

Make sure we have frozen results for `SendingEventsDataSource` right when starting it
When you open a room which already has local echos, these wouldn't show until you create a new one.
1. send message while offline
2. close room
3. re-open room
=> Own messages are not showing, until we sync them back after they reached the server, or we send another new message.

Fix local echos not being shown when re-opening rooms

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/lightweight/LightweightSettingsStorage.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/WorkManagerProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadSummariesTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
vector-config/src/main/res/values/config-settings.xml
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/main/java/im/vector/app/features/MainActivity.kt
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt
vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
vector/src/main/res/values/strings.xml
vector/src/main/res/xml/vector_settings_labs.xml

This PR aims to smoothly migrate users to threads live implementation
- For users with **threads enabled** from lab settings will automatically enable live threads, so no action needed from their side. They will also be notified about the threads transition and what will happen with their old messages
- Preparation to enable threads for everyone. Threads will remain a lab setting until the next RC
Closes #5451

Threads Migration

---

changelog.d/5564.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt

We need both directions so `getOffsetIndex()` produces correct results in
all cases.
Ensure that links in both directions are properly set up, so `getOffsetIndex()` produces correct results.
I was running in a case where the read marker would not properly update to the most recent of my scrolled-to messages. It turned out that the tracker was thinking of a previously read event to be the most recent scrolled-to one, as `LoadTimelineStrategy.getBuiltEventIndex()` was returning a lower index than the others. Turned out that the chunk of that event had not linked nextChunk, even though there were more chunks being displayed. This resulted in a wrong result of `getOffsetIndex() = 0`.
Scroll around in a room affected by the bug and observe what …

Fix another case of read markers not updating: Ensure proper double linking of TimelineChunks

---

changelog.d/5347.misc
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/SectionHeaderAdapter.kt

In room list fragment disable collapse section if there is only section.
#5347 
- Step 1
- Step 2
- Step ...

#5347 Do not suggest collapse if there is only one section

---

vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt

Updates the account creation flow in the sanity test, taking into account the new account created (congratulations!) screen
originally part of https://github.com/vector-im/element-android/pull/5519
| GIF |
| --- |
|![after-account-creation](https://user-images.githubusercontent.com/1848238/159662573-5dbe18b7-3176-4b29-8ad7-7a928c47b89b.gif)
- Run the sanity tests 
- See the tests get stuck on the account created screen
- OS version(s): 32 Sv2

Sanity test getting stuck on account created screen

---

changelog.d/5517.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractFtueAuthFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordMailConfirmationFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt

Marked as draft as this relies on #5408 
- Flattens the onboarding `async states` down into a single `isLoading` 
- Uses a single flow for error handling instead of splitting them across state and events, all errors flow through the events, it's up to the individual fragments to explicitly opt into custom error handling
To simplify, remove code duplication and avoid redundant state updates 
| GENERIC | INVALID USERNAME | IN USE |
| --- | --- | --- |
|![o-no-network](https://user-images.githubusercontent.com/1848238/157873985-754c04b5-358a-4b59-a178-4c8e87dcca6a.png)|![o-invalid-username](https://user-images.githubusercontent.com/1848238/157873982-7d1c3241-c96f-444b-a4a7-a185a13338a4.png)|![Screenshot_20220311_131849](https://user-images.githubusercontent.com/1848238/157873979-33ff5f93-d195 …

FTUE - Single loading state

---

vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt

Fixes a wrong flag on direct login 
Fixes #5623 (Haven't added a changelog due to this only being in dev)
When signing in via a direct login (sign in with full matrix id) the wrong `accountCreated` was being used
- This is not captured by the sanity test suite as we only use the "Other" option for signing in due to needing to force a custom homeserver IP for emulators 
- Another PR will be raised against develop containing a unit test
| --- | --- |
|![before-sign-in-with-id](https://user-images.githubusercontent.com/1848238/159895934-bf6971ce-757f-4878-b7ec-cdfac1c1a702.gif)|![after-sign-in-with-id](https://user-images.githubusercontent.com/1848238/159895937-d76acd3f-3a89-4446-9449-9cfb315f173a.gif)
- Start sign in flow
- Select "Sign in with matrix id"
- After …

Fixing account creation celebration shown on `sign in with matrix id`

---

vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/SectionHeaderAdapter.kt

This PR restore the changes made in #5580 which was reverted in the Element release 1.4.6 because of some UI and functional issues. The issues are fixed in #5616.

Restore #5580 "Do not suggest collapse if there is only one section"

---

changelog.d/5616.bugfix
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/SectionHeaderAdapter.kt

Fix inconsistencies between the arrow visibility and the collapse action by clicking on a room section header.
The sections were always collapsible even if the arrow was not visible. Adding favourites in both DM and Rooms tab was causing issues on the arrow visibility for this section.

Fix rooms section collapsing

---

changelog.d/5497.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/profile/ProfileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt

Add a call to getProfile in the defaultSyncTask and store the result in the DB.
#5497 
- Create an account
- Open the left panel and check if there is the display name
- OS version(s): API30

[Subscribing] Blank display name

---

changelog.d/5628.misc
vector/src/main/java/im/vector/app/features/onboarding/DirectLoginUseCase.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/UriFactory.kt
vector/src/test/java/im/vector/app/features/onboarding/DirectLoginUseCaseTest.kt
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
vector/src/test/java/im/vector/app/test/fakes/FakeAuthenticationService.kt
vector/src/test/java/im/vector/app/test/fakes/FakeDirectLoginUseCase.kt
vector/src/test/java/im/vector/app/test/fakes/FakeStringProvider.kt
vector/src/test/java/im/vector/app/test/fakes/FakeUri.kt
vector/src/test/java/im/vector/app/test/fakes/FakeUriFactory.kt

Adds unit tests around the direct login flow via the `OnboardingViewModel` and the happy paths of the extracted `DirectLoginUseCase`
To ensure the direct login flow is treated as a sign in and avoid regressions such as #5623 
| WRONG ID | WRONG CREDENTIALS | OFFLINE | 404 HOMESERVER | 
|![after-wrong-id](https://user-images.githubusercontent.com/1848238/159958038-a310d989-ddf0-4f1a-8914-cddc9f23de83.gif)|![after-wrong-credentials](https://user-images.githubusercontent.com/1848238/159958312-06c4b005-3a1f-45a0-b837-a1c43e7cae27.gif)|![after-offline](https://user-images.githubusercontent.com/1848238/159958046-127bc745-1030-4059-811a-dee154eac620.gif)|![after-404-hs](https://user-images.githubusercontent.com/1848238/159958043-ec70da04-24ff-4471-9afa-b18ef61d6db2.gif) …

Direct login tests

---

vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/app/features/discovery/DiscoverySettingsController.kt
vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchFragment.kt
vector/src/main/java/im/vector/app/features/login/LoginFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/files/RoomUploadsFilesFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/media/RoomUploadsMediaFragment.kt
vector/src/main/java/im/vector/app/features/settings/devtools/AccountDataEpoxyController.kt
vector/src/main/java/im/vector/app/features/settings/threepids/ThreePidsSettingsController.kt

`is Loading` has been replaced by `Uninitialized, is Loading` in `when` statements, which is not strictly equivalent
This commit revert those changes.
Related: #4471
This PR fixes regressions on:
- create DM screen
- search message screen
Other places were not regression (`is Incomplete` may have been used previously instead of `is Loading`), but I prefer PR #4471 be strictly equivalent to the previous code.

Fix regression from #4471

---

changelog.d/5548.bugfix
vector/src/main/java/im/vector/app/features/call/conference/RemoveJitsiWidgetView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
vector/src/main/res/menu/menu_timeline.xml

Changes the condition for the voice call option on the action bar showing from being in a room of 2 or less people to simply being in a direct message room.
Closes https://github.com/vector-im/element-android/issues/4762
Quoting conversation in the issue (re current behaviour of voice call not showing):
"this is not a normal behaviour for a DM based group chat (using native VoIP system). We should have both voice and video calls displayed.
For "group rooms" e.g: the large Matrix community room, we currently use Jitsi and so only conference calls should be displayed with a video button. The conference calls are controlled by admins with permissions."
| 1:1 DM | Group DM | Non-direct chatroom |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/20701752/158458995-18f203af-5dc …

Fixes voice call button disappearing in DM rooms with more than 2 members

---

changelog.d/5516.misc
vector/src/main/res/layout/item_space_add.xml

Android should use "Create space" in the left panel instead of "Add Space" because "adding" suggests other actions like joining an existing space.
https://github.com/vector-im/element-android/issues/5516
- Login/Signup
- Open left slider
- Scroll to bottom
- Check copy
- OS version(s): A12 (API 31)

"Add space" copy is replaced with "create space" in left sliding panel

---

changelog.d/5663.bugfix
vector/src/main/java/im/vector/app/core/extensions/Context.kt
vector/src/main/java/im/vector/app/features/crypto/keys/KeysExporter.kt
vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupStep3Fragment.kt
vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSaveRecoveryKeyFragment.kt
vector/src/main/java/im/vector/app/features/settings/devtools/KeyRequestsFragment.kt
vector/src/test/java/im/vector/app/features/crypto/keys/KeysExporterTest.kt
vector/src/test/java/im/vector/app/test/fakes/FakeContext.kt

Instances where `ContentResolver.openOutputStream(Uri)` is used to potentially open existing files for writing have been fixed.
`ContentResolver.openOutputStream(Uri)` does not truncate existing files. If the amount of data written is smaller than the file size, you end up with new data at the beginning of the file followed by old data at the end of the file.
Some places where `ContentResolver.openOutputStream(Uri)` is used have not been changed because they only deal with newly created files and are thus not a problem.
1. Create a large text file with arbitrary content on your Android device (1 MB should do)
2. Go to *Settings → Security & Privacy*
3. Select *Export E2E room keys*
4. In the system file picker, select the file created in step 1, confirm that you want to overwrite the file …

Use truncate mode to replace the contents of existing files

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/UnsignedData.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/EventEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt

- When there is an empty thread after a thread event redaction, thread summary should be gone and thread list should remove that root thread record
- Redaction of a thread event should reduce the thread counter in main timeline thread summary
|Before redaction|After redaction|
| --- | --- | 
|![Screenshot_20220324-170027_Element dbg](https://user-images.githubusercontent.com/60798129/159946431-5e4ff86c-b035-4503-9193-eb9dc6f1d8f5.jpg)|![Screenshot_20220324-170045_Element dbg](https://user-images.githubusercontent.com/60798129/159946448-c33ecc01-a413-47e6-8f9e-47ea6f37c451.jpg)|
Closes #5598
Closes #5625

Thread redaction will now update the thread summary counter

---

changelog.d/5562.bugfix
vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewState.kt
vector/src/main/java/im/vector/app/features/home/room/threads/list/views/ThreadListFragment.kt
vector/src/main/res/layout/fragment_thread_list.xml

Add loader when user open/load the thread list
Especially on large rooms and on initial launch of the thread list, we should show an indicator to the user about the progress
|Before|After|
|---|---|
|![Screenshot_20220330-121034_Element dbg](https://user-images.githubusercontent.com/60798129/160796916-cbd6abbe-de7a-41d8-a4c1-5964ef8a0fc6.jpg)|![Screenshot_20220330-121026_Element dbg](https://user-images.githubusercontent.com/60798129/160796904-0e219d74-217b-4937-8d0b-ebefb091e1b9.jpg)|
Closes #5562

Add loader to thread list

---

changelog.d/4445.bugfix
vector/src/main/java/im/vector/app/features/rageshake/RageShake.kt
vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
vector/src/main/res/values/strings.xml

The "settings" button is replaced by a "disable" button when there is no session. Clicking on this button will disable the rage shake feature until the user manually reactive it by opening the application settings from a new session. 
Fix #4445 
Tested by triggering the rageshake dialog in both states (connected & disconnected).

Replace "open settings" button by "disable" action in RageShake dialog if there is no session

---

changelog.d/4867.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/CryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/NewSessionListener.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/actions/MegolmSessionDataImporter.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/IMXDecrypting.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/RoomSummaryEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt
vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt

Fixes #4867 - Message previews not decrypting upon receiving crypto keys
Follows the example of the timeline and adds a `session.cryptoService().addNewSessionListener` which refreshes the `RoomSummary.LatestPreviewContent` whenever we get a new key for the given room, the decryption will only be attempted if the current preview content doesn't contain an already decrypted json
<details>
<summary>
Timeline example
</summary>
https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt#L159
https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt#L121 …

Updating encrypted room list message previews on key updates

---

changelog.d/5660.feature
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt
vector/src/main/java/im/vector/app/features/location/LocationSharingServiceConnection.kt

We have already implemented the banner previously. This PR handles the visibility of the banner by observing the location service lifecycle.

Show a banner in timeline while location sharing service is running

---

changelog.d/5151.misc
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayoutFactory.kt

Currently, when there are multiple consecutive messages by the same author we group them as a single block in the main timeline.
If any of those messages, except for the last one, gets converted to a thread then there's no clear relationship between thread summaries and root messages anymore. This affects all layout modes, but can be especially problematic when Message Bubbles are enabled.
Below you can see the expected result, each root message should have the icon displayed
|Before | After |
|---|---|
|![Screenshot_20220404-115145_Element dbg](https://user-images.githubusercontent.com/60798129/161513395-bf1438f0-b08c-440d-be34-de41d7c9867a.jpg)|![Screenshot_20220404-120227_Element dbg](https://user-images.githubusercontent.com/60798129/161513436-f68b163e-28b9-4cd9-8e2f-d9eb04bec57b.jpg)| …

Improved thread rendering in the main timeline

---

changelog.d/5524.misc
vector/src/main/res/layout/bottom_sheet_space_settings.xml
vector/src/main/res/values/strings.xml

Update Spaces menu ordering and capitalisation
fixes #5524 
- open left slider menu
- open space menu

Update Spaces menu ordering and capitalisation

---

changelog.d/5567.misc
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt

Permalinks to root thread messages will now navigate the user within the thread timeline 
Closes #5567

Improve permalink on thread root message

---

changelog.d/5079.misc
vector/build.gradle
vector/src/main/java/im/vector/app/core/animations/Konfetti.kt
vector/src/main/res/layout/fragment_ftue_account_created.xml
vector/src/main/res/layout/fragment_ftue_personalization_complete.xml
vector/src/main/res/layout/fragment_timeline.xml

Update Konfetti to the latest version
Compilation warning is now fixed, probably due to the update of library Jitsi.
The rendering is not strictly equivalent, but still acceptable to me.
|Before|After|
|-|-|
|![confetti_before](https://user-images.githubusercontent.com/3940906/161565163-108bbf21-40ac-4271-864e-6767471d0ab9.gif)|![confetti_after](https://user-images.githubusercontent.com/3940906/161565211-e5e51a08-2ff1-4e1f-a592-306da60cf14c.gif)|
We are using the "rain" party, but we could choose a different configuration, from the sample app:
Also reporting that on the celebration screen (after account creation), the confetti are displayed below the other views, which is a bit strange to me, and not equivalent to what we have in the timeline. This PR does not change that.

WIP and low priority: upgrade konfetti to 2.0.2

---

changelog.d/5697.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/livelocation/LiveLocationBeaconContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLiveLocationContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/SendService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt
vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt

Sends beacon pulse events with a reference to the initial beacon info event.
```
{
"type": "org.matrix.msc3672.beacon",
"sender": "@user:matrix.org",
"room_id": "!abc123:matrix.org",
"content": {
"m.relates_to": {
"event_id": "<m.beacon_info event_id>",
"rel_type": "m.reference"
},
"org.matrix.msc3488.location": {
"uri": "geo:53.99803101552848,-8.25347900390625;u=10"
},
"org.matrix.msc3488.ts": 1648820683092
}
}
```

Live Location Sharing - Send location data

---

.github/ISSUE_TEMPLATE/release.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Small changes in the doc:
- Add a reminder for the strings cleanup
- Add a handy markdown table in the PR template
- Add a step when scheduling a String to be removed

Small doc udpate

---

changelog.d/5707.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/prune/RedactionEventProcessor.kt

We can prune completely redacted events again.
The reason why we kept the content of redacted events was due to the fact that relations are within the content. So after an event redaction we couldn't know if the event was a thread or a normal event.
Hopefully threads are now dynamic, so the problem is minimised. To further optimise this behaviour backend actions are needed to exclude relations from within the content.
Related [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3389)
Closes #5682

Prune the content of deleted events completely

---

changelog.d/5262.bugfix
vector/src/main/res/values/strings.xml

Fixes #5262 
I do not know why the tag had this attribute, probably some historical reason.

The string `ftue_auth_carousel_workplace_body` was declared not translatable

---

changelog.d/5659.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt

Pass M_NOT_FOUND and M_FORBIDDEN server errors to timeline listeners.
When opening a permalink for a non-existing event (e.g. the event has been deleted on the server), or a forbidden event (e.g. after a moderator redacted the event), we want to tell the user the event wasn't found, and instead reload the timeline without initial eventId. Before, it was just loading endlessly without any indication of a reason.
Create a permalink for a room with changing the eventId to something like "$doesntexist", and click it.

Fix endless loading timeline if opened at non-existing event

---

changelog.d/5481.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ChunkEntityHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt

SetReadMarkerTask was not updating the read marker when both the old and
the new fully read eventId weren't in the last chunk, even when the new
one was after the first one.
Do not assume that the current read marker is in a later chunk then the new requested one, unless it is in the last chunk.
1. Open room at permalink in the past
2. Scroll past the unread marker until you are in a later chunk, but not in the last one
3. Exit and re-enter room at permalink in the past
4. Check if read marker line has updated

Fix updating unread marker if not to latest chunk

---

changelog.d/5609.bugfix
vector/src/main/java/im/vector/app/features/spaces/SpaceMenuViewModel.kt

when user choose "leave all rooms and spaces" while leaving space we should preserve DMs
closes #5609 
- join space
- create DM inside this space
- leave space
DM should be preserved

don't leave DMs when leaving all rooms in space

---

changelog.d/5570.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MergedRoomCreationItem.kt

#5570 
- Create a DM 
-  Update the room name
- Check the Room creation item

[MergedRoomCreationItem] DM: RoomDescriptionText use the roomName instead of memberName

---

changelog.d/5475.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt

1. Permalink the latest message in a chat
2. Close the chat
3. Receive lots of messages
4. Open the chat at the permalink and see if the unread messages line shows up

Fix some cases where the read marker line would not show up when it should

---

changelog.d/5711.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/livelocation/LiveLocationBeaconContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLiveLocationContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventRelationsAggregationProcessor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/DefaultLiveLocationAggregationProcessor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt

First `m.beacon_info` state event is sent and then `m.beacon` event with location data is sent by referencing the state event. Aggregating beacon info state event with the last location will be robust for UI rendering.

Live Location Sharing - Attach location data to beacon info state event

---

changelog.d/5732.misc
vector/src/debug/java/im/vector/app/config/AnalyticsConfig.kt

Fixes #5732
Updates the posthog dev environment credentials as they were changed when the instance was migrated
- Sign up/in
- Enable analytics 
- Monitor the events in https://posthog.element.dev/events
- OS version(s): 29

Updating posthog dev environment credentials

---

changelog.d/5554.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ChunkEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEventPersistor.kt

I ran into following scenario recently: at some point, scrolling down to more recent messages wasn't working anymore, it would endlessly show the loading animation. This was reproducible, so I started debugging. It turned out:
- The TimelineChunk I was viewing had `chunkEntity.nextChunk == null`.
- When trying to download a new chunk, `TokenChunkEventPersistor` aborted, as the next chunk was already in the database.
It turned out that I had multiple chunks in my DB, so only one had the correct reference to `nextChunk`, while the other one, which I was viewing, was stuck at loading forever.
This commit works around this by "repairing" links in this case. I assume there is a better way/place to fix it, but this works for me for now. I figured it might still be interesting for you, maybe you …

Fix endless loading timeline due to conflicting chunks

---

changelog.d/5719.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventRelationsAggregationProcessor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadTimelineTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt
tools/hs_diag.py
vector/src/main/java/im/vector/app/VectorApplication.kt

The important change is in 7cfa38870b5854f733ee4324b4afe2916c3555fc : we do not cancel the current sync request when the app goes to background, to give a chance to the current sync, or the current sync response treatment to finish.
Test:
- on a big account, go to bg
- start the app
- observe that a incr sync is started (show debug info setting can help)
- go the bg
- previously the current incr sync was cancelled
- now the treatment continues
- if the user put the app in fg, we can see the current sync treatment is still in progress
- if the user wait a long time, the current sync treatment can end in bg
- the sync thread does not start another sync request when the app stay in bg
According to my tests, this is all fine.
This PR also contains some other minor changes regarding logs. …

Do not cancel the current sync request when the app goes to background

---

changelog.d/5731.bugfix
gradle/wrapper/gradle-wrapper.properties
vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt

Prevents invites to non-space non-null room types from showing up wrongly in the Space panel
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/2403652/162721016-d4002bb2-01ed-4014-a576-0bbb6dd68b98.png)|![image](https://user-images.githubusercontent.com/2403652/162722406-46ab88a1-ad8a-4db7-ab9e-cb68a5553f86.png)|
- Invited test account to video room
- Checked if invite was (wrongly) visible in the space panel
- OS version(s): API 22

Don't wrongly show non-space invites in the space panel

---

coverage.gradle

Fixes the `:vector` module coverage not being pulled into the jacoco report, this is due to the classes being under the variant name directory `gplayDebug`
To include missing coverage
For example the onboarding package was not being picked up. With the change...
- Run ./gradlew allCodeCoverageReport
N/A

Fixing missing :vector test coverage in Jacoco report

---

changelog.d/5767.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/user/UserService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewEvents.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/settings/ignored/IgnoredUsersAction.kt
vector/src/main/java/im/vector/app/features/settings/ignored/IgnoredUsersViewEvents.kt
vector/src/main/java/im/vector/app/features/settings/ignored/IgnoredUsersViewModel.kt
vector/src/main/java/im/vector/app/features/settings/ignored/IgnoredUsersViewState.kt
vector/src/main/java/im/vector/app/features/settings/ignored/VectorSettingsIgnoredUsersFragment.kt
vector/src/main/res/values/strings.xml

Displaying a confirmation dialog when a user is unignored, and perform an init sync when it's done:
- from the main setting screen
- from the room member list
- from the slash command action
Closes #3439
|From room member list|From settings|From slash command|
|-|-|-|
|![unignore](https://user-images.githubusercontent.com/3940906/163416991-12e3e8f3-8ec0-4b45-bbd3-86df3de7ca46.gif)|![unignore2](https://user-images.githubusercontent.com/3940906/163417010-33c9fb5d-55be-4dc4-b19c-9a60651ecfc2.gif)|![unignore3](https://user-images.githubusercontent.com/3940906/163417030-b8f97965-5da7-4c21-869f-e688d8eb5eec.gif)|
- Ignore a user
- Unignore a user -> observe the initial sync

Unignore user must perform an initial sync

---

changelog.d/5766.bugfix
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/app/features/navigation/Navigator.kt

Changes destination when joining space to explore space rooms (instead of not navigating anywhere)
Closes https://github.com/vector-im/element-android/issues/5334
I only applied this change when joining a room from the HomeActivity (from both the hamburger menu and opening a notification). Looking at the code, there are other places where you can join the space e.g. RoomDetailActivity, but I would have to guess it's more intentional that we don't navigate away from those destinations
TBA
|Before|After|
|-|-|
| ![SVID_20220414_154632_1](https://user-images.githubusercontent.com/20701752/163407427-09e8dc47-7e3f-479d-a1c7-78bdd0ec5b74.gif)  | ![SVID_20220414_153806_1](https://user-images.githubusercontent.com/20701752/163407592-ff706f27-19f7-46c9-afb0-d10945d82b7e.gif) |
- Invite a test …

Changes destination when joining space to explore space rooms

---

changelog.d/5757.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/uploads/GetUploadsTask.kt

Fixes #2530
There are different loading mechanisms for encrypted and non-encrpyted rooms. The correct sorting was only applied to the non-encrypted codepath, this PR adds sorting to the encrypted codepath too.
Note: this PR won't fix the problem with lazy loading more pages of uploads in the encrypted codepath. I'm new to this codebase and don't see the full implications of that issue, but I'm happy to investigate that further in a separate PR.
No screenshots for privacy reasons.
Open encrypted room with known media history.
Test 1: Open uploads list immediately, without scrolling back up in the timeline to load more media
Test 2: Scroll back in the timeline to cache media, then open uploads list

Fix sorting of uploads in encrypted rooms

---

changelog.d/5749.wip
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt
vector/src/main/res/layout/fragment_ftue_server_selection_combined.xml
vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
vector/src/test/java/im/vector/app/test/fakes/FakeRegisterActionHandler.kt

- Uses the TextUri type for url entry (fixes spaces being added when typing)
- Adds missing error states to the `Server Selection` screen instead of when submitting the account details
- Starts the registration flow at the point of setting the homeserver url instead of waiting until details submission  
- Fixes flashing loading state when selecting a usage option by flattening nested scope launching and only applying loading changes to top level entry points
Fixes #5749
|Before|After|
|-|-|
|![before-disabled-reg](https://user-images.githubusercontent.com/1848238/163376485-e021f5c8-efa2-402a-90a6-a273511cdff2.gif)|![after-disabled-reg](https://user-images.githubusercontent.com/1848238/163376507-73c8de5d-f239-4a03-b3ef-e60997b5a5c6.gif)| …

FTUE - Server selection errors

---

changelog.d/4305.bugfix
vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleActivity.kt

- [] Other :
add text to spinner when selecting person to start dm via space people list 
closes #4305
- select space
- select "people" tab
- press fab
- select a person (there shouldn't be already created dm with this person)

add text to spinner when click on space member (dm)

---

changelog.d/5761.feature
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/homeserver/HomeServerCapabilities.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/threads/ThreadsManager.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
vector/src/main/res/values/strings.xml

Users that their home servers do not support MSC3340, they will:
- Have a popup when enabling threads informing them about the inconsistencies may occur
- Will not see the bottom sheet beta `reply in thread `
- Step 1
- Step 2
- Step ...

Enhance user experience when home servers do not support threads.

---

changelog.d/5786.bugfix
vector/src/main/java/im/vector/app/features/matrixto/MatrixToAction.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt

Use matrixId instead of alias for NavigateToRoom
In some cases, the alias was used instead of the room id. The alias was blocking the room creation in the DB.
https://github.com/tchapgouv/tchap-android/issues/554
- Step 1
- Step 2
- Step ...

Crash: open private room by link

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt

Replaces monarchy.doWithRealm with monarchy.awaitTransaction
This fixes a bug that was crashing the whole sync
Test that https://github.com/vector-im/element-android/pull/5618 still works and no errors are thrown as a result of the sync

Replaces monarchy.doWithRealm with monarchy.awaitTransaction

---

changelog.d/5652.bugfix
library/multipicker/src/main/java/im/vector/lib/multipicker/CameraPicker.kt
library/multipicker/src/main/java/im/vector/lib/multipicker/CameraVideoPicker.kt
library/multipicker/src/main/java/im/vector/lib/multipicker/utils/MediaFileUtils.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/TemporaryFileCreator.kt

Edit: This PR's title and description have been updated as an entirely new solution has been implemented
The suspected cause of the error is that depending on the way the device's gallery caches images to be sent to the Element app, the content resolver may need to access IO operations (network, etc)
Currently, we're accessing the content resolver on the main thread
The way the content resolver works, any exception thrown during this operation would be rethrown as a `FileNotFoundException`, the exception we see in the rageshakes
On this PR, I forced the accessing of the io thread on the content resolver operations that send media from gallery. This does of course affect many other files with coroutine scope and suspend chains.
Potentially fixes …

Potentially fixes intermittent crashing from sending gallery images

---

.github/workflows/nightly.yml

With v1.0.0 of matrix-hookshot-action we can use hookshoot to send notifications via generic webhook, rather than embedding an access token with read/write access to the room. Otherwise there's no changes in the new hookshot-action version.
Neatness; avoiding risk of access token to the room leaking.

Move to using hookshot to send notifications, rather than using matrix client directly.

---

.github/workflows/triage-labelled.yml

Don't label A-Threads with Z-Labs any more because threads have been released
Don't label A-Threads with Z-Labs any more because threads have been released
Threads have been released
- Step 1
- Step 2
- Step ...

Update issue labelling automation

---

CHANGES.md
changelog.d/5835.bugfix
fastlane/metadata/android/en-US/changelogs/40104130.txt
matrix-sdk-android/build.gradle
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/space/SpaceService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpaceService.kt
vector/build.gradle
vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt

Ensure `getRootSpaceSummaries()` is not called on the main thread.

---

.github/workflows/triage-labelled.yml
changelog.d/5832.misc

Issues with `Z-ElementX-*` labels will appear in https://github.com/orgs/vector-im/projects/43

Add a GH workflow to push ElementX issues to the global board

---

changelog.d/5847.bugfix
vector/src/main/res/menu/menu_timeline.xml

Fixes missing call menu items due to `ifRoom` being used instead of `always`
Closes https://github.com/vector-im/element-android/issues/5840
I also added lint suprression and comments explaining why we keep these icons as `app:showAsAction="always"` as it can be very easy to overlook with the IDE warnings
|Before|After|
|-|-|
|![Screenshot_20220426_221120_im vector app debug](https://user-images.githubusercontent.com/20701752/165384323-ce7a323f-9832-413c-9dc0-8f32eaca49c4.jpg)|![Screenshot_20220426_220258_im vector app debug](https://user-images.githubusercontent.com/20701752/165384319-8ab2fd31-e968-4f98-8844-68f08a901464.jpg)|
- Enable threads
- Go to any room
- See video call, voice call, and threads icons in the action bar

Fixes Missing Call Icons when threads are enabled
