element-hq/element-android

changelog.d/5836.doc, docs/pull_request.md
We are going to have 2 reviewers per PR to improve the review quality.
=> Update the PR process doc with 2 reviewers and a new reviewer team

changelog.d/5826.bugfix, vector/src/main/java/im/vector/app/features/home/room/list/SpaceChildInfoItem.kt, vector/src/main/java/im/vector/app/features/spaces/explore/SpaceDirectoryController.kt, vector/src/main/res/layout/item_explore_space_child.xml
(Could be feature because it's purely an addition, or could be bugfix because it's techinically a fix for a regression from several versions ago. Considering it a bugfix for that reason)
Adds Suggested Tag in Explore Space (for suggested rooms)
Closes https://github.com/vector-im/element-android/issues/5715
Many versions ago (though I am unsure which), we had a suggested tag on each suggested room in the Explore Space screen. This was before the Open and Join buttons were added in the same screen, which is when I assume we lost this suggested tag.
This PR is adding this back in, with a slight design change from what it used to be to accomodate for the new Open and Join buttons.
||Before|After|
|-|-|-|
| Light | ![lightbefore](https://user-images.githubusercontent.com/20701752/164784373-531 …
=> Adds Suggested Tag in Explore Space

vector/src/main/java/im/vector/app/features/analytics/DecryptionFailureTracker.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
This PR aims to break down E2EE analytics errors into more detailed codes. 
Analytics `Error.context` schema will be used to temporary store a more detailed exception. The plan is to create a crypto specific schema/type to appropriately store crypto errors. 
`mxc_crypto_error_type` will be added in the context to differentiate crypto errors
=> Enhance crypto posthog errors with more details

changelog.d/5783.wip, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueMissingRegistrationStagesComparator.kt, vector/src/test/java/im/vector/app/features/onboarding/ftueauth/FtueMissingRegistrationStagesComparatorTest.kt, vector/src/test/java/im/vector/app/test/fixtures/StageFixtures.kt
Fixes #5783 
Reorders the FTUE onboarding steps to prioritise Email first, instead of consuming the first step given to us by the SDK. 
To match the flow with the designs
No gifs due to needing real email accounts
- Enable the combined register flag
- Start account creation
- Notice email is asked first (if the homeserver requires it)
- OS version(s): 29
=> FTUE - Registration step ordering

changelog.d/5872.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/OlmSessionStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
When we receive an encrypted to device, the SDK has to try to decrypt with all the known endToEnd olm session with the sender, until it founds one working.
According to some android logs, we can see as much as 300 olm session with the same device. This is not expected and probably due to some race issue but none the less currently we are trying to decrypt with all of them but in the wrong order, leading to lot of unnecessary trials. By using proper order we will now decrypt to devices faster.
This PR is not adressing the proliferation of olm session. This [PR](https://github.com/vector-im/element-android/pull/5380) should have adressed this, and the existing logs are probably from older sessions. 
- Step 1
- Step 2
- Step ...
=> olm try to decrypt with recent session first

changelog.d/5886.bugfix, vector/src/main/java/im/vector/app/UISIDetector.kt, vector/src/test/java/im/vector/app/features/crypto/UISIDetectorTest.kt
Grace period for UISIDetection was not working properly, causing errors to be reported even if the event was decrypted during grace period.
Added Unit test on UISIDetector.
=> Fix UISIDetector grace period bug

changelog.d/5855.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/state/StateService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/SendStateTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/CreateWidgetTask.kt
Returning the id of the newly created state event in methods to send state events.
Closes #5855
For instance, In some situation it may be useful to know the id of the newly created event to attach other related events to it.
- Change the name of a room
- Check you see log of the creation of the state event.
=> [SDK] Add missing return type in RoomApi.sendStateEvent()

vector/src/main/java/im/vector/app/features/spaces/SpaceSummaryController.kt
Try to fix https://github.com/matrix-org/element-android-rageshakes/issues/37765 :
> Thread: main, Exception: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
According to the log, this is a space invite. We may have a race condition, where an invite is displayed for a space which is already joined? So displayed twice and the Epoxy item has the same ID. This PR adds a prefix for the space invitation items.
Also space invite will be filtered out from the space root list. This is probably the only required fix, but keeping the previous fix on the `id` does not hurt.
|Before|After|
|-|-|
|<img width="353" alt="image" src="https://user-images.githubusercontent.com/3940906/166645965-277e996f-946e …
=> Space list crash fix

.github/ISSUE_TEMPLATE/release.yml, CONTRIBUTING.md, changelog.d/5854.doc, matrix-sdk-android/build.gradle, matrix-sdk-android/docs/modules.md, matrix-sdk-android/docs/packages.md, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt
Improve the documentation of the project regarding default language.
Small cleanup
Add headers to SDK documentation. It will render like this:
(sadly I did not find a way to include links)
=> Documentation update

changelog.d/5925.bugfix, vector/src/main/java/im/vector/app/core/ui/views/CompatKonfetti.kt, vector/src/main/res/layout/fragment_ftue_account_created.xml, vector/src/main/res/layout/fragment_ftue_personalization_complete.xml, vector/src/main/res/layout/fragment_timeline.xml
Fixes #5925 
The Konfetti v2 upgrade introduce a regression which meant android api 21/22 were no longer able to view the timeline
- The fix is to catch the exception caused by the unexpected non initialised fields in our own `CompatKonfettiView`
To fix a crash!
|Before|After|
|-|-|
|![before-konfetti-crash](https://user-images.githubusercontent.com/1848238/166655097-163c965c-8eb1-4345-ad11-e103dc79ac03.gif)|![after-konfetti-crash](https://user-images.githubusercontent.com/1848238/166655111-c20ca6aa-7505-40c4-bdc5-f0889295b007.gif)|
- Using a device running android 21
- open the timeline
- notice the crash
- OS version(s): 21
=> Crash - Konfetti API 21/22 crash

changelog.d/5421.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/EventInsertLiveObserver.kt
Fixes a crash when receiving and consuming call events #5421 (tentatively fixes #5591 and possibly other VOIP quirks)
- The event insertion logic is designed to be single threaded however due to coroutine continuation, there's unintended multiple thread access when the _processing_ and _post processing_ overlap
- Fixed by converting the launching to a flow which will sequentially process the launch logic on the single threaded scope
To fix a VOIP crash
- Adds a small delay to the postProcessing step
- Send 5 messages 
- Notice multiple concurrent launches    
```
Launch: LIVE_ENTITY_BACKGROUND
Process start: pool-7-thread-1
Process end: LIVE_ENTITY_BACKGROUND
Post start: LIVE_ENTITY_BACKGROUND
Launch: LIVE_ENTITY_BACKGROUND
Process start: pool-7-thread-1
Process end: …
```
=> Fixes crash when accepting VOIP calls

changelog.d/5874.bugfix, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
Fixes #5874 
- Caused by the sign in flow using the registration homeserver validation, fixed by posting the sign in mode event directly
_Will add a test case in a separate PR to help speed this up_
To fix a regression in the onboarding sign in 
|Before|After|
|-|-|
|![before-other-sign-in](https://user-images.githubusercontent.com/1848238/166666042-0ff3b1f0-5f7e-4ecf-b538-6895f1ae7ca3.gif)|![after-other-sign-in](https://user-images.githubusercontent.com/1848238/166666054-d856db9b-9e7f-4be9-83d3-39f1f9f014c6.gif)|
| Before | After |
| --- | --- | 
|![before-matrix-sign-in](https://user-images.githubusercontent.com/1848238/166667173-1565c4ad-c5c0-4330-8acf-bfe75abe3514.gif)|![after-matrix-sign-in](https://user-images.githubusercontent.com/1848238/166666742-8c3556ce-faac-438b-a92b-224e872f8f …
=> Fixing sign in via Other needing registration to be enabled

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo028.kt
Fixes the crash on launch in 1.4.14 when upgrading from a previous version. The crash is caused by a missing migration for the primary key in `LiveLocationShareAggregatedSummaryEntity.eventId`
To fix an upgrade crash
|Before|After|
|-|-|
|![before-missing-migration](https://user-images.githubusercontent.com/1848238/166959041-ea425a57-0123-4b12-93dc-234f85c6161a.gif)|![after-missing-migration](https://user-images.githubusercontent.com/1848238/166959225-788be860-0343-4156-9d5a-2236d53f5ff1.gif)|
- Install 1.4.13
- Upgrade to 1.4.14
- Notice the crash on launch
=> Fixing crash on launch - Missing migration

.github/workflows/nightly.yml
The tests seem to function against a synapse with an incorrect public_baseurl - some parts of the client use the public_baseurl for information and timeout, others use the configured http endpoint (which is hardcoded in the tests to be correct).
Making this change reduces timeouts waiting for requests to these incorrect endpoints.
=> Correct public_baseurl for nightly tests.

build.gradle, library/jsonviewer/build.gradle, matrix-sdk-android/build.gradle
Changed gradle dependency decleration from:
```groovy
mavenCentral()
```
to
```groovy
maven { url 'https://repo1.maven.org/maven2' }
```
probably squash this pr
Signed-off-by: Marcel <34819524+MarcelCoding@users.noreply.github.com>
=> Fixed dependabot

tools/hs_diag.py
Improve the hs_diag script to fetch info about the server version:
For instance, when running ` ./tools/hs_diag.py -s matrix.org`
We will get this extra bloc:
```
====================================================================================================
====================================================================================================
{
"server_version": "1.58.0rc2",
"python_version": "3.7.3"
}
```
=> Add diag request for Synapse

.github/workflows/post-pr.yml, .github/workflows/sonarqube.yml
Additionally move sonarqube as the only nightly run; and again report to the channel only if it fails.
This should reduce noise in the channel and also provide feedback on who merged a PR with a failing test in it.
=> Run the PR test after merge and report to channel if it fails

changelog.d/5941.bugfix, vector/src/fdroid/java/im/vector/app/fdroid/features/settings/troubleshoot/TestBatteryOptimization.kt, vector/src/main/java/im/vector/app/core/utils/SystemUtils.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthPersonalizationCompleteFragment.kt, vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt, vector/src/main/java/im/vector/app/features/settings/notifications/VectorSettingsNotificationPreferenceFragment.kt, vector/src/main/java/im/vector/app/features/sync/widget/SyncStateView.kt
If the user does not want to see animation, no chat effect will be performed. Also no account creation celebration will e displayed.
It will speed up the UI test, which have animation disabled.
It can also be useful to user with health condition (see #5557)
I tried to update the speed for Konfetti regarding the animation scale, but I think it has to be handled by the third party library. Same for the snowfall.
- Step 1
- Step 2
- Step ...
=> No animation -> no chat effect

build.gradle, library/jsonviewer/build.gradle, matrix-sdk-android/build.gradle
See #5961  for more context.
Changed gradle dependency declaration from:
```groovy
mavenCentral()
```
to
```groovy
maven { url 'https://repo1.maven.org/maven2' }
```
and same thing for other gradle repository providers.
Will replace #5966, as it's more complete. But it does not compile locally, let's see what's happening on the CI.
=> Try to workaround Dependabot issue #5961

changelog.d/5911.feature, vector/src/main/java/im/vector/app/features/VectorFeatures.kt, vector/src/main/java/im/vector/app/features/call/CallControlsView.kt, vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt, vector/src/main/java/im/vector/app/features/call/VectorCallViewActions.kt, vector/src/main/java/im/vector/app/features/call/VectorCallViewModel.kt, vector/src/main/java/im/vector/app/features/call/webrtc/ScreenCaptureServiceConnection.kt, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
1. Start a video call between 2 or more devices
2. Once the call is connected tap the menu icon (...)
3. You should see the "Start sharing screen" option, select it
4. A system permission dialog should appear, accept it
5. Your screen will be streamed to other devices (in ~5 seconds)
6. A sticky push notification should appear for Android 10 or later versions
7. "Start sharing screen" button should turn to "Stop sharing screen"
=> Screen sharing over WebRTC

changelog.d/5965.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/wellknown/GetWellknownTask.kt
Applies the SSL/TLS certificate handling logic to the `sign in with matrix id` flow
- Due to the flow inferring the homeserver url from the matrix id domain it meant we were passing a null `HomeserverConnectionConfig` which in turn meant the SSL/TLS socket factory was never applied 
To make the `sign in with matrix id` and `other` sign in flows consistent
|Before|After|
|-|-|
|![Screenshot_20220506_154304](https://user-images.githubusercontent.com/1848238/167163396-e25cf73f-0169-4749-b5c4-fecb4b40b4dd.png)|![after-certs](https://user-images.githubusercontent.com/1848238/167163406-4a9e5e13-be2e-4614-955a-41e527b86089.png)|
- change the device time/date to a month in the past
- attempt to sign in via `sign in with matrix id`
- Notice invalid home server error, however when signing in via …
=> Handling SSL/TLS errors during WellKnown lookup

changelog.d/5997.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/api/auth/data/VersionsKtTest.kt
Citation: https://matrix.to/#/!ewdjhNcPcEmYNKzlWp:t2l.io/$CkPuvKdFZyFL547JCy5J3MfvLaWUo_a1XEdmiop1PKc?via=matrix.org&via=element.io&via=envs.net
=> Remove spec v1.3 check for threads

vector/src/main/res/layout/fragment_ftue_server_selection_combined.xml
- Temporarily hides the EMS section in the server selection screen
Fixes #5975 
- We're still determining the content of this block with marketing
|Before|After|
|-|-|
|![Screenshot_20220510_110116](https://user-images.githubusercontent.com/1848238/167603571-631d77a2-3c91-4e95-99e9-126763ae8291.png)|![Screenshot_20220509_175314](https://user-images.githubusercontent.com/1848238/167602513-6428ae15-7826-4e8e-97a3-5547299df712.png)|
- With the combined login or register feature flag enabled
- Start the account create/login process and edit the homeserver
- Notice the EMS section is no longer shown
=> FTUE - Temporarily hide EMS section

.github/workflows/post-pr.yml
Currently the error message states:
```
Post-merge validation of feature/michaelk/make_things into develop by failed:
```
Let's make it say
```
Post-merge validation of feature/michaelk/make_things into develop by michaelkaye failed:
```
=> Ensure we print the user in the post-PR merge tests.

changelog.d/6047.feature, library/ui-styles/src/main/res/values/colors.xml, library/ui-styles/src/main/res/values/palette.xml, library/ui-styles/src/main/res/values/theme_dark.xml, library/ui-styles/src/main/res/values/theme_light.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/presence/model/PresenceEnum.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncPresence.kt, vector/src/main/java/im/vector/app/core/ui/views/PresenceStateImageView.kt, vector/src/main/res/drawable/ic_presence_away.xml, vector/src/main/res/drawable/ic_presence_busy.xml, vector/src/main/res/values/strings.xml
add presence indicator busy and away.
Parity with web.
It's difficult to test away so I did not and busy was tested on our private setup you have access to some accounts (Aarenet/Element room)
Signed-off-by: Chagai Friedlander @me:chagai.website
=> add presence indicator busy and away

changelog.d/5973.doc, docs/integration_tests.md
In #5949 we corrected the public_baseurl for the integration tests in github actions. This PR adds a note to the troubleshooting of integration tests about the similar failure when it occurs locally.
Docs are good :)
=> Document need for public_baseurl to be correctly set.

.github/workflows/quality.yml, build.gradle, changelog.d/5887.sdk, docs/add_threePids.md, docs/pull_request.md, matrix-sdk-android/build.gradle, matrix-sdk-android/docs/modules.md, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/TestMatrix.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/Matrix.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt, vector/build.gradle, vector/lint.xml, vector/src/androidTest/java/im/vector/app/core/utils/TestMatrixHelper.kt, vector/src/main/java/im/vector/app/VectorApplication.kt, vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
Small change in the Matrix class: deprecated methods have been removed and the constructor is now public. Also the fun `workerFactory()` has been renamed to `getWorkerFactory()`
Documentation has been improved to.
Knit has been set up, also on the CI. For now we are not doing a big usage of it, but can be more useful in the future.
Also generated documentation header will have working link:
(see previous version without links in #5854)
=> Improve Matrix class

changelog.d/5865.bugfix, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
Fixes https://github.com/vector-im/element-android/issues/5865
As per https://www.w3.org/TR/webrtc/#hold-functionality track and direction need to be set for hold/unhold music. 
iOS client was setting tracks.
=> Direction and track need to be set for hold/unhold

changelog.d/5724.sdk, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/qrcode/VerificationTest.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/verification/CancelCode.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/DefaultVerificationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransport.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportRoomMessage.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportToDevice.kt
When a verification request sent from a client is answered, this same client should notify other clients that verification is no longer necessary.
Issue: #5724 .
Using the same account:
- Log into a client, verify session (I used the web client).
- Log into another client.
- Log into the Android client.
- A 'verify your session' banner should appear, tap on it.
- On one of the other clients, accept the verification request.
- Check that the verification popup disappears on the other client.
- OS version(s): 10
=> Notify other devices of acceptance of verification request

.github/workflows/post-pr.yml
I despair at the github actions docs, and also wish this was testable outside of merging a PR, but it is what it is.
Apparently you also need a .login to get the username of the pull requester
Display the name in the alerts.
=> Add `.login` to get the username rather than Object in the test failure alerts.

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineForwardPaginationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelinePreviousLastForwardTest.kt
This permits a clear error when the events are missing / extra and while
not making the test invulnerable to future changes in events, should be
explicit on what's changed.
The test was failing with a count of 58 events not the expected 57. 
To diagnose why, I split out the events by type, and asserted each count individually.
I believe we've gained one state event of some type, but I don't know which one (as we didn't have historical information).
From now, the test will error with a quite specific reason (missing an event or found an event)
A similar issue was fixed in another pagination test (different style of test so splitting out checks by message type was harder)
Fix integration test
=> In TimelineForwardPaginationTest, explicitly test for the events we expect

changelog.d/6089.misc, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/Util.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeSanityTests.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/KeyShareTests.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/WithHeldTests.kt
Ensure tests which should fail are actually failing.
Make test fail if they have to.
A quick local local test confirm that the test was not failing when `fail()` is called in a try block and `Throwable` are caught.
NA
- Run android tests
There are 2 failing tests, not related to this PR: `testUnwedging()` and `trustKeyBackupVersionWithRecoveryKeyTest()`
=> Ensure calling 'fail()' is not caught by the Exception handler

changelog.d/6103.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt
Interestingly, Glide is clearing current image before the new image is loaded which causes a flicker on timeline item. This PR suggests to use current drawable as placeolder while loading the new static map image.
=> Glide - Use current drawable while loading new static map image

changelog.d/6109.bugfix, vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomViewModel.kt
Fixes #6109. Based on the work of @bmarty on #6107.
Prevents early cancelation of the coroutine scope used to send the invites.
When inviting several people to a room, only the first couple of users were actually invited. The `InviteUsersToRoomActivity` was being finished ahead of time, cancelling the `viewModelScope` used to send the invite requests, and this prevented the rest of the users from being invited. This was caused by an `onEach` statement being used as `onCompletion`.
- Create a room or open a room where you can invite other users.
- Invite several users, at least 3 or 4.
=> Fix sending multiple invites to a room reaching only one or two people

changelog.d/5856.bugfix, library/ui-styles/src/main/res/values/styles_timeline.xml, vector/src/main/res/layout/view_read_receipts.xml
Use a fixed `12dp` text size for the read recept counter number instead of `12sp` that would scale with the font scale setting. It's important that text should fit inside the circle and the circle has a fixed size regardless of the font scale.
|Before|After|
|-|-|
|![Screenshot_20220427-201459](https://user-images.githubusercontent.com/1694986/165594717-d4ba276e-96ed-49b2-a07c-18f6069f6a6a.jpg)|![Screenshot_20220427-201526](https://user-images.githubusercontent.com/1694986/165594784-9ecf95d0-0066-44b5-b8e0-3d99df4a1717.jpg)|
Screenshots taken on "Largest" font setting.
- Use the font scale setting to set something above "Normal"
- Visit a room timeline with more than 5 read receipts
Signed-off-by: Olivér Falvai <ofalvai@gmail.com>
=> Use fixed text size in read receipt counter

changelog.d/6141.misc, dependencies.gradle
We downgrade the gradle version to address issues with running jacoco unit test coverage and the realm plugin together.
Based on tests; if the realm plugin is enabled then jacoco will not instrument classes, leading to no coverage information for those tests. This affects things in the android instrumented tests.
If we disable realm then the coverage succeeds.
If we downgrade the gradle version then coverage succeeds regardless of the realm status.
This is a big enough actual change that downgrading separately to work on the coverage tests is valid.
=> Downgrade gradle from 7.2.0 to 7.1.3

changelog.d/6140.bugfix, vector/src/main/AndroidManifest.xml
This applies the same `configChange` settings we use on `VectorCallActivity` and `VectorJitsiActivity` to `WidgetActivity` to prevent the widget web view from reloading on device screen or orientation changes.
We'll be using the widget system to integrate Element Call into the app. Currently rotating the device causes the widget web view to reload which disconnects the call.
- Join #ecwidgettest:matrix.org
- Navigate through into the widget web view running Element Call
- Rotate the device
- The web page shouldn't reload
=> Prevent widget web view from reloading on screen / orientation change (PSF-1034)

changelog.d/6148.bugfix, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/DecryptRedactedEventTest.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/EventDecryptor.kt
The SDK was throwing decryption errors (null algorithm) when trying to decrypt a redacted event.
This was not really visible to the user but it could trigger auto rageshakes (if on in settings), and report decryption failure to posthig
Change is as per js-sdk https://github.com/matrix-org/matrix-js-sdk/blob/ad030bfc1f919fecd80e249fc69769ce58bf9201/src/crypto/index.ts#L2873
|Before|After|
|-|-|
|<img width="428" alt="image" src="https://user-images.githubusercontent.com/9841565/170245337-e42fc68b-72bd-4a5d-8931-c265cc7945ed.png">|<img width="434" alt="image" src="https://user-images.githubusercontent.com/9841565/170245232-4c771a36-4b93-4c2e-9b9b-0a5799c28b86.png">|
=> Fix decrypting redacted event

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/AccountCreationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/ChangePasswordTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/account/DeactivateAccountTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/api/network/ApiInterceptorTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/DecryptRedactedEventTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeSanityTests.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/PreShareKeysTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/UnwedgingTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/crosssigning/XSigningTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/encryption/EncryptionTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/KeyShareTests.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/WithHeldTests.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/replayattack/ReplayAttackTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/ssss/QuadSTests.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/SASTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/qrcode/VerificationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/threads/ThreadMessagingTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/PollAggregationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineForwardPaginationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelinePreviousLastForwardTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineSimpleBackPaginationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineWithManyMembersTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/search/SearchMessagesTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
Improve test stability
Sharing CommonTestHelper / CryptoTest helper between several tests is making tests instable.
Added a new helper to get them per test. It also automatically cleanup opened session
Sample
```
@Test
fun test_Something() = withTestHelpers(context()) { cryptoTestHelper ->
val testHelper = cryptoTestHelper.testHelper
....
}
```
=> Improve test stability

changelog.d/6163.feature, vector/src/main/java/im/vector/app/core/extensions/String.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/test/java/im/vector/app/core/extensions/StringExtensionsTest.kt
Checks for the presence of Right to Left unicode directional overrides when tapping on a URL, if one is found we'll show the user the URL with the overrides disabled and ask them to confirm they want to continue.
Fixes #6163 
Newer versions of Android (31+) seemingly handle the oddness out of the box by avoiding marking the URLs as clickable links, however previous versions will still attempt to link out to them, although the formatting is often broken.
| --- | --- |
- Using Element web /devtools construct and post a link containing a RtL override `\u202E` 
- Using an Android 25 device view and tap the link
- Notice a popup informing the user that the URL may not be what they expect
- OS version(s): 21, 25, 28, 31
=> Ask the user to confirm urls which contain unicode direction overrides

changelog.d/4862.bugfix, vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt, vector/src/main/java/im/vector/app/features/notifications/NotifiableMessageEvent.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt, vector/src/test/java/im/vector/app/test/fixtures/NotifiableEventFixture.kt
Persisting notification info fails for non-null Uris:
```
E NotificationEventPersistence: ## Failed to save cached notification info
E NotificationEventPersistence: java.io.NotSerializableException: android.net.Uri$HierarchicalUri
E NotificationEventPersistence: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
E NotificationEventPersistence: 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
E NotificationEventPersistence: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
E NotificationEventPersistence: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
E NotificationEventPersistence: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
E …
```
=> Fix some notifications never getting dismissed

changelog.d/6166.feature, vector/src/main/java/im/vector/app/core/resources/UserPreferencesProvider.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageItemAttributesFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageImageVideoItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageInformationData.kt, vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/values/strings.xml, vector/src/main/res/xml/vector_settings_preferences.xml
This pull request adds a new switch to the preferences, allowing users to enable autoplaying of animated images in their room timeline.
This feature is already present in element-web and was commonly requested by the community:
The pull request resolves #1160, resolves #5094
|Before|After|
|-|-|
|![autoplay disabled](https://user-images.githubusercontent.com/42888162/170547622-bd33b42b-5994-414f-95fc-3a2be206c08e.gif)|![autoplay enabled](https://user-images.githubusercontent.com/42888162/170547235-d21eefe7-802c-46ea-a790-44a8879f2009.gif)|
- Send a non animated image, an animated image and a video in to a room
- Verify that the animated image animates only when the setting is enabled
- Check that the video retains it's play button and the animated image hides the play button when …
=> [Feature] Add the option to autoplay animated images

changelog.d/6132.misc, vector/src/main/res/values/strings.xml
Fixed 2 strings in English; `room_list_people_empty_body` and `room_list_rooms_empty_body` in /vector/src/main/res/values/strings.xml
I'm submitting this PR because of the other PR I made in [SchildiChat/SchildiChat-android](https://github.com/SchildiChat/SchildiChat-android/): SchildiChat/SchildiChat-android#125
Testing isn't necessary
Signed-off-by: Jeremy Baxter <jeremytbaxter@protonmail.com>
=> Fixed grammar in 2 English strings

changelog.d/6133.feature, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapCrossSigningTask.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSetupRecoveryKeyFragment.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSharedViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapStep.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapViewState.kt, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationAction.kt, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/verification/conclusion/VerificationConclusionController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/conclusion/VerificationConclusionFragment.kt, vector/src/main/java/im/vector/app/features/crypto/verification/request/VerificationRequestController.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnown.kt, vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnownExt.kt, vector/src/main/java/im/vector/app/features/raw/wellknown/SecureBackupMethod.kt, vector/src/main/res/layout/bottom_sheet_bootstrap.xml
Fixes #6133 .
Adds a feature to setup mandatory key backup or passphrase for all users based on the `.well-known` configuration of the home server.
- Set up a server with the following configuration changes:
```
"io.element.e2ee": {
"secure_backup_required": true
"secure_backup_setup_methods": ["passphrase"] (optional, defaults to "all methods accepted")
}
```
- Create an account in it.
=> Add support for mandatory backup or passphrase from .well-known configuration

changelog.d/5827.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Signed-off-by: Michael Loipführer <milo@sft.lol>
When somebody selected the "Show all Rooms in Home" preference all rooms are shown in the home space. A user would therefore not expect to switch away to another space upon clicking a notification for a room.
Currently upon clicking a notification for a room which is part of a space, that space is automatically selected as the current space even if it is part of the home space due to "Show all Rooms in Home" being active.
This PR changes the behavior to properly respect the "Show all Rooms in Home" preference:
Now Element does not switch away from the home space when clicking on a notification.
The current behavior is quite annoying and unintuitive. For example I am part of multiple small spaces. After clicking on a notification I have to …
=> do not switch away from home space on notification

vector/src/main/java/im/vector/app/features/widgets/webview/WebviewPermissionUtils.kt, vector/src/test/java/im/vector/app/features/widgets/WebviewPermissionUtilsTest.kt
As advised by @bmarty [here](https://github.com/vector-im/element-android/pull/6149#discussion_r885413833) this is switching from an NPE to `fatalError` to avoid crashing in production builds.
=> Use fatalError instead of NPE

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/enhancement.yml
Small improvement on the issue template.
Inspired from https://github.com/Kotlin/dokka/blob/master/.github/ISSUE_TEMPLATE/bug.md
@kittykat WDYT?
=> Add a final question to know if the issue submitter will provide a PR

changelog.d/5528.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
I was observing cases where `builtEvents[modificationIndex]` was not
having the same `eventId` as the `udpatedEntity` in `handleDatabaseChangeSet()`.
In particular, I observed both cases that
- there was no item in the list yet with the same `eventId` as the updated
one
- there was an item with the same `eventId` already in the list, but at a
different position.
Whenever this happened, the timeline would render missing, duplicated,
or swapped messages in the timeline.
Instead of relying on `modificationIndex` to be the same for both the
change set and `builtEvents`, look up the proper index by `eventId`.
~~Note: I'm not entirely sure if this is the correct way to fix this.
Is the previously used assumption that `displayIndex == modificationIndex` something that should hold?
If yes, this …
=> Fix missing/swapped/duplicated messages due to wrong TimelineChunk modifications or insertions

changelog.d/6146.feature, vector/src/main/java/im/vector/app/features/crypto/keysrequest/OutboundSessionKeySharingStrategy.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnown.kt, vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnownExt.kt
Fixes #6147 , depends on #6134 .
Variable config `outbound_keys_pre_sharing_mode` in .well-known configuration of home server will be honoured now, overriding the default value of `BuildConfig.outboundSessionKeySharingStrategy`.
See content ^.
- Set up a home server.
- Add this custom config to the `synapse/rest/well_known.py` configuration:
```json
"io.element.e2ee": {
"outbound_keys_pre_sharing_mode": "on_typing" # (or any of on_room_opening, on_typing, disabled)
}
```
- Create an account in that home server.
- Create or join a room, then do the interaction needed to pre-share the keys (just opening it, typing, etc.).
=> Allow .well-known configuration to override key sharing mode

changelog.d/6222.bugfix, vector/src/main/java/im/vector/app/features/voice/AudioWaveformView.kt
- Start recording a voice message and lock the mic.
- Wait for 2 minutes (max length of a voice message)
- The app crashes
Fixes #6137 
- Start recording a voice message and wait for 2 minutes
- Send the record, delete the record and everything should work as expected
=> Fix StackOverflowError while recording voice message [PSF-1065]

changelog.d/5285.wip, vector/src/main/java/im/vector/app/features/analytics/extensions/SignUpExt.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewActions.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewState.kt, vector/src/main/java/im/vector/app/features/login/LoginActivity.kt, vector/src/main/java/im/vector/app/features/login/LoginFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt, vector/src/main/java/im/vector/app/features/login/SocialLoginButtonsView.kt, vector/src/main/java/im/vector/app/features/login2/LoginFragmentSignupUsername2.kt, vector/src/main/java/im/vector/app/features/login2/LoginFragmentToAny2.kt, vector/src/main/java/im/vector/app/features/onboarding/AuthenticationDescription.kt, vector/src/main/java/im/vector/app/features/onboarding/Login2Variant.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractSSOFtueAuthFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSignUpSignInSelectionFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueExtensions.kt
Fixes #5285 
Adds `SignUp` event tracking after the user creates an account **AND** consents to tracking. 
- Creates an `AuthenticationDescription` abstraction  and also sets the ground work for tracking sign in in the future.
- Chains the `AuthenticationDescription` through to the `HomeActivity` in order to be tracked
To enable the collection of sign up metrics (and sign up type)
No UI changes
```
D/Analytics: capture(Signup(authenticationType=Password))
```
- With the combined login feature flag enabled
- Create an account
- Notice the SignUp tracking event in posthog
=> FTUE - Sign up analytics

changelog.d/6017.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/extensions/Strings.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/HomeServerVersion.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/auth/version/HomeServerVersionTest.kt
Fixes #6017 Supporting Homeserver versions without a patch number.
Versions without a patch are considered as having a patch of `0` eg 1.5 is parsed as `major: 1 minor: 5 patch: 0`
- Makes the Homeserver version regex support optional patch numbers 
- Adds unit tests around the parsing
To support version formats defined by the spec 
No UI changes
Handled by unit tests 
=> Homeserver version without patch number parsing

changelog.d/6232.bugfix, vector/src/main/res/layout/bottom_sheet_bootstrap.xml
Closes #6232 
- Step 1
- Step 2
- Step ...
=> Text cropped: "Secure backup"

changelog.d/6209.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/DeactivateLiveLocationShareWorker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessor.kt
Fix in the aggregation process to avoid scheduling deactivation worker too many times and when not necessary.
Closes #6209 
|Before|After|
|-|-|
|<video src="https://user-images.githubusercontent.com/46314705/171189694-7176c173-c7b6-45b5-9159-6d0591944cee.mp4"/>|<video src="https://user-images.githubusercontent.com/46314705/171194021-2b0d43e2-2ee3-4aa2-8d75-a64c74bdb0b3.mp4"/>|  
- Enable location sharing in Settings -> Preferences
- Enable live location sharing in Settings -> Labs
- Go to a room
- Start a live location share
- Remove the app from the stack of opened app
- Go back to the app
- Go to the room timeline where the live is running
- Check the live is still considered as running 
=> Fix wrong status of live location sharing in timeline (PSF-1073)

changelog.d/6244.feature, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayoutFactory.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt, vector/src/main/res/values/strings.xml, vector/src/main/res/xml/vector_settings_labs.xml, vector/src/main/res/xml/vector_settings_preferences.xml
We have many settings flags to be able to enable static/live location sharing:
- Settings > Preferences > Enable Location Sharing
- BuildSettings.enableLocationSharing
- Settings > Labs > Enable Live Location Sharing
To simplify the location sharing feature this PR suggests:
- Remove the “Enable location sharing” from preferences
- Enable location sharing by default using the Build config field
- Use the build config field to check whether the location sharing option should be visible in the composer view
- Remove the “Render user locations in timeline” labs flag because there is no performance concern anymore
- You should see the location sharing icon in composer menu by default and able to share/render a static location
- You can share live location after enabling it under Settings > …
=> Re-organize location settings flags [PSF-1062]

changelog.d/6247.bugfix, library/ui-styles/src/main/res/values/dimens_font.xml, library/ui-styles/src/main/res/values/styles_location.xml, library/ui-styles/src/main/res/values/styles_text_view.xml, library/ui-styles/src/main/res/values/text_appearances.xml, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt, vector/src/main/java/im/vector/app/features/location/MapTilerMapView.kt, vector/src/main/java/im/vector/app/features/location/UrlMapProvider.kt, vector/src/main/java/im/vector/app/features/location/live/map/LocationLiveMapViewFragment.kt, vector/src/main/res/layout/fragment_location_live_map_view.xml, vector/src/main/res/layout/item_timeline_event_location_stub.xml, vector/src/main/res/values/donottranslate.xml, vector/src/main/res/values/strings.xml
- Static map copyright text on the timeline item was not readable because of the font size
- Static map copyright text on the timeline item of live location sharing was behind the informative tile
- Mapbox copyright attribution items on the maximized map were behind the user list bottom sheet
- This PR suggests to use custom copyright text on the timeline item and to fix the position of attribution items
- Required copyright attributes should always be visible and readible
| Before    | After     | Maximized |
|-|-|-|
|![copyright_before](https://user-images.githubusercontent.com/1254401/172388483-d4efbb68-f66f-44d4-9e79-328e33cf171e.png)|![copyright_after](https://user-images.githubusercontent.com/1254401/172388535-a6a95156-292b-4be2-a4fe-5b3867949b4c.png)|![copyright_maximized](https://u …
=> Fix copyright attributions of map views [PSF-1058] - [PSF-1072]

changelog.d/6280.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
"Report Content" action is added in live location timeline item.
There is a chance of abusing this feature so it should be reportable.
=> Add report action for live location messages [PSF-1067]

vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthAccountCreatedFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthPersonalizationCompleteFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthUseCaseFragment.kt, vector/src/main/res/layout/fragment_ftue_auth_use_case.xml, vector/src/main/res/layout/fragment_ftue_personalization_complete.xml
- Making the confetti celebration during the FTUE onboarding always appearing during the account creation breaker. Previously we would show the confetti after the optionally personalisation steps.
- Hiding the connect to server button as we'll revisit for the V2 implementation #5782 
- We want all users to see the confetti during account creation 
- We want to avoid showing previous flows
| --- | --- |
|![before-account-created](https://user-images.githubusercontent.com/1848238/173326338-2965e3fa-1ec7-4207-9e35-f787e803b8b3.gif)|![after-account-created](https://user-images.githubusercontent.com/1848238/173326331-ada5df52-1ee0-47ee-930f-b7db2b906e90.gif)
| --- | --- |
|![Screenshot_20220613_111152](https://user-images.githubusercontent.com/1848238/17333 …
=> FTUE - Minor tweaks

changelog.d/6087.misc, vector/src/main/res/values-bg/strings.xml, vector/src/main/res/values-ca/strings.xml, vector/src/main/res/values-cs/strings.xml, vector/src/main/res/values-de/strings.xml, vector/src/main/res/values-eo/strings.xml, vector/src/main/res/values-es/strings.xml, vector/src/main/res/values-et/strings.xml, vector/src/main/res/values-eu/strings.xml, vector/src/main/res/values-fi/strings.xml, vector/src/main/res/values-fr-rCA/strings.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values-hu/strings.xml, vector/src/main/res/values-in/strings.xml, vector/src/main/res/values-it/strings.xml, vector/src/main/res/values-kab/strings.xml, vector/src/main/res/values-lv/strings.xml, vector/src/main/res/values-nb-rNO/strings.xml, vector/src/main/res/values-nl/strings.xml, vector/src/main/res/values-pl/strings.xml, vector/src/main/res/values-pt-rBR/strings.xml, vector/src/main/res/values-ru/strings.xml, vector/src/main/res/values-sk/strings.xml, vector/src/main/res/values-sq/strings.xml, vector/src/main/res/values-sv/strings.xml, vector/src/main/res/values-tr/strings.xml, vector/src/main/res/values-uk/strings.xml, vector/src/main/res/values-vi/strings.xml, vector/src/main/res/values/strings.xml
Fixes #6087 Updates the copy formatting to match iOS (android/material avoids centered text in dialogs) 
- Doesn't update script based languages as I'm not sure how the sentence should be structured.
To match iOS
|Before|After|
|-|-|
|![Screenshot_20220601_150551](https://user-images.githubusercontent.com/1848238/171423971-c3416137-82c9-46be-b4f3-69f41bdbe8fd.png)|![Screenshot_20220601_145612](https://user-images.githubusercontent.com/1848238/171424006-7dab6761-1601-41aa-8b19-4ac4649cfda7.png)|
- Start creating an account (after submitting username/password)
- Press back
=> Avoid manual line breaks in exit onboarding dialog copy

.github/workflows/build.yml
=> Run exodus privacy scanner on all PRs

changelog.d/6285.feature, vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt
Allows `text/*` content types to be shared via android share menu as file attachments. 
Fixes #6285 
|Before|After|
|-|-|
|![share-ics](https://user-images.githubusercontent.com/1848238/173403246-a72d1b80-ee7b-4e46-b048-4e237bf54a51.gif)|![after-share-calendar](https://user-images.githubusercontent.com/1848238/173403272-1e4ae5ea-59b6-40c4-8289-3c8ba9fec56f.gif)|
- Attempt to share an .ics file to element from another app, like google chrome
=> Allow sharing text mimetype content via android's share menu

changelog.d/6290.bugfix, vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
Fixes large images crashing when opened in the timeline
Closes https://github.com/vector-im/element-android/issues/2642
Also closes https://github.com/vector-im/element-android/issues/1951
Also closes https://github.com/vector-im/element-android/issues/6190
Also closes https://github.com/matrix-org/internal-config/issues/1184
Error:
`java.lang.RuntimeException: Canvas: trying to draw too large(111132000bytes) bitmap.`
Caused when the image is rendered in `AttachmentViewerActivity`. We were overriding the size to scale the bitmap to be much larger than it already is. Upon investigation, this provides no benefit in increasing the quality of the opened image.
An `onlyRetrieveFromCache` line was removed to as this prevented the image transition from happening and seems to give little benefit …
=> Fixes large images crashing when opened in timeline

vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/RegistrationActionHandler.kt, vector/src/main/java/im/vector/app/features/onboarding/RegistrationWizardActionDelegate.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/features/onboarding/RegistrationActionHandlerTest.kt, vector/src/test/java/im/vector/app/features/onboarding/RegistrationWizardActionDelegateTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationActionHandler.kt, vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizardActionDelegate.kt, vector/src/test/java/im/vector/app/test/fixtures/SelectedHomeserverStateFixture.kt
Adds unit tests around the registration stages 
- Lifts the next stage logic out of the UI layer and into a dedicated class `RegistrationActionHandler`
- Extracts all the `RegistrationAction -> Stage` logic out of the `ViewModel` and adds unit tests   
To add missing coverage to the FTUE area
No UI changes
-  Sign up for a new account
=> FTUE - Stage selection and Registration action testing

changelog.d/6261.misc, vector/src/main/java/im/vector/app/features/rageshake/BugReportActivity.kt, vector/src/main/res/layout/activity_bug_report.xml
Makes screenshots opt-in rather than opt-out as screenshots contain messages which the logs do not
Fixes #6261 
|Before|After|
|-|-|
|![Screenshot_20220613_180354](https://user-images.githubusercontent.com/1848238/173408197-8fe0b47b-c677-4d0a-a659-223c71b61fc4.png)|![Screenshot_20220613_181111](https://user-images.githubusercontent.com/1848238/173408214-405d7eaa-e428-431e-bfe8-b5d214b68ecf.png)|
- Open a bug report
- Notice the send screenshot toggle is disabled
=> Making bug report screenshots opt in instead of opt out

changelog.d/5913.misc, vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt, vector/src/main/java/im/vector/app/features/location/LocationTracker.kt, vector/src/test/java/im/vector/app/features/location/LocationTrackerTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeContext.kt, vector/src/test/java/im/vector/app/test/fakes/FakeHandler.kt, vector/src/test/java/im/vector/app/test/fakes/FakeLocationManager.kt
- Use the latest known location among the ones from all providers when starting tracking.
- Adding minimal period of update to notify callback of location change to avoid too many notifications.
- Prioritize locations received from the providers in the following order: “Fused”, “GPS”, other providers
- Avoid calling callback for provider not available when only one of them is disabled (should be called only when all providers are disabled)
Closes #5913 
- Check location sharing is enabled in the settings
- Go to a room
- Start to share location
- Check the current location is good on the map
- Check the logs of the LocationTracker
=> [Location tracker] - Fix some location tracking issues (PSF-1000)

changelog.d/6155.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/LiveLocationShareAggregatedSummaryEntityQuery.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessor.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessorTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/PollAggregationProcessorTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeClock.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeRealm.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeWorkManager.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeWorkManagerProvider.kt
Adding unit tests to cover code of aggregation process of live location share events.
Closes #6155 
- Run unit tests
=> Adding unit tests for live location sharing aggregation code (PSF-1063)

changelog.d/6329.misc, vector/src/androidTest/java/im/vector/app/core/utils/WaitUntil.kt, vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderLTests.kt, vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderQTests.kt, vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderTestExt.kt, vector/src/main/java/im/vector/app/features/voice/AbstractVoiceRecorder.kt
Added a couple of methods to `vector`'s  instrumented tests to retry a check several times, applied this to VoiceRecorder tests.
Fixes #6329 .
VoiceRecorder instrumented tests are a bit flaky as they depend on Audio/MediaRecorder and some JNI code. With this code we'll retry those several times instead of failing on the first try.
=> Fix flaky tests for voice recording feature

.github/workflows/tests.yml, build.gradle, coverage.gradle, matrix-sdk-android/build.gradle, vector/build.gradle
Fixes #6299 missing unit test coverage  
- The current android gradle plugin we're using (7.1.3) has a bug which causes unit test coverage generated with `testCoverageEnabled` to be invalid, we can generate the coverage via jacoco instead.
- The fix is to split the unit tests and instrumentation tasks so that we can change the configuration and collect all the results
- Also disables instrumenting the code for debug builds which should speed up compilation a little~
The include unit test coverage in the sonar reports
https://github.com/vector-im/element-android/pull/6323
- with the gradle build option `testCoverageEnabled = true` run the unit tests `./gradlew testGplayDebugUnitTest`
- attempt to generate a jacoco report from the resulting `unit_test_coverage/*.exec` file
- notice no …
=> Missing unit test coverage 

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo030.kt
App launch crash when migrating database from 29 -> 30
Replacement for #6358 
Tested with Debugger, this is fine.
=> Fix migration to 30. Seems that `isNull` with long path is not working :/

changelog.d/5821.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionListeners.kt
Fixes #5821 & #6080
- Uses a _safe to concurrently modify_ structure for the `SessionListeners` list
We have a few implementations of the `SessionListener` which remove themselves from the `SessionListeners` in `onSessionStopped` ([SessionScopedProperty](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/session/SessionScopedProperty.kt#L39), [InvitesAcceptor](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/invite/InvitesAcceptor.kt#L146)) , this is a problem because we iterate through all the listeners in order to call `onSessionStopped`, resulting in a concurrent modification exception.
The error itself seems to be race condition presenting itself intermittently due to `synchronised` …
=> Fixing concurrent `dispatchTo` crash

.github/workflows/quality.yml
Adds the missing CI arguments to the linting CI tasks, should stop the build from unexpected crashing (most likely due to running out of memory)
To fix the crashing linting CI tasks
No UI changes
Let the CI evaluate a PR...
N/A
=> Fix CI lint tasks unexpectedly crashing

changelog.d/6357.bugfix, vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
Bugfix
Background: Clients write Markdown and convert it to HTML before sending the event. All events are formatted as HTML. However, if an HTML formatted event happened to include markdown characters, Element Android would incorrectly render that markdown.
For example, an event with formatted_body: "*test*" should be displayed as literally *test* with no effects, but Element Android incorrectly displayed it as test in italics.
**This commit fixes this behaviour, making Element Android not parse Markdown in HTML messages.**
From the perspective of most users it will appear that backslash escapes now work properly (even though this wasn't the real issue).
https://github.com/vector-im/element-android/issues/5657
I created 4 messages with the following formatted_body: `*normal*`, …
=> Fix formatted_body being parsed as Markdown

changelog.d/6369.feature, vector/src/main/java/im/vector/app/features/settings/push/PushGatewayItem.kt, vector/src/main/res/layout/item_pushgateway.xml, vector/src/main/res/values/strings.xml
This makes the current pusher's profile tag visible in the advanced settings.
For debugging notifications, it's helpful to know the profile tag.
|Before|After|
|-|-|
| ![Screenshot_20220623_105413](https://user-images.githubusercontent.com/1137962/175259349-7efdce06-e315-43cf-b9ec-f73150c5692e.png) | ![Screenshot_20220623_104538](https://user-images.githubusercontent.com/1137962/175258259-2a14536d-1503-4c68-a356-b8fa371aaf03.png) |
Navigate into Settings > Advanced Settings > Notification Targets
=> Expose pusher profile tag in advanced settings

changelog.d/6375.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/LocationInfo.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLocationContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessorTest.kt, vector/src/main/java/im/vector/app/features/location/LocationData.kt, vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt, vector/src/test/java/im/vector/app/features/location/live/map/UserLiveLocationViewStateMapperTest.kt
Adding a missing prefix "u=" for uncertainty value when building a geo uri.
Closes #6375 
- Enable live location share flag in labs settings
- Share a static location (user or pinned) in a room
- Check the location is correctly shared
- Start a live location share in a room
- Check the live is correctly running in the room
- Stop the live
- Check the live is correctly ended
=> [Location Share] - Adding missing prefix "u=" for uncertainty in geo URI (PSF-945)

changelog.d/6396.doc, docs/pull_request.md
with optional additional reviewers
=> Update the PR process doc to come back to one reviewer

changelog.d/6101.bugfix, vector/src/main/java/im/vector/app/features/call/dialpad/DialPadLookup.kt
refactor - better naming, return native user id and not sip user id and create a dm with the native user instead of with the sip user
When dialing an extension which has a native user behind it, a native matrix call happens instead of a matrix sip call because the user id of the sip user was used instead of the native one - so the sip virtual lookup (which comes in this case after the native lookup) failed. Otherwise also creating a native room when one does not exist seems like the right thing to do and the code looks more clear with these names.
- private setup - you should have access in Aarenet/Element room
Signed-off-by: Chagai Friedlander @me:chagai.website
=> Native lookup fixes

changelog.d/6364.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/CheckIfExistingActiveLiveTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/GetActiveBeaconInfoForUserTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StopLiveLocationShareTask.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultCheckIfExistingActiveLiveTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultGetActiveBeaconInfoForUserTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingServiceTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStopLiveLocationShareTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeGetActiveBeaconInfoForUserTask.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt
When starting a new live location share in a room, a check has been added to stop any current active live location share.
Closes #6364 
2 devices are needed
- Ensure to enable the lab flag for live location sharing on both devices
- Sign in with the same account on both devices
- Start a live location share on one device
- Check it appears correctly in the room for both devices
- Start a live location on the other device
- Check the previous live is stopped
- Check the location sharing service is stopped on the first device
- Check the location sharing service is started on the second device
- Check the new live appears correctly in the room
- OS version(s): Android 11, 10
=> [Location sharing] - Stop any active live before starting a new one (PSF-942)

changelog.d/6350.feature, vector/src/main/java/im/vector/app/features/location/LocationSharingFragment.kt, vector/src/main/java/im/vector/app/features/location/live/LiveLocationLabsFlagPromotionBottomSheet.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/layout/bottom_sheet_live_location_labs_flag_promotion.xml, vector/src/main/res/values/strings.xml
We want to show users the Live Location Sharing option with an informative dialog.
|Screenshot|
|-|
|![lls_promoting_labs_flag](https://user-images.githubusercontent.com/1254401/174619844-00eefb76-27bd-443a-8762-55512fd0871e.png)|
- Disable the live location sharing labs setting if it is enabled
- In a room, choose the location sharing attachment option from the composer
- Choose "Share live location"
- You should see the dialog like the attached screenshot above
- If the user enables location sharing and clicks the OK button then the flag in labs settings should also be enabled
- Share a live location
=> Promote live location labs flag [PSF-959]

.github/ISSUE_TEMPLATE/release.yml
Update the release recipe, for faster release of the SDK.
Manually setting the reviewers to regular release manager of the projects.
=> Replace 5 manual steps to 1 command line step

changelog.d/6392.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/extensions/RealmExtensions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/fatal.kt
Else we will get an infinite loop. This specific error will help to figure out what is happening.
Tested locally with a Realm schema upgrade:
```kotlin
internal class MigrateSessionTo032(realm: DynamicRealm) : RealmMigrator(realm, 32) {
override fun doMigrate(realm: DynamicRealm) {
val chunks = realm.where("ChunkEntity")
.findAll()
chunks.forEach { chunk ->
chunk.getList(ChunkEntityFields.TIMELINE_EVENTS.`$`).clearWith {
// NO OP, let the app crash!
}
}
}
}
```
And got this crash with stacktrace in log:
```shell
java.lang.RuntimeException: Unable to create application im.vector.app.VectorApplication: java.lang.IllegalStateException: `clearWith` MUST delete all elements of the RealmList
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
at …
```
=> Ensure clearWith lambda is deleting all the list item

changelog.d/6288.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/network/ApiPath.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/alias/GetRoomLocalAliasesTask.kt
This increases compatibility with homeservers and allows them to remove
Element Android specific workaround.
fixes #4830
see https://github.com/ruma/ruma/pull/936
see https://github.com/matrix-org/synapse/issues/8334
see https://github.com/matrix-org/synapse/pull/9224
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
It makes Element Android (as the last client still relying on the MSC endpoint) use the stable endpoint to list aliases. Fixes #4830
Servers shouldn't have to implement MSCs, that have long been merged, to allow Element Android to run on them. This allows the removal of workarounds (or the unstable endpoints) in several server implementations and makes development of new servers easier.
- Step 1
- Step 2
- Step ...
=> Use stable endpoint for alias management

vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt
When you click on URL the browser activity is stacked on Element task. it's better to open the URL on existing browser task or open the browser in new task if it's not already opened.
=> Open URL on external browser task

changelog.d/6401.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/location/LocationSharingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StartLiveLocationShareTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingServiceTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStartLiveLocationShareTaskTest.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/CheckIfCanReplyEventUseCase.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingService.kt, vector/src/test/java/im/vector/app/features/home/room/detail/timeline/action/CheckIfCanReplyEventUseCaseTest.kt
Adding a reply action on a live location share message.
Closes #6401
- Enable the live location share flag in Settings -> Labs
- Go to a room
- Start sharing a live location share
- With another account long press the message
- Check "reply" action is available
- Press reply
- Send a reply message
- Check the reply message is correctly displayed
- Check we navigate to and highlight the replied live location share message when pressing the reply message
=> [Location sharing] - Reply action on a live message (PSG-343)

changelog.d/6450.bugfix, library/multipicker/src/main/java/im/vector/lib/multipicker/MediaPicker.kt
- Bugfix
Gallery picker can now pick external images. Previously, choosing an external application would only allow videos, not images. This was due to one of the mime type entries being interpreted incorrectly.
The scenarios for attaching files are as follows:
For comparison.
- "Recent" screen displays other file types and filters
- External gallery displays all image/video files
- External file manager displays all files
- "Recent" screen only displays image/video files and filters - **right**
- External gallery only displays video files - **wrong**
- External file manager displays all files - **technically wrong but not a problem**
- "Recent" screen only displays image/video files and filters - **right**
- External gallery displays all image/video files - **right**
- External file …
=> Gallery picker can pick external images (not just videos)

changelog.d/6423.misc, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/PollItemViewStateFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/PollItem.kt, vector/src/main/java/im/vector/app/features/poll/PollViewState.kt, vector/src/main/res/layout/item_timeline_event_poll.xml, vector/src/main/res/values/strings.xml, vector/src/test/java/im/vector/app/features/home/room/detail/timeline/factory/PollItemViewStateFactoryTest.kt
Add a description "Results will be visible when the poll is ended" under undisclosed and not ended poll.
Closes #6423 
- Go to a room
- Create an closed poll
- Check the description under the poll is correct
- Vote
- End the poll
- Check the description under the poll is correct
=> [Poll] - Add a description under undisclosed poll when not ended (PSB-134)

changelog.d/6430.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/PollOptionView.kt
Hiding explicitely the votes views when rendering a poll with undisclosed state.
Closes #6430 
- Go to a room
- Create a poll 1 (closed or opened)
- Create a poll 2 (closed or opened)
- Remove poll 1
- Remove poll 2
- Create a closed poll
- Check the votes are not visible
- Vote
- End the poll
- Check the ended view is correct
=> [Poll] - Wrong votes in closed poll after removing 2 previous polls (PSG-590)

vector/src/main/java/im/vector/app/core/di/FragmentModule.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthPhoneConfirmationFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/res/layout/fragment_ftue_phone_confirmation.xml, vector/src/main/res/values/donottranslate.xml
The second part to #6108 -  MSISDN registration step #6043
To update the phone number entry confirmation screen to match the FTUE designs.
*using a temporary number
| CONFIRMATION | GIF |
| --- | --- |
- Setup a local synase with ThreePid msisdn's enabled 
- Create an account
- Supply a phone number to receive the confirmation sms on
- Enter the confirmation code and notice the sign up move to the next step
- OS version(s): 31v2
=> [FTUE] MSISDN / Phone number confirmation

changelog.d/6442.bugfix, vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
- Bugfix
HTML entities are now displayed as the characters they represent.
Fixes #6445. This was a regression from #6357.
My test case was an event with `"formatted_body": "&ZeroWidthSpace; ♫ We&apos;re on easy street ♫"`. If successful, when displayed in Element Android, it should look like "♫ We're on easy street ♫".
I also looked at the tests I used in #6357.
```json
{
"body": "raw",
"formatted_body": "&ZeroWidthSpace; ♫ We&apos;re on easy street ♫",
"msgtype": "m.text",
"format": "org.matrix.custom.html"
}
```
| --- | --- |
|![Screenshot_20220704_142338](https://user-images.githubusercontent.com/1848238/177163927-d5e62525-74d6-4668-8136-06a72349d868.png)|![Screenshot_20220704_141944](https://user-images.githubusercontent.com/1848238/177163932-c7cc5f30-5ce4-4e6c-a643 …
=> Fix HTML entities being displayed in messages

changelog.d/6458.misc, coverage.gradle, vector/src/fdroid/AndroidManifest.xml, vector/src/fdroid/java/im/vector/app/fdroid/service/FDroidGuardServiceStarter.kt, vector/src/fdroid/java/im/vector/app/fdroid/service/GuardAndroidService.kt, vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/core/services/CallAndroidService.kt, vector/src/main/java/im/vector/app/core/services/VectorAndroidService.kt, vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt, vector/src/main/java/im/vector/app/features/call/telecom/VectorConnectionAndroidService.kt, vector/src/main/java/im/vector/app/features/call/webrtc/ScreenCaptureAndroidService.kt, vector/src/main/java/im/vector/app/features/call/webrtc/ScreenCaptureServiceConnection.kt, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingAndroidService.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingFragment.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingServiceConnection.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
To limit confusion with our Matrix SDK Services
=> Rename Android Service to use `AndroidService` suffix

changelog.d/6451.bugfix, vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt, vector/src/main/java/im/vector/app/features/attachments/ShareIntentHandler.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/share/IncomingShareFragment.kt, vector/src/main/res/values/strings.xml
Fixes a crash when `text/plain` is shared due to a regression introduced by #6296 which meant plain text was attempting to be read as a file
- Checks for the presence of plain text before `text/*` files (the fix!) 
- Separates the `Share Intent Handling` from the `AttachmentsHelper`, means the callbacks can be separated (and will make introducing tests easier)
To fix #6451 
TIL incognito chrome tabs aren't captured by screen recorders :sweat_smile: 
|Before|After|
|-|-|
|![before-share-crash](https://user-images.githubusercontent.com/1848238/177298392-ec0f2146-e756-4b73-8f17-22f8ea1d468d.gif)|![after-sharing-text](https://user-images.githubusercontent.com/1848238/177298412-013c0fc1-eba3-4a0c-91c4-33b6dbf55a99.gif)|
- With Element installed and signed in
- Open a website in Google Chrome
- …
=> Crash - Sharing text 

vector/src/main/java/im/vector/app/features/widgets/WidgetFragment.kt, vector/src/main/java/im/vector/app/features/widgets/webview/WebviewPermissionUtils.kt
This suppresses the web view / checkbox permission dialog and redirects straight to the system permission dialog (in case it's needed).
=> Suppress webview / checkbox permission dialog

changelog.d/6469.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt
Fix crash
```
Thread: main, Exception: java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
at org.matrix.android.sdk.internal.util.DefaultBackgroundDetectionObserver.onStart(BackgroundDetectionObserver.kt:63)
at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:39)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
```
See https://github.com/matrix-org/element-android-rageshakes/issues/40142
- Step 1
- Step 2
- Step ...
=> Fix ConcurrentModificationException on BackgroundDetectionObserver

changelog.d/6461.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
=> Timeline: fix validation of timeline event changes

changelog.d/4777.bugfix, vector/src/androidTest/java/im/vector/app/core/utils/TestSpan.kt, vector/src/androidTest/java/im/vector/app/features/html/EventHtmlRendererTest.kt, vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt, vector/src/main/java/im/vector/app/features/html/ListHandlerWithInitialStart.java
Includes the html tag start position when parsing html Lists. 
- Copies the [original ListHandler](https://github.com/noties/Markwon/blob/master/markwon-html/src/main/java/io/noties/markwon/html/tag/ListHandler.java#L44) and takes into account the initial starting value.
- Providing our own list tag handler overrides the default
To fix the confusing behaviour of numbered lists losing their initial value #4777 
|Before|After|
|-|-|
|![Screenshot_20220705_143148](https://user-images.githubusercontent.com/1848238/177351720-d3109ba3-df3e-4300-89e9-53632eba21f9.png)|![Screenshot_20220705_142811](https://user-images.githubusercontent.com/1848238/177351745-f29d2434-dc0e-4a74-8713-54d1280ba82a.png)|
- From Element web, send a message starting with `#.` eg `5. July`
- Notice the 5 has been …
=> Fixing numbered lists always starting from 1

vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
Adds missing edit continuation logic which fixes the edit flow not updating with the selection. 
- Updates the unit test to include the `StartRegistration` result type (which catches the broken behaviour)
To fix the broken homeserver edit feature, was likely introduced by a rebase regression
|Before|After|
|-|-|
|![before-server-selection](https://user-images.githubusercontent.com/1848238/177142521-5adce610-4826-4ca5-a9ce-a42e47770ddc.gif)|![after-homeserver-selection](https://user-images.githubusercontent.com/1848238/177142554-29c60ba4-eb45-4555-98d7-be60438f7962.gif)|
- With the combined registration feature flag enabled
- Create a new account
- Edit the selected homeserver
- Notice the UI doesn't change and the back behaviour is inconsistent 
=> FTUE - Homeserver edits not updating the selected server UI

.github/workflows/quality.yml
This PR adds a GitHub action to check if a file has been added to the directory `changelog.d`.
This PR does not include such file (yet), because I want the new check to detect it.
This GHA will not be mandatory for all PRs, but can be used as a reminder.
The plan is also to check that `towncrier` can be setup on GHA, because it will be used in #6478 
Closes #6481
=> Add GitHub action to check for a towncrier file

changelog.d/6510.bugfix, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
- Only making use of the legacy `SETTINGS_LABS_SPACES_HOME_AS_ORPHAN` if it exists and the new key does not
- Manually deletes the legacy `SETTINGS_LABS_SPACES_HOME_AS_ORPHAN` after migrating to `SETTINGS_PREF_SPACE_SHOW_ALL_ROOM_IN_HOME`
Fixes #6510 Inconsistent _rooms in home_ behaviour
The app incorrectly returns the `Show all rooms in home` preference as enabled when it's meant to be disabled by default. This is caused by the migration logic from the previous flag not taking into account if the preference existed, causing us to always default to enabled. 
Will also fix some flakiness in the UI Tests!
|Before|After|
|-|-|
|![before-space-rooms](https://user-images.githubusercontent.com/1848238/177974006-113fcccf-e47b-4202-ba1a-46ac9cdf36df.gif)|![after-spaces-room](https://user-images.g …
=> Fixes inconsistent rooms in home behaviour

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MimeTypes.kt, vector/src/main/java/im/vector/app/features/attachments/MultiPickerIncomingFiles.kt, vector/src/main/java/im/vector/app/features/attachments/ShareIntentHandler.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/share/IncomingShareFragment.kt, vector/src/test/java/im/vector/app/features/attachments/ShareIntentHandlerTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeFunction1.kt, vector/src/test/java/im/vector/app/test/fakes/FakeIntent.kt, vector/src/test/java/im/vector/app/test/fakes/FakeMultiPickerIncomingFiles.kt, vector/src/test/java/im/vector/app/test/fixtures/ContentAttachmentDataFixture.kt
Adds unit tests around the `ShareIntentHandler` as a way to help avoid regressions around the sharing intents. 
- Introduces a `MultiPickerIncomingFiles` to keep the tests simpler, avoids needing to handle the mapping of `MultiPicker / *` to `ContentAttachmentData`, allowing the test to focus on intent types -> file parsing
To add tests to #6467 , they were split in order to help the origin PR be review/merged quicker
No UI changes
Same as #6467 
=> Adding tests around the share intent handling

vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt, vector/src/androidTest/java/im/vector/app/ui/robot/CreateNewRoomRobot.kt, vector/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt, vector/src/androidTest/java/im/vector/app/ui/robot/MessageMenuRobot.kt, vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt, vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceCreateRobot.kt, vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceMenuRobot.kt, vector/src/androidTest/java/im/vector/app/ui/robot/space/SpaceRobot.kt
- Always attempts to close the soft keyboard
- Avoids creating multiple rooms with the same name (empty room)
To get `./gradlew connectedGplayDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=im.vector.app.ui.UiAllScreensSanityTest` to consistently pass locally across different emulators
This check also caught #6511  
No business logic changes
- OS version(s): 28, 31v2
=> UI test stabilization

changelog.d/6534.bugfix, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/UnwedgingTest.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/EventDecryptor.kt
When a to_device olm message cannot be decrypted (BAD_ENCRYPTED_MESSAGE), the sending devices was marked as wedged (ratchet got desync). 
In order to fix it, the SDK will automatically try to refresh the session with this device by creating a new session and sending a new dummy prekey message.
This unwedging mechanism can only be done once per hour.
The issue is that when a device was marked as wedged it was never removed later. Meaning that if the app stayed on for long, a new olm session will be created every hour. This could explain the proliferation of olm sessions noticed in some logs:
Fixes #6534
Can be tested by commenting out persisting olm sessions in the code, then force discard session and send messages. Kill/Restart the sending device will then restore an old ratchet version …
=> fix olm session proliferation

changelog.d/6541.misc, library/ui-styles/src/main/res/values/styles_location.xml, vector/src/main/res/layout/item_live_location_users_bottom_sheet.xml, vector/src/main/res/layout/view_location_live_message_banner.xml, vector/src/main/res/layout/view_location_live_status.xml, vector/src/main/res/values/strings.xml
Using the same text for stop button in live location share feature.
Fixing some button insets problem on some languages.
Closes #6541 
- Start a live location share in a room
- Check the same text is used for stop buttons in the top status bar in the room and in the tile message
- Check insets are good in your language
- Press the tile message
- Check the correct text is used for the stop button in the bottom sheet list
- Check insets are good in your language
=> [Location Share] - Standardise "Stop" texts for live (PSG-622)

changelog.d/6538.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/db/AuthRealmMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/raw/GlobalRealmMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/db/RealmIdentityStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/database/MatrixRealmMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/database/RealmMigrator.kt
Log the duration of the DB migrations.
Just have more info on the logs and the rageshakes.
- Step 1
- Step 2
- Step ...
=> More DB migration log

changelog.d/6579.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt
We should remove location related logs even if they are debug logs.
- Step 1
- Step 2
- Step ...
=> Do not log the live location of the user (PSG-63)

vector/src/main/java/im/vector/app/core/utils/SystemSettingsProvider.kt
added default value for system font scale setting
if user never changed system font scale (Settings->Display->Font Scale) app will crash on start
- Step 1
- Step 2
- Step ...
=> fixed crash when system font scale setting isn't set

vector/build.gradle
Just reordering lines.
Error was `No matching client found for package name 'im.vector.app'`
Full logs: https://github.com/vector-im/element-android/runs/7402504552?check_suite_focus=true
Let's merge this today and see tomorrow morning for the next try!
=> Fix error when building `./gradlew assembleGplayNightly`

changelog.d/6546.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixPatterns.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/api/MatrixPatternsTest.kt, vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt, vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt, vector/src/main/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCase.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueExtensions.kt, vector/src/main/res/layout/fragment_ftue_combined_register.xml, vector/src/main/res/values/donottranslate.xml, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
- Matches iOS and checks for user name availability on the loss of focus on the user name field
- Updates the register page design to match the latest iteration of the designs (removes the subtitle and selected homeserver description)
- Adds a footer to the user name reinforcing the full matrix id as a way of discoverability 
- Adds a check for minimum 8 characters password length
Fixes #6546
To simplify the registration screen copy and reinforce the matrix id concept
| --- | --- |
|![before-register](https://user-images.githubusercontent.com/1848238/178773071-da21bb34-55af-490e-884a-c7132f44361c.png)|![after-register](https://user-images.githubusercontent.com/1848238/178773073-5f4c2c4a-3575-4082-8530-3a967c8f3bc3.png)
| PASSWORD MINIMUM | USERNAME TAKEN | FULL MATRIX …
=> FTUE - Combined register copy review

changelog.d/6567.feature, vector/src/main/java/im/vector/app/features/location/live/map/LocationLiveMapMarkerOptionsDialog.kt, vector/src/main/java/im/vector/app/features/location/live/map/LocationLiveMapViewFragment.kt, vector/src/main/res/drawable/bg_live_location_marker_popup.xml, vector/src/main/res/layout/fragment_location_live_map_view.xml, vector/src/main/res/layout/view_live_location_marker_popup.xml, vector/src/main/res/values/strings.xml
Users can now open others' (or their own) live locations with other map applications by tapping the marker of the users. Shared location is the static location at the time users click to share button.
|Share location|Open with|
|-|-|
|![share_location](https://user-images.githubusercontent.com/1254401/179224377-fee6f39a-3dbc-4256-a1f7-9ae749d0d631.png)|![share_location_2](https://user-images.githubusercontent.com/1254401/179224754-5404d1c6-5159-4e6c-be59-f0e4ae9a2304.png)|
- Share a live location
- Click on timeline item to open maximized map
- Click on user's marker on the map
- You should see the "share" action
=> Share location with other apps (PSG-242)

changelog.d/6487.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventVisibilityHelper.kt, vector/src/main/res/values/strings.xml
Collapsing multiple successive redacted events to save space on timeline. Refactoring a little the code to ease the readability.
Closes #6487 
- Go to a room
- Send multiple different types of messages
- Delete successive sent messages
- Check successive redacted messages are collapsed
- Check you can expand to see redacted messages individually
=> [Timeline] - Collapse redacted events (PSG-523)

changelog.d/6585.bugfix, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupTest.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/InboundGroupSessionStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/MXOlmDevice.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/keysbackup/DefaultKeysBackupService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
Fixes a regression on backup introduced by #5853
The backedUp boolean was reset to false by the InboundGroupSessionStore when saving inbound session.
Also there is no point in persisting back inbound group session after a decryption, so I removed that.
Added back the `KeysBackupTest`, they were ignored.
=> fix backup looping same keys

changelog.d/6596.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo034.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/livelocation/LiveLocationShareAggregatedSummaryEntity.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/LiveLocationShareAggregatedSummaryEntityQuery.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessor.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/livelocation/LiveLocationAggregationProcessorTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeRealm.kt
When aggregating a new beacon event, deactivating only the previous beacon using start timestamp of the live as comparison. Without it, receiving old beacons results in deactivating the current one. 
Closes #6596 
- Start and stop several lives in a room
- Start a new live
- Switch the light/dark theme in the system
- Check the current live is not deactivated
As there is a DB migration
- install a previous version of the app.
- install this new version
- check there is no crash at startup
=> [Location Share] - Live is considered as ended while still active (PSG-617)

changelog.d/6395.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/qrcode/DefaultQrCodeVerificationTransaction.kt, vector/src/main/java/im/vector/app/features/crypto/verification/conclusion/VerificationConclusionController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/conclusion/VerificationConclusionViewModel.kt, vector/src/main/res/values/strings.xml
When scanning an invalid (malformed) QR code during a user verification, the application will display the compromised warning modal. It looks like this warning is a bit too much compared to other reason like mismatched keys or users.
And given that some mobile clients can have issues decoding some QR code it's worth it to create a specific screen.
So now instead a specific warning is shown for QR code format issues
|Before|After|
|-|-|
|<img width="269" alt="image" src="https://user-images.githubusercontent.com/9841565/176155997-04723a25-67dd-4ec7-8d91-4f37bf0071d9.png">|<img width="272" alt="image" src="https://user-images.githubusercontent.com/9841565/176155938-5f18f7e8-845e-4081-9fa2-c918a4b779ea.png">|
- Step 1
- Step 2
- Step ...
=> Display specific message when verif code malformed

changelog.d/6548.feature, vector/src/debug/java/im/vector/app/features/MainViewModel.kt, vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/VectorApplication.kt, vector/src/main/java/im/vector/app/core/di/ActiveSessionSetter.kt, vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt, vector/src/main/java/im/vector/app/core/pushers/VectorMessagingReceiver.kt, vector/src/main/java/im/vector/app/features/MainActivity.kt, vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/link/LinkHandlerActivity.kt, vector/src/main/java/im/vector/app/features/login/LoginActivity.kt, vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt, vector/src/main/java/im/vector/app/features/onboarding/Login2Variant.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/java/im/vector/app/features/share/IncomingShareAction.kt, vector/src/main/java/im/vector/app/features/share/IncomingShareActivity.kt, vector/src/main/java/im/vector/app/features/share/IncomingShareFragment.kt, vector/src/main/java/im/vector/app/features/share/IncomingShareViewModel.kt, vector/src/main/java/im/vector/app/features/start/StartAppAction.kt, vector/src/main/java/im/vector/app/features/start/StartAppAndroidService.kt, vector/src/main/java/im/vector/app/features/start/StartAppViewEvent.kt, vector/src/main/java/im/vector/app/features/start/StartAppViewModel.kt, vector/src/main/java/im/vector/app/features/start/StartAppViewState.kt, vector/src/main/res/layout/activity_main.xml, vector/src/main/res/values/strings.xml
This PR tries to move the Realm migration DB into background.
The first commit ensure there is always a migration to do and the migration will last 5 minutes. To be dropped of course.
|Before - migration in `VectorApplication.onCreate()`|After - migration in `MainActivity` view model|
|-|-|
|![DbMigrationInFg](https://user-images.githubusercontent.com/3940906/178817395-90a76b18-d0f9-4fce-a8fb-062b9e368bdd.gif)|![DbMigrationInBg](https://user-images.githubusercontent.com/3940906/178817199-bc2c64d2-e169-40a0-baf2-2e652cceb245.gif)|
New design with a wording (will iterate with @ganfra ):
Before we can have ANR if the migration takes time. After this should not happen anymore.
I create the PR to make this work public.
There are still some limitations:
=> Realm migration bg

vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
MainActivity is not able to display alert because the theme is not compliant. Anyway we should not display alert on this screen.
Reproduced locally on debug build and confirm this change fixes the crash.
No need for changelog since this does not affect previous released version.
=> Fix crash observed on nightly build

changelog.d/6609.misc, vector/src/main/java/im/vector/app/features/location/MapBoxMapExt.kt, vector/src/main/java/im/vector/app/features/location/live/map/LocationLiveMapViewFragment.kt, vector/src/main/res/layout/fragment_location_live_map_view.xml
When a user is selected on bottom sheet of maximized live location map view, we shouldn't preserve the current zoom level. Changing zoom level to a meaningful value will improve UX.
https://user-images.githubusercontent.com/1254401/179989271-83b390a8-2b7a-46c1-ad6e-9624855a5295.mp4
- Share a live location
- Tap on the live location message in the timeline
- On maximized map screen tap on user to focus
=> Live Location Sharing - Reset zoom level while focusing a user (PSG-624)

changelog.d/6616.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/widgets/model/WidgetType.kt, vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/core/utils/CheckWebViewPermissionsUseCase.kt, vector/src/main/java/im/vector/app/core/utils/PermissionsTools.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt, vector/src/main/java/im/vector/app/features/home/room/detail/StartCallActionsHandler.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetAction.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetActivity.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetArgsBuilder.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetFragment.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetViewModel.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetViewState.kt, vector/src/main/java/im/vector/app/features/widgets/webview/WebviewPermissionUtils.kt, vector/src/main/java/im/vector/app/features/widgets/webview/WidgetWebView.kt, vector/src/test/java/im/vector/app/core/utils/CheckWebViewPermissionsUseCaseTest.kt
We implement Element Call as a widget with some extra functionalities.
Since this is a call widget we need to make it run in the background, provide a picture-in-picture mode and also preserve the current native WebRTC call implementation for rooms which does not have an active Element Call widget.
This PR is a cherry-pick version of [PR #6464](https://github.com/vector-im/element-android/pull/6464) which additionally implements a Bluetooth connection with push-to-talk devices. Since it is an experimental PR with a hardcoded device name and service address without a good UX, we wanted to create this PR to be able to merge into develop.
https://user-images.githubusercontent.com/1254401/180235359-19dcf0c3-05a8-4202-8ce3-7359de96a630.mp4
- Request an invite (from me?) to the room which has …
=> Support element call widget (PSG-627)

changelog.d/6341.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/sync/SyncService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/DefaultSyncService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncRequestStateTracker.kt, vector/src/main/java/im/vector/app/AppStateHandler.kt, vector/src/main/java/im/vector/app/AutoRageShaker.kt, vector/src/main/java/im/vector/app/features/analytics/accountdata/AnalyticsAccountDataViewModel.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Replaced `LiveData` with `Flow` for sync state reporting.
`SyncRequestStateTracker` instance is reused in different threads, because of the `Scope` annotation. If `LiveData::postValue` is called fast enough, some events can get lost, because only the last one is dispatched. 
So in my case I could reproduce loosing of `InitialSyncRequestState.Idle` due to sending `IncrementalSyncIdle` from another thread.
Signed-off-by: Artjom König artkoenig@gmail.com
=> Fixed issues with reporting sync state events from different threads

dependencies.gradle
Probably due to some merge conflicts, and because [it was not added in the alphabetical order at the beginning](https://github.com/vector-im/element-android/commit/6fc278eb2b463388a95e11d86293d6ae118b4249), we end up with duplicated entries here. But actually this is not used, so I just remove them.
If CI is happy, can be merged.
=> Remove duplicated and unused dependencies.

dependencies.gradle, vector/build.gradle, vector/src/fdroid/java/im/vector/app/nightly/NightlyProxy.kt, vector/src/gplay/java/im/vector/app/nightly/NightlyProxy.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
Add in app new version alert on nightly build version of the app, following this recipe: https://firebase.google.com/docs/app-distribution/set-up-alerts?platform=android, step 1, step 2 and step 4.
Still not working on my device with my account.
I have got this error when sign in to my Google Account:
The step 4 suggest that the app have to be installed from Firebase to test the implementation. Let's merge this PR, wait for the next nightly build and get the app from Firebase to see if it's working?
=> Add in-app alert to let user know if a new version is available.

changelog.d/6625.misc, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/location/live/LocationLiveStatusView.kt
Navigating to expanded map view when tapping on the status bar which indicates a live is active.
Closes #6625 
- Go to a room
- Start a live location share
- Press on the top status bar
- Check it navigates to the expanded map view
- Go back to timeline
- Press the stop button on the top status bar
- Check the live is ended
=> [Location sharing] - OnTap on the top live status bar, display the expanded map view (PSG-614)

changelog.d/6634.bugfix, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetActivity.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetFragment.kt, vector/src/main/res/values/strings.xml, vector/src/main/res/xml/vector_settings_labs.xml
Signed-off-by: Johannes Marbach <johannesm@element.io>
This is a follow-up on https://github.com/vector-im/element-android/pull/6616 that puts the Element Call permission shortcuts behind a labs flag. Anyone can create a false widget of type `io.element.call` and silently acquire permissions so we don't want to enable this behavior by default.
Can be tested e.g. in #ecwidgettest:matrix.org
CC @onurays
=> Put EC permission shortcuts behind labs flag (PSG-630)

changelog.d/6466.bugfix, vector/src/androidTest/java/im/vector/app/CantVerifyTest.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/DeviceVerificationInfoBottomSheetController.kt, vector/src/main/java/im/vector/app/features/settings/devices/DevicesAction.kt, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewEvents.kt, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/VectorSettingsDevicesFragment.kt, vector/src/main/res/values/strings.xml
Fixes #6466
When there is no way to verify a new device, prompt and propose to reset verifications keys.
|Before|After|
|-|-|
|<img width="290" alt="image" src="https://user-images.githubusercontent.com/9841565/177367712-934e01ff-3e1a-47af-a887-844d2a807177.png">|<img width="418" alt="image" src="https://user-images.githubusercontent.com/9841565/177367420-98a44090-8331-4809-a218-2cee3089b44d.png">|
This can be performed from settings also
A click on the popup will open the 4S setup bottomsheet
- Step 1: Create an account then logout
- Step 2: Login this account again
=> Handle case when device cannot be verified

vector/src/main/java/im/vector/app/core/di/FragmentModule.kt, vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListAction.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomSection.kt
There is already `RoomListFragment` and some classes around it, which are dedicated to showing different list of rooms with multiple sections, but they all are tied together and have a hardcoded sections per use case. In EditLayout we'll need to provide a list which can be configured by user and this require different approach + this list will not have sections as collapsible list parts and also it needs to be put under Feature flag. As a result I've created a new implementation, but in this PR is more like copy-past dummy with excessive things taken away. I'll expand this implementation and probably even change it's design, while I'll complete tasks with sections, necessary for EditLayout and in the end I would like to align `RoomListFragment` and `HomeRoomListFragment` to avoid …
=> new room list implementation for EditLayout

changelog.d/6522.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/securestorage/SecretStoringUtils.kt, vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelperTests.kt, vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/crypto/KeyStoreCryptoTests.kt, vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeyRepositoryTests.kt, vector/src/androidTest/java/im/vector/app/features/pin/lockscreen/crypto/migrations/LegacyPinCodeMigratorTests.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/biometrics/BiometricHelper.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/KeyStoreCrypto.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeyRepository.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeysMigrator.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/LegacyPinCodeMigrator.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/SystemKeyV1Migrator.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/di/LockScreenModule.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/di/LockScreenQualifiers.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/pincode/PinCodeHelper.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/LockScreenTestMigratorTests.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigratorTests.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/SystemKeyV1MigratorTests.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/fragment/LockScreenViewModelTests.kt
See #6522 .
We want to add additional security measures to the biometric authentication of the lock screen feature: 
1. An extra check to make sure the `Cipher` used is unlocked after authentication.
2. Enabling a setting to only be able to use this `Cipher` while the device is unlocked.
- With your app in `develop` or any other branch, go to Settings -> Security -> Protect access, and create a PIN code and enable biometric authentication. This can be done on the emulator too, but you need to make sure you're on API >= 30).
- Build and launch this branch, make sure you can still use biometric authentication.
=> Improve lock screen implementation with extra security measures

changelog.d/6622.feature, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractFtueAuthFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthEmailEntryFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWaitForEmailFragment.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
Avoids marking the "Waiting for email verification" as a hard exit, which allows the user to go back and edit the entered email address.
- When restoring the session (eg killing the app whilst within the waiting for verification) the back action will force the user to start the flow again from scratch.
#6622 Allow editing email during the verification steps
| --- | --- | 
|![before-change-email](https://user-images.githubusercontent.com/1848238/181026288-31700142-e38f-4405-824e-d1ab3f5b6919.gif)|![after-change-email](https://user-images.githubusercontent.com/1848238/181017183-e6971302-c445-4f36-932b-c009b9a1e25a.gif)|
- With the FTUE flags enabled
- Start the account creation process on a homeserver with email verification (eg matrix.org)
- type an incorrect email and …
=> FTUE - Allow editing email during email verification 

changelog.d/5546.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimelineService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt
Revert #6404 as it breaks Thread and implementation is not working properly (timeline is not refreshed in live).
@Claire1817
=> Revert #6404

changelog.d/6663.bugfix, vector/src/main/java/im/vector/app/core/ui/views/TypingMessageDotsView.kt
Canceling the infinite animations when the view is destroyed.
Closes #6663 
Easier to enable LeakCanary to check everything is correct.
- Go to a room where there are threads
- Open a thread timeline
- Press back
- Open again the thread timeline
- Press back
- Check there is no slowness
- If leakcanary is enabled, check there is no leak detected which is related to ObjectAnimator 
=> Cancel infinite animations in TypingMessageDotsView

changelog.d/6665.bugfix, changelog.d/6666.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/query/SpaceFilter.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt, vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilder.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt
- Updates the `toActiveSpaceOrOrphanRooms` usages to avoid the nullsafe fallback, the extension already handles the null case for us (this is the fix!)
- Replaces the nullable `SpaceFilter` in favour of a dedicated `NoFilter` type, should help address the ambiguity of the different states 
Fixes #6665 
| --- | --- | 
|![before-show-rooms](https://user-images.githubusercontent.com/1848238/181473554-20be90d2-0cfa-40d3-8d57-afa0241c1346.gif)|![after-rooms-in-home](https://user-images.githubusercontent.com/1848238/181473565-bb15a375-33f2-4cd6-a929-fad4db06f208.gif)
- Have rooms across spaces
- Notice Home is always showing all rooms
- Notice the `Show all rooms in Home` preference has no effect
=> `Home` always showing all rooms

vector/src/main/java/im/vector/app/features/MainActivity.kt, vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt, vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
Closes #6672 
Fix tested OK on my side, using the two ways to have a shortcut.
Will double check what we can do for existing shortcuts on home screen, but I think there is nothing we can do except try to remove / disable them.
**EDIT** Ok, pinned shortcut can be updated, tested OK on my device.
No changelog since it's not released code.
- See #6672 
Also:
- create a shortcut with the previous version
- click on the shortcut: the app crash
- install the app with this PR
- the existing shortcuts are migrated
- clicking on the same shortcut open the app without crashing
=> Shortcuts must first start MainActivity to ensure the session is restored.

changelog.d/6642.misc, vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/features/location/LocationSharingFragment.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingServiceConnection.kt, vector/src/main/java/im/vector/app/features/location/live/map/LocationLiveMapViewActivity.kt, vector/src/main/java/im/vector/app/features/location/live/tracking/LiveLocationNotificationBuilder.kt, vector/src/main/java/im/vector/app/features/location/live/tracking/LocationSharingAndroidService.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
Modifying the notification of the foreground service so that it forwards to the live location map of the last room where a live has been started by the user.
Closes #6642 
- Start a live in a room
- Put the app in background
- Press the service notification
- Check the map associated to the room where the live has been started is displayed
- Press back
- Check the timeline of the room is displayed
- Press back
- Check the home is displayed
- Start another live in another room
- Press the service notification
- Check the map associated to the last room where the live has been started is displayed
=> [Location Share] Open maximized map on tapping on live sharing notification (PSG-616)

.github/workflows/gradle-wrapper-validation.yml
Should fix #6690. This workflow should run on every PR, and when pushing on `main` and on `develop` (just in case wrapper is updated outside of a PR, which should not happen). Note that the doc https://github.com/gradle/wrapper-validation-action should probably be udpated too.
See what will happen to this PR.
**EDIT** OK, only one check here:
=> Avoid running this workflow twice on PR. #6690

changelog.d/6706.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationMessageProcessor.kt
=> Fix cleartext leak in log

tools/danger/dangerfile.js
- Reads the `requested_reviewers` from the `github` object as per the [dsl reference](https://danger.systems/js/reference.html#GitHubPRDSL)
- Updates all `let`'s to `const` as the values are not mutated
To avoid danger incorrectly warning on PRs
N/A
Running locally against this PR (without a changelog or reviewers set) 
```
Please add a changelog. See instructions [here](https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog)
-
Please add a reviewer to your PR.
```
N/A
N/A
=> Fix danger reviewers PR comment

changelog.d/6687.bugfix, vector/src/main/java/im/vector/app/features/location/MapTilerMapView.kt
Convert the map symbol drawable to bitmap to be able to see text on it.
Closes #6687 
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/46314705/182378222-f2f9009c-d15b-44cb-a90e-bc0cd0be0a1e.png" width=300/>|<img src="https://user-images.githubusercontent.com/46314705/182378230-222597a3-633c-4fda-9e1c-351e94ec9ba3.png" width=300/>|
- Share you current location in a room with a user without picture
- Open the new message
- Check the shortname of the user is displayed on the map pin
=> [Location sharing] Invisible text on map symbol

changelog.d/6680.misc, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashCarouselFragment.kt
Clearing references on the `TabLayoutMediator` and `adapter` when `FtueAuthSplashCarouselFragment` is destroyed.
Closes #6680 
To check, you need to enable LeakCanary. When doing tests, ensure there is no leak detected and related to `FtueAuthSplashCarouselFragment`.
- Start the app from scratch
- Press "I already have an account" or "Create an account" button
=> [FTUE] Memory leak on FtueAuthSplashCarouselFragment

vector-config/src/main/res/values/config.xml
Otherwise the widgets end up with invalid URLs
- Step 1
- Step 2
- Step ...
=> Add scheme to element call domain

.github/workflows/build.yml, .github/workflows/nightly.yml, .github/workflows/post-pr.yml, .github/workflows/quality.yml, .github/workflows/tests.yml, docs/nightly_build.md
- Reduces the JVM memory allowance, we have multiple toolchains competing for memory which is causing the upper limit (currently 4g) to be reached however the VM doesn't have this much available, causing the compilation to crash.
- Makes use of the `GRADLE_OPTS` environmental var to avoid needing to pass the additional flags
- Re-enables parallel compilation, disables predexing and enforces a max worker count
We've been seeing the android lint task fail due to process crashes (out of memory) and the introduction of top level module exaggerated the issue https://github.com/vector-im/element-android/pull/6720
The fix is to limit the upper bound of the jvm during compilation to avoid over allocating available VM memory.
N/A
- Run the CI!
N/A
=> Fixing CI crashing during compilation/linting

changelog.d/6678.misc, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Clearing the listeners on `AudioMessagePlaybackTracker` when `TimelineFragment` is destroyed.
Closes #6678 
To check, you need to enable LeakCanary. When doing tests, check there is no leaks notified and related to `AudioMessagePlaybackTracker`.
- Go to a room timeline
- Press back
=> [Timeline] Memory leak in audio message playback tracker

changelog.d/6737.bugfix, vector/src/main/java/im/vector/app/core/extensions/TextInputLayout.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt, vector/src/main/res/layout/fragment_ftue_combined_login.xml, vector/src/main/res/layout/fragment_ftue_combined_register.xml
- Ensures we only execute _lost focus_ checks whilst the screen is still in view
- Adds missing view ids to the input field edit text views 
Fixes #6737 
When the username field loses focus we're doing a user name availability check, however this check was also being triggered when navigating away from the page (such as pressing EDIT or back) causing the next page to display the availability result.
Fixed by only checking for availability whilst the username field is visible.
| --- | --- |
- Select the username field within account creation
- Tap `EDIT`
- Notice an empty user id error
=> FTUE - Focus errors showing on wrong page

vector/build.gradle, vector/src/androidTest/java/im/vector/app/CantVerifyTest.kt, vector/src/androidTest/java/im/vector/app/ClearCurrentSessionRule.kt, vector/src/main/java/im/vector/app/features/analytics/store/AnalyticsStore.kt
Adds a test rule to reset an active session in order to force the app to go through the authentication flow
- Fixes the `CantVerifyTest` failing if the test is executed after a session has been cached. The test can sometimes be triggered with a cached `Session` which means the app is already logged in. 
No production changes
- Run the `CantVerifyTest` multiple times without clearing data between tests
=> Fixing flaky `CantVerifyTest`

changelog.d/6735.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeRegistrationWizard.kt
- Handles the exception throwing of the username availability check 
To avoid a crash when non ascii characters are used in the username during account creation
|Before|After|
|-|-|
|![before-non-ascii-account](https://user-images.githubusercontent.com/1848238/182831158-3469f5fc-5e1b-419d-b9d7-a58146d1faee.gif)|![after-ascii](https://user-images.githubusercontent.com/1848238/182831463-f060da44-5b5a-44dc-9332-a7719915a3e7.gif)|
- In the account creation screen
- Enter non ascii characters in the username field
=> Fixes crash when entering non ascii username during account creation

changelog.d/6769.bugfix, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/LockScreenKeysMigrator.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigrator.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/crypto/migrations/SystemKeyV1Migrator.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/LockScreenKeysMigratorTests.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/MissingSystemKeyMigratorTests.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/crypto/migrations/SystemKeyV1MigratorTests.kt
Fixes #6769 .
During lockscreen biometric key migrations, both `UserNotAuthenticatedException` and `KeyPermanentlyInvalidatedException` were caught, but there are many other possible exceptions that can be thrown. If any exceptions are thrown, we'll catch them, disable biometric authentication, then show pin code authentication.
- Install a version < 1.4.31 (1.4.27 maybe?).
- Make sure you have biometric authentication enabled on your device.
- Enable biometric auth in Settings > Security and Privacy > Protect access. You'll need to enable pin code auth, then biometric one.
- Close the app.
- Disable biometric authentication on your *device* (delete all fingerprints, disable face unlock, etc.).
- Upgrade to this version and launch the app.
If the app doesn't crash, everything is fine. …
=> Avoid crashes from unknown exceptions on lockscreen key migration.

tools/release/pushPlayStoreMetaData.sh
Marks the `gl` locale as ignored from the play store upload process as it's unsupported 
```
http_command.rb:236:in `check_status': \e[31m[!] Invalid request\e[0m (Google::Apis::ClientError)
The requested language is not currently supported: gl
```
To fix the `tools/release/pushPlayStoreMetaData.sh` release script
No UI changes
N/A
N/A
=> Disabling unsupported play store language

vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewModel.kt, vector/src/main/java/im/vector/app/features/pin/lockscreen/ui/LockScreenViewState.kt, vector/src/test/java/im/vector/app/features/pin/lockscreen/fragment/LockScreenViewModelTests.kt, vector/src/test/java/im/vector/app/test/Extensions.kt, vector/src/test/java/im/vector/app/test/FlowTestObserver.kt
A few new tests for lockscreen.
Improving coverage and making sure we won't break the feature with new changes in the future
- Run unit tests.
=> Improve tests for lockscreen

changelog.d/6746.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageBeaconLocationDataContent.kt, vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
Adding support for notification creation when receiving live location or poll start events.
Closes #6746 
This cannot really be tested right now since the default push rules on server side have not been deployed yet (need to validate some MSC first). The only notification we can have now is when starting a poll in an encrypted room.
On my side, I have tested it by adding the corresponding push rules on my test account.
In encrypted room: 
- Start a poll 
- Check you receive a notification on another device
- Start a live location share
- Check you don't receive any notification (note the unread notification counter is not correct due to the lack of push rules)
In non-encrypted room:
- Start a poll 
- Check you don't receive any notification (note the unread notification counter is at 0 …
=> [Notification] - Handle creation of notification for live location and poll start (PSG-41)

changelog.d/6808.misc, vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt, vector/src/main/java/im/vector/app/features/call/webrtc/ScreenCaptureServiceConnection.kt
Setting the callback to `null` in `ScreenCaptureServiceConnection` when `VectorCallActivity` is destroyed.
Closes #6808 
- Enable the developer mode
- Enable the memory leak analysis in the debug settings
- Start a call in a room
- End the call
- Check there is no leak detected by LeakCanary
=> [Call] Memory leak after a call

changelog.d/6799.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomGuestAccessContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomHistoryVisibility.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomHistoryVisibilityContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/create/RoomFeaturePreset.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBodyBuilder.kt
Improve some sdk stuff:
- Provide JSON keys inside enum fields as a `value` for `GuestAccess` and `RoomHistoryVisibility` (It is already the case for some existing enums) -> It limits the duplication of the keys by having them in a single place
- Replace manual mapping with the related `Content` models in `CreateRoomBodyBuilder` -> it removes some JSON keys duplication and adds clarity to the code
- Replace the return type of `RoomFeaturePreset.setupInitialStates` from a `List<Event>` to a `List<CreateRoomStateEvent>` to be consistent with `CreateRoomParams.initialStates`
Further developments related to #5525 
By creating rooms in order to trigger the modified code, adding breakpoints and checking that the code was correctly executed.
=> Reduce boilerplate with some minor sdk improvements

changelog.d/6806.wip, library/ui-styles/src/main/res/values/stylable_devices_list_header_view.xml, library/ui-styles/src/main/res/values/styles_devices_management.xml, vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/DevicesListHeaderView.kt, vector/src/main/res/layout/fragment_settings_devices.xml, vector/src/main/res/layout/view_devices_list_header.xml, vector/src/main/res/values/strings.xml
Adding a nex custom view for headers which will be used in sessions lists in the new layout.
See #6806 
- Enable the new device management feature flag
- Go to "Security & Privacy" settings
- Press the "Show all sessions (V2, WIP)" entry
- Check the header for "Other sessions" section is visible
- Press "Learn more"
- Check there is a toast displayed
=> [Devices Management] Header view for sessions lists in new layout (PSG-668)

changelog.d/6645.misc, vector/src/main/java/im/vector/app/features/form/FormEditTextItem.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomController.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
#6645 
- Step 1
- Step 2
- Step ...
- [] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
=> Add inputType for room name creation and settings

changelog.d/6795.wip, vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt, vector/src/main/res/layout/fragment_new_home_detail.xml
Changes the space name shown in the toolbar as the space is switched
Closes https://github.com/vector-im/element-android/issues/6752
- Make sure New App Layout feature flag is enabled
- Switch spaces and see that the space title in the toolbar is also updated
=> New App Layout: Space name reflected in toolbar

.github/workflows/danger.yml, .github/workflows/quality.yml, docs/danger.md
Copied from the doc in this PR:
> PRs from forks do not always have access to the secret `secrets.DANGER_GITHUB_API_TOKEN`, so `secrets.GITHUB_TOKEN` is also provided to the job environment. If `secrets.DANGER_GITHUB_API_TOKEN` is available, it will be used, so user `ElementBot` will comment the PR. Else `secrets.GITHUB_TOKEN` will be used, and bot `github-actions` will comment the PR.
Doing some test, it seems fine for internal and external PR.
Let see with this solution how it will behave.
No changelog required, but happy to see that @ElementBot is commenting correctly this PR!
=> Try to fix Danger job

build.gradle
Reverts vector-im/element-android#6838
Develop is broken.
Dependabot will create again the PR and we will fix any issue there.
=> Revert "Bump stem-plugin from 2.1.1 to 2.2.0"

vector/src/androidTest/java/im/vector/app/features/reactions/data/EmojiDataSourceTest.kt
Fix the unit test which was broken since the emoji filter on "france" does not return the expected result anymore. Replaced the filter with "flag-france" which returns a single result and should not change in the long term.
FIx the broken CI on develop
N/A
- Run `EmojiDataSourceTest.searchTestOneResult()`
=> Fix broken unit test on emoji search

changelog.d/5525.wip, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt, vector/src/main/java/im/vector/app/features/createdirect/DirectRoomHelper.kt
When we select the option "Direct Message" on a room member details screen, the start DM flow is now triggered.
This means that the DM room will not be created by selecting the option but only after sending the first message in the local room.
This is almost the same behaviour as creating a DM from the fab button on the home screen, without having to select the users to invite. The local room is directly shown with the related room member.
https://github.com/vector-im/element-android/issues/5525#issuecomment-1158963336
1. Activate the start DM feature flag from the debug menu
2. Open a room with several users
3. Select a user to open the member profile screen
4. Select "Direct Message"
=> Start DM on first message when selecting "direct message" from the room member details screen

changelog.d/6827.bugfix, vector/src/main/java/im/vector/app/features/login/AbstractSSOLoginFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginMode.kt, vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt, vector/src/main/java/im/vector/app/features/login/SocialLoginButtonsView.kt, vector/src/main/java/im/vector/app/features/login/SsoState.kt, vector/src/main/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCase.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractSSOFtueAuthFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSignUpSignInSelectionFragment.kt, vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutFragment.kt, vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt, vector/src/test/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCaseTest.kt
- Treats null `identity_providers` as a valid  SSO case
- Models the `fallback` through the `ViewModel/Auth` chain to make the behaviour more obvious (and adds tests to the creation)
Fixes #6827 
|Before|After|
|-|-|
|![Screenshot_20220815_093113](https://user-images.githubusercontent.com/1848238/184646210-61f6ecaf-da28-477e-98e1-134e2999f524.png)|![Screenshot_20220815_125843](https://user-images.githubusercontent.com/1848238/184646225-56021d66-74e1-4ff8-9a1a-331cc234fd4c.png)|
- Select a homeserver which provides SSO via the fallback mechanism (eg without using `identity_providers`) 
- Attempt to register/sign in
=> Allow empty SSO `identity_providers`

changelog.d/6884.bugfix, changelog.d/6884.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/debug/DebugService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/sync/SyncService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmLiveEntityObserver.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/tools/RealmDebugTools.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/debug/DefaultDebugService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/MatrixModule.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorThread.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/DefaultSyncService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/BackgroundDetectionObserver.kt, vector/src/main/java/im/vector/app/VectorApplication.kt, vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt, vector/src/main/java/im/vector/app/core/extensions/Session.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineAsyncHelper.kt, vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt, vector/src/main/java/im/vector/app/features/rageshake/ProcessInfo.kt
- Fix #6782. This is this commit: 0b1b228. - **I am still investigating, because sometimes, the SyncThread stays in the  PAUSE state, which is not correct.**
- Improve SDK Debug API
- Log Thread before rageshake are sent.
- Rename thread names
- Fix #6782
Regression from #6710, release in Element and SDK v1.4.31 (2022-08-01)
NA
- See the step to repro [here](https://github.com/vector-im/element-android/issues/6782#issuecomment-1219602578).
=> Ensure sync thread is started

changelog.d/6891.bugfix, vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt
- We were saving the default distributor before asking the user, which meant when the user selected the same option it was skipped from being registered
- Only _unregisters_ during the force flow, otherwise we'll crash due to no app being registered
Fixes #6891 relates to #6782 
No UI changes
- Have a unified push distributor installed eg ntfy
- With a fresh install, login 
- Select `Google services` when prompted
- Exit the app, notice no push messages are received  
=> Missing push notifications on login

changelog.d/6864.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt, vector/src/main/java/im/vector/app/features/login/HomeServerConnectionConfigFactory.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractFtueAuthFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerConnectionConfigFactory.kt, vector/src/test/java/im/vector/app/test/fakes/FakeStartAuthenticationFlowUseCase.kt, vector/src/test/java/im/vector/app/test/fixtures/FailureFixture.kt
- Includes the `EditHomeserver` flow when handling certificate trusting
- Removes the mutable `HomeserverConfig` state in favour of recreating when needed (when trusting the certificate) which massively simplifies the unit testing setup
- Supplies a `retryAction` when creating the `CertificateError`, avoids needing _non persisted_ mutable state in the view model and reduces unit test setup 
Fixes #6864  - Certificate trusting during the edit homeserver flow doing nothing
|Before|After|
|-|-|
|![before-trust-server-ca](https://user-images.githubusercontent.com/1848238/185374004-948cdce6-83b3-4f1d-9269-904506c6bec2.gif)|![after-allow-trusting-ca-during-edits](https://user-images.githubusercontent.com/1848238/185374030-57a7e162-8d48-41cb-93d9-058e42c62c52.gif)|
- Set your device time to the …
=> FTUE - Fix trusting certificates during edit server flow

changelog.d/6855.bugfix, changelog.d/6860.bugfix, changelog.d/6861.bugfix, vector/src/main/java/im/vector/app/core/extensions/Throwable.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCaptchaFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/res/layout/fragment_ftue_login_captcha.xml, vector/src/main/res/layout/view_stub_webview.xml, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
- Removes the ability to continue the account creation process after the app has been destroyed. This was not taking into account the missing data from the previous onboarding steps, causing the `OnboardingViewState` to be in an invalid empty state. Fixes #6860
- Replaces the captcha `WebView` xml declaration with a `ViewStub` which try/catches the inflation. Allows us to catch the missing webview crash and provide an error dialog with information about the error. Fixes #6855 
- Allows the initial login and registration fragment transactions to have _state loss_, as these fragments are the entry points the UX damage is minimal and will simply require the user pressing the `already have an account` or `use case selection` buttons again. Fixes #6861
- #6860 Crash when attempting to continue …
=> FTUE - Crash fixes

changelog.d/6859.wip, vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
Adds a click action to the toolbar in the new app layout to open space settings
Closes https://github.com/vector-im/element-android/issues/6859
This functionality is present in the old app layout but wasn't yet present in the new layout.
We need to add the click listener on both the collapsing toolbar and the toolbar to have an effective click area of the whole toolbar. Adding a click listener on AppBarLayout doesn't work.
=> Space Switching: Adds Toolbar Click To Open Space Settings

changelog.d/6718.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt
- Checks for network errors on the initial homeserver selection (starting the login or account creation step) and forwards the user to Edit server screen instead to allow them to choose a different homeserver
- Removes the dedicated deeplink failure dialog in favour of reusing the edit server flow 
Fixes #6718 - Allowing the homeserver server to be changed on failure when starting the onboarding (matches iOS) 
|Before|After|
|-|-|
|![before-edit-server-on-error](https://user-images.githubusercontent.com/1848238/185615058-952351fb-c5d8-4f26-a151-949785fc1d09.gif)|![edit-server-on-error](https://user-images.githubusercontent.com/1848238/185615076-94107f41-110b-4e87-ace3-edd97b9f7d57.gif)|
- Block matrix.org or within the code change the default matrix.org address to an invalid url
- Attempt …
=> FTUE - Allow changing server on onboarding start error

vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt
At this point, we do not want the sync to start, the DB is already deleted.
Do not start the SyncThread if the user want to sign out.
Related to #6884 
Fix crash when signing out.
- Step 1
- Step 2
- Step ...
=> Fix crash when signing out.

changelog.d/6750.wip, vector/src/main/java/im/vector/app/features/spaces/SpaceListFragment.kt
sometimes space switching dialog appears with wrong height measured
closes #6750
- navigate to home screen
- show space switcher dialog via FAB
=> fixed space switching dialog measured with wrong height sometimes

changelog.d/6926.misc, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedServerSelectionFragment.kt
When the server selection fragment is shown and after the previously entered or default server address is set, the input for the server gets selected and requests focus. At the same time the keyboard is shown so you can immediately type away when the fragment is shown. That should remove the need for two additional clicks, one to focus the input field and one to clear it.
#6926
|Before|After|Light|
|-|-|-|
|![Screenshot_20220824-145117](https://user-images.githubusercontent.com/39308834/186422993-a709414b-60a9-435e-8f90-cda22138d3dd.png)|![Screenshot_20220824-145338](https://user-images.githubusercontent.com/39308834/186423868-5fc4f900-6956-43aa-ba57-4edcb45829ea.png)|![Screenshot_20220824-145421](https://user-images.githubusercontent.com/39308834/186424003-f43192de-f9db-41a0-aa94-d8790f23 …
=> FTUE: Make entering a custom Homeserver address faster by focusing the input

changelog.d/6844.bugfix, vector/src/main/java/im/vector/app/features/command/CommandParser.kt, vector/src/test/java/im/vector/app/features/command/CommandParserTest.kt
Fixes the join and add to space commands not working due to expecting only 1 message part, the command itself. This was incorrect as we need to pass the id/alias to the command
- Updates the unit tests 
Fixes #6844 
|Before|After|
|-|-|
|![before-add-to-space](https://user-images.githubusercontent.com/1848238/186696412-4bf4c122-383d-4965-b501-e929cb35be5f.png)|![after-add-to-space](https://user-images.githubusercontent.com/1848238/186696628-30c042b4-d424-4981-8396-5cbc34b4ba99.gif)|
- In a room, use the `/addToSpace ${space id}` command
- Notice an error popup
=> Fixing /joinSpace and /addToSpace commands

changelog.d/6947.wip, vector/src/main/res/layout/item_invites_count.xml
With recents carousel enabled, the Invites text button looks very close to the carousel
closes #6947
=> fixed invites count badge bottom margin on a home screen

changelog.d/6967.bugfix, vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
This PR fixes some crashes, this commit message for the details.
Less crashes.
- Step 1
- Step 2
- Step ...
=> Fix crashes

changelog.d/6978.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/error/RoomNotFound.kt, vector/src/main/res/layout/fragment_timeline.xml, vector/src/main/res/values/strings.xml
Fix a crash when user opens a Timeline of a unknown room. This PR also contains some code cleanup, can be reviewed commit per commit if necessary.
This PR does not fix the root cause, which is quite unclear for now. This can be related to thread / space / etc. But it fixes the crash, and display a full screen error to the user.
If we got rageshake with the screen content in developer mode, we may have more info on the room which is tried to be open.
Note: I have seen #6543, but I think this is compatible with this change. I would prefer to first merge this PR, and then handle #6543.
Less crash.
fixes #5611 
|Before|After|
|-|-|
|**crash**|![RoomNotFound](https://user-images.githubusercontent.com/3940906/187687634-ab0909f0-551c-4afa-94ca-779770e40c1e.gif)|
In developer mode, more info will …
=> Fix crash when opening an unknown room

changelog.d/6979.bugfix, vector/src/main/java/im/vector/app/features/settings/VectorSettingsPinFragment.kt
Made `VectorSettingsPinFragment.biometricHelper` lazy so it's not instantiated before `biometricHelperFactory` is injected.
See #6979.
- Go to Settings > Security & Privacy > Protect access.
=> Fix crash on PIN code settings screen

changelog.d/6982.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageImageVideoItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/style/TimelineMessageLayoutFactory.kt, vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
It removes the play button on animated stickers and increase the stickers size.
* ATM, auto-played animated stickers are indeed auto-played but the play button is shown above it
* Stickers are very small, the same size than emojis sent alone
|Before|After|
|-|-|
|![screen2](https://user-images.githubusercontent.com/31284753/187788604-93842c2a-1c80-4ff2-8761-288fcc63fec1.gif)|![screen1](https://user-images.githubusercontent.com/31284753/187788662-070e5060-58fa-4693-b28c-127f9e4f4c03.gif)|
|![Screenshot_20220831-230338_Element dbg](https://user-images.githubusercontent.com/31284753/187786485-21b5c9fe-4c2e-4ef4-a59f-8e88df29d0fb.png)|![Screenshot_20220831-230920_Element dbg](https://user-images.githubusercontent.com/31284753/187786140-ea99b32b-3467-49d5-8ec5-ed4cf3265050.png)|
For …
=> Fix autoplayed animated sticker

changelog.d/6969.bugfix, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthEmailEntryFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt, vector/src/main/res/layout/fragment_ftue_email_input.xml
- Takes into account the mandatory status of the email registration step and sends a "Dummy" event when it's empty, as per the previous legacy flow
Fixes #6969 by allowing non mandatory emails to submit empty emails 
|Before|After| Legacy |
|-|-|-|
|![before-optional-email](https://user-images.githubusercontent.com/1848238/187732065-30759289-4127-4bd2-a4c0-d8e2b9b630e6.gif)|![after-optional-email](https://user-images.githubusercontent.com/1848238/187732074-6a6759cd-371f-47e1-8bb3-970b2f5c4141.gif)|![legacy-optional-email](https://user-images.githubusercontent.com/1848238/187732097-78fc3ddf-85a2-496a-8b2b-0732b81ec393.gif)|
- With a homeserver with optional email 
```
account_threepid_delegates:
email: https://matrix.org
```
- Start the account creation process
- Attempt to skip the email …
=> Allowing optional email registration 

changelog.d/6989.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Modified `AudioMessageHelper` to catch possible `RuntimeException` caused by race conditions while retrieving the audio file.
See #6989.
This is difficult to reproduce, to be honest.
- On a room/DM, tap on the record voice message icon for 1-2s.
- Repeatedly tap on it again.
With some luck, you'll trigger this race condition.
=> Catch race condition while recording voice audio

vector/src/main/res/layout/fragment_new_home_detail.xml
Fixes XML positioning of sync state in new layout
Closes https://github.com/vector-im/element-android/issues/7011
Enable airplane mode or lose connectivity while in the home screen. You should see an indicator at the top of the screen
=> New Layout - Fixes sync state not being visible

changelog.d/7010.feature, vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt, vector/src/main/java/im/vector/app/features/voice/VoiceRecorderProvider.kt
Try to detect if the OS has support for the Opus encoder, if it doesn't, use the bundled libopus one.
See #7010 .
Testing this is probably impossible unless you're one of the few affected users. You could force the check to return true and verify that `VoiceRecorderL` is used instead, but that's not really helpful.
=> Use libopus encoder for devices that lack the official codec

changelog.d/7016.wip, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/spaces/NewSpaceSummaryItem.kt, vector/src/main/java/im/vector/app/features/spaces/NewSubSpaceSummaryItem.kt, vector/src/main/res/layout/fragment_new_home_detail.xml, vector/src/main/res/layout/item_recent_room.xml
Fixes errors in the talkback accessibility of new layout
Closes https://github.com/vector-im/element-android/issues/6756
See commit messages for specific changes
N/A
Enable talkback and navigate around the new layout. See that everything is sensible
=> New Layout Accessibility Fixes

vector/src/main/java/im/vector/app/features/home/room/list/home/recent/RecentRoomCarouselController.kt, vector/src/main/res/layout/item_invites_count.xml, vector/src/main/res/layout/item_recent_room.xml
Fixes recents background color not matching app bar
Closes https://github.com/vector-im/element-android/issues/6817
| Light | Dark | Black |
|-|-|-|
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/20701752/188490781-916338ba-3fef-4e3e-b6ef-09d2c78a9d79.png"> | <img width="200" alt="image" src="https://user-images.githubusercontent.com/20701752/188490694-7652a283-8eea-49d2-86c0-b01b059f9144.png"> | <img width="200" alt="image" src="https://user-images.githubusercontent.com/20701752/188490913-e79aec0b-d0b3-47c8-ae3d-d87b23c6f73e.png"> |
- Go to home with recents enabled. See that background is consistent with toolbar and divider under INVITES is visible on all themes
=> New Layout - Fixes recents background color not matching app bar

.github/workflows/triage-labelled.yml
The threads board has been closed and is now replaced by the Delight board
- Step 1
- Step 2
- Step ...
Signed-off-by: Germain Souquet [germains@element.io](mailto:germains@element.io)
=> Remove threads board automation

changelog.d/6646.misc, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt, vector/src/main/res/xml/vector_settings_preferences.xml
some app settings became obsolete with new app layout, we should not display them when flag is enabled
closes #6646
=> obsolete settings are hidden when app layout flag is enabled

vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt
favourites and dms filter tabs should not be shown if there is no content for them for selected space
closes #6770
=> hide favourites and dms filters for a selected space, if they are empty

vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderProviderTests.kt, vector/src/main/java/im/vector/app/features/voice/VoiceRecorderProvider.kt
=> Fix voice recording tests

vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsFragment.kt, vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewActions.kt, vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewModel.kt, vector/src/debug/java/im/vector/app/features/debug/settings/DebugPrivateSettingsViewState.kt, vector/src/debug/res/layout/fragment_debug_private_settings.xml, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesActivity.kt
Add some debug tools about ReleaseNotesActivity.
- reset the show status
- display this Activity
Also moving `releaseNotesPreferencesStore.setAppLayoutOnboardingShown(true)` to the `ReleaseNotesActivity.onResume()`, which make more sense to me.
Help developer who work on this feature.
- Step 1
- Step 2
- Step ...
=> Debug release note

changelog.d/7040.wip, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/spaces/NewSpaceListHeaderItem.kt, vector/src/main/java/im/vector/app/features/spaces/NewSpaceSummaryController.kt, vector/src/main/res/layout/item_new_space_list_header.xml
Adds the "CHANGE SPACE" header to the space list that got lost in a recent pr
Part 1/2 of work for https://github.com/vector-im/element-android/issues/7027
Open the space list. See CHANGE SPACE header
=> New Layout - Adds missing space list header

vector/src/main/java/im/vector/app/features/home/room/list/home/recent/RecentRoomCarouselController.kt, vector/src/main/res/layout/item_recent_room.xml
Fixes padding of recents item selectable background
Closes https://github.com/vector-im/element-android/issues/7023
With recents enabled press or hold on a recent item and see that the selection background doesn't look too thin
=> New Layout - Fixes padding of recents item selectable background

vector-app/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/NewRoomRobot.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/RoomListRobot.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceCreateRobot.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceRobot.kt, vector/src/main/res/layout/fragment_space_list.xml
updates all screens ui test for new app layout
closes #7019
=> fixed allscreens sanity test for enabled app layout flag

changelog.d/6529.feature, vector/src/main/java/im/vector/app/features/autocomplete/member/AutocompleteMemberPresenter.kt
Closes #6529
Signed-off-by: Prat T <pt2121@users.noreply.github.com>
Addressing #6529 - suggest @room when a user typed in comparable keywords in the compose view.
following the web client.
- Log in
- Navigate to any room that you have a permission to notify the whole room by using `@room`
- Type in any `@channel`, `@everyone`, or `@here`
- See a suggestion for `@room`
- N/A
=> Suggest @room when @channel, @everyone, or @here is typed in composer

changelog.d/6727.doc, docs/unifiedpush.md
After https://github.com/vector-im/element-android/pull/6228 was merged, an enterprise chimed in with worry that they'd need to set up an FCM Rewrite Proxy in order to continue using FCM, as is [documented here](https://unifiedpush.org/developers/embedded_fcm/#fcm-rewrite-proxy).
After discussing with the UnifiedPush developers however, it appears that Sygnal replaces the need for this in the case of Element Android.
This change adds a bit to the documentation to clarify this.
=> Clarify that setting up a FCM Rewrite Proxy is not necessary for use of the UnifiedPush FCM distributor.

vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
Ensure the state is up to date, when we will request it later with withState{}
Ensure the state is up to date, else at this point: https://github.com/vector-im/element-android/blob/62e8beadf8c0ece8e56e21b86d9e96c0ec68d3b2/vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt#L498 the state is not up to date, and `it.selectedAuthenticationState.description` is null. So at this point https://github.com/vector-im/element-android/blob/16fad63e49eb408a4ccf066341e5b9cd5745fc66/vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt#L123 `state.authenticationDescription` is null and we display ReleaseNotesActivity, if never displayed before.
The fix is maybe not the best thing to do, [I already had concern about …
=> Fix ReleaseNotesActivity displayed after login.

.github/workflows/tests.yml, changelog.d/7057.misc
Adding a condition on the content of sonar tokens to run the sonarqube task only when they are not empty.
Closes #7057 
- Check this PR is running the sonarqube job
- Need to merge and wait for a new dependabot PR to check the result
=> CI: only run sonarqube task when token is known

changelog.d/5424.bugfix, vector/src/main/res/layout/fragment_user_code_show.xml
When `showUserCodeCardNameText` is gone, `showUserCodeCardUserIdText` top constraint is missing. Updated the top margin when the referenced view is gone.
54dp is from adding up both views margin tops (50dp + 4dp).
Addressing #5424
I tested this from the old UI flow and followed the steps in #5424
1. Enable the old flow
2. Open the hamburger menu on the top left
3. Tap the QR code icon
- OS version(s): Android 12 and also API 21
=> Fix add by QR code layout (#5424)

changelog.d/7102.bugfix, vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/NewChatBottomSheet.kt
Fixes Crash On Double Click Of Space FABs
Fixes https://github.com/vector-im/element-android/issues/7087
N/A
Double quick really quickly on the space list or new chat FABs in the new layout. These would have previously crashed the app.
=> Fixes Crash On Double Click Of Space FABs

changelog.d/7122.bugfix, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt
Context:
given new App Layout is enabled when user at home screen and leaves room via long-press context menu
Expected:
then prompt dialog should be shown and when user press "leave" button in this dialog then room is left.
Actual:
then dialog is shown but room is left immediately
closes #7122
=> room leaving prompt dialog now waits user to confirm 

changelog.d/6776.bugfix, vector/src/main/java/im/vector/app/features/home/room/list/home/header/HomeRoomsHeadersController.kt
when item is added or moved to the first position of recents carousel, it needs to be scrolled to that item. Currently it keeps position instead
closes #6776
=> scroll recents carouse to start when item added/moved to start

changelog.d/7121.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/query/QueryStringValue.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/localecho/RoomLocalEcho.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/query/QueryStringValueProcessor.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewState.kt
Fix a glitch when we go back to the room list from the DM creation screen
close #7121 
- Start a DM creation with the start DM feature flag enabled
- Go back to the room list (after creating the DM, cancelling the flow or relaunching the app)
- The local room is not shown anymore in the room list
=> Start DM - Fix glitch in the room list

changelog.d/7140.misc, dependencies_groups.gradle, library/jsonviewer/build.gradle, vector/build.gradle
- Excludes usages of the support annotation library, these are compile time hints and safe to remove.
- Removes unused `progressPieIndicator` dependency
- Excludes the appcompat library from jitsi's `android-scalablevideoview`, the library is pre-jetified but includes a redundant legacy support library transitive dependency  
The time has come to avoid using the Jetifier (the process of converting libraries from the legacy support library to androidx). The `Paparazzi` integration is blocked due to the plugin requiring the jetifier to be disabled for the base android libraries which causes the unit tests with android imports to fail. 
There is one more library to update `im.dlg:android-dialer:1.2.5` which will need to be manually included as the upstream project no longer exists, although …
=> Excluding legacy support library annotation usages

changelog.d/7132.bugfix, vector/src/main/java/im/vector/app/features/home/room/list/home/NewChatBottomSheet.kt
Dismisses new chat dialog when its actions are clicked
Closes https://github.com/vector-im/element-android/issues/6950
- With new layout enabled, click the new chat FAB
- Select any of its options
- See dialog is dismissed when you go back
=> Adds dismissal to new chat bottom sheet actions

changelog.d/7157.misc, library/ui-strings/build.gradle
- Forcing the stem string template generator tasks to be cachable, without this the templates are regenerated causing the `vector` module to recompile its sources (our slowest task!)
The build cache was enabled by default with #6788 but the `vector` module was getting constant cache misses when the `library/ui-strings` executed it's generator tasks 
N/A
Compile the project twice (on a branch other than develop)
```
./gradlew clean assembleGplayDebug // 3 minutes
./gradlew clean assembleGplayDebug // 18 seconds
```
N/A
=> Fix build cache misses

changelog.d/7130.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/SessionExtensions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/user/UserService.kt, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheet.kt, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/verification/cancel/VerificationCancelController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodFragment.kt, vector/src/main/java/im/vector/app/features/crypto/verification/emoji/VerificationEmojiCodeController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/emoji/VerificationEmojiCodeFragment.kt, vector/src/main/java/im/vector/app/features/crypto/verification/emoji/VerificationEmojiCodeViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/verification/qrconfirmation/VerificationQrScannedByOtherController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/request/VerificationRequestController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/request/VerificationRequestFragment.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/main/java/im/vector/app/features/popup/VerificationVectorAlert.kt, vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt
When the User with `otherUserId` was not known by the SDK, it was not possible to verify them.
First commit https://github.com/vector-im/element-android/pull/7130/commits/6d2a9ec9d5535b04ec5e9bcafc20da0e27e84c79 is the first part of the fix. `otherUserId` was null because retrieved from a null `MatrixItem`.
Second commit https://github.com/vector-im/element-android/pull/7130/commits/92d73912323f7b6ce8f4fff0c22941cf44ce2590 ensure that the `MatrixItem` cannot be null.
The 2nd commit should be sufficient to fix the issue, but the first commit make thing clearer IMHO.
Be able to Verify every users.
|Before|After|
|-|-|
|<img width="188" alt="image" src="https://user-images.githubusercontent.com/3940906/190234065-84d0e82b-3cd4-4953-9801-3b7fbebf7000.png"><img width="191" alt="image" …
=> Fix empty verification bottom sheet

vector-app/build.gradle
We do not use `android-embedded_fcm_distributor` anymore (since #7068). The code was compiling because `android-embedded_fcm_distributor` has a dependency on `firebase-messaging`.
No need for a changelog, since the code is not released.
=> Fix regression on our dependency, due to merge of #6788.

changelog.d/6970.wip, matrix-sdk-android-flow/src/main/java/org/matrix/android/sdk/flow/FlowRoom.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/Room.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/LocalRoomCreationState.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/LocalRoomSummary.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/LocalRoomSummaryMapper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo037.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/LocalRoomSummaryEntity.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoom.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomFromLocalRoomTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/create/DefaultCreateRoomFromLocalRoomTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeMonarchy.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeRoomSummaryDataSource.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
While creating the DM (ie. after sending the first message), a loading wheel is now displayed until switching to the created room.
In case of failure, the loading wheel is hidden to unblock the UI.
close #6970 
- Create a DM on first message
- Verify that a loading wheel is shown during the process creation
=> Deferred DM - Add a loading wheel while creating the DM

changelog.d/7166.misc, vector-app/src/androidTest/java/im/vector/app/VerifySessionInteractiveTest.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt, vector-config/src/main/res/values/config-settings.xml
Enables New App Layout in Labs (set default to true)
Closes https://github.com/vector-im/element-android/issues/7165
Test this branch from having the labs flag disabled or clear your data and start the app from a fresh install. See that new app layout is enabled by default
=> Enables New App Layout in Labs

vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/res/menu/menu_new_home.xml
before new app layout we had "add by QR code" image button inside the drawer. Since we don't have drawer in new layour, we need to put corresponding option to a home screen's menu (three dots)
closes #7176
=> add qr code option to home screen menu

vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/release/ReleaseNotesPreferencesStore.kt
release notes screen is not shown shown on update to a version with app layout labs flag enabled by default
closes #7174
=> Show release experience screen on app update

changelog.d/7153.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadReceiptEntityQueries.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/delete/DeleteLocalRoomTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/accountdata/UpdateBreadcrumbsTask.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListAction.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewState.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListAction.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt
This PR adds the deletion of the local rooms from the database when the room list is shown within the new AppLayout feature enabled.
Close #7153
- Start creating a DM with the start DM feature flag and the new App Layout enabled
- Activate the recent rooms display from the AppLayout configuration
- Write some text without sending it
- Abort the DM creation and go back to the home list
- Verify that the local rooms does not appear in the recent rooms
- Start creating again a DM with the same person
- Verify that the local room has not been retrieved (the draft is not persisted) 
We can also observe logs in the console about the deletion of the local rooms when the home room list is shown again.
=> Deferred DMs - Handle the local rooms within the new AppLayout

changelog.d/7186.bugfix, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeFilteredRoomsController.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt
We had a bug where if you join or leave a room from an activity/fragment other than room list, the list would often not update and would sometimes also crash. This fixes that by converting the room paged list livedata instead of passing livedata in a mavericks state update and observing it there
Fixes https://github.com/vector-im/element-android/issues/7152
- Open room list
- Go into room
- Leave room from room settings
- Go back to list
- See list is updated
Try the above scenario but also for joining rooms
=> Fixes Room List not getting updated when fragment is not in focus

changelog.d/7180.feature, library/ui-strings/src/main/res/values/strings.xml, vector-app/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt, vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt, vector-config/src/main/res/values/config-settings.xml, vector/src/main/java/im/vector/app/features/VectorFeatures.kt, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt, vector/src/main/java/im/vector/app/features/createdirect/DirectRoomHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/xml/vector_settings_labs.xml
Add the deferred DMs feature in the labs settings, enabled by default
Release #5525
1. Play with the labs setting (default / disabled / enabled)
2. Create a DM
=> Deferred DMs - Add and enable the feature by default in the labs settings

changelog.d/7114.wip, vector/src/main/java/im/vector/app/features/settings/devices/VectorSettingsDevicesFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesAction.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesViewEvent.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/IsCurrentSessionUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewAction.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewEvent.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/CheckIfCurrentSessionCanBeVerifiedUseCase.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/DevicesViewModelTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/IsCurrentSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModelTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/verification/CheckIfCurrentSessionCanBeVerifiedUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSharedSecretStorageService.kt
Start the verification process when pressing the "Verify" button only for the current Session.
Bonus: Fix missing sending of verification event to other verified sessions in the devices list V1.
Closes #7114 
No UI has been changed.
- Enable the new device management feature flag
- Sign in on a new device
- Go to Settings -> Security & Privacy -> Show all sessions (V2, WIP)
- Check the current session is displayed as not verified
- Press the "Verify" button
- Check another verified session received the request
- Cancel it
- Go to the session overview screen by pressing the current Session card
- Press the "Verify" button
- Check another verified session received the request
- Do the verification process
- Check the current session is shown as verified in the overview screen
- Press back
- …
=> [Device management] Verify current session (PSG-722)

changelog.d/7143.wip, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/GetCurrentSessionCrossSigningInfoUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesViewState.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoViewState.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/GetDeviceFullInfoUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewEvent.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewState.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/CurrentSessionCrossSigningInfo.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetCurrentSessionCrossSigningInfoUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForCurrentDeviceUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForOtherDeviceUseCase.kt, vector/src/test/java/im/vector/app/features/settings/devices/GetCurrentSessionCrossSigningInfoUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/DevicesViewModelTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/IsCurrentSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/GetDeviceFullInfoUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModelTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/verification/GetCurrentSessionCrossSigningInfoUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForCurrentDeviceUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForOtherDeviceUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt
Handling click on the "Verify" button in the session overview screen for other session than the current one.
Closes #7143 
No UI changed.
- Enable the new device management feature flag
- Go to Settings -> Security & Privacy -> Show All Sessions (V2, WIP)
- Find another session which is not verified
- Go to the session overview screen
- Check the "Verify" button is only visible when the current signed in session is verified
- Press the "Verify" button
- Check the verification request is received in the other session
=> [Device management] Verify another session (PSG-722)

changelog.d/7198.sdk, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/SyncConfig.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt, vector-app/src/androidTest/java/im/vector/app/core/utils/TestMatrixHelper.kt
Allows the sync timeout to be configured via the `MatrixConfiguration`
Our instrumentation tests can use a shorter timeout (5 seconds instead of 30 seconds) 
Before: **23m 43s**
After: **16m 39s**
**30% reduction** in runtime, saving around 7 minutes~
|Before|After|
|-|-|
|![2022-09-21T15:28:49,352822323+01:00](https://user-images.githubusercontent.com/1848238/191531870-1040160a-642a-4401-b6b5-2d143cd31d75.png)|![2022-09-21T15:03:35,811981115+01:00](https://user-images.githubusercontent.com/1848238/191526056-b577e5a2-287a-4ff9-934a-9c4615be863d.png)|
Run the `./gradlew matrix-sdk-android:connectedAndroidTest`, or all the `matrix-sdk-android androidTest` tests from within Android Studio 
=> Allow configurable sync timeout

CONTRIBUTING.md, changelog.d/7211.misc, docs/danger.md, tools/danger/dangerfile.js
Fixes #7195 
Avoid being blocked with merge conflicts when doing a Weblate sync.
Update the doc.
NA
Running locally against various PRs, using `bundle exec danger pr PR_URL --dangerfile=./tools/danger/dangerfile.js`
Will throw an error.
For instance #7084, output:
```
Some translation files have been edited. Only user `RiotTranslateBot` (i.e. translations coming from Weblate) is allowed to do that.
Please read more about translations management [in the doc](https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#internationalisation).
```
#6608, no error on output
#7201, no error on output
NA
=> Prevent modification of translations

vector-app/src/androidTest/java/im/vector/app/CantVerifyTest.kt, vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderLTests.kt
To give us time to work on it and unblock other PRs so they can be merged.
=> Ignore flaky test "CantVerifyTest" and "fix" VoiceRecorderLTests

changelog.d/7193.misc, vector/src/main/java/im/vector/app/features/auth/PendingAuthHandler.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSharedViewModel.kt, vector/src/main/java/im/vector/app/features/settings/account/deactivation/DeactivateAccountViewModel.kt, vector/src/main/java/im/vector/app/features/settings/crosssigning/CrossSigningSettingsViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/threepids/ThreePidsSettingsViewModel.kt, vector/src/test/java/im/vector/app/features/auth/PendingAuthHandlerTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeMatrix.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSecureStorageService.kt
Creation of a new class `PendingAuthHandler` to mutualize the handling of pending auth for actions which require authentication. It was previously used in several `ViewModel`. I am doing this refactor to be able to test this and because we will need it for sign out action in the new device management screens.
Closes #7193 
- Go to a screen using re-auth for example the device manager screen
- Go to settings -> Security & Privacy -> Show all sessions
- Long press on of your devices
- Press the sign out action
- Check the authentication flow is working well
=> Mutualize the pending auth handling (PSG-742)

.github/workflows/tests.yml, vector-app/src/androidTest/java/im/vector/app/CantVerifyTest.kt
Fixes the `CantVerifyTest` failing when running on the buildjet github action runner, the cause seems to be related to the emulator not having access to the wider network, which meant the initial matrix.org requests would timeout.
For reasons unknown to me, switching the emulator image to use the play store version ensures that the outside network is accessible.
To re-enable an ignored test
No production code changes
Run on the CI!
=> Missing buildjet Emulator network

changelog.d/7166.misc, vector-app/src/androidTest/java/im/vector/app/VerifySessionInteractiveTest.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt, vector-config/src/main/res/values/config-settings.xml
- [] Other :
reenable app layout by default
=> app layout labs flag is enabled by default

changelog.d/12.misc, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/command/Command.kt, vector/src/main/java/im/vector/app/features/command/CommandParser.kt, vector/src/main/java/im/vector/app/features/command/ParsedCommand.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
re #12
(╯°□°）╯︵ ┻━┻
1. Open the composer area
2. Type `/t` to see a list of commands starting with `t`
3. Select `/tableflip` or directly type in the command
- OS version(s): API 21 and API 32
=> Add support for `/tableflip` command (#12)

vector/src/main/java/im/vector/app/features/home/room/list/home/HomeFilteredRoomsController.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewState.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/header/RoomsHeadersData.kt
Fixes an issue where the roomList wil continuously flicker from one space to another space.
2 things changed:
- Multiple unneeded registration to spaceStateHandler.getSelectedSpaceFlow() (leak)
- Race condition in observeRooms() that would cause the livepagedList to receveive udpdates from two different data source (space filter)
Race description
On launch observeRooms() is called twice quickly
- init()
- observeOrderPreferences
The first call starts and suspends on preferencesStore.isAZOrderingEnabledFlow.first()
The second call then proceed and call
`filteredPagedRoomSummariesLive?.livePagedList?.removeObserver`
With no effects as the first call suspended before setting  `filteredPagedRoomSummariesLive`
After that both call continue their execution and call this twice
> …
=> Fix new layout flicker/leaks

gradle.properties
- re-enabling the jetifier, it's required by the autocomplete library
- the upstream library source doesn't require the jetifier however it hasn't been released  https://github.com/natario1/Autocomplete/issues/51
Fixes a crash when opening the autocomplete popup (typing a #) 
- Originally the jetifier was disable due to an incompatibility between the screenshot and unit tests, however this was resolved by switching the gradle tasks to be lazy instead of eager.
|Before|After|
|-|-|
|![before-autocomplete](https://user-images.githubusercontent.com/1848238/192740626-0abe3408-2883-40c2-b786-0730fce17938.gif)|![after-autocomplete](https://user-images.githubusercontent.com/1848238/192741341-b460ab46-76e3-4229-84db-6c81a954a46e.gif)|
- In a room
- Type a `#`
- Notice a crash
=> [Crash] Autocomplete crashes on open 

changelog.d/7247.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/model/DeviceInfo.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DeviceExtendedInfo.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DeviceFullInfo.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DeviceUserAgent.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/ParseDeviceUserAgentUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/GetDeviceFullInfoUseCase.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/DevicesViewModelTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/ParseDeviceUserAgentUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/filter/FilterDevicesUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/GetDeviceFullInfoUseCaseTest.kt
We need to parse user agents of all platforms to be able to render them on new device manager screens.
=> [Device Manager] Parse user agents (PSG-762)

changelog.d/6702.bugfix, dependencies.gradle, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/crosssigning/XSigningTest.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/crosssigning/MXCrossSigningInfo.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/model/UserVerificationLevel.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo019.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/CrossSigningInfoEntity.kt, vector/build.gradle, vector/src/main/java/im/vector/app/core/epoxy/profiles/BaseProfileMatrixItem.kt, vector/src/main/java/im/vector/app/core/ui/views/ShieldImageView.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt, vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListController.kt, vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewModel.kt, vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewState.kt, vector/src/main/java/im/vector/app/features/spaces/people/SpacePeopleListController.kt, vector/src/test/java/im/vector/app/features/MemberListViewModelTest.kt, vector/src/test/java/im/vector/app/features/RoomMemberListControllerTest.kt
Fixes #6702 
Parity with web. Show a warning when a previously verified user rotated his cross signing keys.
We now remember locally when a user was verified once.
When/If that user rotate his cross signing keys he will be marked with a red shield instead of black shield.
- Requires a database migration to remember that the user was verfied once
- Refactoring: The shield state of users was using the same enum as rooms `RoomEncryptionTrustLevel`, now I introduced a new enum for users `UserVerificationLevel` that is used in UI to decorate avatars.
- Step 1
- Step 2
- Step ...
=> warn on cross signing reset

changelog.d/7224.bugfix, vector/src/main/java/im/vector/app/features/lifecycle/VectorActivityLifecycleCallbacks.kt
=> Add Activities of android permission controller in the whitelist

changelog.d/7184.bugfix, library/multipicker/src/main/java/im/vector/lib/multipicker/utils/ImageUtils.kt
Closes #1404, closes #1851, closes #4545
Use software bitmap allocation when previewing images to upload on devices with Android Pie.
Using hardware bitmap allocation on Android framework versions prior to Android Q causes a crash when decoding a bitmap if GL context wasn't initialised. The issue is not documented in ImageDecoder reference but it is mentioned in the comments of glide[1] with a link to internal google discussion.
[1] https://github.com/bumptech/glide/blob/f83cc274b42cf02af6611d2a8c21e4a9b1f5d592/library/src/main/java/com/bumptech/glide/load/resource/bitmap/HardwareConfigState.java#L22
1. Sending images from within Element
- select "send images and videos" from attachment picker
- select image that caused a native crash on develop branch
2. Sharing images to Element from …
=> [Bugfix] Fix crash on previewing image to upload on Android P

dependencies.gradle, dependencies_groups.gradle, vector/build.gradle, vector/src/androidTest/java/im/vector/app/features/RoomMemberListControllerTest.kt
Removed Robolectric dependency, made the single Robolectric test we had `RoomMemberListControllerTest` an instrumentation test instead.
Since we're not actively using Robolectric at the moment we decided to remove it. If there is a need to add it back in the future we can always revert this.
- Run `RoomMemberListControllerTest`.
=> Remove Robolectric, make previous Robolectric test an instrumentation test

vector/src/main/res/drawable/poll_option_checked.xml
Hello,
I found an issue induced by ``android:gravity`` in https://github.com/vector-im/element-android/blob/81897a179e4cbd836c97f86a207d14c84ff85151/vector/src/main/res/drawable/poll_option_checked.xml#L13
This attribute can only be used in layer-list starting from API Level 23. Therefore the padding of the icon is wrong.
This issue can be reproduced when I participate a vote in the chat. You can see the tick is full of the icon at API Level 22.
API Level 31
API Level 22
To fix this issue, I use ``android:top``, ``android:bottom``, ``android:left`` and ``android:right``. 2dp is set by considering the 16dp width and height of tick mark and 20dp width and height of the whole icon. The issue have gone on my side.
Hope the above information is useful 
- [x ] Changes has been …
=> replace android:gravity for backward compatibility

changelog.d/5029.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerView.kt, vector/src/main/res/layout/composer_layout.xml, vector/src/main/res/layout/composer_layout_constraint_set_compact.xml, vector/src/main/res/layout/composer_layout_constraint_set_expanded.xml
When emoji keyboard was disabled in settings, it didn't apply when you replied to a message
https://github.com/vector-im/element-android/issues/5029
- Disable emoji keyboard
- Open a room
- Reply to a message
- Close reply
- Enable emoji keyboard
- Open a room
- Reply to a message
- Close repoly
- OS version(s): Android 13 beta
=> [Bugfix #5029] disable emoji keyboard not applies to reply

changelog.d/6215.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
This pull request fixes autoplaying animated images only actually autoplaying in some cases as only thumbnail data would be fetched in the other cases.
It introduces a new `ImageContentRenderer` mode specifically for animated images with thumbnail sizing that always resolves to the actual image url just like stickers for example
The autoplaying feature was originally introduced in #6166
This issue was brought up in the element-android matrix channel after release 1.4.18
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/42888162/171280858-bfbc721c-055b-4dad-b419-a7c6f1d30327.gif)|![after](https://user-images.githubusercontent.com/42888162/171280945-dacc24cc-bbd6-40a3-83bb-ac0fe32fc0b0.gif)|
- Send an animated image in a public room
- Check that the image actually …
=> Fix animated images only autoplaying sometimes

changelog.d/6633.feature, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/ComposerEditText.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt, vector/src/main/res/xml/vector_settings_security_privacy.xml
A new option has been added to the Privacy settings, which requests that the keyboard should not update any personalized data such as typing history and dictionary based on what the user typed.
Requesting that the keyboard minimize the amount of data it records about your private communications seems sensible for an encrypted messaging app.
It should disable the keyboard's personalized learning features, like adding your typed words into the personalized dictionary or storing the history of what you type. Some keyboards may not respect this setting. Signal messenger has this feature and missed it here.
- Use a keyboard that supports incognito mode, like Gboard
- In Element, enable "Incognito keyboard" in Settings->Security & Privacy->Other
- Enter a chat, focus the message input field, …
=> Add privacy setting to disable personalized learning by the keyboard

vector/src/androidTest/java/im/vector/app/features/html/EventHtmlRendererTest.kt
Fix broken `EventHtmlRendererTest`.
#5877 introduced changes to `EventHtmlRenderer` and some changes were needed to fix the UI tests.
- `EventHtmlRendererTest` should pass again.
=> Fix EventHtmlRendererTest

vector/src/androidTest/java/im/vector/app/features/RoomMemberListControllerTest.kt
Change the way `RoomMemberListControllerTest` waits for the models to be built, as it seems like `hasPendingModelBuild()` can return true before the model is actually updated.
`RoomMemberListControllerTest` is failing sometimes in our test workflow.
- UI tests should pass.
=> Try to fix flaky RoomMemberListControllerTest

changelog.d/6723.bugfix, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeSanityTests.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt
Fixes #6723 
Verification events sent in e2ee rooms should bypass the encrypt to verified devices only option. If not it renders verification impossible.
As per spec:
> When using in-room messages and the room has encryption enabled, clients should ensure that encryption does not hinder the verification. For example, if the verification messages are encrypted, clients must ensure that all the recipient’s unverified devices receive the keys necessary to decrypt the messages, even if they would normally not be given the keys to decrypt messages in the room. Alternatively, verification messages may be sent unencrypted, though this is not encouraged.
- Step 1
- Step 2
- Step ...
=> E2ee dos not hinder verification

changelog.d/7277.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/mapper/MyDeviceLastSeenInfoEntityMapper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo019.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo020.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/MyDeviceLastSeenInfoEntity.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/crypto/store/db/mapper/MyDeviceLastSeenInfoEntityMapperTest.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionItem.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionsController.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SetDeviceTypeIconUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/list/SetDeviceTypeIconUseCaseTest.kt
Display the correct device type icon on item in lists and in the session overview view.
Adding mapping from `DeviceInfo` to Realm entity for the user agent field with the corresponding migration.
Closes #7277 
- Login to an account in https://synapse-prefill.lab.element.dev (Synapse deployment with experimental feature flags for MSC3852 (exposure of user agent))
- Enable the new device manager feature flag
- Go to Settings -> Security & Privacy -> Show all sessions (WIP, V2)
- Check there are correct icons for device types of each of the sessions in the other sessions list and in the session overview views
=> [Device Management] Show correct device type icons (PSG-775)

changelog.d/7285.misc, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerView.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageItem.kt, vector/src/main/res/layout/fragment_composer.xml, vector/src/main/res/layout/fragment_timeline.xml, vector/src/main/res/layout/fragment_voice_recorder.xml
Split `TimelineFragment` into 3 separate entities:
- TimelineFragment.
- MessageComposerFragment.
- VoiceRecorderFragment.
`TimelineFragment` is a large class that has many responsibilities: rendering timeline events, handling composer input, handling voice recording, etc. This is an attempt to separate those into separate components that can be worked on independently.
UI hasn't changed.
- Go into any room.
- Try sending a message, see that the UI behaves as expected.
- Try also replies, quotes, attachments, editing events, etc.
- Try autocompletion.
- Try tapping on usernames in the timeline.
- Try voice recordings.
- In general, try anything that's related to either the message composer or voice recording.
- OS version(s): 11, 12.
=> Refactor: split TimelineFragment into MessageComposerFragment and VoiceRecorderFragment

changelog.d/7283.wip, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventsGroups.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastItem.kt
Display a single voice broadcast state event in the timeline. Each change related to the voice broadcast state will update the tile of the first state event. The position of the tile remains the same.
Continue #7127
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/11990514/193785715-d6d5461d-54ea-42a6-8d70-3252feb6c6bc.png)|![vb_tile_timeline_position](https://user-images.githubusercontent.com/11990514/193787566-2f2022ac-ae11-4bfb-89c7-0419eb83d0de.gif)|
- Enable the voice broadcast feature flag
- Start a voice broadcast in a room
- Send several messages
- Update the voice broadcast state (pause/resume/stop)
- Verify that the voice broadcast tile is correctly updated and that the position of the tile has not changed
=> Aggregate voice broadcast state events

vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt
(Not in prod so no changelog)
Fix regression from #7285.
When switching room using left panel breadcrumbs, a TimelineFragment was recreated, but because of the usage of `activityViewModel`, the ViewModel was not, so the current room was not changed. Using `fragmentViewModel` in TimelineFragment and `parentFragmentViewModel` in the 2 children it fixes the pb.
Fix regression
- Switch room using breadcrumbs in a timeline.
=> Fix breadcrumbs

library/ui-strings/src/main/res/values/strings.xml
“Set an email address to recover your account. Later, you can optionally allow people you know to discover you by ~~your~~ this address.”
Corrected the string as noted in this [comment by @lvre](https://translate.element.io/translate/element-android/element-app/en/?checksum=8cfc63845b17eca4#comments) over on Weblate.
Signed-off-by: Vri <vrifox@vrifox.cc>
=> correct login_set_email_notice

vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt, vector/src/main/res/layout/fragment_session_overview.xml
Due to errors during merge, re-putting in place the navigation to session details and fixing layout.
No changelog added since this is a fix during development and it has not been released yet.
Have correct UX.
- Enable the feature flag for new device manager feature
- Go to Settings -> Security & Privacy -> Show all sessions (WIP, V2)
- Go to a session overview screen
- Check the UI is correct
- Press the session details entry
- Check the details screen is displayed
=> [Device manager] Fixing navigation to session details + layout in session overview screen

changelog.d/7336.feature, library/ui-strings/src/main/res/values/strings.xml, vector-app/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt, vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt, vector-config/src/main/res/values/config-settings.xml, vector/src/main/java/im/vector/app/features/VectorFeatures.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt, vector/src/main/res/xml/vector_settings_labs.xml
Adding lab flag for the new session manager screens.
Closes #7336 
- Go to Settings -> Labs
- Enable the new session manager flag
- Check the entry leads to the new session manager screens
- Go to Settings -> Labs
- Disable the new session manager flag
- Check the entry leads to the old session manager screens
=> [Device management] Add lab flag for the feature (PSG-793)

changelog.d/7324.wip, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
Hiding the last seen info details on the Session Info card view when it is the current session.
Closes #7324 
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/46314705/194884903-03e83124-00a0-4757-bd83-88b06984de1d.png" width=300 />|<img src="https://user-images.githubusercontent.com/46314705/194884909-063a82e8-3c77-492a-9de8-a3cecf4cd0ed.png" width=300 />|
- Enable the feature flag for new device manager
- Go to Settings -> Security & Privacy -> Show all sessions (V2, WIP)
- Check the current session info card view does not show the last seen details in the main screen and in the overview screen
- Check the last seen details info is displayed for other sessions when on session overview screen
=> [Device management] Hide the IP address and last activity date on current session (PSG-823)

changelog.d/7335.misc, dependencies.gradle, dependencies_groups.gradle, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/Optional.kt, vector/build.gradle, vector/src/main/java/im/vector/app/ActiveSessionDataSource.kt, vector/src/main/java/im/vector/app/SpaceStateHandler.kt, vector/src/main/java/im/vector/app/SpaceStateHandlerImpl.kt, vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt, vector/src/main/java/im/vector/app/core/files/FileSaver.kt, vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupStep3Fragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt, vector/src/test/java/im/vector/app/test/fakes/FakeActiveSessionDataSource.kt
Remove Arrow-kt dependency.
- Smoke test (in progress)
=> Remove Arrow-kt dependency

changelog.d/7321.wip, vector/src/main/java/im/vector/app/features/settings/devices/v2/ParseDeviceUserAgentUseCase.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/ParseDeviceUserAgentUseCaseTest.kt
Improving the parsing of the user agent in the operating system fields.
Closes #7321 
- Enable the feature flag for new device management
- Sign-in a Web session using the test server: synapse-prefill.lab.element.dev
- Sign-in a mobile session
- Go to Settings -> Security & Privacy -> Show all sessions (V2, WIP)
- Go to the session details screen of the Web session
- Check the operating system is correct
=> [Device management] Improve the parsing for OS of Desktop/Web sessions (PSG-823)

tools/check/check_code_quality.sh
Previous log:
```
Search for forbidden patterns in code...
Can't stat ./library/jsonviewer/src/main/java: No such file or directory
at ./tmp/search_forbidden_strings.pl line 79.
Can't stat ./vector/src/debug/java: No such file or directory
at ./tmp/search_forbidden_strings.pl line 79.
Can't stat ./vector/src/release/java: No such file or directory
at ./tmp/search_forbidden_strings.pl line 79.
Can't stat ./vector/src/fdroid/java: No such file or directory
at ./tmp/search_forbidden_strings.pl line 79.
Can't stat ./vector/src/gplay/java: No such file or directory
at ./tmp/search_forbidden_strings.pl line 79.
All clear!
Search for forbidden patterns specific for SDK code...
All clear!
Search for forbidden patterns specific for App code...
Can't stat ./vector/src/debug/java: No such file or …
```
=> Fix the check script, some folders have changed.

changelog.d/5968.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/DraggableStateProcessor.kt
Fix the wrong mic button direction to cancel on RTL languages.
The cause of this bug is due to the distance calculation of X coordinate in ```DraggableStateProcessor```.
The way to measure distance seems like not considering RTL languages.
So When it becomes RTL, the distance value becomes negative.
So I take the absolute value of the calculation.
Fix #5968 
|Before|After|
|-|-|
| <video src="https://user-images.githubusercontent.com/39683194/194820876-204a5b34-109f-4ac2-a8d3-00e2ea9ce4a7.mp4" /> |  <video src="https://user-images.githubusercontent.com/39683194/194820935-ee3e1ff3-78ae-4aed-8773-5f7aa05129e6.mp4" />|
- Step 1
Enter the chat room
- Step 2
Test when it is not RTL. it works fine.
- Step 3
Developer Options -> Turn on "Force RTL Layout direction"
- Step 4
When dragging the mic …
=> Fix the wrong mic button direction to cancel on RTL languages

changelog.d/7344.feature, library/ui-strings/src/main/res/values/strings.xml, vector-config/src/main/res/values/config-settings.xml, vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt, vector/src/main/java/im/vector/app/core/session/ConfigureAndStartSessionUseCase.kt, vector/src/main/java/im/vector/app/core/session/clientinfo/DeleteMatrixClientInfoUseCase.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsAction.kt, vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsFragment.kt, vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsViewModel.kt, vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsViewState.kt, vector/src/main/res/xml/vector_settings_labs.xml, vector/src/main/res/xml/vector_settings_root.xml, vector/src/test/java/im/vector/app/core/session/ConfigureAndStartSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/core/session/clientinfo/DeleteMatrixClientInfoUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/labs/VectorSettingsLabsViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeVectorPreferences.kt
Adding a lab flag to toggle the client info recording used to provide Application info in the session details screen.
Closes #7344 
- Sign-in to synapse-prefill.lab.element.dev
- Go to Settings -> Labs
- Enable the new session manager
- Check the "Enable client info recording" flag
- Go to Settings -> Show all sessions
- Go to the session details screen of the current session
- Check the Application section is displayed
- Go to Settings -> Labs
- Uncheck the "Enable client info recording" flag
- Go to the session details screen of the current session
- Check the Application section is not displayed
=> [Device management] Add lab flag for matrix client info account data event (PSG-800)

changelog.d/7359.bugfix, changelog.d/7359.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Changes to both the SDK and `MessageComposerViewModel` to retrieve and edit the right message body in the plain text editor.
See #7359 .
- Enable the rich text editor in labs in the Android app and send a formatted message. Alternatively, write some formatted message in the web version.
- Disable the rich text editor, try to edit the formatted message.
=> Fix editing formatted messages in plain text editor

changelog.d/7374.feature, vector/src/main/java/im/vector/app/features/settings/VectorSettingsActivity.kt
Checking the lab flag value for new session manager to select the correct session manager screen to navigate to.
Closes #7374 
- Sign in to a verified session
- Enable the lab flag for new session manager
- Restart the app
- Press the in app alert to review the session appearing in the home screen
- Check the new session manager main screen is opened
- Disable the lab flag for new session manager
- Restart the app
- Press the in app alert to review the session appearing in the home screen
- Check the old session manager main screen is opened
=> [Device Management] Redirect to the new screen everywhere when lab flag is on

changelog.d/7282.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/FetchEditHistoryTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/RelationsResponse.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadTimelineTask.kt
Homeservers will not return `RelationsResponse.original_event` in the future.
See #7275: stop using `original_event` field.
We will move to `v1` endpoint later (and probably more globally).
Comply with spec.
- Smoke tests
=> Stop using `original_event` field

tools/gradle/doctor.gradle
Keep the useful log "Is CI build: $isCiBuild".
Avoid error on developers env.
- Step 1
- Step 2
- Step ...
=> Let the doctor be less strict and just warn.

.github/workflows/post-pr.yml
Jobs `codecov-units` and `integration-tests` do not exist anymore.
This should fix wrong message that we receive like this one:
-> failed even when successful
No need for a changelog here.
=> Fix message sent even if the step `ui-tests` is successful.

changelog.d/7384.misc, dependencies.gradle
Bump WYSIWYG dependency version to 0.2.1.
Get the latest fixes.
- Enable the WYSIWYG editor in Settings > Labs.
- Try using the different features of the editor.
=> Bump WYSIWYG lib to 0.2.1

changelog.d/7387.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageAudioEvent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimelineService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineEventDataSource.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventsGroups.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastItem.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastExtensions.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastHelper.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastPlayer.kt
Add the ability to listen to a voice broadcast.
For the moment, the incoming voice messages are not added to the queue when the listening is ongoing.
Continue #7127 
- Enable the voice broadcast feature flag
- Start a voice broadcast in a room
- Verify that you can listen to a voice broadcast from another account when it has ended
- Verify that you can listen to an ongoing voice broadcast from another account (only for the already received events)
- Verify that the UI is correctly updated
=> Voice Broadcast - Listening

changelog.d/7397.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/SendService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastConstants.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastExtensions.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastPlayer.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/model/MessageVoiceBroadcastInfoContent.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/model/VoiceBroadcastChunk.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCase.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSendService.kt
Add `io.element.voice_broadcast_chunk` in voice message content
Add `device_id` in `io.element.voice_broadcast_info` state event
Add entries in matrix-sdk to add additional content fields to the events
Continue #7127 and follow the "specification" defined in https://github.com/vector-im/element-meta/discussions/632 
=> Add additional data in voice broadcast events 

changelog.d/7372.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/GetProfileInfoTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/UpdateUserWorker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/UserDataSource.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/helper/WidgetFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/LocationPinProvider.kt, vector/src/main/java/im/vector/app/features/html/PillsPostProcessor.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt, vector/src/main/java/im/vector/app/features/location/live/map/UserLiveLocationViewStateMapper.kt, vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListBottomSheetViewModel.kt, vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt, vector/src/main/java/im/vector/app/features/spaces/invite/SpaceInviteBottomSheetViewModel.kt, vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt
getUser can return null, since the loading of profile is now async. It may lead to unexpected issue and a crash, fixed by this commit: 0a6d620f27d3160d273f6d0a2b5e13936a333d23
Other commits fixes similar things. Also when retrieved, the profile is now stored into DB for future usage.
To reproduce the crash (but this is not 100% reproducible due to race condition)
- Do an initial sync on a big account
- Quickly open a room a start verifying a user.
=> Handle properly when getUser returns null - prefer using getUserOrDefault

changelog.d/7419.wip, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineEventDataSource.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastHelper.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastPlayer.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastRecorder.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastRecorderQ.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/model/MessageVoiceBroadcastInfoContent.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetVoiceBroadcastStateUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/PauseVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/StopVoiceBroadcastUseCase.kt
Be able to listen to an ongoing voice broadcast
When a voice broadcast is live, trigger the play action will start listening to the last received chunk and wait for the new ones with a "buffering" state in the meantime.
Also, when the recording is paused, the current chunk is now stopped and sent to the room. Resume the recording will start a new chunk file.
Note: the UI will be improved in a dedicated PR for a better rendering of the listening state
Continue #7127
- Start playing a live voice broadcast
- Verify that we are able to listen it until it is stopped or paused by the recorder
- Verify that when the recorder resume the voice broadcast, you continue to listen to the new chunks
- Verify that the listener is able to pause and resume the listening without problem
=> Voice broadcast - live listening

changelog.d/7431.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt
Add a check on the recorder device id before showing the recording or listening tile in the timeline
Fix https://github.com/vector-im/element-android/issues/7431
- Record a voice broadcast on a sessionA in a room
- Open the room with a sessionB while the voice broadcast is live
- Verify that the sessionB is in a listening state (can start/pause listening to the VB but cannot pause or stop the recording)
=> Voice Broadcast - Do not display the recording tile on the other sessions

changelog.d/7454.misc, dependencies.gradle, dependencies_groups.gradle, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ImageExifTagRemover.kt
Replace outdated dependency. Not sure why sanselan was used at the beginning.
Fixes #7453
- Send an image with GPS data, without compressing
- Check that the sent image does not contains GPS data
Available info after sending (so visible by everyone in the room):
We could strip more data, but this is maybe out of scope of this PR.
=> Replace org.apache.sanselan:sanselan by org.apache.commons:commons-imaging

changelog.d/7429.feature, changelog.d/7452.feature, dependencies.gradle, library/ui-strings/src/main/res/values/strings.xml, library/ui-styles/src/main/res/values/styles_bottom_sheet.xml, vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt, vector/src/main/java/im/vector/app/core/ui/views/BottomSheetActionButton.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentType.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorBottomSheet.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorSharedActionViewModel.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorView.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorViewModel.kt, vector/src/main/java/im/vector/app/features/attachments/AttachmentsHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/drawable/ic_text_formatting.xml, vector/src/main/res/drawable/ic_text_formatting_disabled.xml, vector/src/main/res/layout/bottom_sheet_attachment_type_selector.xml, vector/src/main/res/layout/composer_rich_text_layout.xml, vector/src/main/res/layout/composer_rich_text_layout_constraint_set_compact.xml, vector/src/main/res/layout/composer_rich_text_layout_constraint_set_expanded.xml, vector/src/main/res/layout/composer_rich_text_layout_constraint_set_fullscreen.xml, vector/src/main/res/layout/view_bottom_sheet_action_button.xml, vector/src/test/java/im/vector/app/features/attachments/AttachmentTypeSelectorViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeVectorFeatures.kt, vector/src/test/java/im/vector/app/test/fakes/FakeVectorPreferences.kt
Combination of two changes rebased on `resilience-rc`.
See the original PRs:
- https://github.com/vector-im/element-android/pull/7452
- https://github.com/vector-im/element-android/pull/7429
=> [Rich text editor] Add plain text mode and new attachment UI

changelog.d/7478.wip, vector/src/main/java/im/vector/app/core/di/VoiceModule.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageVoiceBroadcastItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastListeningItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastRecordingItem.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastHelper.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayer.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/usecase/GetLiveVoiceBroadcastChunksUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorder.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorderQ.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/PauseVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/ResumeVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StartVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StopOngoingVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StopVoiceBroadcastUseCase.kt, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/PauseVoiceBroadcastUseCaseTest.kt, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/ResumeVoiceBroadcastUseCaseTest.kt, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCaseTest.kt, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/StopVoiceBroadcastUseCaseTest.kt
- Added an interface upon the voice broadcast player implementation to clarify which methods are exposed to the application and move some code
- Added a use case dedicated to the fetch of a voice broadcast playlist (live or ended)
- Rework some code in the player implementation
Consolidate the code base of the voice broadcast player
=> Voice Broadcast - Some internal improvements related to the player

changelog.d/7400.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
Uses right logic to show the share screen in a room.
Fixes #7400 .
- Select a file from another app (ideally image/video) and share it with Element Android.
- Select a room, the share dialog should appear as it used to do before.
=> Fix share actions from share dialog

changelog.d/7357.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
Removes a line that incorrectly tried to clear the contents of the composer even if the text wasn't being sent when using enter key.
Fixes #7357 .
- Open settings -> preferences.
- Enable 'Send message with enter' preference.
- Open any room, type a message and hit either an Enter hardware key (emulator) or the new line button in some non-standard software keyboard (SwiftKey seems to be a good example, it sends KEY_ENTER keycodes instead of an IME action).
- OS version(s): 11, 13.
=> Fix new line and enter key presses deleting existing text in some keyboards

changelog.d/7485.wip, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastFailure.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StartVoiceBroadcastUseCase.kt, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCaseTest.kt
Display a dialog if the user cannot start a voice broadcast (no permission, another user already recording in the room, user is already recording a voice broadcast) 
Continue #7127 
|Permission|Other user is recording|User already recording|
|-|-|-|
|![Screenshot_20221028_101706](https://user-images.githubusercontent.com/11990514/198546070-08604ff3-ce9f-4e9d-9dab-666c7aa55573.png)|![Screenshot_20221028_101659](https://user-images.githubusercontent.com/11990514/198546187-4c31260d-15e8-4cb6-8b68-290579c794d4.png)|![Screenshot_20221028_101649](https://user-images.githubusercontent.com/11990514/198546219-5081225e-526b-4bda-9bdb-0ba8ff09f5a8.png)|
Try starting a voice broadcast in the several contexts
=> Voice Broadcast - Show start voice broadcast errors in a dialog

.github/workflows/triage-labelled.yml
All "good first issue" and "Hacktoberfest" qualify as "Help Wanted" so the label should be added automatically
- Step 1
- Step 2
- Step ...
=> Add issue automation to tidy Help Wanted

changelog.d/7457.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/homeserver/HomeServerCapabilities.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/HomeServerCapabilitiesMapper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo042.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/HomeServerCapabilitiesEntity.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/homeserver/GetHomeServerCapabilitiesTask.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/notification/CheckIfCanTogglePushNotificationsViaAccountDataUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/notification/CheckIfCanTogglePushNotificationsViaPusherUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/notification/GetNotificationsStatusUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/notification/NotificationsStatus.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/notification/TogglePushNotificationUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewState.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/notification/CheckIfCanTogglePushNotificationsViaAccountDataUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/notification/CheckIfCanTogglePushNotificationsViaPusherUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/notification/GetNotificationsStatusUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/notification/TogglePushNotificationUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSessionAccountDataService.kt, vector/src/test/java/im/vector/app/test/fixtures/HomeserverCapabilityFixture.kt
Checking the support for MC3881 about new enabled field for Pusher to render the push notification toggle for a session in the overview screen.
Closes #7457 
- Signin to matrix server
- Enable the new session manager labs flag
- Go to a mobile session overview
- Check the push notification toggle is not displayed (matrix does not support the feature yet)
- Go to a web session overview
- Check the push notification toggle is displayed (since there should be an associated account data setting)
- Signin to a server which supports MCS3881
- Go to a mobile session overview
- Check the push notification toggle is displayed
=> [Session manager] Hide push notification toggle when there is no server support (PSG-970)

changelog.d/7519.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
Fix incorrect type of event content entries when sending unencrypted events related to media files
After uploading a media file (eg. voice message), the local event related to the media is updated with some metadata (eg. size). The event entity was retrieved from the database and mapped to the Event model without casting the json numbers to their original type.
Here is the issue, after retrieving some additional data, the entity was updated with the new metadata plus the additional data, with the wrong number types, causing an error when sending the event to the server.
This PR forces the cast of the json number before updating the event in the database.
Note: the issue is only visible on voice broadcast because additional data are added to the voice message events triggering a specific …
=> Fix bad content types when sending unencrypted media event with additional content data

changelog.d/7509.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Restored some code that correctly displayed the composer when the user joins a room but only after the room has been completely loaded.
Fixes #7509 .
|Before|After|
|-|-|
|![Screenshot_1667399487](https://user-images.githubusercontent.com/480955/199516903-3b98e4d5-4c34-49fe-abf0-91aa5a072ea0.png)|![Screenshot_1667399492](https://user-images.githubusercontent.com/480955/199516952-cd3a96c5-f190-42df-ab7f-5e46ebf8a19b.png)|
- Get invited to a room.
- Join it.
=> When joining a room the message composer should be visible once the room loads

changelog.d/7501.bugfix, vector/src/main/java/im/vector/app/features/html/PillsPostProcessor.kt
Remove spans conflicting within pill spans
- Duplicated pills if the mention contains an image: https://github.com/SchildiChat/SchildiChat-android/issues/148
- Duplicated pills if the mention contains underscores: https://github.com/SchildiChat/SchildiChat-android/issues/156
|Before|After|
|-|-|
|![device-2022-11-01-113714](https://user-images.githubusercontent.com/12481742/199254899-953140a9-8950-4b44-82ba-6982a4ec3e15.png)|![device-2022-11-01-151524](https://user-images.githubusercontent.com/12481742/199254926-58070b88-a7d2-46d8-9ba2-2f6b5586f23b.png)|
- Send or receive events with mention-urls that contain another span, such as:
- At least two underscores, which markdown will want to put italic (https://github.com/SchildiChat/SchildiChat-android/issues/156)
- An inline image …
=> Fix duplicated pills when pills contain other spans

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/search/SearchMessagesTest.kt
Synapse is not returning result for incomplete word anymore.
This PR take into account this change.
A new test is added to check this new behavior about incomplete word.
Maybe related to recent change on Synapse 1.71.0: https://github.com/matrix-org/synapse/releases/tag/v1.71.0 :
> Allow use of Postgres and SQLlite full-text search operators in search queries. (https://github.com/matrix-org/synapse/issues/11635, https://github.com/matrix-org/synapse/issues/14310, https://github.com/matrix-org/synapse/issues/14311)
No need for a changelog.
=> Fix search tests

changelog.d/7496.wip, library/attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/VideoViewHolder.kt, library/core-utils/src/main/java/im/vector/lib/core/utils/timer/CountUpTimer.kt, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceMessageRecorderView.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VoiceBroadcastItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/AudioMessagePlaybackTracker.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageVoiceBroadcastItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageAudioItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastListeningItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceItem.kt, vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationUserItem.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastExtensions.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastHelper.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayer.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlaylist.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/usecase/GetLiveVoiceBroadcastChunksUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/model/VoiceBroadcast.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetVoiceBroadcastEventUseCase.kt, vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml
Update the live position of the playback when the voice broadcast is in a playing state.
Plus some improvements on the voice broadcast player.
Continue #7127 and improve #7494 
|Ended VB | Live VB|
|-|-|
|https://user-images.githubusercontent.com/11990514/200355744-69dea59f-3b0a-48ab-9c41-ca4ced2fbc52.mp4|https://user-images.githubusercontent.com/11990514/200355809-5139985f-b764-48ee-bc7a-9c605f971ef7.mp4 (the duration of the chunks has been set to 5 sec for this demo) |
Play an ended / live voice broadcast and observe the seekbar behaviour
=> Voice Broadcast - Update seek bar position while playing

changelog.d/7496.feature, vector/src/main/java/im/vector/app/core/ui/views/TypingMessageView.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/TypingItem.kt, vector/src/main/res/layout/fragment_timeline.xml, vector/src/main/res/layout/item_typing_users.xml
Creates a new `TypingItem` that contains a `TypingView` so it's not part of the timeline.
Closes #7564 .
|Before|After|
|-|-|
|[old_typing_view.webm](https://user-images.githubusercontent.com/480955/201083798-678abb55-982e-4bd7-982c-690eb1d668e1.webm)|[new_typing_item.webm](https://user-images.githubusercontent.com/480955/201089117-8eb10ec2-7f1a-4113-a8ff-325e46c952a5.webm)|
- Open a room shared with another account you can sign in into.
- Write from that other account.
- OS version(s): 9
=> Move TypingView into the timeline as another item

changelog.d/7530.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactoryTests.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeClipboardManager.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeConnectivityManager.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeContext.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeNetworkCapabilities.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/internal/session/content/FakeThumbnailExtractor.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/internal/session/permalinks/FakePermalinkFactory.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/internal/session/room/send/FakeLocalEchoRepository.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/internal/session/room/send/FakeMarkdownParser.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/internal/session/room/send/FakeWaveFormSanitizer.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/internal/session/room/send/pills/FakeTextPillsUtils.kt
`LocalEchoEventFactory.createQuotedTextEvent` incorrectly handled messages with no formatted text in quotes.
Fixes #7530 .
- With Rich Text Editor disabled (using the default composer), type a message.
- Quote this message.
- Then enable markdown formatting (Settings > Preferences).
- Quote the previous message using some MD formatting (bold, italic, etc.).
- Create a new MD message, quote it too with no markdown in the new text.
No "null" text should appear and formatting should look good (correct new line after quote, etc.).
- OS version(s): API 29
=> Fix some quoted messages having 'null' message bodies

changelog.d/7582.feature, vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/AudioMessagePlaybackTracker.kt
When pausing a voice message playback, the playback position is now persisted when closing the room timeline.
This also affects voice broadcast playbacks.
[Voice Broadcast](https://github.com/vector-im/element-android/issues/7127) feature requires to be able to listen to a voice broadcast when navigating across the app. For this need, we decided to not reset the playback position for voice messages when closing the room timeline.
The positions will be reset only after killing the application.
- Have a room timeline with several voice broadcasts and voice messages
- Play/pause some of them or seek to a given position
- Navigate into the app
- Go back to the previous room
- Verify that the playback positions are not reset
- Verify that the position is correct when resuming the playback
- OS …
=> Persist the playback state of voice messages across different screens

changelog.d/7588.wip, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/home/room/detail/composer/AudioMessageHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/AudioMessagePlaybackTracker.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastRecordingItem.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastConstants.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorder.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorderQ.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StartVoiceBroadcastUseCase.kt, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCaseTest.kt
Add max time for voice broadcast recording and display the remaining time in the timeline tile.
Voice broadcast is automatically stopped when the max time is reached.
Continue #7127
https://user-images.githubusercontent.com/11990514/201884354-d1a4512a-3bb5-42a3-b637-6e6a07628aa7.mp4
Note: The video has been accelerated
- Start recording a new voice broadcast
- Observe that the remaining time is correctly updated
- Observe that the recording is automatically stopped when at the end of the remaining time
Note: you can change the max length in `VoiceBroadcastConstants.MAX_VOICE_BROADCAST_LENGTH_IN_SECONDS` for tests purpose 
=> Voice Broadcast - Add max length for recording

changelog.d/7574.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
When user wants to edit a message in the RTE and no `formattedBody` is present, just default to the `body` property instead.
FIxes #7574 .
- Make sure RTE is disabled in Labs (it's disabled by default). Markdown conversion should be disabled too.
- Write a message using the default editor, in plain text.
- Enable RTE in Labs.
- Edit the message using the RTE. The contents of the message should be in the editor now.
=> Editing: default to `MessageContent.body` when no `formattedBody` is present

changelog.d/7604.bugfix, vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt, vector/src/main/java/im/vector/app/core/session/ConfigureAndStartSessionUseCase.kt, vector/src/test/java/im/vector/app/core/session/ConfigureAndStartSessionUseCaseTest.kt
Launch the sending of client info in a dedicated coroutine so that it does not block the main thread on app startup and leads to ANR.
Closes #7604 
- Enable the labs flag about "Client info recording" in a previous version of the app
- Update the app with this fix
- The app should not block on startup
=> ANR on session start when sending client info is enabled

changelog.d/7555.bugfix, library/ui-strings/src/main/res/values/strings.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/location/LocationSharingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/relation/RelationDefaultContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StartLiveLocationShareTask.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingServiceTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStartLiveLocationShareTaskTest.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/render/EventTextRenderer.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCase.kt, vector/src/main/java/im/vector/app/features/location/live/tracking/LocationSharingAndroidService.kt, vector/src/test/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeTimelineService.kt
Adding translations for "replyTo" events message on application side.
The description parameter exposed in SDK API for the start of a live location has also been removed to avoid introducing translated text in Matrix events.
Closes #7555 
- Go to a room (encrypted or not)
- Send different type of messages
- Reply to these messages
- Check the replies are well rendered (right now they are not translated: we should wait for Weblate sync to see the changes)
=> Missing translations on "replyTo" messages (PSG-978)

changelog.d/5679.bugfix, vector/src/androidTest/java/im/vector/app/core/utils/TestSpan.kt, vector/src/main/java/im/vector/app/features/html/EventHtmlRenderer.kt
When bubble mode and markdown are enabled, then italic texts are truncated at the end.
This is a known [issue](https://github.com/noties/Markwon/issues/101) both for the library we use and the Android OS. The root cause is that it is not actually using an italic font instead it is just skewing the view of text.
Fixes #5679.
|Before|After|
|-|-|
|![italic_before](https://user-images.githubusercontent.com/1254401/202451860-9c58dbb1-fe4b-4f20-978f-ce88d1927dd9.jpeg)|![italic_after](https://user-images.githubusercontent.com/1254401/202451888-b087bded-d1b6-4390-a834-2773b2e39ee4.jpeg)|
- Enable markdown formatting and bubble mode in settings
- Send an italic message by using * message * (without spaces)
=> Fix italic text is truncated when bubble mode and markdown is enabled (PSG-1006)

changelog.d/7620.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt, vector/src/main/res/layout/composer_rich_text_layout.xml
- Creates a ConstraintSet change when the rich text mode of the editor is enabled/disabled.
- Disables the full screen button when either the rich text mode is disabled or it's in landscape orientation, since there is almost no vertical space available.
Fixes #7620.
|Before|After|
|-|-|
|![IMAGE 2022-11-21 09:31:59](https://user-images.githubusercontent.com/480955/203002602-4d880dbb-7ce4-4acd-86d3-800139f4c0f9.jpg)|![Screen](https://user-images.githubusercontent.com/480955/203002671-e9b2ed5a-a5eb-497d-9bfd-67317524b414.png)|
- Enabled the Rich Text Editor in Labs.
- Enter a room, make sure your device is in portrait orientation (vertical).
- Enter full screen mode using the 'maximise' button.
- Tap on the "+" button, disable formatting. Check that the full screen mode was cancelled and …
=> [RTE] Change layout based on plain text / rich text mode

CONTRIBUTING.md, README.md, changelog.d/7583.misc, docs/installing_from_ci.md, tools/gradle/doctor.gradle, tools/install/installFromBuildkite.sh, tools/install/installFromGitHub.sh, tools/release/download_buildkite_artifacts.py, tools/release/download_github_artifacts.py, tools/release/releaseScript.sh, vector-app/build.gradle, vector-app/signature/README.md, vector-app/src/main/java/im/vector/app/VectorApplication.kt, vector-app/src/main/java/im/vector/app/core/di/SingletonModule.kt, vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/core/resources/BuildMeta.kt, vector/src/main/java/im/vector/app/features/login/LoginSplashFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashCarouselFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashFragment.kt, vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt, vector/src/main/java/im/vector/app/features/rageshake/VectorUncaughtExceptionHandler.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsHelpAboutFragment.kt, vector/src/main/java/im/vector/app/features/version/VersionProvider.kt, vector/src/test/java/im/vector/app/test/fixtures/BuildMetaFixture.kt
Remove usage of Buildkite.
Build number is just removed.
Related script will need to be updated separately.
Closes #7493 
Release script will have to be updated for the next release, but it's not part of the project file.
TODO:
- NA
=> Remove usage of Buildkite.

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo044.kt
hotfix for migration missing in this [PR](https://github.com/vector-im/element-android/pull/7474)
=> read receipt migration added

changelog.d/7646.bugfix, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
Improvement related to the voice broadcast playback, fix issues with buffering state
Also fixed an issue when the live broadcast is ended, the playback was not automatically reset after listening to the last chunk.
Sometimes, the (live) playback was stuck in a buffering state after a pause/resume from the recorder or when receiving new chunks after reaching the current duration
Verify that the playback is not stuck in buffering when starting listening to a live voice broadcast (from the beggining & after reaching the end)
The playback should be automatically reset when the listening is over and the live VB has ended.
=> Voice Broadcast - Fix playback stuck in buffering

changelog.d/2725.feature, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/home/ShortcutCreator.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/xml/vector_settings_preferences.xml
Direct share continues to be enabled by default.
As requested in #2725
Signed-off-by: Joaquín Aguirrezabalaga <kinote@kinote.org>
Adds a new setting under preferences "Enable direct share" that allows enabling or disabling direct share.
Direct share support was added in #2029, this PR allows the user to disable it.
Closes #2725
| Before | After |
|-|-|
| ![menu-no-option](https://user-images.githubusercontent.com/1480/198875056-0b951651-fe81-4983-9942-6991a3255776.png) | ![menu-option-on](https://user-images.githubusercontent.com/1480/198875063-ce9790c1-34ab-45dd-b276-33bd2751bd13.png) |
| Setting | Effect |
|-|-|
|![menu-option-on](https://user-images.githubusercontent.com/1480/198875214-a741d600-4ea4-465e-919a-ca460b04f351.png)|![share-on](https://user-images.githubusercontent.com/1480/1 …
=> Add setting to allow disabling direct share

changelog.d/7656.wip, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventVisibilityHelper.kt, vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt
Remove the voice messages related to a VB from the room attachments.
Improve #7127 
1. Record a VB in a room
2. Send several media and files in the room (voice messages, images, videos, pdf, etc...)
3. Verify that the voice messages related to the VB are not displayed in the attachments lists (room details -> uploads)
=> [Voice Broadcast] Remove chunks from the room attachments

7658.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt, vector/src/main/res/layout/composer_rich_text_layout.xml
Improve design and spacing of the rich text editor.
Minor changes to
- position of input field relative to buttons
- spacing around attachments button
- spacing around send button
- selectable backgrounds
https://element-io.atlassian.net/browse/PSU-994
| |Before|After|
|-|-|-|
|Empty input, formatting disabled|![rich-text-formatting-disabled-before](https://user-images.githubusercontent.com/4940864/204543837-23a2ccfa-1e0b-4c82-903b-b397bf53317f.png)|![rich-text-formatting-disabled](https://user-images.githubusercontent.com/4940864/204539450-d28db31c-afbb-4091-b90d-6c6811a63aef.png)|
|Empty input, formatting enabled|![rich-text-formatting-enabled-before](https://user-images.githubusercontent.com/4940864/204543891-61d9fd70-fe63-424e-a046-850026602aa5.png)|![rich-text-formatting-enabled](http …
=> [Rich text editor] Fix design and spacing of rich text editor

changelog.d/7680.bugfix, vector/src/main/java/im/vector/app/core/utils/ExpandingBottomSheetBehavior.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/res/layout/fragment_timeline.xml
* Changes the way insets are applied in `ExpandingBottomSheetBehavior`.
* Hides the composer using `isVisible = false` instead of `isInvisible = true` in `MessageComposerFragment`.
* Also fixes a small issue with constraints in `fragment_timeline.xml`.
Fixes #7680 .
See the issue linked above.
To test the issue with the blank space:
- Open a room where you have no permission to post messages.
To test the issue with insets not being applied when coming back to the chat screen.
- Open a room.
- Open the keyboard by tapping on the composer.
- Open the settings screen for the room.
- Come back.
=> Rich Text Editor: fix several inset issues in room screen

changelog.d/7659.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt
Fix keyboard closing after collapsing rich text editor.
https://element-io.atlassian.net/browse/PSU-994
When enabling the full-screen mode of the rich text editor, the keyboard should be opened. However, when collapsing, the keyboard should not be closed if it is already open.
[expand-collapse-keyboard.webm](https://user-images.githubusercontent.com/4940864/204552865-3c8b12f9-4f45-40eb-8c1d-f59996d07450.webm)
1. Enable the rich text editor via labs
2. Navigate to a room
3. Expand the text input
4. *Check the keyboard is opened*
5. Collapse the text input
6. *Check the keyboard is closed*
=> [Rich text editor] Fix keyboard closing after collapsing rich text editor

changelog.d/7683.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewState.kt
- Handle a missing room safely when starting the message composer
- Hide the message composer UI when the room is missing
- Hide the voice recorder UI when the room is missing
This error was seen before but has been reintroduced during refactoring.
- see https://github.com/vector-im/element-android/pull/6978
|Before|After|
|-|-|
|N/A|![room-error-after](https://user-images.githubusercontent.com/4940864/205034569-de54a53c-f9cc-4e24-97d1-3a3e5c5d41f0.png)|
- Manually force `Session.getRoom()` to return null.
- Open a room
- Verify no crash and UI looks correct
- 
=> Fix crash in message composer when room is missing

changelog.d/7684.bugfix, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeAuthenticationService.kt
Invoke `checkQrCodeLoginCapability()` only after the homeserver url has been safely validated.
Fixes #7672 
- See #7672
=> Fix crash when invalid url is entered #7672

changelog.d/7694.feature, library/ui-strings/src/main/res/values/strings.xml, vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt, vector-config/src/main/java/im/vector/app/config/Config.kt, vector/src/main/java/im/vector/app/features/VectorFeatures.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/IsNewLoginAlertShownUseCase.kt, vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/SetNewLoginAlertShownUseCase.kt, vector/src/main/java/im/vector/app/features/home/SetUnverifiedSessionsAlertShownUseCase.kt, vector/src/main/java/im/vector/app/features/home/ShouldShowUnverifiedSessionsAlertUseCase.kt, vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/test/java/im/vector/app/features/home/ShouldShowUnverifiedSessionsAlertUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeVectorFeatures.kt, vector/src/test/java/im/vector/app/test/fakes/FakeVectorPreferences.kt
Currently, we never remind users about their unverified sessions once the alert banner is dismissed. We want to remind users to review unverified sessions in a certain period.
When we detect a new login on another device, we are showing a "New Login" banner on verified devices. If the user dismisses it we need to show "Review your logins" banners to the user. If the user dismisses this banner too, then we don't show a banner for a while (1 week in current config).
- Set `Config.SHOW_UNVERIFIED_SESSIONS_ALERT_AFTER_MILLIS = 60_000` for test purposes
- Have a verified session
- Login from another session
- See "New login" banner appears in verified device
- Dismiss the banner
- See "Review your logins" banner
- Dismiss the banner
- Wait 1 minute and see the banner again
=> Remind unverified sessions with a banner once a week (PSG-892)

changelog.d/7710.bugfix, vector/src/main/java/im/vector/app/core/ui/views/ShieldImageView.kt, vector/src/main/java/im/vector/app/features/settings/devices/DeviceItem.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionItem.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt
While we are developing new Session Management screens we introduced a new shield for devices which has an unknown e2e status. But this also accidentally effected the shield of rooms. This PR will revert these changes.
- Login with an unverified session
- Enable new session management in Labs settings
- Navigate to Settings > Security & Privacy > Show All Sessions
- See unknown shield ("?") for the current session 
- Navigate to an encrypted room details
- See black shield next to the room name instead of an unknown shield
=> Fix usage of unknown shield in room summary (PSG-1019)

changelog.d/7725.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/filter/GetCurrentFilterTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/filter/SaveFilterTask.kt
Uploading will be retried later.
Ignore errors when uploading the filter to the server. The SDK will not get a filterId, so will try to upload again later.
Fixes #7720
- Start the app in airplane mode and observe that there is no crash anymore.
=> Do not propagate failure if saving the filter server side fails

changelog.d/7723.misc, library/ui-strings/src/main/res/values/strings.xml, vector-app/build.gradle, vector-app/src/fdroid/java/im/vector/app/di/FlavorModule.kt, vector-app/src/gplay/java/im/vector/app/nightly/FirebaseNightlyProxy.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/NightlyProxy.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsAdvancedSettingsFragment.kt, vector/src/main/res/xml/vector_settings_advanced_settings.xml
sign in to firebase app inside the app does not work properly, so it is annoying to have a popup, even only once a day.
This PR disables the popup and add a section in the preference (Advanced settings), only visible in nightly builds, to be able to try to upgrade (and sign in) manually from there.
Do not annoy the user with a non-working feature.
|Sign in issue|New setting|
|-|-|
|<img width="324" alt="image" src="https://user-images.githubusercontent.com/3940906/205905086-3f9217a2-4674-4f1b-82fd-18810130210e.png">|<img width="321" alt="image" src="https://user-images.githubusercontent.com/3940906/205905145-5c4903b1-6ffe-483b-9c27-e229203b0622.png">|
- NA
=> Disable nightly popup

library/ui-strings/src/main/res/values/strings.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/RoomSummaryEventDecryptor.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/api/session/crypto/keysbackup/BackupUtils.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/OlmMachine.kt, vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageActivity.kt, vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationAction.kt, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewEvents.kt, vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationBottomSheet.kt, vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationFragment.kt, vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/verification/user/UserVerificationBottomSheet.kt, vector/src/main/java/im/vector/app/features/crypto/verification/user/UserVerificationViewModel.kt, vector/src/main/res/layout/fragment_ssss_reset_all.xml
- Implemented ResetAll for self verification.
- Skip option is enabled for self verification.
- Fixed back navigation with SharedSecureStorage.
Part of element-r refactor alignment with web.
- Login to an account in Element-android
- Start self verification, Click on "Forgot or lost all recovery options".
- It should work as before.
=> Enable reset all and skip options

changelog.d/7708.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/SendToDeviceTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/CryptoSyncHandler.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/crypto/DefaultSendToDeviceTaskTest.kt
Fixes #7708
Adding a tracing id to to-device messages that can be tracked synapse side in order to debug to-device delivery problems.
EA logs on reception updated to match web
```
received to-device m.room_key from:@sample:localhost:8480 id:b62c9f76-880d-4fbe-b9d7-f9b13c957d8d
```
EA logs on sending updated to match web
```
I  Sent to device  type=m.room.encrypted txnid=d99afdf1-b244-478b-bd72-eba892419893 [@eve:localhost:8480/YJQWVBZUWC (msgid 21ba49f2-8be0-440f-9c22-ba6e41a0d83c),@eve:localhost:8480/PMFTXZAUTL (msgid 58cd9624-137a-4c05-b5da-1a9e587364ef),@web:localhost:8481/FJQUOWZCIX (msgid f854cc8e-603f-48d5-953c-1ed1864b91cd)]
I  shareUserDevicesKey() : sendToDevice succeeds after 158 ms
```
Decorated content from sync:
```
{
"content": {
"algorithm": "m.olm.v1.curve25519-aes-sha2", …
```
=> add to device tracing id

changelog.d/7697.feature, vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesViewNavigator.kt, vector/src/main/res/menu/menu_current_session_header.xml, vector/src/test/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesViewNavigatorTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsViewNavigatorTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewViewNavigatorTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeContext.kt
Adding 2 actions in the overflow menu of the current session card view in the new main session manager screen:
- rename current session
- signout current session
Closes #7697 
- Enable the new Session manager in labs settings
- Press the menu in the current session card view
- Check actions to rename and sign out the session are present
- Press the rename item
- Check the rename screen is opened for the current session
- Rename the session
- Check it updates the name of the session
- Press the menu in the current session card view
- Press the sign out item
- Check a confirm dialog is displayed
- Confirm
- Check the current session is signed out 
=> [Session manager] Add actions to rename and signout current session (PSG-885)

changelog.d/7643.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
currently we are listening to update in temeline events and request epoxy to build models even when app is on background. This triggers RR to be sent for this messages, while user actually haven't seen them yet. 
In this PR adapter is removed on pause and set back on resume to not trigger visibility listener 
closes #7643
- Open any room
- Put app on background
- Receive push notification for message in this room
- Notification should not be dismissed shortly after it was shown
=> stop listening timeline collection changes when app is not resumed

changelog.d/7733.bugfix, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/core/ui/views/ShieldImageView.kt, vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DeviceFullInfo.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCase.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCaseTest.kt
Render a specific UI in session manager screens (main screen and session overview screen) when a session does not support encryption.
Closes #7733 
See also https://github.com/vector-im/element-web/issues/23722
For my tests, I mocked locally the data (setting the `CryptoDeviceInfo` to `null`)
- Enable new Session manager labs flag
- Go to "Settings -> Security & Privacy -> Show all sessions"
- Check the UI for the current session is correct
- Press a session entry in the other sessions list which does support encryption
- Check the UI for the session overview screen is correct
- Press "Learn more"
- Check the displayed text is correct
=> [Session manager] Sessions without encryption support should not prompt to verify (PSG-1004)

changelog.d/7751.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StartLiveLocationShareTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/location/StopLiveLocationShareTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/PollEventsTestData.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultGetActiveBeaconInfoForUserTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStartLiveLocationShareTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultStopLiveLocationShareTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/LiveLocationShareRedactionEventProcessorTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeCreatePollViewStates.kt
Change usage of stable fields to the unstable ones in live location share and polls events.
Closes #7751 
- Check live location share is working correctly in a room
- Check creation of polls is working correctly in a room
=> Revert usage of stable fields in live location sharing and polls

changelog.d/7743.bugfix, vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt, vector/src/main/java/im/vector/app/features/popup/VectorAlert.kt, vector/src/main/java/im/vector/app/features/popup/VerificationVectorAlert.kt
Fix an issue about the display priority of popup alerts when there is an incoming verification request. Priority of the incoming verification requests alert has been raised and any existing alerts about verification of sessions are canceled when a new request arrives.
Closes #7743 
- Open a verified session on device A (can be any client: web, Android, iOS)
- Login to a new session in the Android app (device B)
- When landing in the home screen, see there is a popup displayed to ask to verify the session
- From device A, request a verification on the new session on device B
- Check the popup for the incoming request is displayed on device B
- Tap the popup
- Check the verification flow is started
- Check there is no popup to ask to verify the session on device B
- OS version(s): Android …
=> Verification request is not showing when verify session popup is displayed (PSG-1017)

changelog.d/7691.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerMode.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt
Store the current `MessageComposerMode` so we can diff and avoid unnecessary updates. 
Also, only change some layout params for the editor if we don't want to animate the full screen change (keeps compatibility with both Element Android and Element X).
Element X stopped properly responding to input as the `renderComposerMode` method was being triggered for each change (on Element Android this is not so noticeable). It also had some issues with resizing the editor properly.
As both apps share most of this code, it's better to also handle it properly here.
It's quite difficult to test, as it wasn't a noticeable issue in Element Android.
- Enable the Rich Text Editor in Labs.
- Open a room.
- Select a message and edit or quote it, or reply to it.
- Exit the editing/replying/quoting mode. …
=> Rich text editor: improve performance when changing composer mode

changelog.d/7737.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/LoginFlowResult.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt, vector/src/main/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCase.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/features/onboarding/StartAuthenticationFlowUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeAuthenticationService.kt
Refactor of logic to determine whether sign in with QR is available so that it interacts with base URL resolved from well-known.
Previously the logic to determine if sign in with QR is supported was based on fetching the `versions`  directly from the actual user input of the homeserver.
However, this doesn't work when the user input needs to be resolved to a new base URL using well-known.
To demonstrate:
- enter `element.io` and no QR is offered
- enter `element.ems.host` and QR is offered
I've used the existing pattern from `SelectedHomeserverState`.
- Tap `I already have an account`
- Press `Edit` next to homeserver
- Enter `element.io`
- Press `Next`
- The scan QR button should show
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
=> Determine availability of QR sign in from resolved homeserver

changelog.d/7770.bugfix, vector/src/main/java/im/vector/app/features/home/room/threads/ThreadsActivity.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt, vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt
Currently when user presses on a push notification for a threaded message they are navigated to a room instead of a thread timeline
closes #7770 
- Step 1
- Step 2
- Step ...
=> thread message notification should navigate to thread timeline

changelog.d/5503.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixConfiguration.kt, vector-config/src/main/res/values/config-settings.xml, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/java/im/vector/app/features/settings/labs/VectorSettingsLabsFragment.kt
we want to enable threads by default and force to be enabled for existing users, but still let users disable it via labs flag
closes #5503 
- Step 1
- Step 2
- Step ...
=> threads are enabled by default end forced to enabled for existing users

changelog.d/7753.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessorTest.kt
Retrieve the related event id in poll end event using the dedicated `getRelationContent()` method to avoid misssing aggregation of this event.
Closes #7753 
- Create a poll (open or closed) in a room from Web using account A
- Vote from web using account A
- Close the poll using account A
- Open the room from Android app using account B
- Check the poll is considered as ended and result is visible even if account B did not vote
=> [Poll] Poll end event is not recognized (PSG-948 and PSG-949)

changelog.d/7767.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/EventDecryptor.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/FetchEditHistoryTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/poll/FetchPollResponseEventsTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/threads/FetchThreadTimelineTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/GetEventTask.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessorTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/relation/poll/DefaultFetchPollResponseEventsTaskTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeEventDecryptor.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeFetchPollResponseEventsTask.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeRealm.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/test/fakes/FakeRoomApi.kt
When receiving a poll end event, the /relations API is used to fetch all related events so that we ensure to aggregate all the poll responses for this poll. It is performed so that correct results are displayed to the user.
Closes #7767 
- Create a poll
- Vote from different users
- End the poll
- Check the results of the poll are correct
- Check with flipper correct network calls are done on end poll event reception
=> [Poll] When a poll is ended, use /relations API to ensure poll results are correct (PSG-1013)

changelog.d/7797.feature, vector/src/main/res/layout/fragment_other_sessions.xml
In the other sessions list screen, making the header as collapsable so that it gives more place to the list.
Closes #7797 
- Enable the labs setting for the new session manager
- Press the View All button in the Other sessions section (need more than 5 other sessions)
- Check the scrolling behavior of the list and the header with the different filter options
=> [Session manager] Other sessions list: header should not be sticky (PSG-1115)

changelog.d/7795.feature, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SecurityRecommendationView.kt, vector/src/main/res/layout/view_security_recommendation.xml
In the session manager main screen, making the whole security recommendation card as tappable (same action as the "View All" button).
Closes #7795 
- Enable the labs setting for the new session manager
- Check you can press either the View All button or the whole card on the security recommendations cards. They should appear when there are either inactive or unverified sessions.
=> [Session manager] Security recommendations cards: whole view should be tappable (PSG-1117)

changelog.d/7784.bugfix, vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsFragment.kt
In the other session list screen in session manager, hiding the filter option in the top bar when the selection mode is enabled.
Closes #7784 
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/46314705/208381768-817baa20-b186-4624-9ed3-07b28838e1ce.png" width=300 />|<img src="https://user-images.githubusercontent.com/46314705/207831407-c60213de-1416-48f1-bab2-db82546feb8a.png" width=300 />|
- Enable the new session manager labs setting
- Press "View All" button in the other sessions section (need more than 5 other sessions)
- Select one session
- Check the filter icon is not displayed
- Leave the selection mode
- Check the filter icon is displayed
=> [Session manager] Other sessions list: filter option is displayed when selection mode is enabled (PSG-1113)

changelog.d/7794.bugfix, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoViewState.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/SessionOverviewFragment.kt
We had a bug on current session details screen. Even if user selects "Show IP address" menu item it is not shown because we accidentally depend it to "last activity time" flag. This PR solves the problem by separating activity and ip address flags. 
Fix UX review remarks.
- Enable new session manager from Labs settings
- Navigate to Settings > Security & Privacy -> Show all sessions
- Select "view session details" on current session card
- Select "Show/Hide IP address" menu item
=> Fix current session ip address visibility (PSG-1109)

changelog.d/7786.bugfix, vector/src/main/res/layout/bottom_sheet_device_manager_filter.xml
In the other sessions list screen, making content of bottom sheet to set the filtering option as scrollable.
Closes #7786 
Use a small device (e.g 3.7'')
- Enable the new session manager labs setting
- Press the View all button in the other sessions section (need more than 5 other sessions)
- Put the phone in landscape mode
- Press the filter option in the top app bar
- Check you can scroll the content to see and select the different options
=> [Session manager] Other sessions: Filter bottom sheet cut in landscape mode (PSG-1107)

changelog.d/7792.bugfix, vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsFragment.kt
In the other sessions list screen, when long pressing a session item, toggle selection of this item even in selection mode.
Closes #7792 
- Enable the labs setting for new session manager
- Press the View all button in the other sessions list (need more than 5 other sessions)
- Long press one session to enable the selection mode
- Long press another session
- Check it select this other session
- Long press a selected session
- Check it un-select the pressed session
=> [Session Manager] Other sessions list: cannot select/deselect session by a long press when in select mode (PSG-1111)

changelog.d/2965.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomTypingUsersHandler.kt
Filter out ignored user from typing events. Also did a small optimization in a separate commit.
See #2965 (this PR does not close it)
- Ignore a user you share a room with
- When the ignored user is typing in the room, this is not shown in the timeline
=> No typing for ignored user

changelog.d/7475.bugfix, vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
Currently reply to push notification of threaded messages goes to main timeline instead of thread
closes #7475 
- Step 1
- Step 2
- Step ...
=> reply to threaded push notification now sent to thread 

changelog.d/7821.misc, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastListeningItem.kt, vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml
=> Replace the player timeline

vector-app/src/androidTest/java/im/vector/app/EspressoExt.kt, vector-app/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceCreateRobot.kt, vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceMenuRobot.kt
UI tests failing for several reasons:
- Threads are enabled by default now, so existing test was toggling off before running the tests
- Was testing some (old) feature on spaces where the bottom sheet to invite was shown on first enter room
- Flackiness with the space bottomsheet chooser (was ok when in drawerà
=> FIx UI Tests

changelog.d/5546.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimelineService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/TimelineEventDecorator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/UiEchoDecorator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/UpdatedReplyDecorator.kt
#5546 
- Step 1
- Step 2
- Step ...
=> Fix: ISSUE-5546: replyTo are not updated if the original message is edited 

gradle.properties, vector/src/main/java/im/vector/app/features/home/NotificationPermissionManager.kt, vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestSystemSettings.kt
Using gradle flag to set lint version to a more recent one than the one bundled with AGP version.
With the current version (7.3.1) there are many false positives reported by Lint.
N/A
- Run `./gradlew vector-app:lintGplayRelease`
- Check there are no errors reported by the analysis
N/A
=> Update to latest version of Lint (8.0.0-alpha10)

changelog.d/7853.bugfix, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/DevicesViewState.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/GetDeviceFullInfoListUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/filter/FilterDevicesUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/CheckIfSessionIsInactiveUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionsController.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/list/SessionInfoView.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/overview/GetDeviceFullInfoUseCase.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/DevicesViewModelTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/filter/FilterDevicesUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/list/CheckIfSessionIsInactiveUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/devices/v2/overview/GetDeviceFullInfoUseCaseTest.kt
Fixing small issues in session manager mainly about session which does not support encryption (it might happen for very old sessions).
Closes #7853 
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/46314705/209790375-596f3f38-8911-4793-9edf-28b14843d882.png" width=300 />|<img src="https://user-images.githubusercontent.com/46314705/209789585-2aac9ade-6ac3-4049-b6d4-bfeafcfba3c0.png" width=300 />|
|<img src="https://user-images.githubusercontent.com/46314705/209790368-e765fc81-8ec9-430a-b1fa-96b8b715bec4.png" width=300 />|<img src="https://user-images.githubusercontent.com/46314705/209789580-3207b889-7a7d-46f1-a5fe-be4a56acf71f.png" width=300 />|
|<img src="https://user-images.githubusercontent.com/46314705/209790372-23f111bd-01d8-40a9-bbf4-715ffbf9cb93.png" …
=> [Session manager] Missing info when a session does not support encryption (PSG-1074)

changelog.d/7899.bugfix, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
Fix voice broadcast stuck in buffering if there is no last sequence number in the state event (app restart, bad event format).
Also, stop buffering if the current chunk number is higher than the last sequence number (should not happen)
Fix issue with buffering
- Start recording a VB on device A
- Wait for several chunks to be sent
- Listen to the VB on device B (optional)
- Restart the app on device A -> VB will be automatically stopped
- Verify that the listening is automatically stopped when reaching the last chunk
=> [Voice Broadcast] Stop listening if we reach the last received chunk and there is no last sequence number

changelog.d/7879.bugfix, library/ui-strings/src/main/res/values/strings.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/crosssigning/CryptoCrossSigningKeys.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/crosssigning/UserIdentity.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DeviceListManager.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/IMXCryptoStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/UserDataToStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/CryptoStoreAggregator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/Helper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/StreamEventsManager.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateLocalRoomTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponsePostTreatmentAggregator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/CryptoSyncHandler.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/RoomSyncHandler.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsAdvancedSettingsFragment.kt, vector/src/main/res/xml/vector_settings_advanced_settings.xml
Batch crypto database writing to avoid multiple transactions which takes about 100ms each.
See commit per commit for the changes.
On my main Matrix account (~600 rooms) an initial sync (clear cache, so with non-empty crypto DB) was taking 8 minutes, with this change, it's only 1 minutes and 40 seconds. With a fake crypto store, it's only 30 seconds, but I do not want to dig more since this code will be replaced soon.
This PR also add a way to copy the access token to the clipboard.
Changing the way data is inserted in the Crypto database may have some side effect. Can you check that @BillCarsonFr ?
Improve perf of the app and SDK.
- Perform initial sync.
=> Reduce number of crypto database transactions when handling the sync response

changelog.d/7724.bugfix, vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt, vector/src/main/java/im/vector/app/core/platform/VectorBaseBottomSheetDialogFragment.kt, vector/src/main/java/im/vector/app/core/platform/VectorBaseDialogFragment.kt, vector/src/main/java/im/vector/app/core/platform/VectorBaseFragment.kt, vector/src/main/java/im/vector/app/core/platform/VectorViewModel.kt, vector/src/main/java/im/vector/app/core/utils/SharedEvent.kt, vector/src/main/java/im/vector/app/features/MainActivity.kt, vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageActivity.kt, vector/src/main/java/im/vector/app/features/media/VectorAttachmentViewerActivity.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsBaseFragment.kt, vector/src/test/java/im/vector/app/test/Extensions.kt
Observe ViewEvents only when the lifecycle is in the RESUMED state.
Closes #7722. `launchWhenResumed` is never used when observing flow, so there is no change to do on that.
- Step 1
- Step 2
- Step ...
=> Observe ViewEvents only when resumed

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/SerializeNulls.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/interceptors/FormattedJsonHttpLogger.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/parsing/CheckNumberType.kt, tools/lint/lint.xml, vector/src/main/java/im/vector/app/core/resources/StringArrayProvider.kt, vector/src/main/java/im/vector/app/core/resources/StringProvider.kt
Sometimes lint reports false positives. I do not want to ignore the corresponding rules, instead I have added a baseline with all the false positive so that they are ignore now.
This is a temporary solution, but I do not know why lint is changing behavior. AGP version hasn't been changed recently (7.3.1).
This is a recurring issue though...
=> Fix lint false positive

tools/release/releaseScript.sh
Small improvement on the release script.
=> Release script update

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/GetPushRulesResponse.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/SavePushRulesTask.kt
Remove unused field, see https://github.com/matrix-org/synapse/issues/12482
It's worth noting that if removed from the server response, the existing code will not crash since a default value was assign to `device`.
Be spec compliant.
NA
Code compiles.
NA
=> Remove the "device" field from get `/pushrules` response model.

vector/src/main/java/im/vector/app/core/utils/SharedEvent.kt
https://github.com/vector-im/element-android/pull/7724 introduced a regression, especially on the login screen.
In case of error, a ViewEvent can be triggered. But next Fragment to be displayed will also handle this Event, which is not expected.
The change in this PR ensure that Event older than 150ms cannot be handled.
Navigation Event triggered when the app is in background can be ignored due to this change, but this is an edge case, and we do not want to do a bigger rework of this part on the code base right now, and fixing the issue is more important.
Mainly avoid displaying several time the same issue during the sign up / sign in flow.
- Step 1
- Step 2
- Step ...
=> View event replay

changelog.d/7111.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/login/DefaultLoginWizard.kt, vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
Add trim to username input when sign-in on the app side and SDK side.
When the user inputs the username string, trailing whitespace can be added due to the autocomplete.
This issue can be solved by just warning about invalid characters like discussed in #7111
But This can lead to unnecessary user actions like deleting unnecessary whitespace.
So I add trim logic to the username's input so that the user's additional action is not needed.
Closes #7111 
No UI changes
- Step 1
- Step 2
- Step ...
- OS version(s): OS12
=> Add trim to username input when sign-in

changelog.d/7930.feature, dependencies.gradle, library/ui-styles/src/main/res/values/styles_edit_text.xml, vector/src/main/res/layout/composer_rich_text_layout.xml
Update the list item bullet appearance in the rich text editor.
[`PSU-1063`](https://element-io.atlassian.net/browse/PSU-1063)
|Before|After|
|-|-|
|![bullet-before](https://user-images.githubusercontent.com/4940864/211568116-56334b79-0956-4fd2-8569-6a5489266c19.png)|![bullet-after](https://user-images.githubusercontent.com/4940864/211564847-7da25adc-54e3-489a-a3d1-5f020ae06413.png)|
- Enable the rich text editor in labs
- Start typing a message
- Tap the bullet list button
- _Note the appearance of the bullets_
=> [Rich text editor] Update list item bullet appearance

changelog.d/7845.wip, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt, vector/src/main/java/im/vector/app/features/notifications/FilteredEventDetector.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
During the handling of the notifications, notify only the first voice chunk of a voice broadcast, and ignore the other events related to the voice broadcast chunks
Close #7845 
https://user-images.githubusercontent.com/11990514/212134974-33339bae-49ca-40d7-b801-c58ee13231a2.mp4
- Enable all notifications on Android device
- Start a voice broadcast from another device
- Pause or wait 2 min to send a chunk
- Verify that a voice broadcast notification appears on Android device
- Resume & Pause again the VB or wait for a second chunk
- Verify that there is no new notification
- Verify that the other notifications (text or simple voice message) are still working
=> Voice Broadcast - only send a notification on the first chunk

changelog.d/4025.bugfix, vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheet.kt
Verification bottom sheet was not cancellable when tapping outside of it. The only way was to click skip and answer are you sure bottom sheet. And users report that verification process can be stuck and there is no way to dismiss the bottom sheet.
Fixes #4025.
- Login from another device
- Relaunch Android application
- See the "New login" alert, tap on it
- See the verification bottom sheet is shown
- Tap outside of the bottom sheet and see it is dismissed and process is cancelled
=> Make verification bottom sheet cancellable on tap outside (PSG-1139)

changelog.d/7962.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/SendingEventsDataSource.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineChunk.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/UiEchoDecorator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
This PR fixes 2 abusive memory usage issues:
- First one (4c06bdc14e0c72d77b601e06c5906598e19d642b) is regarding the settings of a click listener on MenuItem, which was creating Job each time the Fragment in invalidated. But previous Job was not cancelled. Replacing by simple `setOnClickListener` fixes the issue.
- Second one (0b5e0fea72e08a9986631869f2c6f2e913d5ac35) is regarding frozen Realm objects. When Realm object are frozen, further Realm transactions consumes more memory. It was useless to freeze empty list, and non empty list are temporary, since this is for sending Events, so it's still OK to freeze them.
Other commits are just cleanup.
Application stability
- Open a room.
- Observe application memory usage, or wait for the app to crash.
It can be speed up by setting timeout for …
=> Fix oom crashes.

changelog.d/7929.misc, vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml
=> Tapping slightly left or right of the 30s buttons highlights the whole cell instead of registering as button presses

changelog.d/7807.misc, vector/src/main/java/im/vector/app/core/extensions/TimelineEvent.kt
=> Support reactions on Voice Broadcast

changelog.d/7895.bugfix, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/voice/VoiceRecorderFragment.kt, vector/src/main/java/im/vector/app/features/voice/VoiceFailure.kt
=> Send voice message should not be allowed during a voice broadcast recording

changelog.d/7830.misc, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
=> Pause voice broadcast listening on new VB recording

changelog.d/7961.bugfix, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
Fix voice broadcast listening not starting from the saved position.
Fix #7961 
- Move the cursor of the seek bar of a voice broadcast
- Press the play button
- Then the playback should be started from the cursor position
=> Voice Broadcast - Fix playback scrubbing not working if playback is stopped

changelog.d/7979.misc, vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/VoiceBroadcastFailure.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/VoiceBroadcastPlayerImpl.kt
- Rework internal media player coordination:
Fix multiple media player created in the same time
Properly cancel and release media player in preparation if needed 
- Remove some legacy code related to the live listening (we don't need to check anymore the playback position)
- Fix playback restart handling
Prevent potential media player leaked and improve voice broadcast playback
- Play voice broadcasts (live & ended)
- Change the current voice broadcast in the fly, play with the buttons
=> Voice Broadcast - Rework internal media players coordination

changelog.d/7890.feature, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceBroadcastRecordingItem.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorder.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/VoiceBroadcastRecorderQ.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/PauseVoiceBroadcastUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/recording/usecase/StartVoiceBroadcastUseCase.kt, vector/src/main/res/layout/item_timeline_event_voice_broadcast_listening_stub.xml, vector/src/main/res/layout/item_timeline_event_voice_broadcast_recording_stub.xml, vector/src/test/java/im/vector/app/features/voicebroadcast/usecase/StartVoiceBroadcastUseCaseTest.kt
Handle the connection errors during a voice broadcast by pausing the recorder and sending the pause state event when the network is back.
Also fixed some layout issues on voice broadcast tiles
Close #7890 
- Start a VB
- Turn off mobile data & wifi
- Then an error message about the connection status should be displayed in the VB tile with no controls available.
- Turn on the network, then the VB is correctly paused, controls are available and the previous chunk should be sent.
- We can then resume and stop the VB.
=> Pause voice broadcast if there is no network

vector/src/main/res/layout/fragment_room_widget.xml
Target branch is `feature/ons/ptt_bluetooth`
Fix touch events passing through bluetooth bottom sheet.
Prevents accidental touching of the push-to-talk button underneath.
- Fixes https://github.com/matrix-org/element-android-rageshakes/issues/48981
- Fixes https://github.com/matrix-org/element-android-rageshakes/issues/48901
N/A
- Start the push-to-talk POC (see https://github.com/vector-im/element-android/pull/6464)
- Open the bluetooth bottom sheet using the toolbar action button
- Tap inside the bottom sheet above where the element call walkie-talkie button is
- Observe the button is not toggled
=> [PTT] Fix element call UI touchable through bottom sheet

changelog.d/7967.feature, changelog.d/7988.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/homeserver/HomeServerCapabilities.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/SendService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/RedactEventTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/HomeServerCapabilitiesMapper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/migration/MigrateSessionTo049.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/HomeServerCapabilitiesEntity.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/homeserver/GetHomeServerCapabilitiesTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventRedactBody.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/RedactEventWorker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/model/EventRedactBody.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessor.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorCoroutine.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/QueueMemento.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/QueuedTaskFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/RedactQueuedTask.kt, vector/src/main/java/im/vector/app/core/extensions/TimelineEvent.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/model/VoiceBroadcastEvent.kt
=> Implement MSC3912 to delete server side all the data of a deleted voice broadcast

vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/features/widgets/WidgetActivity.kt
Note the target branch is the push-to-talk POC (`feature/ons/ptt_bluetooth`)
Start Element Call widget in it's own task.
- So that the push-to-talk call POC can continue running either in the background or in picture-in-picture mode while sending messages to the room.
- So that pressing back from the home screen does not end the ongoing call or bluetooth connection.
N/A
- Start a push-to-talk call (see https://github.com/vector-im/element-android/pull/6464)
- Put the call into PiP or background
- Go to recent apps
- _Note there are two separate tasks: one for the room and one for the call_
- Navigate to the room task
- Press back until you see the home screen
- _Note the call is still running (given the Activity has not been destroyed by the OS)_
- OS version(s): Android 13, Android 11
=> [PTT] Start Element Call widget in its own task

changelog.d/8005.sdk, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/UpdatePushRuleActionsTask.kt
When updating a push rule, calling the /actions endpoint first before calling the /enabled endpoint
Closes #8005 
N/A
- Go into Settings -> Notifications -> Default notifications
- Toggle some setting and check the notifications behavior is correct
=> [Push rules] Call /actions api before /enabled api (PSG-1099)

changelog.d/8031.bugfix, vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt, vector/src/test/java/im/vector/app/features/analytics/impl/DefaultVectorAnalyticsTest.kt
Ensure we never call `posthog.identify` if user did not consent, because it sends request `<server>/decide/?v=2` to the analytic server.
Despite the fact that `posthog.optout(true)` has been called and no analytics is sent when the user has opt-out, calling `posthog.identify` trigger a request to the analytics server. We may consider this as a bug in the library itself, but in the mean time, this PR prevent calling `posthog.identify` is user consent is not set to `true`.
Closes #8020 
- Add a breakpoint to `Posthog::identify` and ensure that it's never called when analytics consent is not provided, for instance when the application is started.
- Breakpoints can also be put in `com.posthog.android.ConnectionFactory`.
=> Do not send any request to Posthog if no consent is provided.

changelog.d/8042.misc, vector/src/main/java/im/vector/app/features/home/room/list/usecase/GetLatestPreviewableEventUseCase.kt, vector/src/main/java/im/vector/app/features/voicebroadcast/listening/usecase/GetLiveVoiceBroadcastChunksUseCase.kt, vector/src/test/java/im/vector/app/features/home/room/list/usecase/GetLatestPreviewableEventUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeVectorPreferences.kt
- The computation of the `Live broadcast` label in the room list is moved behind the voice broadcast lab flag. This is a temporary workaround before changing the current implementation.
- Improve existing use case by removing a useless blocking call on a Kotlin Flow. 
The computation of the `Live broadcast` label introduced performance issues in the rendering of the room list because it requires a lot of DB queries as this cannot be done at the sdk level by updating the RoomSummaryEntity.
- Start a voice broadcast in a room
- Verify that the `live broadcast` label is displayed or not in the room list according to the lab flag status
=> [Voice Broadcast] Move the live broadcast computation in the room list behind the lab flag

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/summary/RoomSummaryConstants.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoRepository.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCase.kt, vector/src/test/java/im/vector/app/features/home/room/detail/timeline/render/ProcessBodyOfReplyToEventUseCaseTest.kt, vector/src/test/java/im/vector/app/features/poll/create/CreatePollViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeTimelineService.kt
We recently started to render a message when a poll is ended and users are able to reply ended polls. We need to render poll question for ended poll messages.
Instead of rendering "In reply to ended poll" we will render "In reply to {poll_question}"
- Create a poll
- End a poll
- Reply to the ended poll message
- See the replied message is rendered by including the poll question
=> Show poll question when rendering reply to a poll end event (PSG-1133)

changelog.d/5918.bugfix, vector/src/main/java/im/vector/app/core/utils/FileUtils.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
Compute cache storage in background.
Closes #5918 
Also reported in FOSDEM.
- Open the general setting with a big cache. For test add a delay to simulate a long computation and see that the screen is opened and `Loading...` is displayed in the preference summary.
=> Open general settings performance

changelog.d/7801.bugfix, library/ui-styles/src/main/res/values/styles_edit_text.xml, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt
- Hides the container for the rich text menu instead of the rich text menu instead. This should prevent the invisible `HorizontalScrollView` from overlapping with the `EditText` and intercepting touch events.
- Also removes a `minHeight` value from styles that's no longer needed.
Fixes #7801 .
- Enable the Rich Text Editor in `Settings > Labs`.
- Open a room.
- Tap on the `+` icon, disable 'Text formatting' option at the bottom.
- Write some text (it's even better if it has several lines) and then try to select any point of it.
=> Fix: cannot select text in plain text mode in Rich Text Editor

changelog.d/7928.bugfix, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt
Fix the next button disabled issue after going to change homeserver screen.
The initial emission of flow is an empty string when coming back after visiting homeserver screen.
Because at that time(```onViewCreated```) the view's state is not restored yet.
Collecting flow after ```onViewStateRestored``` can be the one way to solve this problem.
So ```flowWithLifecycle()``` is added to collect flow after ```onViewStateRestored``` is called.
Fix #7928 
|Before|After|
|-|-|
|<video src="https://user-images.githubusercontent.com/39683194/217267533-0564ba09-f107-4a2c-8872-dcf361225de4.mp4" />|<video src="https://user-images.githubusercontent.com/39683194/217267763-681c30e0-8060-4c53-986c-dd3565c53025.mp4" />|
-->
Same steps as mentioned in the issue #7928
- OS version(s): API 33 …
=> Fix the next button disable issue after visiting homeserver screen

changelog.d/8127.bugfix, library/core-utils/src/main/java/im/vector/lib/core/utils/timer/CountUpTimer.kt, library/core-utils/src/test/java/im/vector/lib/core/utils/timer/CountUpTimerTest.kt
Verify if the timer is still running before calling the stop or pause action and triggering a new tick event
Fix a regression introduced by #8058 
- Record a voice message
- Listen to the voice message until the end
- The timer should be correctly stopped and reset, the app should not freeze anymore
=> Fix StackOverFlow exception when stop action is called within the tick event

changelog.d/8115.misc, library/ui-strings/src/main/res/values/strings.xml
Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>
This PR replace `Bots` with `bots` to help translators choose an existing translation, if any. Please note that localized keys are case sensitive on Weblate:
- https://translate.element.io/translate/element-web/matrix-react-sdk/en/?checksum=da6abfa2f95bf3c
- https://translate.element.io/translate/element-android/element-app/en/?checksum=87ef32a0d2e7c642
Create a Weblate account to see the difference, if you do not have one yet.
1. Let translators reuse an existing translation, if any
2. Make translation consistent among projects
=> Replace 'Use Bots' with 'Use bots' for localization experience on Weblate

changelog.d/8139.misc, library/core-utils/src/main/java/im/vector/lib/core/utils/timer/CountUpTimer.kt
Fixed a ktlint issue about a field with a comment being right below another one with no extra line breaks.
Fix ktlint issue in `develop` branch mentioned in #8138.
The quality workflow of the CI should pass now.
=> Fix ktlint issue that was accidentally merged

changelog.d/6121.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessor.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/aggregation/poll/DefaultPollAggregationProcessorTest.kt
Fixing issue about poll votes aggregation: taking the poll response events into account even if the related poll start event has not been synced yet.
Closes #6121 
- Go to a room with polls and many users (e.g. https://matrix.to/#/#archlinux:archlinux.org)
- Go to the poll history list
- After some polls have been loaded, check the number of votes is correct
=> [Poll] Fix votes aggregation process (PSG-1153)

changelog.d/8130.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/pushrules/RuleIds.kt, vector/src/main/java/im/vector/app/core/notification/PushRulesUpdater.kt, vector/src/main/java/im/vector/app/core/session/ConfigureAndStartSessionUseCase.kt, vector/src/main/java/im/vector/app/features/settings/notifications/RuleIdsExt.kt, vector/src/main/java/im/vector/app/features/settings/notifications/VectorSettingsPushRuleNotificationViewModel.kt, vector/src/main/java/im/vector/app/features/settings/notifications/usecase/UpdatePushRulesIfNeededUseCase.kt, vector/src/test/java/im/vector/app/core/session/ConfigureAndStartSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/notifications/usecase/DisableNotificationsForCurrentSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/notifications/usecase/EnableNotificationsForCurrentSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/notifications/usecase/ToggleNotificationsForCurrentSessionUseCaseTest.kt, vector/src/test/java/im/vector/app/features/settings/notifications/usecase/UpdatePushRulesIfNeededUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakePushRulesUpdater.kt
Add an observer on the push rule updates in the account data and realign the push rules with their parent if needed.
#8114 introduces the new push rules in the notification settings. The new rules should be aligned with their parent rules as described in the following table:
The purpose of this PR is to verify and fix if necessary the consistency of the new rules with their parent when changes are detected in the account data.
- Manually change and break the poll rules in the account data using the devtools on the web interface
- Verify that the Android client automatically realign the rules with the parent one (by refreshing the account data after an incremental sync)
=> [Poll] Synchronize polls and message push rules after creation (PSG-1137)

changelog.d/8129.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageEndPollContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/PollItem.kt, vector/src/main/res/layout/item_timeline_event_poll.xml
Add a special rendering for the message when receiving a poll End event while the related poll start is not available in the timeline.
Send a fallback text in the poll end event (may be needed by other Matrix clients).
Closes #8129
- Create a new room
- Set the setting in the room so that new joiners cannot see the history
- Create a poll
- Invite another user
- Wait for the user to join
- End the previously created poll
- Check the other user sees a simple "Poll ended" message without any other info
=> [Poll] Improve rendering of poll end message when poll start event isn't available (PSG-1157)

changelog.d/8110.feature, library/core-utils/src/main/java/im/vector/lib/core/utils/timer/CountUpTimer.kt, vector/src/main/java/im/vector/app/features/location/LocationDialog.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingFragment.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingViewState.kt, vector/src/main/java/im/vector/app/features/location/LocationTracker.kt, vector/src/main/java/im/vector/app/features/location/MapState.kt, vector/src/main/java/im/vector/app/features/location/MapTilerMapView.kt, vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapAction.kt, vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewEvents.kt, vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewFragment.kt, vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewModel.kt, vector/src/main/java/im/vector/app/features/location/live/map/LiveLocationMapViewState.kt, vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewFragment.kt, vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewViewEvents.kt, vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewViewModel.kt, vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewViewState.kt, vector/src/main/res/drawable/ic_location_user.xml, vector/src/main/res/layout/fragment_live_location_map_view.xml, vector/src/main/res/layout/fragment_location_preview.xml, vector/src/test/java/im/vector/app/features/location/live/map/LiveLocationMapViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeLocationTracker.kt
Adding locate button in the expanded map views when looking at static or live location sharing.
Closes #8110 
Static location share
Live location share
- Open a static location share message
- Check a locate button is displayed on the map
- Press the locate button
- Check the map is centered on the current user location
- Open a running live location share message
- Check a locate button is displayed on the map (only when current user is not live sharing their location)
- Press the locate button
- Check the map is centered on the current user location
=> [Location sharing] Show own location in map views

changelog.d/8090.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Fix #8090 
The regression came from this https://github.com/vector-im/element-android/pull/7734 
I've checked it was still fixing the related notification issue ^
=> Fix always jumps to the bottom of the timeline #8090

changelog.d/8150.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
When getting the last edited content for a reply, we ensure there is a formatted body so that it is still considered as a reply in the timeline.
According to [Matrix specification](https://spec.matrix.org/v1.4/client-server-api/#applying-mnew_content) the formatted body is not mandatory so we should cover missing formatted body cases.
Closes #8150 
- From iOS client, send a reply to a message
- From iOS client, edit the reply
- Check in Android client, the message is well rendered in the timeline
=> [Timeline]: Editing a reply from iOS breaks the "in reply to" rendering (PSG-1168)

changelog.d/7989.bugfix, vector/src/main/java/im/vector/app/features/settings/VectorSettingsPreferencesFragment.kt
Display the "Space" category setting when in old app layout.
Closes #7989 
- Enable the new app layout in the labs settings
- Go to Settings -> Preferences
- Check the "Space" category setting is not displayed
- Disable the new app layout in the labs settings
- Go to Settings -> Preferences
- Check the "Space" category setting is displayed
- Check the settings can be edited
- Check the home displays the correct rooms depending on the value of the setting
=> Space setting category doesn't show up

changelog.d/8157.feature, vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt, vector/src/main/java/im/vector/app/features/home/GetSpacesNotificationBadgeStateUseCase.kt, vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/NewHomeDetailViewModel.kt, vector/src/main/java/im/vector/app/features/home/NewHomeDetailViewState.kt, vector/src/main/java/im/vector/app/features/spaces/GetSpacesUseCase.kt, vector/src/main/java/im/vector/app/features/spaces/SpaceListViewModel.kt, vector/src/main/java/im/vector/app/features/spaces/notification/GetNotificationCountForSpacesUseCase.kt, vector/src/main/res/layout/fragment_new_home_detail.xml, vector/src/test/java/im/vector/app/features/home/GetSpacesNotificationBadgeStateUseCaseTest.kt, vector/src/test/java/im/vector/app/features/home/NewHomeDetailViewModelTest.kt, vector/src/test/java/im/vector/app/features/spaces/GetSpacesUseCaseTest.kt, vector/src/test/java/im/vector/app/features/spaces/notification/GetNotificationCountForSpacesUseCaseTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeAutoAcceptInvites.kt, vector/src/test/java/im/vector/app/test/fakes/FakeFlowLiveDataConversions.kt, vector/src/test/java/im/vector/app/test/fakes/FakeRoomService.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSession.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSpaceService.kt
In the new app layout, adding a notification badge on top of the floating action button which opens the spaces list bottom sheet.
Closes #8157 
- Open the app with new layout
- Send message in some rooms and check the badge counter is correctly displayed
- Send invite to a space
- Check the badge counter is red while the space invite is pending
=> Add aggregated unread indicator for spaces in the new layout

changelog.d/8171.bugfix, vector/src/main/res/drawable/bg_code_block.xml, vector/src/main/res/drawable/bg_inline_code_multi_line_left.xml, vector/src/main/res/drawable/bg_inline_code_multi_line_mid.xml, vector/src/main/res/drawable/bg_inline_code_multi_line_right.xml, vector/src/main/res/drawable/bg_inline_code_single_line.xml, vector/src/main/res/layout/composer_rich_text_layout.xml, vector/src/main/res/layout/item_timeline_event_text_message_rich_stub.xml
Fix issue where inline code does not display with the correct background color if the system theme is different to the theme selected in the in-app settings.
Fixes vector-im/verticals-internal#23
| Light in-app, dark system | Dark in-app, light system | Black in-app, light system|
|-|-|-|
|![light](https://user-images.githubusercontent.com/4940864/221224502-68313f7a-4363-4777-999d-77b658648925.png)|![dark](https://user-images.githubusercontent.com/4940864/221224491-3ea9d8dd-67fe-463e-b147-cb638d46a3ef.png)|![black](https://user-images.githubusercontent.com/4940864/221224506-73680542-90af-4472-8347-9320497bed3e.png)|
- Go to the in-app settings and enable the light theme
- Go to the system settings and enable dark mode
- (or vice-versa)
- Enable the rich text editor
- Compose code in the …
=> [Rich text editor] Fix code appearance

changelog.d/8190.bugfix, vector/src/main/res/layout/fragment_room_polls_list.xml
Reducing size and increasing the line spacing of the empty list title in poll history screen.
Feedback from design review.
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/46314705/222100497-f144c55d-eda1-4571-a23d-78a7ffb83616.png" width=300>|<img src="https://user-images.githubusercontent.com/46314705/222100261-56f3aa60-705d-40dd-a696-ee7ae3cf208d.png" width=300>|
- Go to a poll history of a room with no polls
=> [Poll history] Fixing small issue about font style (PSG-1178)

changelog.d/8168.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ThreadEventsHelper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ChunkEntityQueries.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ReadQueries.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/FetchTokenAndPaginateTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt
Chunks should not load events from other rooms if they happen to be requested for one eventId that already exists in a different room.
Always check for correct roomId when loading events from chunks.
Motivation from a client that renders rich replies (although the broken scenario can most likely appear in other cases as well, may be less severe):
If somebody links an invalid eventId in a room, which however is valid in a different room, this can mess up our timelines badly. This can be reproduced by replying to an event in a room, then forward the reply to a different room with a client that also forwards the replied-to information (such as FluffyChat - likely a bug though). Then click on the rich reply to open the eventId. Previously, Android could find the event from the other room and …
=> matrix-sdk: Ensure correct room for events loaded by chunks

changelog.d/8185.feature, vector/src/main/java/im/vector/app/features/home/room/detail/composer/ComposerEditText.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/images/UriContentListener.kt
Add ability to insert GIFs from keyboard when rich text editor is enabled.
Closes vector-im/verticals-internal#21
[gifs.webm](https://user-images.githubusercontent.com/4940864/221870717-7e4eb449-6427-4302-aa6c-d55bef96192d.webm)
- Enable rich text editor in labs
- Enable Gboard system keyboard
- Select a GIF from the keyboard
- Send the GIF to the room
- Switch to plain text mode
- Select a GIF from the keyboard
- Send the GIF to the room
=> [Rich text editor] Add ability to insert GIFs from keyboard

vector/src/main/java/im/vector/app/features/login/HomeServerConnectionConfigFactory.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/test/java/im/vector/app/features/onboarding/OnboardingViewModelTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeHomeServerConnectionConfigFactory.kt
It was the case before, see `LoginViewModel.handleUserAcceptCertificate(...)`
- Step 1
- Step 2
- Step ...
=> Be able to let the user trust several Fingerprints during login flow.

changelog.d/8208.bugfix, vector/src/main/res/drawable/ic_composer_rich_text_save.xml
Save button background color is hardcoded. Now we use the theming colors instead.
Similar to : 
- https://github.com/vector-im/element-android/pull/8142
- Edit a message
Signed-off-by: Julien DAUPHANT <julien.dauphant@beta.gouv.fr>
=> Remove hardcoded color on save button

vector/src/main/java/im/vector/app/features/analytics/impl/DefaultVectorAnalytics.kt, vector/src/test/java/im/vector/app/features/analytics/impl/DefaultVectorAnalyticsTest.kt
The app is creating the Posthog instance even if use consent to use analytics is not given. And when Posthog is created it tries to refresh the feature flag by requesting the server. We want to avoid that.
So in this PR: Create Posthog instance only when user consent is given, to avoid pinging Posthog server at application startup when consent is not given.
Note that feature flag will not work, but for now they are not used. All the `?.takeIf { userConsent == true }` could be removed with this change, but let's keep them for safety...
Closes  #8020
N/A
- Add a breakpoint to `com.posthog.android.ConnectionFactory:openConnection`
- Disable analytics
- Start the app in debug mode
- See that no connection is created
=> Create Posthog instance only when user consent is given

changelog.d/8210.bugfix, vector/src/main/java/im/vector/app/features/call/conference/RemoveJitsiWidgetView.kt
This PR adds RTL support to ```RemoveJitsiWidgetView``` as the original code did not seem to consider RTL.
In RTL, ```translationX``` can be a negative value in RTL since it slides from right to left.
Therefore I updated ```translationX```calculation logic so that it can accept negative value in RTL.
Additionally, I modified the activation threshold check logic to use the absolute value of ```traslationX``` since it can be negative in RTL.
Fix #8210 
https://user-images.githubusercontent.com/39683194/224473109-4ec51e27-63d4-49de-aedd-b5134732cc85.mp4
https://user-images.githubusercontent.com/39683194/224473094-b0c84f37-6612-4a94-b87f-d543068f026f.mp4
- Step 1. Set the device environment to the RTL
- Step 2. Launch the element App and enter the room
- Step 3. Start a room call and come …
=> Add RTL support to RemoveJitsiWidgetView

changelog.d/8217.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/members/RoomMemberQueryParams.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/DefaultMembershipService.kt, vector/src/main/java/im/vector/app/features/autocomplete/member/AutocompleteMemberController.kt, vector/src/main/java/im/vector/app/features/autocomplete/member/AutocompleteMemberPresenter.kt
Add user completion for matrix ids
#8217 
- Step 1
- Step 2
- Step ...
=> Add user completion for matrix ids

changelog.d/8026.bugfix, vector/src/main/java/im/vector/app/features/widgets/WidgetFragment.kt
#8026 
- Step 1
- Step 2
- Step ...
=> Fix custom sticker url loading

changelog.d/8268.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
#8268 
- Step 1
- Step 2
- Step ...
=> Jump to unread marker instead of first unread message

changelog.d/7882.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ChunkEntityHelper.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/readreceipts/DisplayReadReceiptItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/readreceipts/DisplayReadReceiptsBottomSheet.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/readreceipts/DisplayReadReceiptsController.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/readreceipts/ReadReceiptsCache.kt
Fixes #7882 
As we can now have multiple read receipts for the same user because of threads, we need to ensure we only show the most recent in a timeline.
We also need to handle clients not handling threads.
It could be handled in the sdk but it's easier to manage in the presentation layer.
=> Fix multiple read receipts for the same user in timeline #7882

vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
Changelog already exists from #8305 
#8268 
- Step 1
- Step 2
- Step ...
=> Update read marker when we go back in live

changelog.d/8340.misc, vector/src/main/java/im/vector/app/core/di/ActiveSessionHolder.kt, vector/src/main/java/im/vector/app/features/analytics/DecryptionFailureTracker.kt
New property in analytics errors to track native vs rust failures 
- Step 1
- Step 2
- Step ...
=> rust/native analytics E2E errors

changelog.d/8352.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/crosssigning/CrossSigningService.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCrossSigningService.kt
Quick fix on RustCrossSigningService. 
`isCrossSigningVerified()` was checking if the current identity trust the user own device instead of just checking if the user identity is trusted
Fixes https://github.com/vector-im/crypto-internal/issues/57
=> fix rust isCrossSigningVerified

changelog.d/7628.sdk, changelog.d/8354.misc, matrix-sdk-android/build.gradle, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/WithHeldTests.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/OlmMachine.kt
Bump rust crypto crate to 0.3.5
=> bump rust crypto to 0.3.5 (withheld)

changelog.d/8376.bugfix, vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt
Allow a custom push gateway to use a non-default port
When a custom UnifiedPush push gateway is detected, it's gateway URL is constructed from URL components contained within the push key. However, if the gateway URL contains a custom port, this is ignored and the push gateway test fails.
- Set up a custom push gateway which uses a custom port
- Go to settings > notifications > troubleshoot
=> Allow custom push gateway to use non-default port

changelog.d/748.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/PlainTextComposerLayout.kt
#748 
- Step 1
- Step 2
- Step ...
=> Improve message rendering when editing

build.gradle, changelog.d/7619.bugfix, dependencies_groups.gradle, docs/jitsi.md, tools/jitsi/build_jisti_libs.sh, vector/build.gradle, vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
Upgrade Jitsi library to 8.1.1. Note: SDK is now supporting API 24 and more, so the check on API 23 has been updated. See https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md for mre details.
Should fix #7619
The Jitsi libre SDK has been built and published at https://github.com/vector-im/jitsi_libre_maven/tree/main/android-sdk-8.1.1
fixes #7619
- Make audio call
- Make video call
- Join Jitsi meeting
=> Upgrade jitsi to version 8.1.1

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt, vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt, vector/src/main/java/im/vector/app/features/settings/devices/DevicesViewModel.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/RefreshDevicesOnCryptoDevicesChangeUseCase.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/RefreshDevicesUseCase.kt
Probably due to the merge of EAR rework, the app was crashing again when started without network. This PR fixes that.
I added some `tryOrNull` on the usage and let the Rust implementation fail again. It helps not resetting the lists of session in the settings when there is no network.
Fix crash
- Start the app without network.
=> Fix crash no network

changelog.d/8325.feature, vector/src/main/java/im/vector/app/features/media/UCropHelper.kt
This pull request enables the ability to crop images uploaded from the gallery or taken from within the app without a fixed aspect ratio. This allows users to be specific about the parts of an image they wish to send.
A friend told me how she has to use another messaging application to crop images as her screenshot tool has no editing tools and Element doesn't allow her to be specific.
Resolves #2356, which shows popular demand for the feature.
Note that support for free style cropping was previously removed in 3ac2296464f348e98341bdbefe8e285da3597b45.
|Before|After|
|-|-|
|![old](https://user-images.githubusercontent.com/42888162/231284095-1d9e4400-e0e5-48e7-aa4a-bd5537ca280c.gif)|![new](https://user-images.githubusercontent.com/42888162/231283584-707889a6-2365-490b-9cec-00886af2214a.gif) …
=> Enable free style cropping for camera and gallery images

.github/workflows/tests-rust.yml, changelog.d/8366.misc, coverage.gradle, matrix-sdk-android/build.gradle, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupTest.kt, matrix-sdk-android/src/androidTestRustCrypto/java/org/matrix/android/sdk/internal/crypto/store/migration/ElementAndroidToElementRMigrationTest.kt, matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/session/MigrateEAtoEROperation.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/OlmMachine.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCrossSigningService.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/keysbackup/RustKeyBackupService.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/store/db/migration/rust/ExtractMigrationDataUseCase.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/session/MigrateEAtoEROperation.kt
Add a new workflow to run integration test with the rust flavor 
- Step 1
- Step 2
- Step ...
=> add workflow for rust test

changelog.d/8436.misc, vector-config/src/main/java/im/vector/app/config/Config.kt, vector/src/main/java/im/vector/app/core/di/ConfigurationModule.kt
Updated posthog url (cosmetic, target same server) and added a new sentry env.
Sentry: Created a new Env in order to monitor specificly issues on the release using the rust crypto sdk
Posthog: Updated the posthog URL to match web (see this [PR](https://github.com/vector-im/element-web/pull/21559))
- Step 1
- Step 2
- Step ...
=> Add sentry config for rust crypto

changelog.d/8454.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/read/SetReadMarkersTask.kt, vector/src/main/java/im/vector/app/core/session/clientinfo/DeleteUnusedClientInformationUseCase.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationDrawerManager.kt
Fixes several ANR reported in sentry
Fixes #8454 
Fixes #8455
This is a quick fix, but it would be a good idea to have all Task<..> not dispatching on Main by default. 
- Step 1
- Step 2
- Step ...
=> Fix several app non responsive issues

changelog.d/8458.misc, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecuredStorageResetAllFragment.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListAction.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListBottomSheet.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListBottomSheetViewEvents.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListBottomSheetViewModel.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceTrustInfoActionFragment.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceTrustInfoEpoxyController.kt, vector/src/main/java/im/vector/app/features/settings/devices/TrustUtils.kt, vector/src/main/java/im/vector/app/features/settings/devices/v2/verification/GetEncryptionTrustLevelForDeviceUseCase.kt
In the member profile it was possible to manually verify a specific device of a given user. This is will perform a verification to mark this device as locally verified, but local verificaiton is not considered anymore in UI, so the device will not pass to a green shield after that (it's passing to a shield with a question mark now (?), this should be changed as part of another PR). 
Devices of other users are the responsability of other users, on your side you should verify the user and let him verifiy its devices.
The UI to perform this action is removed by this PR. 
If you want to verify your own device you should go to settings.
|Before|After|
|-|-|
|||
- Step 1
- Step 2
- Step ...
=> Remove legacy manually verify specific other device

changelog.d/8445.bugfix, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/MainActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
Fixes #8485
If you have a read only device (not all secrets available):
After the migration to rust you will need to re-verify, the text is updated like this in this case
- Step 1
- Step 2
- Step ...
=> Special text for re-verification after update

changelog.d/8439.bugfix, vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
The app crashes sometimes when self verification dialog tries to show.
```
Exception java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManager.checkStateLoss (FragmentManager.java:1610)
at androidx.fragment.app.FragmentManager.enqueueAction (FragmentManager.java:1650)
at androidx.fragment.app.BackStackRecord.commitInternal (BackStackRecord.java:341)
at androidx.fragment.app.BackStackRecord.commit (BackStackRecord.java:306)
at androidx.fragment.app.DialogFragment.show (DialogFragment.java:262)
at im.vector.app.features.navigation.DefaultNavigator.requestSelfSessionVerification (DefaultNavigator.kt:273)
at im.vector.app.features.home.HomeActivity$onCreate$3.invoke (HomeActivity.kt:275)
at …
```
=> Allow stateloss on verification dialogfragment

changelog.d/4855.bugfix, library/ui-strings/src/main/res/values/strings.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/signout/SignOutService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/signout/DefaultSignOutService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/signout/SignOutTask.kt, vector/src/main/java/im/vector/app/features/MainActivity.kt
Fixes https://github.com/vector-im/element-android/issues/4855
- Updates the sign out error dialog with a more helpful message for the user, letting them know what happens if they logout without informing the homeserver and giving them the option to sign out anyway.
- Manually tested the alert shows correctly if the server is not reachable
- Manually tested each of the actions on the dialog
- Manually tested the normal sign out flow, when the dialog does not display in the case the request succeeds.
=> Always allow users sign out

changelog.d/8482.bugfix, matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/CryptoService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventEditValidator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/read/DefaultReadService.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt, vector-app/src/gplay/java/im/vector/app/gplay/features/settings/troubleshoot/TestTokenRegistration.kt, vector-app/src/gplay/java/im/vector/app/push/fcm/GoogleFcmHelper.kt, vector-app/src/gplay/java/im/vector/app/push/fcm/VectorFirebaseMessagingService.kt, vector/src/main/java/im/vector/app/core/device/GetDeviceInfoUseCase.kt, vector/src/main/java/im/vector/app/core/pushers/PushersManager.kt, vector/src/main/java/im/vector/app/core/pushers/VectorUnifiedPushMessagingReceiver.kt, vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationViewModel.kt, vector/src/main/java/im/vector/app/features/home/UnknownDeviceDetectorSharedViewModel.kt, vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestEndpointAsTokenRegistration.kt, vector/src/test/java/im/vector/app/core/device/DefaultGetDeviceInfoUseCaseTest.kt, vector/src/test/java/im/vector/app/core/pushers/PushersManagerTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeCryptoService.kt, vector/src/test/java/im/vector/app/test/fakes/FakeGetDeviceInfoUseCase.kt
Fixes #8482
`getCryptoDevice` calls in rust are using `runBlocking`, it was causing ANRs. These calls are now suspendable, updated the code accordingly.
Additional change in ReadService on `getHomeServerCapabilities()` that was also causing ANRs.
- Step 1
- Step 2
- Step ...
=> Make cryptoDevice calls suspendable

changelog.d/8299.feature, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/homeserver/GetCapabilitiesResult.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/homeserver/GetHomeServerCapabilitiesTask.kt
This adds support for the stable capability negotiation for the [get login token](https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv1loginget_token) endpoint used by Sign in with QR.
These PR leaves support for the unstable release 0 in place. It is my intention that the support for the unstable version would be removed in a future release once the stable support has made it into Synapse via https://github.com/matrix-org/synapse/pull/15388.
- Step 1
- Step 2
- Step ...
- OS version(s): SDK 33
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
=> Support for stable MSC3882 get_login_token

changelog.d/8471.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
Previously, the "end poll" timeline item always showed the title and options from the start event, regardless of whether any edits had been made.
Now we show the latest edit, if available, falling back to the original otherwise.
[device-2023-05-26-114409.webm](https://github.com/vector-im/element-android/assets/189133/e19376ba-9efd-412a-9fe7-840b3c93f15d)
- Create a poll
- Edit the poll
- Vote (optional)
- End the poll
- Look at the created ended poll result event in the timeline
=> Show correct details when a poll is ended.

changelog.d/8507.bugfix, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/RoomShieldTest.kt, matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt, matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt, matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/session/sync/handler/ShieldSummaryUpdater.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/CryptoSessionInfoProvider.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorkerDataRepository.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponsePostTreatmentAggregator.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/network/OutgoingRequestsProcessor.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/session/sync/handler/ShieldSummaryUpdater.kt
Cleaned a bit the room shield update logic, as some issues are reported against outdated shields.
The logic is cleaned so that shields are updated:
- When a change of devices/keys/signeture of one of the member is detected (DeviceListManager for kotlin / OutgoingRequestsProcessor for rust
- When a membership change is detected on the room (or encryption has been set)
Rust code was missing the update on membership changes.
The kotlin code seems to be subject to some races while accessing realm in a multithreaded context. 
Added some integration test to check the different updates `RoomShieldTest`
Should fix https://github.com/vector-im/element-android/issues/8308 but main focus is to have the rust flavor working correctly.
- Step 1
- Step 2
- Step ...
=> Clean room shield update logic

changelog.d/8541.bugfix, vector/src/main/java/im/vector/app/core/di/ConfigurationModule.kt
This PR fixes the fallback key sharing strategy to return the correct value
The fallback key sharing strategy was always set to `OutboundSessionKeySharingStrategy.WhenSendingEvent` regardless of the config setting
=> Fix fallbackKeySharingStrategy

changelog.d/8481.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/homeserver/HomeServerCapabilities.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/send/SendService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/version/Versions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/RedactEventTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/HomeServerCapabilitiesMapper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/homeserver/GetHomeServerCapabilitiesTask.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/RedactEventWorker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/model/EventRedactBody.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessor.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorCoroutine.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/QueueMemento.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/QueuedTaskFactory.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/RedactQueuedTask.kt
#8481 
- Step 1
- Step 2
- Step ...
=> Update MSC3912 implementation: Redaction of related events

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/SyncResponsePostTreatmentAggregatorHandler.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/UserAccountDataSyncHandler.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapActions.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapBottomSheet.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapErrorFragment.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSharedViewModel.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapStep.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt, vector/src/main/res/layout/fragment_bootstrap_error.xml
Same change than #8542, by applied on top of the develop branch.
=> Crash fixes

changelog.d/8623.misc, tools/import_sas_strings.py
See https://github.com/vector-im/element-android/issues/8525
N/A
N/A
N/A
N/A
----
Signed-off-by: Travis Ralston <travis.ralston@matrix.org>
Signed-off-by: Travis Ralston <travis.ralston@element.io>
=> Fix SAS strings import URL

changelog.d/7758.bugfix, vector/build.gradle, vector/src/main/java/im/vector/app/features/call/conference/jwt/JitsiJWTFactory.kt, vector/src/test/java/im/vector/app/features/call/conference/jwt/JitsiJWTFactoryTest.kt
Used the hard-coded key from the module `prosody-mod-auth-matrix-user-verification` to sign the JWT  for Jitsi `openidtoken-jwt` authentication to pass token [validation](https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification/blob/v1.8.0/mod_auth_matrix_user_verification.lua#L179) at Prosody side.
#7758
- start a group video call
- get into the video call
- OS version(s): Android 6.0, Android 10.0
=> Fixes #7758: Fixed JWT token for Jitsi openidtoken-jwt authentication

changelog.d/8619.misc, vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt, vector/src/main/res/xml/vector_settings_general.xml
Hide deactivate account setting if account is manged externally.
Closes #8619
- connect to a matrix.org account. Observe that you can deactivate the account from the app (general settings).
- connect to a element.io account. Observe that you cannot deactivate the account from the app (general settings).
=> Hide deactivate account section in case of account managed externally.

changelog.d/8645.misc, vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
Not the external browser.
This is a follow-on from QA on https://github.com/vector-im/element-android/pull/8620
- Step 1
- Step 2
- Step ...
=> Open OIDC account management URL in chrome tab

changelog.d/8653.bugfix, matrix-sdk-android/build.gradle, matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/E2eeShareKeysHistoryTest.kt, matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/crypto/SecretShareManager.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/rendezvous/Rendezvous.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/securestorage/SharedSecretStorageService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/secrets/DefaultSharedSecretStorageService.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/OlmMachine.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/SecretShareManager.kt, vector/src/test/java/im/vector/app/test/fakes/FakeSharedSecretStorageService.kt
Fixes https://github.com/vector-im/element-android/issues/8653
Depends on new rust sdk  https://github.com/matrix-org/matrix-rust-sdk/pull/2632
- Step 1
- Step 2
- Step ...
=> Fix QR code login support in rust

changelog.d/8178.bugfix, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt
Ensure the incoming call will not ring forever, in case the call is not ended by another way.
Add a safe 2 minutes timer.
Fixes #8178
- Receive a call, the phone rings
- move to airplane mode
- without the patch: the phone rings forever
- with the patch: the phone stop ringing after 2 minutes
=> Ensure the incoming call will not ring forever, in case the call is not ended by another way

changelog.d/8671.misc, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/extensions/Strings.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/login/DefaultLoginWizard.kt, vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt, vector/src/main/java/im/vector/app/features/command/CommandParser.kt, vector/src/main/java/im/vector/app/features/login/LoginGenericTextInputFormFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginResetPasswordFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthEmailEntryFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthGenericTextInputFormFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordEmailEntryFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordFragment.kt, vector/src/main/java/im/vector/app/features/settings/threepids/ThreePidsSettingsFragment.kt, vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModel.kt, vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
Update regex for email address to be aligned on RFC 5322
Similar to [Matrix React SDK](https://github.com/matrix-org/matrix-react-sdk/blob/c28f3164bda5de130faf465f2d819726c2d5690e/src/email.ts#L19)
Some characters in email address are not allowed in Element Android but should be accepted according to RFC 5322.
=> Update regex for email address to be aligned on RFC 5322

changelog.d/8679.misc, matrix-sdk-android/build.gradle, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/CryptoService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/OlmMachine.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
Update the rust crypto sdk version. There are a couple of source breaking change on the binding side
- Step 1
- Step 2
- Step ...
=> bump crypto sdk to 0.3.16

changelog.d/8683.bugfix, vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt
When the Unified Push is enabled, the application checks the potential custom gateway before applying it. If an SSL error happens, the application may ignore this error and keep using this custom gateway. The actual SSL check will be done server side where this gateway is actually used.
Signed-off-by: giomfo gforet@matrix.org
=> Unified Push: Ignore the potential SSL error when the custom gateway is testing

changelog.d/8688.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt
Fix issue with timeline message view reuse while Rich Text Editor (RTE) is enabled.
- Fixes https://github.com/vector-im/element-android/issues/8684
- With RTE on, then with RTE off
- In a room with some encryption messages
- Send some messages
- Scroll up and down the timeline
- Observe the messages
=> Fix issue with timeline message view reuse while rich text editor is enabled

changelog.d/4066.bugfix, vector-app/src/main/java/im/vector/app/VectorApplication.kt, vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt
Ensure Background sync is not stopped when there is an active call.
It was happening since the application is foregrounded when VectorCallActivity is displayed.
Closes #4066 
1. Clear task (make sure Element is not running on the background).
2. Turn off/lock the screen.
3. Don't do anything, let the screen wake up by itself from call notification.
4. Don't pick up the call.
Then either the caller cancel the call, or answer the call from another session.
Previously the call was ringing forever. With this change, the device stops ringing, and the background sync is correctly cancelled. The device does not need to sync forever once the call is over.
Also did some smoke test around call, since this code is quite complex and not covered by unit tests.
=> Ensure Background sync is not stopped when there is an active call.

.github/workflows/build.yml
Make Exodus ignore Sentry, as it's a known an opt-in tracker.
Exodus now detects Sentry and was failing because of this. The new code should ensure it's the only detected tracker and make the check pass.
=> Try fixing exodus CI job

changelog.d/5969.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/relation/RelationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/ContentUtils.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/DefaultRelationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/EventEditor.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoEventFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/PlainTextComposerLayout.kt
This fixes #5969 
It replaces [this PR](https://github.com/element-hq/element-android/pull/8638) even if the fix is not the same. 
The downside is, it doesn't fix the edition of markdown, but at least we can keep the permalink...
=> Fix a bunch of issues related to edition and reply #5969

changelog.d/8744.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/event/ValidDecryptedEventTest.kt
The first commit should prevent encrypted content to be parsed as decoded Event. Hopefully there will be no side effect. I have checked and this should be fine.
The last commit is fixing an issue, calling `RoomService.refreshJoinedRoomSummaryPreviews` has never worked as expected with the Crypto Rust SDK.
Should fix lots of error logs when undecrypted Events content are mapped to Content model.
- Run the app and send encrypted message after discarding the session.
=> [Crypto] Improve Event.getClearContent() and fix assignement issue.

changelog.d/+update-login-splash-screen.bugfix, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/res/layout/fragment_ftue_splash_carousel.xml
- "I already have an account" and "Create account" buttons in the initial screens have swaped places and styles.
- "I already have an account" is now "Sign in" to make it clearer to the user.
Requested by a customer.
The new design should look like:
- Open the app, check the buttons look like the design above.
- OS version(s): 14
=> Make 'sign in' flow more important in the initial screen

changelog.d/8749.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/SessionExtensions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/livelocation/LiveLocationShareAggregatedSummary.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/LiveLocationShareAggregatedSummaryMapper.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/database/mapper/LiveLocationShareAggregatedSummaryMapperTest.kt, matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/session/room/location/DefaultLocationSharingServiceTest.kt, vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/LocationPinProvider.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageLiveLocationItem.kt, vector/src/main/java/im/vector/app/features/location/LocationSharingViewModel.kt, vector/src/main/java/im/vector/app/features/location/live/map/UserLiveLocationViewStateMapper.kt, vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewViewModel.kt, vector/src/main/java/im/vector/app/features/location/preview/LocationPreviewViewState.kt, vector/src/test/java/im/vector/app/features/location/LocationDataTest.kt, vector/src/test/java/im/vector/app/features/location/live/GetLiveLocationShareSummaryUseCaseTest.kt, vector/src/test/java/im/vector/app/features/location/live/map/GetListOfUserLiveLocationUseCaseTest.kt, vector/src/test/java/im/vector/app/features/location/live/map/UserLiveLocationViewStateMapperTest.kt, vector/src/test/java/im/vector/app/test/fakes/FakeLocationPinProvider.kt
This change ensure that the user Avatar used in location Event rendering is the same avatar than the avatar of the user in the room. Previously the application was using the Avatar from the user profile, but it can happen that the profile is not loaded into the DB, and so the fallback avatar was used (with the userId first later). As a consequence, if the user has set a avatar just on the current room, it will also be used.
This PR also improves how the cache works in `LocationPinProvider`. Rely on Glide cache, limit size, and invalidate cache in case of error, then success retrieving avatar data. Also use `UserItem` for the cache key, to invalidate cache if user avatar / display name change. So this PR also fix a refresh issue if user change their avatar.
This PR also fix a rendering …
=> Location avatar

changelog.d/send_button_blinking.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt
Add a small debounce operation in the `TextWatcher` so we don't process the temporary empty text triggered by the RTE.
=> Fix send button blinking with RTE

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DecryptRoomEventUseCase.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt
Fix `StreamEventsManager` not signaling event decrytions.
Was not wired when switching to rust crypto.
As a consequence the `UISIDetector` that is suppose to auto-report UISI (if enabled in settings) was not working.
- Step 1
- Step 2
- Step ...
=> Fix StreamEventsManager not signaling event decryptions

changelog.d/8786.bugfix, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapReAuthFragment.kt, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapReAuthViewModel.kt, vector/src/main/java/im/vector/app/features/settings/crosssigning/CrossSigningSettingsViewModel.kt
This PR contains 2 fixes:
- the first one (5cd78c02aacb697f2cfe19fead1b29a4e22d9f95) ensure that the keys displayed on screen are refresh as fast as possible after a reset key. Previously the user had to wait for the next sync response to see the displayed key change in this screen:
To reproduce, on this screen ^ click on "Reset Keys" and observe that as soon as the loading dialog is dimissed, the keys are updated on screen. Previously user had to wait at most 30s to see the update.
- The second fix (1155c43fe07c10e46e3e187b40b028bff30e04aa) ensures that when the `BootstrapReAuthFragment` is displayed, a first submit request is performed. Else an infinite loading wheel was displayed.
To reproduce the issue:
- create a new account on EA by selecting matrix.org (or another HS)
- when the …
=> Fix setup secure backup

vector/src/main/java/im/vector/app/features/analytics/plan/Error.kt, vector/src/main/java/im/vector/app/features/analytics/plan/Interaction.kt, vector/src/main/java/im/vector/app/features/analytics/plan/MobileScreen.kt, vector/src/main/java/im/vector/app/features/analytics/plan/NotificationTroubleshoot.kt, vector/src/main/java/im/vector/app/features/analytics/plan/PollCreation.kt, vector/src/main/java/im/vector/app/features/analytics/plan/PollVote.kt, vector/src/main/java/im/vector/app/features/analytics/plan/RoomModeration.kt, vector/src/main/java/im/vector/app/features/analytics/plan/SuperProperties.kt, vector/src/main/java/im/vector/app/features/analytics/plan/ViewRoom.kt
Update analytics event to 0.15.0
- Step 1
- Step 2
- Step ...
=> Update analytic events

changelog.d/8796.misc, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileAction.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileController.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewEvents.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
Let the user able to report another user:
- from any messages (not from the current user), new action "Report user"
- from the user profile page (not for the current user), new action "Report user". Also "Ignore" wording has been replaced by "Ignore user" for parity.
Closes #8796 
See above
- Open a message detail and see the new action
- Open a user profile and see the new action.
=> Report user

vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
=> When reporting a user, use the membership state eventId for the eventId.

vector/src/androidTest/java/im/vector/app/features/ReportedDecryptionFailurePersistenceTest.kt, vector/src/main/java/im/vector/app/features/analytics/DecryptionFailureTracker.kt, vector/src/main/java/im/vector/app/features/analytics/ReportedDecryptionFailurePersistence.kt, vector/src/test/java/im/vector/app/features/analytics/DecryptionFailureTrackerTest.kt
Fixes https://github.com/element-hq/element-android/issues/8800
- Step 1
- Step 2
- Step ...
=> Analyics: stop double reporting posthog utds

changelog.d/3616.bugfix, library/multipicker/src/main/java/im/vector/lib/multipicker/AudioPicker.kt, library/multipicker/src/main/java/im/vector/lib/multipicker/FilePicker.kt, library/multipicker/src/main/java/im/vector/lib/multipicker/ImagePicker.kt, library/multipicker/src/main/java/im/vector/lib/multipicker/MediaPicker.kt, library/multipicker/src/main/java/im/vector/lib/multipicker/Picker.kt, library/multipicker/src/main/java/im/vector/lib/multipicker/VideoPicker.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
Keep local file access permission when we quit and return to a room.
Fix crash when accessing a local file and permission is revoked. #3616 
https://github.com/element-hq/element-android/issues/3616#issuecomment-2037682976
=> fix: update local file access permission

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/rendezvous/Rendezvous.kt, vector/src/main/java/im/vector/app/features/login/qr/QrCodeLoginActivity.kt
=> Add note about MSC3886, MSC3903 and MSC3906 being closed

changelog.d/7466.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
- First commit: When using the RichTextEditor, store the formatted text into the Draft, to be able to restore it correctly.
- Second commit: Keep the formatted text into memory to be able to keep it when switching between composer modes.
Avoid formatting loses.
Closes #7466 
- Enable the RichTextEditor
- Add some formatted content to the composer, and do not send the message
- go back to the room list
- open the room with the draft
- observe that the text is formatted as before.
- swipe a previous message to start replying to it
- observe that the formatting is not lost when doing that
- Disable the RichTextEditor
- observe that draft feature works like before (so no regression)
As a limitation, a draft saved with the RTE enabled can be restored a bit wildly once the RTE has been …
=> Fix Rich Text Editor issues: save formatted text in draft and keep formatting when switching between modes

changelog.d/8840.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineEventVisibilityHelper.kt
Closes #8840
The algorithm was only checking for `m.room.redaction` but this could happen for any invisible events.
=> Fix redacted events not grouped correctly

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/session/room/send/MarkdownParserTest.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/pills/TextPillsUtils.kt, vector/src/main/java/im/vector/app/features/home/room/detail/AutoCompleter.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
- Make sure the rich text editor and the markdown one both send mentions with the user id as the fallback text for the permalink.
Sending the user's display name can lead to other clients rendering outdated names or incorrect ones, so we'd rather fall back to the user id.
Send user mentions with both the RTE enabled and disabled, check the formatted body contains user id as the link's fallback text.
- OS version(s): 14
=> When sending user mentions, always send the user id as the fallback text

changelog.d/8894.bugfix, vector/src/main/AndroidManifest.xml
Replace `*.element.io` deep link with actual hosts.
Fixes https://github.com/element-hq/element-android/issues/8849. 
1. Have EA installed on your device with permission to open links.
2. Install EXA, try to log into an account using OIDC.
3. If you can log in normally, it's working.
- OS version(s): 14
=> Replace `*.element.io` deep link with actual hosts

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/NetworkCallbackStrategy.kt, vector-app/src/debug/java/im/vector/app/receivers/VectorDebugReceiver.kt, vector-app/src/main/java/im/vector/app/VectorApplication.kt, vector/src/main/java/im/vector/app/core/services/BluetoothHeadsetReceiver.kt, vector/src/main/java/im/vector/app/core/services/WiredHeadsetStateReceiver.kt, vector/src/main/java/im/vector/app/features/mdm/DefaultMdmService.kt, vector/src/main/java/im/vector/app/features/widgets/WidgetActivity.kt
Use ContextCompat.registerReceiver with explicit RECEIVER_NOT_EXPORTED to fix crash on API 34.
> java.lang.SecurityException: im.vector.app.debug: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
=> Use ContextCompat.registerReceiver with explicit RECEIVER_EXPORTED

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/session/contentscanner/ScanEncryptorUtilsTest.kt
Add test to check that content can be decrypted. When we will switch to Vodozemac, the test will be updated, to ensure that content encrypted by libolm will be decryptable by Vodozemac.
Part of libolm removal.
CC @poljar @Velin92 
- Step 1
- Step 2
- Step ...
=> Add unit test on ScanEncryptorUtils.

library/ui-strings/src/main/res/values/strings.xml
"See and managed addresses[…]" typo fixed to "See and manage addresses[…]"
Erroneous past tense. Revised into present tense as intended by context.
Has been annoying me for quite some time.
Signed-off-by: Murad "Gness Erquint" Beybalaev <gness.na@gmail.com>
=> Update strings.xml to fix the "see and managed addresses[…]" typo.

library/external/realmfieldnameshelper/build.gradle
The value should be the same, but the reference name was incorrect.
See the value definitions on develop (at this time):
https://github.com/element-hq/element-android/blob/21e751e50f49c446d37a778709b0bf6d5449cfab/dependencies.gradle#L5-L6
=> Fix reference

library/ui-strings/src/main/res/values/strings.xml, vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/core/services/CallAndroidService.kt, vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt, vector/src/main/java/im/vector/app/features/call/audio/MicrophoneAccessService.kt, vector/src/main/java/im/vector/app/features/notifications/NotificationUtils.kt
Implemented a microphone access service to ensure uninterrupted microphone usage during voice calls, even when the app is running in the background.
Left photo represent when the call is in the background, and right when the app is open (no change in this case).
0240920_153721" width="300"/>
This pull request fixes a bug where the app loses microphone access when it goes into the background during a voice call. The issue has been resolved by ensuring that microphone access is maintained during background operations and that the microphone service continues running as needed.
Issue: **App loses microphone access when not active on v 1.6.20 #8881**
Steps to reproduce:
1. Start a voice call.
2. Click the Home button or switch to another app.
**Expected outcome**:
The conversation should …
=> [Bugfix] Fix microphone loss during background voice calls on Android 14

changelog.d/8938.misc, library/ui-strings/src/main/res/values/strings.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/ElementCallNotifyContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushrules/ProcessEventForPushTask.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/ElementCallItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/ElementCallTileTimelineItem.kt, vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt, vector/src/main/res/layout/item_timeline_event_base_state.xml, vector/src/main/res/layout/item_timeline_event_element_call_tile_stub.xml
Render incoming Element Call in the timeline as an informative tile.
Also render incoming Element Call in the notification drawer.
Closes #8938 
https://github.com/user-attachments/assets/88505e2a-0285-46ca-995e-144e2afa9e5b
- Run Element Android
- In an app supporting Element Call (such as Element Web), start an Element Call
- Observe that EA is rendering a notification and now renders the incoming call in the timeline
=> Element call incoming call

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/pushrules/RuleIds.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushrules/DefaultPushRuleService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushrules/LocalElementCallPushRule.kt
Follow up for #8941 
The incoming EC notification was displayed on my account because of specific push rules that trigger notification for every message in the room.
But with a brand new room, the EC notify notification was not displayed.
This PR is adding local push rules, if their id is not present in the push rules already, to ensure that incoming call will always be notified to the user.
=> Ensure m.call.notify event is not filtered out by push rules.

changelog.d/8960.misc, matrix-sdk-android/build.gradle
Based on matrix-sdk-crypto-0.9.0
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4424 causing apps to crash in some cases (if session was in verification violation state at time of migration). Would cause also decryption of messages sent by users in verification violation to fail 
(from @BillCarsonFr internal message)
- Given an existing session on web.
- With the previous android version 1.6.0 you login and verify. Then from web you reset the identity. Now android should became unverified, stay like that and do the update to the version 1.6.22.
- 1.6.22 will crash on startup
=> Bump org.matrix.rustcomponents:crypto-android from 0.5.0 to 0.6.0

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/UpdatedReplyDecorator.kt
Reply fallbacks are about to go away completely (https://github.com/matrix-org/matrix-spec-proposals/pull/2781, https://github.com/element-hq/element-web/pull/28406) and Element will probably get a lot of complaints if rendering replies doesn't work correctly. According to @AmineI (in https://github.com/element-hq/element-android/issues/8162#issuecomment-2249178511) just switching `formattedText` to `takeFormatted()` may resolve the issue for text replies.
I haven't tested this myself. If the fix works, I assume the problem is that element was assuming `formatted_body` is always present, even though it's not required. To test: send `/plain text` as a reply using develop.element.io and ensure both the quote and reply text are visible in element android (the `/plain` should prevent …
=> Fix rendering text replies

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/migration/MigrateCryptoTo024.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/extensions/RealmExtensions.kt
Fixes #8962. Not sure how to repro, maybe by migrating from an old DB version, but this PR is adding safety on the removal by checking that the class exists first.
=> Ensure Realm migration does not crash

README.md, build.gradle
For https://github.com/element-hq/sre-internal/issues/3184
Signed-off-by: Guillaume Villemont <guillaumev@element.io>
=> Update sonarcloud project key

changelog.d/8964.bugfix, vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
I removed the call to start the MicrophoneAccessService on Android 14+.
This change is in response to this GitHub Issue: https://github.com/element-hq/element-android/issues/8964
When running on Android 14+, if you have the microphone permission granted to the app, incoming calls while the app is in the background causes the app to crash, and the incoming call to not come through. The Android documentation for that is here: https://developer.android.com/develop/background-work/services/fgs/service-types#microphone
and here: https://developer.android.com/develop/background-work/services/fgs/restrictions-bg-start#wiu-restrictions
I tested by making a call to a device running Android 14 and my changes while the device is locked, as well as unlocked with the app open.
- OS version(s): Android …
=> #8964 Fix app crash on incoming call when running Android 14+

changelog.d/8998.misc, library/ui-strings/src/main/res/values/strings.xml, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/reporting/ReportingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/reporting/DefaultReportingService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/reporting/ReportRoomBody.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/reporting/ReportRoomTask.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileAction.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewEvents.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
Add new action to be able to report a room to the homeserver moderator.
Closes #8998
https://github.com/user-attachments/assets/55ce77a5-e0c6-41ee-90ba-cbeb75ffa391
- Open a room 
- Navigate to the setting
- Observe that there is a new action "Report Room".
=> Add action to report room.

changelog.d/9033.misc, tools/tests/test_configuration_link.sh, vector/src/main/AndroidManifest.xml
Accept only root path on mobile.element.io link, to prevent Element Android to intercept link that are for Element X Android or Element Pro.
Note that the link must contain the path `/` like this:
- https://mobile.element.io/?hs_url=https%3A%2F%2Felement.io
Without it, i.e.:
- https://mobile.element.io?hs_url=https%3A%2F%2Felement.io
Element Android will not handle the link and it will be opened in the browser.
Ensure the targeted application open the link and not another one.
NA
- Install the app
- Run the script `tools/tests/test_configuration_link.sh`
- Ensure that Element Android is started and not another app or the browser
- Click on "SIGN IN"
- Ensure that the default account provider is `element.io`
=> Filter mobile link

.github/workflows/post-pr.yml, .github/workflows/tests.yml
- Remove the BuildJet runner from our CI jobs.
- Make the UI test one run only after merging PRs or manually for a branch, since it's not really maintained.
We want to get rid of the BuildJet runners.
=> Use ubuntu-22.04 runner instead of buildjet for the UI tests
