element-hq/element-android

README.md

Fix room link in readme

---

app/src/main/res/drawable/bg_splash.xml

At least you can take inspiration from this :wink: 
I was able to log in and view chats and send a message
References:
https://developer.android.com/studio/build/multidex
https://stackoverflow.com/questions/27986204/cant-convert-to-color-type-0x2-error-when-inflating-layout-in-fragment-but-onl

Hacks to get it running on API 19

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/permalinks/MatrixLinkify.kt
vector/src/main/java/im/vector/riotredesign/core/linkify/VectorAutoLinkPatterns.kt
vector/src/main/java/im/vector/riotredesign/core/linkify/VectorLinkify.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/factory/MessageItemFactory.kt

Linkification: import workaround done on Riot

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/Room.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/SendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/state/StateService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoom.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/EventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/state/DefaultStateService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/state/SendStateTask.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailViewModel.kt

Send emote and update room topic

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/Matrix.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/Session.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/sync/FilterService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/AuthModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/db/AuthRealmModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/FilterEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/SessionRealmModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/FilterEntityQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/DefaultFilterRepository.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/DefaultFilterService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/DefaultSaveFilterTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/FilterApi.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/FilterFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/FilterRepository.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/FilterUtil.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultGetContextOfEventTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultPaginationTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncThread.kt
vector/src/main/java/im/vector/riotredesign/features/home/HomeActivityViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotredesign/features/login/LoginActivity.kt

Handle filter for sync

---

.buildkite/pipeline.yml
README.md
build.gradle

Buildkite - WIP

---

matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/permalinks/MatrixLinkify.kt
vector/build.gradle
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/MessageImageVideoItem.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/item/MessageTextItem.kt
vector/src/main/java/im/vector/riotredesign/features/html/EventHtmlRenderer.kt
vector/src/main/java/im/vector/riotredesign/features/html/FontTagHandler.kt
vector/src/main/res/layout/item_timeline_event_base.xml

Fix / When long clicking on an url link, both menu and open url was launched
+ Fix issue with markwon mx html parcing (not perfect, will need a cusom parser)
+ some missing long click (image content wrapper)
+ update markwon version

Fix / click|longclick link interference

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/failure/Failure.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/data/InteractiveAuthenticationFlow.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/data/LoginFlow.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/data/LoginFlowResponse.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/registration/RegistrationFlowResponse.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/DeleteDeviceAuth.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/DeleteDeviceParams.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/DeleteDeviceTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/Request.kt
vector/src/main/java/im/vector/riotredesign/features/settings/VectorSettingsPreferencesFragment.kt

Add delete device capability to RiotX

Crypto: Delete device

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/failure/Failure.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/CryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/data/InteractiveAuthenticationFlow.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/data/LoginFlowTypes.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/registration/RegistrationFlowResponse.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/DeleteDeviceAuth.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/DeleteDeviceParams.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/DeleteDeviceTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/DeleteDeviceWithUserPasswordTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/Request.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/group/DefaultGetGroupDataTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/SendRelationWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/RedactEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/SendEventWorker.kt
vector/src/main/java/im/vector/riotredesign/features/settings/VectorSettingsPreferencesFragment.kt

It handles canceling request and fix race issue with pagination.

Request can now be canceled properly

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/SASVerificationTransaction.kt
vector/src/main/java/im/vector/riotredesign/features/crypto/keysbackup/setup/KeysBackupSetupActivity.kt
vector/src/main/java/im/vector/riotredesign/features/crypto/keysbackup/setup/KeysBackupSetupSharedViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/crypto/keysbackup/setup/KeysBackupSetupStep1Fragment.kt
vector/src/main/java/im/vector/riotredesign/features/crypto/keysbackup/setup/KeysBackupSetupStep2Fragment.kt
vector/src/main/java/im/vector/riotredesign/features/crypto/keysbackup/setup/KeysBackupSetupStep3Fragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotredesign/features/workers/signout/SignOutViewModel.kt

Introduce change from matrix-org/matrix-android-sdk#467
KeysBackup: import change from vector-im/riot-android#3127

Crypto work

---

vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/composer/TextComposerView.kt
vector/src/main/res/layout/merge_composer_layout.xml

Change hint for encrypted room (fix #210)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/notification/BingRuleWatcher.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/notification/ProcessEventForPushTask.kt
vector/src/fdroid/AndroidManifest.xml
vector/src/fdroid/java/im/vector/riotredesign/fdroid/features/settings/troubleshoot/TestAutoStartBoot.kt
vector/src/fdroid/java/im/vector/riotredesign/fdroid/features/settings/troubleshoot/TestBackgroundRestrictions.kt
vector/src/fdroid/java/im/vector/riotredesign/fdroid/features/settings/troubleshoot/TestBatteryOptimization.kt
vector/src/fdroid/java/im/vector/riotredesign/fdroid/package-info.kt
vector/src/fdroid/java/im/vector/riotredesign/fdroid/receiver/AlarmSyncBroadcastReceiver.kt
vector/src/fdroid/java/im/vector/riotredesign/fdroid/receiver/OnApplicationUpgradeOrRebootReceiver.kt
vector/src/fdroid/java/im/vector/riotredesign/fdroid/service/VectorSyncService.kt
vector/src/fdroid/java/im/vector/riotredesign/push/fcm/FcmHelper.kt
vector/src/fdroid/java/im/vector/riotredesign/push/fcm/NotificationTroubleshootTestManagerFactory.kt
vector/src/gplay/AndroidManifest.xml
vector/src/gplay/java/im/vector/riotredesign/gplay/features/settings/troubleshoot/TestFirebaseToken.kt
vector/src/gplay/java/im/vector/riotredesign/gplay/features/settings/troubleshoot/TestPlayServices.kt
vector/src/gplay/java/im/vector/riotredesign/gplay/features/settings/troubleshoot/TestTokenRegistration.kt
vector/src/gplay/java/im/vector/riotredesign/gplay/package-info.kt
vector/src/gplay/java/im/vector/riotredesign/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/gplay/java/im/vector/riotredesign/push/fcm/FcmHelper.kt
vector/src/gplay/java/im/vector/riotredesign/push/fcm/NotificationTroubleshootTestManagerFactory.kt
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/riotredesign/VectorApplication.kt
vector/src/main/java/im/vector/riotredesign/features/notifications/PushRuleTriggerListener.kt

A few cleanup on Push/Notification code

Notification beta

---

vector/build.gradle

Upgrade firebase messaging version and disable Firebase Analytics

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/pushers/PushersService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/DefaultPusherService.kt
vector/src/gplay/java/im/vector/riotredesign/gplay/features/settings/troubleshoot/TestFirebaseToken.kt
vector/src/gplay/java/im/vector/riotredesign/gplay/features/settings/troubleshoot/TestTokenRegistration.kt
vector/src/main/java/im/vector/riotredesign/core/pushers/PushersManager.kt
vector/src/main/java/im/vector/riotredesign/features/settings/PreferencesManager.java
vector/src/main/java/im/vector/riotredesign/features/settings/VectorSettingsNotificationFragment.kt
vector/src/main/java/im/vector/riotredesign/features/settings/troubleshoot/TestBingRulesSettings.kt
vector/src/main/java/im/vector/riotredesign/features/settings/troubleshoot/TestDeviceSettings.kt
vector/src/main/res/values/strings_riotX.xml
vector/src/main/res/xml/vector_settings_notifications.xml

Enable / Disable for account will toggle .m.rule.master
Enable / Disable for account will register/unregister the pusher
+ fix troubleshoots

Cleans notification pref screen

---

vector/src/main/java/im/vector/riotredesign/core/extensions/LiveData.kt
vector/src/main/java/im/vector/riotredesign/core/utils/Debouncer.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/list/RoomListFragment.kt

Debounce click on room

---

matrix-sdk-android/build.gradle
vector/build.gradle
vector/lint.xml
vector/src/main/java/im/vector/riotredesign/features/media/ImageContentRenderer.kt
vector/src/main/res/anim/unread_marker_anim.xml
vector/src/main/res/layout/bottom_sheet_logout_and_backup.xml
vector/src/main/res/layout/constraint_set_composer_layout_compact.xml
vector/src/main/res/layout/constraint_set_composer_layout_expanded.xml
vector/src/main/res/layout/merge_composer_layout.xml

There is a lot to do to clean resource/color, but not P1
Fixes #237

min API 19 - tested

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/events/model/Event.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/EncryptEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/JsonCanonicalizer.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageActionsBottomSheet.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageMenuViewModel.kt

Fixes #211 
Fixes #242 
+ Add reply option in e2e room
+ Fix bug 242
+ Show preview of messages in menu and in text composer preview
+ Fix / crash on long click on event due to dagger migration

Reply in e2e room

---

matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxRoom.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/relation/RelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/timeline/TimelineService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimelineService.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageMenuFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/QuickReactionFragment.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/QuickReactionViewModel.kt
vector/src/main/java/im/vector/riotredesign/features/home/room/detail/timeline/action/ViewReactionViewModel.kt

Fix crash on long click due to impure reducers
+ bottom sheet message menu is live (updated on new reactions, edits,..)

Fix impure reducer and use live event

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/Session.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
vector/src/main/java/im/vector/riotredesign/features/MainActivity.kt

FIx / logout then login not working

Fix / signout sign-in not working

---

vector/src/main/java/im/vector/riotredesign/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/riotredesign/features/notifications/NotificationUtils.kt

Fixes #247 
Notification compatibility for pre N 
Before it was

Better summary for pre N devices

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/MXCryptoError.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/MXOlmDevice.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/ObjectSigner.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/IMXDecrypting.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/olm/MXOlmDecryption.kt
vector/src/main/java/im/vector/riotx/core/platform/VectorViewModel.kt

https://github.com/matrix-org/riot-android-rageshakes/issues/5880
https://github.com/matrix-org/riot-android-rageshakes/issues/5877
https://github.com/matrix-org/riot-android-rageshakes/issues/5873
https://github.com/matrix-org/riot-android-rageshakes/issues/5871

Fix / Rageshake crashes + cleaning

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/SendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt

Fix issue when quoting event in e2e rooms (Fixes #295)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/MXCryptoError.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/create/CreateRoomParams.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DeviceListManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/MXOlmDevice.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/OneTimeKeysUploader.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/olm/MXOlmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/attachments/ElementToDecrypt.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/KeysBackup.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/model/rest/KeysAlgorithmAndData.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/MXDeviceInfo.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/MXUsersDevicesMap.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/OlmInboundGroupSessionWrapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/event/OlmPayloadContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/ClaimOneTimeKeysForUsersDeviceTask.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreActivity.kt

Especially to stabilize crypto code
Tested:
- Send e2e message
- Receive e2e message
- Incoming device verification

Safely remove all usage of `!![`

---

.buildkite/pipeline.yml

Build every branch which is not master, to be able to build PR from external repository

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/MatrixPatterns.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/permalinks/MatrixLinkify.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/MatrixCallbackDelegate.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/StringUtils.kt
vector/src/main/java/im/vector/riotx/EmojiCompatFontProvider.kt
vector/src/main/java/im/vector/riotx/core/dialogs/DialogAdapter.kt
vector/src/main/java/im/vector/riotx/features/home/UserColor.kt

Some "Kotlinification"

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/CancelableBag.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimeline.kt

Enhance CancelableBag

---

vector/src/main/java/im/vector/riotx/core/extensions/LiveData.kt
vector/src/main/java/im/vector/riotx/core/utils/FirstThrottler.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/riotx/features/notifications/BitmapLoader.kt
vector/src/main/java/im/vector/riotx/features/notifications/IconLoader.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationDrawerManager.kt

Improve notification drawer manager: Dagger, throttle, and icon for API 9

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/timeline/TimelineEvent.kt
vector/src/main/java/im/vector/riotx/core/extensions/TimelineEvent.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/QuickReactionFragment.kt

Quick react on e2e was not displayed

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/relation/RelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/timeline/TimelineEvent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/KeysBackup.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/cache/DefaultCacheService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/DefaultPusherService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoomDirectoryService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/TextContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/signout/DefaultSignOutService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/task/ConfigurableTask.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/api/pushrules/PushrulesConditionTest.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotx/features/html/EventHtmlRenderer.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableEventResolver.kt
vector/src/main/res/values/strings_riotX.xml

Especially reply with formatted body
also fixes extra space in generated body
also create .toConfigurableTask() for task without parameters

Improve reply feature

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/relation/RelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/TextContent.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/api/pushrules/PushrulesConditionTest.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt

Edit emote

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/AuthAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/di/NetworkModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/TimeOutInterceptor.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncAPI.kt

Create a TimeOutInterceptor to set specific timeout on some request

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/permalinks/MatrixLinkify.kt
vector/src/main/java/im/vector/riotx/core/extensions/TimelineEvent.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt

And fix a regression on permalink click

Handle click on redacted event

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/EncryptedItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/helper/ContentUploadStateTrackerBinder.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/BaseEventItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/DefaultItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MergedHeaderItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageFileItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageImageVideoItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/NoticeItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/RedactedMessageItem.kt
vector/src/main/java/im/vector/riotx/features/ui/ColorProviderExt.kt
vector/src/main/res/values/theme_dark.xml
vector/src/main/res/values/theme_light.xml

Text in green when encrypting

---

CHANGES.md
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/riotx/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/riotx/core/extensions/Activity.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailActivity.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/riotx/features/home/room/filtered/FilteredRoomFooterItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/filtered/FilteredRoomsActivity.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListActions.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListDisplayModeFilter.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListNameFilter.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewState.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/riotx/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/riotx/features/navigation/Navigator.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomActivity.kt
vector/src/main/res/drawable/ic_filter.xml
vector/src/main/res/drawable/ic_x_green.xml
vector/src/main/res/layout/activity_filtered_rooms.xml
vector/src/main/res/layout/item_room.xml
vector/src/main/res/layout/item_room_filter_footer.xml
vector/src/main/res/menu/home.xml
vector/src/main/res/values/strings_riotX.xml

Room filtering

---

CHANGES.md
build.gradle
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/events/model/RelationType.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/relation/RelationContent.kt
vector/build.gradle
vector/src/main/java/im/vector/riotx/features/login/LoginActivity.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
vector/src/main/res/drawable/ic_search.xml
vector/src/main/res/layout/activity_filtered_rooms.xml
vector/src/main/res/layout/fragment_public_rooms.xml
vector/src/main/res/values/strings_riotX.xml
vector/src/main/res/values/styles_riot.xml

Also migrate to rxbinding 3
Fixes #349

Fix bad View used for searching in room directory.

---

vector/src/main/java/im/vector/riotx/core/di/ViewModelModule.kt
vector/src/main/java/im/vector/riotx/features/home/room/filtered/FilteredRoomFooterItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/filtered/FilteredRoomsActivity.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/widget/FabMenuView.kt
vector/src/main/java/im/vector/riotx/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/riotx/features/navigation/Navigator.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsViewState.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/RoomDirectoryActivity.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/RoomDirectoryViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomActivity.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomFragment.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomViewModel.kt
vector/src/main/res/layout/activity_filtered_rooms.xml
vector/src/main/res/layout/fragment_create_room.xml
vector/src/main/res/layout/fragment_home_detail.xml
vector/src/main/res/layout/fragment_public_rooms.xml
vector/src/main/res/layout/fragment_room_detail.xml
vector/src/main/res/layout/fragment_room_list.xml
vector/src/main/res/layout/fragment_room_preview_no_preview.xml
vector/src/main/res/values/styles_riot.xml

When filtering in room directory:
-> pass the filter to the room creation form
When filtering the room list:
-> pass the filter to the room creation form
-> pass the filter to the room directory list

Pass filter to room directory screen or create room screen

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/Session.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/SessionManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
vector/src/gplay/java/im/vector/riotx/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/riotx/core/preference/UserAvatarPreference.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromKeyViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromPassphraseViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDrawerFragment.kt
vector/src/main/java/im/vector/riotx/features/home/group/GroupListViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableEventResolver.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/riotx/features/rageshake/BugReporter.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsActivity.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsGeneralFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsSecurityPrivacyFragment.kt
vector/src/main/java/im/vector/riotx/features/workers/signout/SignOutUiWorker.kt

Fix a crash in notificationwhen display name is empty

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/utils/SystemUtils.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt
vector/src/main/res/values/strings_riotX.xml

WIP /  Fix Copying link from a message shouldn't open context menu

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt

Maybe we should have a proxy to handle join/leave globally...

Cancel invitation notification when handling the invitation in the application

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncThread.kt

Fix the progress bar always displayed on home

Fix sync state progress bar

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/sync/SyncState.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncThread.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/HomeRoomListObservableStore.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListNameFilter.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt

Do not show invitation in the filtered room list 

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageImageVideoItem.kt
vector/src/main/java/im/vector/riotx/features/media/ImageContentRenderer.kt
vector/src/main/java/im/vector/riotx/features/media/ImageMediaViewerActivity.kt
vector/src/main/res/layout/activity_image_media_viewer.xml
vector/src/main/res/transition/image_preview_transition.xml
vector/src/main/res/values-v21/theme_black.xml
vector/src/main/res/values-v21/theme_dark.xml
vector/src/main/res/values-v21/theme_light.xml

Better image fullscreen preview animation

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/auth/data/HomeServerConnectionConfig.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/create/CreateRoomParams.kt
vector/src/main/java/im/vector/riotx/features/homeserver/ServerUrlsRepository.kt
vector/src/main/java/im/vector/riotx/features/login/LoginActivity.kt
vector/src/main/res/values/config.xml

Fix https://github.com/vector-im/riotX-android/issues/445

Remove default identity server as we don't use it.

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomSummaryUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncResponseHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/UserAccountDataSyncHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/DirectChatsHelper.kt

User Account Data: fix sync issues with direct invites

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/UserAccountDataSyncHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/DirectChatsHelper.kt
vector/src/main/res/layout/fragment_create_direct_room.xml

Fix code quality issues

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/res/layout/activity_image_media_viewer.xml
vector/src/main/res/layout/fragment_room_detail.xml

Shared element was overlapping top system bars
- Added system status bar (top) and navigation bar (bottom) as shared element transition
- Share the toolbar between activities
- For composer, created a fake view that is out of screen in image preview

Fix / Shared element transition overlap

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/FileSaver.kt

If sink creation fails, the source is leaked.
This change ensures both are released if they are created.

Fix potential resource leak

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/KeysBackupPassword.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/MXKey.kt

Some optimisations

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/MatrixPatterns.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/events/model/Event.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/SessionParamsStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/db/RealmSessionParamsStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/extensions/Try.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/NoMerger.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TimelineSendEventWorkCommon.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/AccountDataModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/UpdateUserAccountDataTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/worker/AlwaysSuccessfulWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/worker/Extensions.kt
vector/src/main/java/im/vector/riotx/core/error/ErrorFormatter.kt
vector/src/main/java/im/vector/riotx/core/extensions/EditText.kt
vector/src/main/java/im/vector/riotx/core/platform/ConfigurationViewModel.kt
vector/src/main/java/im/vector/riotx/core/platform/SimpleTextWatcher.kt
vector/src/main/java/im/vector/riotx/features/home/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/riotx/features/home/createdirect/CreateDirectRoomViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ActionsHandler.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageImageVideoItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/riotx/features/media/ImageContentRenderer.kt
vector/src/main/res/values-v21/theme_dark.xml

Review of merged PRs:
#397 
#407 
#446 
#437 
#448 
#451 
#444 
#453 
#449 
#456

Review of merged PRs

---

vector/src/main/java/im/vector/riotx/core/platform/VectorBaseActivity.kt

Fix theme not well defined at runtime after configurationChange

---

CHANGES.md
vector/src/fdroid/java/im/vector/riotx/fdroid/features/settings/troubleshoot/TestAutoStartBoot.kt
vector/src/fdroid/java/im/vector/riotx/push/fcm/FcmHelper.kt
vector/src/gplay/java/im/vector/riotx/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/gplay/java/im/vector/riotx/push/fcm/FcmHelper.kt
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/core/resources/UserPreferencesProvider.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/SendMessageResult.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationUtils.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsAdvancedNotificationPreferenceFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsNotificationFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsPreferencesFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsSecurityPrivacyFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/troubleshoot/TestDeviceSettings.kt

Dagger for VectorPreferences and /markdown command as a bonus

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/di/SessionAssistedInjectModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionComponent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/membership/DefaultMembershipService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/read/DefaultReadService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/state/DefaultStateService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/DefaultTimelineService.kt
vector/src/main/java/im/vector/riotx/core/di/AssistedInjectModule.kt
vector/src/main/java/im/vector/riotx/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/riotx/core/di/ViewModelModule.kt

Some DI code cleaning (mostly use AssistedInject)

Dagger clean

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/util/MessageInformationDataFactory.kt

Date change message repeats for each redaction until a normal message

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ViewEditHistoryEpoxyController.kt

Fix text diff removed linebreak

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt

Fixes a regression on e2e replies

Fix / regression on e2e reply and edit of reply

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/notifications/PushRuleTriggerListener.kt

Privacy: remove log of notifiable event (#519)

---

vector/src/main/java/im/vector/riotx/EmojiCompatHelper.kt
vector/src/main/java/im/vector/riotx/EmojiCompatWrapper.kt
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ViewReactionBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/ViewReactionsEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/reactions/widget/ReactionButton.kt

Fix / EmojiCompat not initialized

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt

Also some formatting, which pollute the diff...

Fix crash due to missing informationData (#535)

---

CHANGES.md
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/features/rageshake/BugReporter.kt
vector/src/main/java/im/vector/riotx/features/rageshake/VectorFileLogger.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/res/values/strings_riotX.xml
vector/src/main/res/xml/vector_settings_labs.xml

Enhance log management.
- Timber Debug tree only planted in Debug build
- Reduced release log level (Waring+), can be extended with lab settings

Reduce release build log level

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/SecretStoringUtils.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/olm/MXOlmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/attachments/MXEncryptedAttachments.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/MXKey.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/MXUsersDevicesMap.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultSasVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/ssl/TLSSocketFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomTagHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/JsonCanonicalizer.kt

Some more kotlinification

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/sync/SyncState.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/NetworkConnectivityChecker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncThread.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/BackgroundDetectionObserver.kt
matrix-sdk-android/src/main/res/values/strings_RiotX.xml
vector/src/main/java/im/vector/riotx/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/sync/widget/SyncStateView.kt
vector/src/main/res/layout/fragment_home_detail.xml
vector/src/main/res/layout/fragment_room_detail.xml
vector/src/main/res/layout/view_sync_state.xml

In Room list and in room detail screen
Fixes #559

Display a "No network" banner when the device has no network

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/failure/Failure.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/Request.kt
vector/src/main/java/im/vector/riotx/core/error/ErrorFormatter.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/RoomDirectoryViewModel.kt
vector/src/main/res/values/strings_riotX.xml

And better message for timeout error
Fixes #545

Cleanup on the room search screen

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/PushRuleService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/notification/DefaultPushRuleService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/notification/ProcessEventForPushTask.kt
vector/src/gplay/java/im/vector/riotx/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/core/services/CallService.kt
vector/src/main/java/im/vector/riotx/core/utils/SystemUtils.kt
vector/src/main/java/im/vector/riotx/features/notifications/InviteNotifiableEvent.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableEvent.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotifiableMessageEvent.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationDrawerManager.kt
vector/src/main/java/im/vector/riotx/features/notifications/NotificationUtils.kt
vector/src/main/java/im/vector/riotx/features/notifications/PushRuleTriggerListener.kt
vector/src/main/java/im/vector/riotx/features/notifications/SimpleNotifiableEvent.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsAdvancedNotificationPreferenceFragment.kt

Fixes #563 
Also kotlinification, daggerization and cleanupization

Redact notification

---

vector/src/main/java/im/vector/riotx/features/login/LoginFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewModel.kt
vector/src/main/res/layout/fragment_login.xml

Fix infinite focus on HS field

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/core/utils/DimensionConverter.kt
vector/src/main/java/im/vector/riotx/core/utils/DimensionUtils.kt
vector/src/main/java/im/vector/riotx/features/home/createdirect/CreateDirectRoomKnownUsersFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/EncryptedItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/EncryptionItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/NoticeItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/AbsMessageItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/BaseEventItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/item/MessageTextItem.kt
vector/src/main/java/im/vector/riotx/features/media/ImageContentRenderer.kt

And daggerize DimensionUtils
Fixes #458 -> 5 emojis max to use big font

Embiggen messages with multiple emojis also for edited messages

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/ReadQueries.kt

isEventRead() returns true if the event has been sent by the user

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/FilterModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/GetPushersTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/PushersModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
vector/src/main/java/im/vector/riotx/core/di/ScreenComponent.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/core/di/VectorModule.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivityViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewState.kt
vector/src/main/java/im/vector/riotx/features/ui/SharedPreferencesUiStateRepository.kt
vector/src/main/java/im/vector/riotx/features/ui/UiStateRepository.kt

Fixes #503, after the usual cleanup

Persist opened tab between session (i.e. after application restart)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/homeserver/HomeServerCapabilities.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/HomeServerCapabilitiesMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/HomeServerCapabilitiesQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/homeserver/DefaultGetHomeServerCapabilitiesTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/homeserver/DefaultHomeServerCapabilitiesService.kt

Fix my dirty code

---

CHANGES.md
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/LiveDataObservable.kt
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/user/UserService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/util/Optional.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/DefaultUserService.kt
vector/src/main/java/im/vector/riotx/core/utils/RxStore.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivityViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDetailViewState.kt
vector/src/main/java/im/vector/riotx/features/home/HomeDrawerFragment.kt
vector/src/main/java/im/vector/riotx/features/home/HomeNavigator.kt
vector/src/main/java/im/vector/riotx/features/home/group/GroupListViewModel.kt

Group avatar live

---

CHANGES.md
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/content/ContentAttachmentData.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/message/ImageInfo.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/core/images/ImageTools.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageMenuViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/riotx/features/media/ImageContentRenderer.kt

Fix issue with image orientation

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/Session.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionListeners.kt
vector/build.gradle
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/core/di/VectorComponent.kt
vector/src/main/java/im/vector/riotx/core/extensions/Session.kt
vector/src/main/java/im/vector/riotx/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivityViewModel.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewModel.kt
vector/src/main/java/im/vector/riotx/features/session/SessionListener.kt

Stop sending bus event from SDK to App.

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt

Fix some typos/errors in documentation.

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/utils/ExternalApplicationsUtil.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt

Opening links from RiotX reuses browser tab (#599)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/events/model/Event.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/actions/EnsureOlmSessionsForUsersAction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/olm/MXOlmEncryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/KeysBackup.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TimelineEventDecryptor.kt
vector/src/gplay/java/im/vector/riotx/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/riotx/core/utils/FileUtils.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsGeneralFragment.kt

Ok, the dead lock should be fixed. PR can be reviewed.

Fix dead lock on crypto

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/extensions/RealmExtensions.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/TextContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/timeline/TimelineEventDecryptor.kt
tools/check/forbidden_strings_in_code.txt

More cleanup

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/command/CommandParser.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/res/xml/vector_settings_preferences.xml

Small cleanup and disable markdown by default
Fixes #412

Markdown off

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/Helper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt
vector/src/main/java/im/vector/riotx/features/command/CommandParser.kt

Import change form https://github.com/matrix-org/matrix-android-sdk/pull/505

---

vector/src/main/java/im/vector/riotx/core/resources/ColorProvider.kt
vector/src/main/java/im/vector/riotx/features/html/EventHtmlRenderer.kt
vector/src/main/java/im/vector/riotx/features/html/SpanHandler.kt
vector/src/main/java/im/vector/riotx/features/html/SpoilerSpan.kt

Ensure color is retrieved from current theme, even when theme change

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/EventSharedAction.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/res/drawable/ic_alert_triangle.xml
vector/src/main/res/values/strings_riotX.xml

Add action to block user in the message action bottom sheet

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/riotx/features/reactions/EmojiSearchResultFragment.kt
vector/src/main/res/layout/activity_emoji_reaction_picker.xml

2 quick fixes

---

CHANGES.md
vector/src/main/res/values/strings.xml

Signed off by Andrew Morgan (andrew \at/ amorgan.xyz)

Small typo fix

---

vector/build.gradle

Force android-gif-drawable version

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/relation/RelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/SendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/TextPillsUtils.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/send/UserMentionSpan.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/pills/MentionLinkSpec.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/pills/MentionLinkSpecComparator.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/pills/TextPillsUtils.kt
vector/src/main/java/im/vector/riotx/core/extensions/BasicExtensions.kt
vector/src/main/java/im/vector/riotx/core/extensions/View.kt
vector/src/main/java/im/vector/riotx/features/command/CommandParser.kt
vector/src/main/java/im/vector/riotx/features/command/ParsedCommand.kt
vector/src/main/java/im/vector/riotx/features/home/createdirect/CreateDirectRoomDirectoryUsersFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/composer/ComposerEditText.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/composer/TextComposerView.kt
vector/src/main/java/im/vector/riotx/features/html/MxLinkTagHandler.kt
vector/src/main/java/im/vector/riotx/features/html/PillImageSpan.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsGeneralFragment.kt

Pills are sent as links in timeline

Send mention pills from composer

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/file/FileService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/db/RealmSessionParamsStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/IncomingRoomKeyRequestManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/MXOlmDevice.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/OutgoingRoomKeyRequestManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryption.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/algorithms/megolm/MXMegolmDecryptionFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/KeysBackup.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/UploadKeysTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/SessionRealmConfigurationFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/query/FilterEntityQueries.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultFileService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultInitialSyncProgressService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/DefaultFilterRepository.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/signout/SignOutTask.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/login/Config.kt
vector/src/main/java/im/vector/riotx/features/login/LoginFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginSignUpSignInSelectionFragment.kt

Registration stabilization

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/OneTimeKeysUploader.kt

Fix boolean reset if request fails
Implement https://github.com/matrix-org/matrix-js-sdk/pull/493

Improve and cleanup OneTimeKey uploader

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt

Fixes #739

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/failure/Failure.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/AuthAPI.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/DefaultAuthenticationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/data/RiotConfig.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/RetrofitExtensions.kt
vector/src/main/java/im/vector/riotx/core/error/ErrorFormatter.kt
vector/src/main/java/im/vector/riotx/features/login/LoginViewModel.kt
vector/src/main/res/values/strings.xml

Support entering a RiotWeb client URL instead of the homeserver URL

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomActivity.kt

Fix crash when opening room creation screen from the room filtering screen

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/SessionId.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/db/AuthRealmMigration.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/db/SessionParamsEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/auth/db/SessionParamsMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/SessionRealmConfigurationFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/di/StringQualifiers.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultFileService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/signout/SignOutTask.kt

Identify a session with the userId and the deviceId

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/utils/Debouncer.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/JumpToBottomViewVisibilityManager.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt

Show skip to bottom FAB while scrolling down (Fixes #752)

 Show skip to bottom FAB while scrolling down (#752) 

---

CHANGES.md
vector/build.gradle
vector/src/fdroid/java/im/vector/riotx/FlavorCode.kt
vector/src/gplay/java/im/vector/riotx/FlavorCode.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsHelpAboutFragment.kt
vector/src/main/res/xml/vector_settings_help_about.xml

Fixes #814 
@Bubu please let me know if it's ok for you.

Exclude play-services-oss-licenses library from F-Droid build (#814)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/RealmQueryLatch.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/membership/joining/JoinRoomTask.kt

All the credit goes to @Dominaezzz :), which has done #419.
I've just included the timeout in the method and fix the conflicts.

Remove CountDownLatch (inspired from #419)

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
vector/src/main/res/xml/vector_settings_advanced_settings.xml

Minor change to display every events in developer mode

Show all hidden event in the timeline when the developer settings is ON

---

AUTHORS.md
CHANGES.md
matrix-sdk-android/build.gradle
vector/build.gradle

Fixes #842 
This PR adds an AUTHORS file.

Builds repoductibility and Authors file

---

.idea/dictionaries/bmarty.xml
CHANGES.md
vector/build.gradle

F-Droid: fix the "-dev" issue in version name (#815)

---

.idea/codeStyles/codeStyleConfig.xml
CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/RoomSummary.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/RoomSummaryMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/model/RoomSummaryEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoomService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/UserAccountDataSyncHandler.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/SaveBreadcrumbsTask.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/BreadcrumbsRoomComparator.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/ChronologicalRoomComparator.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListViewState.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/riotx/features/share/IncomingShareActivity.kt
vector/src/main/java/im/vector/riotx/features/share/IncomingShareViewModel.kt
vector/src/main/res/values/strings_riotX.xml

Improve the room list when sharing to RiotX

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/form/FormSwitchItem.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomAction.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomController.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomFragment.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomViewState.kt
vector/src/main/res/layout/item_form_switch.xml
vector/src/main/res/values/strings_riotX.xml

Fixes #837 
The DM part is handled by #907

e2e opt in when creating room (not DM)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/crosssigning/CrossSigningService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/sas/QrCodeVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/sas/VerificationTxState.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/DefaultCrossSigningService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/model/CrossSigningInfoEntity.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/DefaultQrCodeVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/Extensions.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/create/CreateRoomTask.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/crypto/verification/qrcode/QrCodeTest.kt
vector/src/main/java/im/vector/riotx/core/di/FragmentModule.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationAction.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/qrconfirmation/VerificationQrScannedByOtherController.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/qrconfirmation/VerificationQrScannedByOtherFragment.kt
vector/src/main/res/values/strings_riotX.xml

Add a step to validate that the other user has scanned my QR code

Qr step validate

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/sas/VerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/KeyVerificationRequest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/PendingVerificationRequest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransport.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransportRoomMessage.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransportToDevice.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/DefaultQrCodeVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/Extensions.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/QrCodeData.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/crypto/verification/qrcode/QrCodeTest.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/conclusion/VerificationConclusionController.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/conclusion/VerificationConclusionViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/request/VerificationRequestController.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/devices/DeviceListBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewModel.kt
vector/src/main/res/layout/bottom_sheet_verification.xml

Add field in QR code and make some optional

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/roomprofile/members/RoomMemberListViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/members/RoomMemberSummaryComparator.kt

Sort room members by display names

---

matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxRoom.kt
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/CryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/crypto/crosssigning/CrossSigningService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/DefaultCrossSigningService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/IMXCryptoStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt
vector/src/main/java/im/vector/riotx/core/animations/AppBarStateChangeListener.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/reactions/ViewReactionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/actions/RoomListQuickActionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileFragment.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/members/RoomMemberListViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/settings/RoomSettingsViewModel.kt
vector/src/main/res/layout/fragment_matrix_profile.xml
vector/src/main/res/layout/view_stub_room_profile_header.xml

Decoration in room profile and improve Rx flow

---

.buildkite/pipeline.yml
.gitignore
.idea/copyright/NewVector.xml
.idea/copyright/profiles_settings.xml

Note that for this time, Buildkite will complain, but the fix has already be done in Weblate, so the step will be ok after the next Weblate sync

Import Indonesian resource check from TravisCI to Weblate pipeline

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/login/LoginWebFragment.kt

By enabling the local storage of the WebView as a quick fix
Fixes #606

Support SSO login with Firefox account (#606)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/Condition.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/ConditionResolver.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/ContainsDisplayNameCondition.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/EventMatchCondition.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/RoomMemberCountCondition.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/SenderNotificationPermissionCondition.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/rest/GetPushRulesResponse.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/rest/PushCondition.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/pushrules/rest/Ruleset.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/ShieldTrustUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/mapper/PushRulesMapper.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/notification/DefaultPushRuleService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/notification/ProcessEventForPushTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/DefaultConditionResolver.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/DefaultRoomService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomGetter.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/RoomModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/notification/RoomPushRuleMapper.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/api/pushrules/PushrulesConditionTest.kt

Cleanup push rule code

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/EventSharedAction.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/res/layout/dialog_delete_event.xml
vector/src/main/res/values/strings_riotX.xml

In complement to #977 
@onurays can you review it please? Thanks

Redact message step2

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/message/MessageOptionsContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/message/MessageType.kt

Migrate to vendor prefixes, as per recommendation for non merged MSC
https://github.com/matrix-org/matrix-doc/blob/travis/msc/shipit/proposals/2324-when-to-ship.md

Use vendor prefix for non merged MSC

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/pushers/PushersService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/cache/CacheModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/filter/FilterModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/group/GroupModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/homeserver/HomeServerCapabilitiesModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/DefaultPusherService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/DefaultPushersService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/PushersModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/SyncModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/UserModule.kt
vector/src/gplay/java/im/vector/riotx/gplay/features/settings/troubleshoot/TestTokenRegistration.kt
vector/src/main/java/im/vector/riotx/core/pushers/PushersManager.kt
vector/src/main/res/values/config.xml

Cleanup pusher service and improve API

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/login/LoginFragment.kt
vector/src/main/res/layout/fragment_login.xml
vector/src/main/res/values-bg/strings.xml
vector/src/main/res/values-de/strings.xml
vector/src/main/res/values-eu/strings.xml
vector/src/main/res/values-fi/strings.xml
vector/src/main/res/values-fr/strings.xml
vector/src/main/res/values-hu/strings.xml
vector/src/main/res/values-it/strings.xml
vector/src/main/res/values-sq/strings.xml
vector/src/main/res/values-zh-rTW/strings.xml
vector/src/main/res/values/strings.xml
vector/src/main/res/values/strings_riotX.xml

Account creation: wrongly hints that an email can be used to create an account (#941)

---

.idea/dictionaries/bmarty.xml
matrix-sdk-android-rx/src/main/java/im/vector/matrix/rx/RxSession.kt
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/ssss/QuadSTests.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/accountdata/AccountDataService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/securestorage/EncryptedSecretContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/securestorage/SecretStorageKeyContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/securestorage/SharedSecretStorageError.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/securestorage/SharedSecretStorageService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/securestorage/SsssKeySpec.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/secrets/DefaultSharedSecretStorageService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tools/Tools.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/model/accountdata/UserAccountData.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/AccountDataContent.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/accountdata/DefaultAccountDataService.kt
vector/src/main/java/im/vector/riotx/features/settings/devtools/AccountDataViewModel.kt

Complement to #995 
Try to make the code clearer and add missing Javadoc
Also in the test, use doSync() to reduce (massively) the code boilerplate

Cleanup quad s and AccountData service

---

vector/src/main/java/im/vector/riotx/core/extensions/Set.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/share/IncomingShareViewModel.kt

Fix share text to a single room issue

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/listeners/ProgressListener.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/actions/MegolmSessionDataImporter.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/keysbackup/DefaultKeysBackupService.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreActivity.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromKeyViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromPassphraseViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreSuccessFragment.kt
vector/src/main/res/layout/fragment_keys_backup_restore_from_key.xml
vector/src/main/res/layout/fragment_keys_backup_restore_from_passphrase.xml
vector/src/main/res/layout/fragment_keys_backup_restore_success.xml
vector/src/main/res/layout/fragment_keys_backup_settings.xml
vector/src/main/res/layout/fragment_keys_backup_setup_step1.xml
vector/src/main/res/layout/fragment_keys_backup_setup_step2.xml
vector/src/main/res/layout/fragment_keys_backup_setup_step3.xml
vector/src/main/res/values/strings_riotX.xml

Fix threading issues while restoring keys backup.

---

vector/src/main/java/im/vector/riotx/features/notifications/NotifiableEventResolver.kt

Fixes #712

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/roommemberprofile/RoomMemberProfileAction.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/RoomMemberProfileViewEvents.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileAction.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileFragment.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileViewEvents.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/RoomProfileViewModel.kt
vector/src/main/res/drawable/ic_material_share.xml
vector/src/main/res/layout/fragment_matrix_profile.xml
vector/src/main/res/menu/vector_room_member_profile.xml
vector/src/main/res/menu/vector_room_profile.xml
vector/src/main/res/values/styles_riot.xml

Share action is added to room profile and room member profile

---

.idea/codeStyles/Project.xml
CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/create/CreateRoomParams.kt
vector/src/main/java/im/vector/riotx/features/roomdirectory/createroom/CreateRoomViewModel.kt

Fixes #1070 
This PR also allow the app to create direct chat with more than 1 invitees
CC @david1hyman

Improve api of CreateRoomParams

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/NoticeEventFormatter.kt

Fix redacted event format on room overview.

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/NetworkCallbackStrategy.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/content/ThumbnailExtractor.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/LocalEchoEventFactory.kt
vector/src/fdroid/java/im/vector/riotx/fdroid/receiver/AlarmSyncBroadcastReceiver.kt
vector/src/main/java/im/vector/riotx/core/platform/EllipsizingTextView.kt
vector/src/main/java/im/vector/riotx/features/attachments/AttachmentsHelper.kt
vector/src/main/java/im/vector/riotx/features/media/ImageContentRenderer.kt
vector/src/main/java/im/vector/riotx/features/permalink/PermalinkHandler.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsNotificationPreferenceFragment.kt

Fix crashes reported by rageshakes

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/IncomingRoomKeyRequestManager.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/model/rest/RoomKeyShareCancellation.kt

Fix crash after rework. RoomKeyShare is now an interface

---

matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/crosssigning/ExtensionsKtTest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/securestorage/SharedSecretStorageError.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/DefaultCrossSigningService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/Extensions.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/secrets/DefaultSharedSecretStorageService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/SASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/DefaultQrCodeVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/Extensions.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt

The commits contains what has been done :)

Verification cleanup

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/attachments/preview/AttachmentsPreviewFragment.kt

Fix crash on attachment preview screen (#1088)

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/command/Command.kt
vector/src/main/java/im/vector/riotx/features/command/CommandParser.kt
vector/src/main/java/im/vector/riotx/features/command/ParsedCommand.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/res/values/strings_riotX.xml

Small, easy PR for a Sunday morning

Add support for `/plain` command (#12)

---

CONTRIBUTING.md
docs/integration_tests.md

@onurays could you please follow this guide please?

Add documentation to install environment and run integration tests

---

tools/workmanager/dumpsys_debug.sh
tools/workmanager/dumpsys_release.sh

Add script to dumpsys work manager data

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/JsonPusher.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/JsonPusherData.kt
vector/src/fdroid/java/im/vector/riotx/push/fcm/FcmHelper.kt
vector/src/gplay/java/im/vector/riotx/push/fcm/FcmHelper.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorSettingsNotificationPreferenceFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/push/PushGatewayAction.kt
vector/src/main/java/im/vector/riotx/features/settings/push/PushGatewaysFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/push/PushGatewaysViewModel.kt
vector/src/main/res/menu/menu_push_gateways.xml
vector/src/main/res/values/strings_riotX.xml

Pusher was set up at each startup, even if notification for the session was disabled.

Pusher fix

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/qrcode/DefaultQrCodeVerificationTransaction.kt

Fix / Self verification mode 1 was not working

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/attachments/AttachmentsHelper.kt

WorkAround / crash android 10 gif from keyboard

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/content/UploadContentWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/MultipleEventSendingDispatcherWorker.kt

Fixes #1145 
+ ensure Workmanager queues are reset after a clear cache

Fix / correctly update local echo failed state

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/common/CommonTestHelper.kt
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/common/TestConstants.kt
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/gossiping/KeyShareTests.kt
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/verification/SASTest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt

Fixes #794
(Verification DM / Handle concurrent .start after .ready)

Verif / handle concurrent start

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/rageshake/VectorFileLogger.kt

Quick PR to increase a bit the log history
Currently we have to few history (to much noise) to resolve a lot of issues

Increase file logger size

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/gossiping/KeyShareTests.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationInfoDone.kt

Fixes #1210 
Send gossiping requests after the reception of the done from the other session

Fix / Send gossip request on other done received

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/crypto/quads/SharedSecureStorageViewModel.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/res/values/strings_riotX.xml

Fixes #1214

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/composer/TextComposerView.kt
vector/src/main/res/layout/constraint_set_composer_layout_compact.xml
vector/src/main/res/layout/constraint_set_composer_layout_expanded.xml
vector/src/main/res/layout/merge_composer_layout.xml
vector/src/main/res/values/strings.xml
vector/src/main/res/values/strings_riotX.xml

Add shield in composer

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/CryptoModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/crosssigning/DefaultCrossSigningService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tasks/InitializeCrossSigningTask.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tools/Tools.kt

Move initializeCrossSigning to a task

Make initialize cross signing as a task

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/res/values/strings_riotX.xml
vector/src/main/res/xml/vector_settings_security_privacy.xml

Fixes #1027 .
Disabled by default, so by default, screenshots are allowed.

Add a setting to prevent screenshot of the application, disabled by default (#1027)

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/SendVerificationMessageWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransport.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationTransportRoomMessage.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/content/UploadContentWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/group/GetGroupDataWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/group/GroupSummaryUpdater.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/AddHttpPusherWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/relation/SendRelationWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/EncryptEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/MultipleEventSendingDispatcherWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/RedactEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/SendEventWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/job/SyncWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/worker/SessionWorkerParams.kt

Add some documentation on Workers

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/content/ContentUrlResolver.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/content/DefaultContentUrlResolver.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/content/FileUploader.kt

Fix download and upload media path

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
vector/src/main/java/im/vector/riotx/features/home/UnknwonDeviceDetectorSharedViewModel.kt

Avoid unnecessary /device call

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/riotx/features/createdirect/DirectoryUsersController.kt
vector/src/main/res/values/strings_riotX.xml

Add user to direct chat by user id.

---

matrix-sdk-android/build.gradle
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/common/CommonTestHelper.kt
matrix-sdk-android/src/debug/java/im/vector/matrix/android/internal/network/interceptors/CurlLoggingInterceptor.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/di/NetworkModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/eventbus/EventBusTimberLogger.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/pushers/AddHttpPusherWorker.kt
matrix-sdk-android/src/release/java/im/vector/matrix/android/internal/network/interceptors/CurlLoggingInterceptor.kt
matrix-sdk-android/src/sharedTest/java/im/vector/matrix/android/test/shared/TestRules.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/MatrixTest.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/api/pushrules/PushRuleActionsTest.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/api/pushrules/PushrulesConditionTest.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/crypto/keysbackup/util/Base58Test.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/crypto/keysbackup/util/RecoveryKeyTest.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/crypto/store/db/HelperTest.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/crypto/verification/qrcode/BinaryStringTest.kt
matrix-sdk-android/src/test/java/im/vector/matrix/android/internal/task/CoroutineSequencersTest.kt

This PR ensure log output when running tests are working 🎉

Log improvement for test

---

vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/res/values/colors_riotx.xml
vector/src/main/res/values/theme_black.xml
vector/src/main/res/values/theme_dark.xml
vector/src/main/res/values/theme_light.xml

Fix the color of misleading url according to design document.

---

vector/src/main/java/im/vector/riotx/features/crypto/recover/BootstrapCrossSigningTask.kt

Fix / backup key was not saved in QuadS after bootstrap

Fix / backup key was not save in 4S after bootstrap

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/auth/Constants.kt
vector/src/main/java/im/vector/riotx/features/login/LoginWebFragment.kt

Fixes #1178 
I use the login fallback url as a target to the after login SSO redirection, I will ask in #1178 if this is acceptable
Tested ok with `mozilla.modular.im`

Use correct sso url

---

vector/src/main/java/im/vector/riotx/features/MainActivity.kt
vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt
vector/src/main/java/im/vector/riotx/features/ui/SharedPreferencesUiStateRepository.kt
vector/src/main/java/im/vector/riotx/features/ui/UiStateRepository.kt

The corresponding code was not yet called.
Remark:
We have a mechanism to keep some preferences, but the list is long now.
Maybe for clarity, we should maintain a list of preferences to remove when user logs out.

Clear preferences when user logs out

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/dialogs/ManuallyVerifyDialog.kt
vector/src/main/java/im/vector/riotx/core/ui/list/GenericButtonItem.kt
vector/src/main/java/im/vector/riotx/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/riotx/features/home/HomeActivity.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/devices/DeviceTrustInfoEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/settings/crosssigning/CrossSigningEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DeviceItem.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DeviceVerificationInfoBottomSheetViewModel.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DeviceVerificationInfoEpoxyController.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesAction.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesController.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewEvents.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/DevicesViewModel.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/TrustUtils.kt
vector/src/main/java/im/vector/riotx/features/settings/devices/VectorSettingsDevicesFragment.kt
vector/src/main/res/layout/alerter_verification_layout.xml
vector/src/main/res/layout/item_generic_button.xml
vector/src/main/res/values/strings.xml
vector/src/main/res/values/strings_riotX.xml

Fixes #1295
- With new options to verify
- Manually verify will cross sign and uplaod signature

Update manage sessions screen

---

CHANGES.md
matrix-sdk-android/src/sharedTest/java/im/vector/matrix/android/test/shared/TestRules.kt
vector/build.gradle
vector/src/androidTest/java/im/vector/riotx/InstrumentedTest.kt
vector/src/androidTest/java/im/vector/riotx/features/reactions/data/EmojiDataSourceTest.kt
vector/src/main/java/im/vector/riotx/features/reactions/data/EmojiDataSource.kt
vector/src/sharedTest/java/im/vector/riotx/test/shared/TestRules.kt

Emoji completion for 🎉

---

CONTRIBUTING.md

Add instruction regarding the template

---

matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt

Fix: Crash on bootstrap 
Step to reproduce, create new account, start bootstrap, app will crash after confirmation of passphrase
>val keyEntity = crossSigningKeysMapper.map(cryptoCrossSigningKey)
xkeys.add(keyEntity)
````
Thread: Crypto_Thread, Exception: java.lang.IllegalArgumentException: 'value' is not a valid managed object.
at io.realm.ProxyState.checkValidObject(ProxyState.java:213)
at io.realm.im_vector_matrix_android_internal_crypto_store_db_model_CrossSigningInfoEntityRealmProxy.realmSet$crossSigningKeys(im_vector_matrix_android_internal_crypto_store_db_model_CrossSigningInfoEntityRealmProxy.java:170)
at im.vector.matrix.android.internal.crypto.store.db.model.CrossSigningInfoEntity.setCrossSigningKeys(CrossSigningInfoEntity.kt:27)
at …
```

Fix / Crash on bootstrap

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt

Fix crash 1364

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/crypto/keysbackup/restore/KeysBackupRestoreFromKeyViewModel.kt

Fix crash on restore backup from ky

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/verification/SASTest.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultIncomingSASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultOutgoingSASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/DefaultVerificationService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/SASDefaultVerificationTransaction.kt

See https://github.com/matrix-org/matrix-js-sdk/pull/1376

support new key agreement method for SAS

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/Matrix.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/config/ProxyConfiguration.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/di/NetworkModule.kt

Signed-off-by: Jürgen Wischer <github@unclejay.de>

added network proxy configuration

---

vector/src/main/java/im/vector/riotx/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/riotx/core/utils/JsonViewerStyler.kt
vector/src/main/java/im/vector/riotx/core/utils/UserColor.kt
vector/src/main/java/im/vector/riotx/features/crypto/quads/SharedSecureStorageActivity.kt
vector/src/main/java/im/vector/riotx/features/crypto/quads/SharedSecuredStorageKeyFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/quads/SharedSecuredStoragePassphraseFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/recover/BootstrapAccountPasswordFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/recover/BootstrapConfirmPassphraseFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/recover/BootstrapEnterPassphraseFragment.kt
vector/src/main/java/im/vector/riotx/features/crypto/recover/BootstrapMigrateBackupFragment.kt
vector/src/main/java/im/vector/riotx/features/grouplist/GroupListFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/breadcrumbs/BreadcrumbsFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/riotx/features/login/LoginActivity.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/devices/DeviceListFragment.kt
vector/src/main/java/im/vector/riotx/features/roommemberprofile/devices/DeviceTrustInfoActionFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/devtools/AccountDataFragment.kt
vector/src/main/java/im/vector/riotx/features/settings/devtools/GossipingEventsPaperTrailFragment.kt
vector/src/main/java/im/vector/riotx/features/signout/soft/SoftLogoutActivity.kt

- use invalidate() from MvRx
- use throttleFirst instead of debounce
- remove useless observe on main thread
- remove useless calls to super.invalidate()

Yet another cleanup PR

---

docs/integration_tests.md

Add command line to run Android test

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/im/vector/matrix/android/internal/crypto/gossiping/KeyShareTests.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/auth/data/HomeServerConnectionConfig.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/tools/HkdfSha256.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/SendVerificationMessageWorker.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/ssl/Fingerprint.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/notification/DefaultRoomPushRuleService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/send/MarkdownParser.kt

- Here is few improvements which Lint indicated when running it on the project.
- The last commit contains a fix where a self-assignment looks wrong.
Signed-off-by: Tobias Preuss <tobias.preuss@googlemail.com>

Random housekeeping indicated by Lint

---

CHANGES.md
CONTRIBUTING.md

Signed-off-by: Tobias Preuss tobias.preuss@googlemail.com

Fix minor typo in contribution guide.

---

vector/src/main/java/im/vector/riotx/features/home/room/list/RoomCategoryItem.kt
vector/src/main/java/im/vector/riotx/features/home/room/list/RoomSummaryController.kt
vector/src/main/res/layout/item_room_category.xml
vector/src/main/res/values/strings.xml

Updated as per initial design + fix margin consistency

Update room category as per design

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionState.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt

User could not redact messages that he has sent (#1543)

---

CHANGES.md
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/RealmKeysUtils.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/database/SessionRealmConfigurationFactory.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/util/CompatUtil.kt
vector/src/gplay/java/im/vector/riotx/push/fcm/FcmHelper.kt

+ Add `androidx.core:core-ktx:1.1.0` to `matrix-sdk-android` module which was already used in `vector` module.
+ Sources: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-preference-release/core/core-ktx/src/main/java/androidx/core/content/SharedPreferences.kt.
Signed-off-by: Tobias Preuss <tobias.preuss@googlemail.com>

Use SharedPreferences#edit extension function consistently.

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/user/UserDataSource.kt

Fixes #1468 user search case

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/network/ssl/CertUtil.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/summary/RoomSummaryUpdater.kt
matrix-sdk-android/src/main/res/values/strings.xml
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/NoticeEventFormatter.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
vector/src/main/res/layout/item_form_switch.xml

Render room avatar change and other fixes

---

CHANGES.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
matrix-sdk-android/src/main/AndroidManifest.xml
vector/build.gradle
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/riotx/VectorApplication.kt
vector/src/main/java/im/vector/riotx/features/form/FormEditTextWithButtonItem.kt

Fixes #1012, it was a false positive on lint.
Also upgrade build-tools and gradle version

Work manager init

---

CHANGES.md
vector/src/main/java/im/vector/riotx/core/utils/ExternalApplicationsUtil.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/action/MessageSharedActionViewModel.kt

Fixes save attachement issues on pre Q
I'll need some older devices to test the gallery update
Fixes #1578
Fixes #1324
Change log 
- File isn't downloaded when another file with the same name already exists (#1578)
- saved images don't show up in gallery (#1324)

Fix / save media on old android

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/IMXCryptoStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStoreMigration.kt
matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/model/CryptoMetadataEntity.kt

Upload device keys only once to the homeserver and fix crash when no network (#1629)

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/riotx/features/media/ImageMediaViewerActivity.kt
vector/src/main/java/im/vector/riotx/features/media/VideoContentRenderer.kt
vector/src/main/java/im/vector/riotx/features/media/VideoMediaViewerActivity.kt
vector/src/main/java/im/vector/riotx/features/roomprofile/uploads/RoomUploadsViewModel.kt

Fixes #1647 
Due to bad argument order (mimetype passed as url...)

Fixes #1647 share not working

---

CHANGES.md
matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/call/CallInviteContent.kt
vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/format/NoticeEventFormatter.kt

Video calls are shown as a voice ones in the timeline (Fixes #1676)

---

CHANGES.md
vector/src/main/java/im/vector/riotx/features/roommemberprofile/RoomMemberProfileController.kt
vector/src/main/res/drawable/ic_edit.xml
vector/src/main/res/values/strings.xml

Improve UI of edit role button.

Improve UI of edit role button

---

CHANGES.md
vector/src/main/java/im/vector/app/features/login/LoginCaptchaFragment.kt

Fix crash reported by RageShake

---

.github/workflows/gradle-wrapper-validation.yml
CHANGES.md

This GitHub Action validates the `gradle-wrapper.jar` on each PR, to make sure that no malicious one gets merged into the code base.
See: https://github.com/gradle/wrapper-validation-action

Official Gradle Wrapper Validation Action

---

CHANGES.md
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt

Fix save media error: Failed to build unique file

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/NoticeEventFormatter.kt

Fixes #1959 which contain all the details about the pb

A Kick appears has "someone has made no change" (Fixes #1959)

---

CHANGES.md
tools/import_sas_strings.py

It will be run at the next Weblate sync, since we have to remove previous translations
No change on the code for this PR

Create a script to import SAS strings (#1909)

---

.github/PULL_REQUEST_TEMPLATE.md
AUTHORS.md
README.md
build.gradle
vector/build.gradle
vector/src/debug/java/im/vector/app/features/debug/DebugMenuActivity.kt
vector/src/main/java/im/vector/app/core/ui/views/QrCodeImageView.kt
vector/src/main/java/im/vector/app/features/crypto/verification/choose/VerificationChooseMethodController.kt
vector/src/main/java/im/vector/app/features/crypto/verification/epoxy/BottomSheetVerificationQrCodeItem.kt
vector/src/main/java/im/vector/app/features/roomdirectory/roompreview/RoomPreviewActivity.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt
vector/src/main/java/im/vector/app/features/settings/devices/VectorSettingsDevicesFragment.kt

Also rename sonar project to Element-Android et id to `im.vector.app.android`

Sonar fixes

---

CHANGES.md
README.md
build.gradle
tools/release/download_buildkite_artifacts.py

New pipeline location: https://github.com/matrix-org/pipelines/blob/master/element-android/pipeline.yml
New build location: https://buildkite.com/matrix-dot-org/element-android

Update of Buildkite configuration

---

CHANGES.md
vector/src/main/java/im/vector/app/core/services/VectorService.kt
vector/src/main/java/im/vector/app/features/call/CallProximityManager.kt
vector/src/main/java/im/vector/app/features/call/VectorCallViewModel.kt

Turn the screen off while using ear speaker

---

vector/src/main/play/listings/en-US/full_description.txt

Mention thousands of public servers in Play Store

---

CHANGES.md
vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/app/features/invite/InviteUsersToRoomActivity.kt

Ugly fix for #2064.
Tested ok on Emulator running Android 6 (API 23).
I cannot find a better fix for now. @onurays @BillCarsonFr @ganfra any thoughts?

Android 6: App crash when read Contact permission is granted (#2064)

---

CHANGES.md
vector/src/gplay/java/im/vector/app/gplay/push/fcm/VectorFirebaseMessagingService.kt

Clear the notification when the event is read elsewhere

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/MatrixError.kt
vector/src/main/java/im/vector/app/features/login/LoginFragment.kt

Small PR for a small bug
Password related error is displayed on the password field

Show M_WEAK_PASSWORD error in the password field

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt

output stream not closed

---

CHANGES.md
vector/src/main/java/im/vector/app/features/call/WebRtcPeerConnectionManager.kt

Fixes #1776
Signed-off-by: Constantin Wartenburger <ginnythecat@lelux.net>

Only front camera is mirrored now

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/SendVerificationMessageWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportRoomMessage.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/parsing/CheckNumberType.kt

CheckNumberType crashing on timestamp number making workdata parsing failing, and then broke the sending queue on verification requests

Fix / Verification in DM not working

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/WidgetManager.kt

Fix widget creation permission check on group calls

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/LoginFlowResult.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt
vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt
vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt
vector/src/main/res/values/strings.xml

Just warn the user by a non blocking popup
Tested OK using outdated homeserver (from #1972): `m.ruslo.pro`.

Allow using an outdated homeserver, at user's risk (#1972)

---

CHANGES.md
vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnownMapper.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt

or redirect to some HTML content (reported by rageshakes)

Fix crash when wellknown are malformed

---

CHANGES.md
vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/features/pin/PinLocker.kt

PIN code: request PIN code if phone has been locked. No grace period in this case.

PIN code: request PIN code if phone has been locked

---

.github/workflows/update-gradle-wrapper.yml
CHANGES.md

Hey there 👋, first of all thanks for your work on Element!
I've got a suggested change: would you be willing to use [this GitHub Action](https://github.com/gradle-update/update-gradle-wrapper-action) to automatically keep Gradle Wrapper updated to latest release?
**What does "Update Gradle Wrapper Action" do?** It can be configured to run at scheduled intervals (e.g. daily or weekly) and will check whether the Wrapper script in the repo is up-to-date to the latest Gradle release: in case a new Gradle version is available, it will create a PR to update the Wrapper. And that's it!
**Why is that a good thing?** Well, first of all it alleviates the chore of manually updating the Wrapper, as you got a task that keeps track of new Gradle releases for you! More importantly, it boosts security …

Add workflow for Update Gradle Wrapper Action.

---

CHANGES.md
matrix-sdk-android/src/main/res/values/strings.xml
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptionItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MergedHeaderItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/NoticeItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/RoomCreateItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/VerificationItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/NoticeEventFormatter.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/BasedMergedItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MergedRoomCreationItem.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
vector/src/main/res/values/strings.xml

Wording differentiation for DM "chat" instead of "room"

---

vector/src/main/res/values/strings.xml

All genders can spam a chatroom :)
This is a translations change. I have not tested it, but I see no reason why it would not work.
Signed-off-by: Cadence Ember <cloudrac3r@vivaldi.net>

Replace "him" with "them" in report interface

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/list/RoomListNameFilter.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedListMemberAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedListMemberViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedMemberListController.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedMemberListFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/banned/RoomBannedMemberListViewState.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListController.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListViewState.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberSummaryFilter.kt
vector/src/main/res/layout/fragment_room_setting_generic.xml
vector/src/main/res/values/strings.xml

Add SearchView to filter room members

---

CHANGES.md
vector/build.gradle
vector/src/main/java/im/vector/app/features/home/room/detail/composer/TextComposerView.kt
vector/src/main/res/layout/constraint_set_composer_layout_expanded.xml

This PR update constraint layout dependency to the last stable version.
It fixes some glitch on the composer animation.
And fixes this issue : #2234

Fix composer: update constraints layout and fix some glitches

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt

Uploading a file to a room caused it to have a info.size of -1

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStoreMigration.kt

Fix crpyto store migration from RiotX.

---

vector/src/main/res/values/strings.xml

This leads to wrongly escaped string

Fix missing newline in strings.xml

---

matrix-sdk-android/src/main/res/values-bg/strings.xml
matrix-sdk-android/src/main/res/values-eo/strings.xml
matrix-sdk-android/src/main/res/values-fr/strings.xml
matrix-sdk-android/src/main/res/values-zh-rCN/strings.xml
vector/src/main/res/values-el/strings.xml
vector/src/main/res/values-sq/strings.xml

Fix lint issue

---

matrix-sdk-android/src/main/res/values-bn-rIN/strings.xml
matrix-sdk-android/src/main/res/values-cs/strings.xml
matrix-sdk-android/src/main/res/values-eo/strings.xml
matrix-sdk-android/src/main/res/values-es/strings.xml
matrix-sdk-android/src/main/res/values-it/strings.xml
matrix-sdk-android/src/main/res/values-kab/strings.xml
matrix-sdk-android/src/main/res/values-pt-rBR/strings.xml
matrix-sdk-android/src/main/res/values-sk/strings.xml
matrix-sdk-android/src/main/res/values-sv/strings.xml
matrix-sdk-android/src/main/res/values-zh-rCN/strings.xml
matrix-sdk-android/src/main/res/values-zh-rTW/strings.xml
matrix-sdk-android/src/main/res/values/strings.xml

[Reported by Slavi](https://matrix.to/#/!yvhoprZiKmhjxKfNHa:matrix.org/$dg2RmMoac_jTBjl59dt5qInUzsjMSd46B9Y-TbNZTc4?via=matrix.org&via=privacytools.io&via=t2l.io)

Fix issue with plurals

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoomService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomGetter.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailPendingAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileController.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileFragment.kt
vector/src/main/res/values/strings.xml

Fixes #2310 
New Action: "Direct message":

Room member profile: Add action to create (or open) a DM (#2310)

---

CHANGES.md
vector/src/main/java/im/vector/app/features/reactions/widget/ReactionButton.kt
vector/src/main/res/drawable/reaction_rounded_rect_shape.xml
vector/src/main/res/drawable/reaction_rounded_rect_shape_off.xml
vector/src/main/res/layout/reaction_button.xml
vector/src/main/res/values/colors_riotx.xml
vector/src/main/res/values/theme_black.xml
vector/src/main/res/values/theme_dark.xml
vector/src/main/res/values/theme_light.xml

Fix background color of reactions.

---

CHANGES.md
vector/src/main/AndroidManifest.xml

Two elements in the task switcher (#2299)

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/SASTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/verification/VerificationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/DefaultVerificationService.kt
multipicker/src/main/java/im/vector/lib/multipicker/CameraPicker.kt
vector/src/main/java/im/vector/app/core/dialogs/GalleryOrCameraDialogHelper.kt
vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt
vector/src/main/java/im/vector/app/features/attachments/preview/AttachmentsPreviewFragment.kt
vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModel.kt
vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapCrossSigningTask.kt
vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt
vector/src/main/res/xml/vector_settings_security_privacy.xml

Several independent commits, please review one by one.
@BillCarsonFr please confirm that you are ok with https://github.com/vector-im/element-android/commit/15ad35157916781f45e63302aadc42f4df269715
I am more confident with the other commits

Small fixes

---

CHANGES.md
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomAction.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt
vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt
vector/src/main/java/im/vector/app/features/userdirectory/KnownUsersFragment.kt
vector/src/main/java/im/vector/app/features/userdirectory/KnownUsersFragmentArgs.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserDirectorySharedAction.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserDirectoryViewModel.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserDirectoryViewState.kt

Navigate to an existing DM instead of creating a new one.

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt

Fixes https://github.com/vector-im/element-android/issues/2287

Fix draft share sheet

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/crypto/RoomCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/DefaultRoom.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt

Convert RoomCryptoService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/notification/RoomPushRuleService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/notification/DefaultRoomPushRuleService.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt

Convert RoomPushRuleService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/tags/TagsService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/tags/DefaultTagsService.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt

Convert TagsService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/reporting/ReportingService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/reporting/DefaultReportingService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt

Convert ReportingService to suspend functions

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/search/SearchMessagesTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/search/SearchService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/search/DefaultSearchService.kt

Convert SearchService to suspend functions

---

CHANGES.md
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewState.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsAction.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewState.kt
vector/src/main/res/layout/fragment_matrix_profile.xml
vector/src/main/res/values/strings.xml

Move "Enable Encryption" from room setting screen to room profile screen

---

tools/templates/unconfigure.sh

Add a script to delete the configured template, which can prevent Android Studio from being upgraded.

Un configure the template, to be able to upgrade Android Studio

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/user/UserService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/DefaultUserService.kt
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToAction.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetState.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToViewEvents.kt
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandlerActivity.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeActivity.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeState.kt
vector/src/main/res/layout/bottom_sheet_matrix_to_card.xml

matrix.to deep linking had some issues:
- Clicking a matrix.to link works only the first time
- Could end up with two instances of the app 
Home activity implements navigation interceptor to display the matrix to bottom sheet
Fixes #2349

Fix issues with matrix.to deep linking

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/terms/TermsService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/terms/DefaultTermsService.kt
vector/src/main/java/im/vector/app/features/discovery/change/SetIdentityServerViewModel.kt
vector/src/main/java/im/vector/app/features/terms/ReviewTermsViewModel.kt

Convert TermsService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/uploads/UploadsService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/uploads/DefaultUploadsService.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt

Convert UploadsService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/integrationmanager/IntegrationManagerService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/integrationmanager/DefaultIntegrationManagerService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/integrationmanager/IntegrationManager.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
vector/src/main/java/im/vector/app/features/widgets/permissions/RoomWidgetPermissionViewModel.kt
vector/src/main/java/im/vector/app/features/widgets/permissions/WidgetPermissionsHelper.kt

Convert IntegrationManagerService to suspend functions

---

CHANGES.md
vector/src/main/java/im/vector/app/core/extensions/EditText.kt
vector/src/main/java/im/vector/app/features/form/FormEditTextItem.kt
vector/src/main/java/im/vector/app/features/form/FormEditTextWithButtonItem.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/RoomAliasEditItem.kt

Move cursor to the end to fix the jumping cursor bug.

---

CHANGES.md
attachment-viewer/build.gradle
build.gradle
matrix-sdk-android-rx/build.gradle
matrix-sdk-android-rx/src/main/java/org/matrix/android/sdk/rx/RxCallbackBuilders.kt
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/SASDefaultVerificationTransaction.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/Hash.kt
multipicker/build.gradle
vector/build.gradle
vector/lint.xml
vector/src/gplay/java/im/vector/app/gplay/features/settings/troubleshoot/TestFirebaseToken.kt
vector/src/gplay/java/im/vector/app/push/fcm/FcmHelper.kt
vector/src/main/java/im/vector/app/core/intent/VectorMimeType.kt
vector/src/main/java/im/vector/app/core/platform/VectorViewModel.kt
vector/src/main/java/im/vector/app/core/ui/bottomsheet/BottomSheetGenericViewModel.kt
vector/src/main/java/im/vector/app/core/utils/DataSource.kt
vector/src/main/java/im/vector/app/core/utils/FileUtils.kt
vector/src/main/java/im/vector/app/features/attachments/preview/AttachmentsPreviewFragment.kt
vector/src/main/java/im/vector/app/features/attachments/preview/AttachmentsPreviewViewModel.kt
vector/src/main/java/im/vector/app/features/pin/PinFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/historyvisibility/RoomHistoryVisibilityBottomSheet.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/historyvisibility/RoomHistoryVisibilityViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/joinrule/RoomJoinRuleBottomSheet.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/joinrule/RoomJoinRuleViewModel.kt

Upgrade of some library + cleanup

---

CHANGES.md
vector/build.gradle
vector/src/main/assets/open_source_licenses.html
vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/ComposerEditText.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/TextComposerView.kt
vector/src/main/res/drawable/bg_send.xml
vector/src/main/res/drawable/ic_insert_emoji.xml
vector/src/main/res/drawable/ic_keyboard.xml
vector/src/main/res/layout/constraint_set_composer_layout_compact.xml
vector/src/main/res/layout/constraint_set_composer_layout_expanded.xml
vector/src/main/res/layout/merge_composer_layout.xml

Emoji Keyboard

---

CHANGES.md
docs/signin.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/Constants.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginFlowResponse.kt
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/app/features/login/LoginViewState.kt

Also improve the redirect url value

MSC2858 unstable prefix

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/media/UrlsExtractor.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt

Desktop has those too.
~~- [ ] UI change has been tested on both light and dark themes~~
~~- [ ] Pull request includes screenshots or videos if containing UI changes~~

Enable URL-previews for notices

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageStickerContent.kt

Unspecced msgType field in m.sticker (#2580)

---

attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/AttachmentViewerActivity.kt

Fix crash in AttachmentViewerActivity (after ViewBindings)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/PermalinkService.kt
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt

Fixes #2605, ignore "foobar://" URL used to launch the HomeActivity from a Notification intent

Tapping drawer having more than 1 room in notifications gives "malformed link" error (#2605)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncService.kt
vector/src/main/java/im/vector/app/core/services/VectorSyncService.kt

Sync: fix initial sync retry

---

CHANGES.md
vector/src/main/java/im/vector/app/core/files/LocalFilesHelper.kt
vector/src/main/java/im/vector/app/core/glide/MyAppGlideModule.kt
vector/src/main/java/im/vector/app/core/glide/VectorGlideModelLoader.kt
vector/src/main/java/im/vector/app/core/utils/FileUtils.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageImageVideoItem.kt
vector/src/main/java/im/vector/app/features/media/ImageContentRenderer.kt
vector/src/main/java/im/vector/app/features/media/VideoContentRenderer.kt

Sent image not displayed when opened immediately after sending

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
vector/src/main/res/values/strings.xml
vector/src/main/res/xml/vector_settings_preferences.xml

Option to hide emoji keyboard.

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CommonTestHelper.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineForwardPaginationTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/signout/SignOutService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/cache/DefaultCacheService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/signout/DefaultSignOutService.kt
vector/src/main/java/im/vector/app/core/platform/EmptyState.kt
vector/src/main/java/im/vector/app/core/platform/EmptyViewModel.kt
vector/src/main/java/im/vector/app/features/MainActivity.kt
vector/src/main/java/im/vector/app/features/link/LinkHandlerActivity.kt
vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutViewModel.kt

Migratiing to supend methods fixes the problem, I'm not sure why...

Fix clear cache issue: sometimes, after a clear cache, there is still a token, so the init sync service is not started.

---

CHANGES.md
vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchFragment.kt

Fix viewbinding NPE crashes

---

CHANGES.md
attachment-viewer/build.gradle
attachment-viewer/src/main/java/im/vector/lib/attachmentviewer/AttachmentViewerActivity.kt
attachment-viewer/src/main/res/values/colors.xml
matrix-sdk-android-rx/build.gradle
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/ThumbnailExtractor.kt
multipicker/build.gradle
multipicker/src/main/java/im/vector/lib/multipicker/AudioPicker.kt
multipicker/src/main/java/im/vector/lib/multipicker/VideoPicker.kt
vector/build.gradle
vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/app/features/attachments/preview/AttachmentsPreviewFragment.kt
vector/src/main/java/im/vector/app/features/call/CallAudioManager.kt
vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapBottomSheet.kt
vector/src/main/java/im/vector/app/features/login/LoginWebFragment.kt
vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/media/RoomUploadsMediaFragment.kt
vector/src/main/java/im/vector/app/features/webview/VectorWebViewActivity.kt
vector/src/main/java/im/vector/app/features/widgets/webview/WidgetWebView.kt

Migrate to Android 11, API 30.

---

CHANGES.md
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/session/media/UrlsExtractorTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/media/MediaService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/media/DefaultMediaService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/media/UrlsExtractor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/DefaultRelationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/FetchEditHistoryTask.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/url/PreviewUrlRetriever.kt

Update url preview when the event is edited.

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/helper/WidgetFactory.kt

Support $matrix_widget_id parameter.

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorkerDataRepository.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt

This is the first part of #2722
Other stuff about database will be handled later in a dedicated PR
Fixes #2721 
The code has been tested OK

Data for Worker overload (#2721)

---

CHANGES.md
vector/src/main/AndroidManifest.xml

Should remove issues with login/logout cases

Fix multiple tasks

---

CHANGES.md
vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt

Fix crash on API < 30 and light theme (#2774)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/peeking/PeekRoomTask.kt

Fixes #2778
Peek room task was not catching enough failures (of child tasks call)

Join room other federation via alias error

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/Extensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/CryptoCrossSigningKey.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/CrossSigningInfoEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/DeviceInfoEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/KeyInfoEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/UserEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/query/UserEntitiesQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tools/Tools.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/DatabaseCleaner.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/ChunkEntityHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/RoomEntityHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/TimelineEventEntityHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/ChunkEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/EventAnnotationsSummaryEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/PushRuleEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/PushRulesEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/PusherEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/ReadReceiptsSummaryEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/TimelineEventEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/extensions/RealmExtensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/GetPushersTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/SavePushRulesTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TokenChunkEventPersistor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/UserAccountDataSyncHandler.kt

@ganfra  /!\ Please review carefully, especially the part on chunk deletion.
This PR is the second part of #2227. It fixes #2759

[DANGEROUS PR] Properly delete all objects from Realm, avoid orphaned

---

CHANGES.md

- it's 2021
Signed-off-by: Maximillian Bensch <lorddavidiii@qi0.de>

CHANGES.md: fix typos

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt

Dendrite | fix crash after initial sync (regression from SSO UIA work)

fix post initial sync crash on 404

---

vector/src/main/java/im/vector/app/features/rageshake/LogFormatter.kt
vector/src/main/java/im/vector/app/features/rageshake/VectorFileLogger.kt

Cleanup VectorFileLogger.kt

---

CONTRIBUTING.md

compilator -> compiler
`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

Fix spelling in CONTRIBUTING.md

---

CHANGES.md
build.gradle
matrix-sdk-android/build.gradle
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/ChunkEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/PushersQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/UserDraftsEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineHiddenReadReceipts.kt
vector/build.gradle
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt
vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
vector/src/main/java/im/vector/app/features/themes/ThemeUtils.kt

Handle Dependabot's bumps and handle errors manually.

Upgrade dependencies

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/url/PreviewUrlRetriever.kt

Did not reproduce the bug, but this should fix it...

Try to fix crash about UrlPreview (#2640)

---

CHANGES.md
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/core/ui/views/ActiveConferenceView.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiCallViewActions.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiCallViewEvents.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiCallViewModel.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiCallViewState.kt
vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt
vector/src/main/res/values/strings.xml

Fixes #2418
Also handle switch to another conference.

PIP support for Jitsi call

---

CHANGES.md
vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetRoomPreviewItem.kt
vector/src/main/res/values/strings.xml

Add tooltip for low priority, favorite, and room settings quick actions.
Signed-off-by: Kafji <k@kafji.net>
https://user-images.githubusercontent.com/1842143/109649735-39ac6200-7b54-11eb-8c63-b49d99c2fbea.mp4
https://user-images.githubusercontent.com/1842143/109649776-4761e780-7b54-11eb-8194-45502aedc96d.mp4

Add tooltip for room quick actions

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/Event.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/EncryptEventTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/SendEventTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/SendVerificationMessageTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/EventMapper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/LoadRoomMembersTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/SendRelationWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoRepository.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
vector/src/gplay/java/im/vector/app/gplay/push/fcm/VectorFirebaseMessagingService.kt
vector/src/main/java/im/vector/app/features/devtools/RoomStateListController.kt
vector/src/main/java/im/vector/app/features/notifications/NotifiableEventResolver.kt

Make Event.type optional

---

.idea/dictionaries/bmarty.xml
CHANGES.md
vector/src/main/java/im/vector/app/core/extensions/TextView.kt
vector/src/main/java/im/vector/app/core/platform/SnackbarExt.kt
vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/app/core/platform/VectorBaseFragment.kt
vector/src/main/java/im/vector/app/features/MainActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsFragment.kt
vector/src/main/res/layout/activity_main.xml
vector/src/main/res/layout/fragment_loading.xml

Fixes #2927 : Main Activity now have an horizontal loader:
Also fixes #2929

Fixes before the release

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimelineService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LiveTimelineEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineInput.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
vector/build.gradle
vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
vector/src/main/res/layout/item_bottom_sheet_message_preview.xml
vector/src/main/res/values/strings.xml

Improve bottom sheet for message and fix crash on JsonViewer (see https://github.com/BillCarsonFr/JsonViewer/pull/1)

2 fixes for release 1.1.2

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DeviceListManager.kt

See https://github.com/vector-im/element-android/pull/3001#pullrequestreview-613195611

Restore code

---

CHANGES.md
vector/src/main/res/layout/item_timeline_event_day_separator.xml
vector/src/main/res/layout/item_timeline_event_text_message_stub.xml
vector/src/main/res/layout/item_timeline_read_marker.xml

Just fix some minor ui issues on timeline: 
- Ripple effect on text item 
- Background color of day separator and read marker

Feature/fga/fix UI timeline

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/GossipingWorkManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/DefaultCrossSigningService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/crosssigning/UpdateTrustWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/mapper/CrossSigningKeysMapper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportRoomMessage.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/di/WorkManagerProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/pushers/DefaultPushersService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/DefaultSendService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineSendEventWorkCommon.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/InitialSyncStatusRepository.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/RoomSyncHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncWorker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/parsing/DefaultLazyRoomSyncEphemeralJsonAdapter.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/parsing/InitialSyncResponseParser.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/LogUtil.kt

Fix issue with Realm in UpdateTrustWorker

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/space/Space.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/space/model/SpaceChildContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/DefaultSpace.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/SpaceApi.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/space/SpaceSummaryParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/ReadReceiptHandler.kt
vector/src/main/java/im/vector/app/AppStateHandler.kt
vector/src/main/java/im/vector/app/core/di/VectorComponent.kt
vector/src/main/java/im/vector/app/features/home/CurrentSpaceSuggestedRoomListDataSource.kt
vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListAction.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModelFactory.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewState.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryController.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/list/SuggestedRoomItem.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/SpacesListViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModelTask.kt
vector/src/main/java/im/vector/app/features/ui/SharedPreferencesUiStateRepository.kt
vector/src/main/res/layout/item_suggested_room.xml
vector/src/main/res/values/strings.xml

Add support for suggested rooms:
- After joining a space, a list of suggested rooms will be displayed in a new section at the bottom of room list
- The default rooms created in the creation flow are now suggested instead of auto-join
- Save current space in uiState

Suggested Space support

---

CHANGES.md
docs/notifications.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventRelationsAggregationProcessor.kt
vector/src/main/java/im/vector/app/core/utils/Emoji.kt
vector/src/main/java/im/vector/app/features/MainActivity.kt
vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecuredStoragePassphraseFragment.kt
vector/src/main/java/im/vector/app/features/crypto/verification/IncomingVerificationRequestHandler.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
vector/src/main/java/im/vector/app/features/themes/ActivityOtherThemes.kt
vector/src/main/res/layout/fragment_ssss_access_from_passphrase.xml

Fixes #3017 
Fixes #2509 
Improve UX for the enter passphrase bottom sheet, from
to
and many other small fixes

Some fixies

---

CHANGES.md
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/url/PreviewUrlRetriever.kt

Disable URL preview for some domains (#2995)

---

CHANGES.md
vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/image/ImageContentRendererFactory.kt
vector/src/main/res/layout/composer_layout.xml
vector/src/main/res/layout/composer_layout_constraint_set_compact.xml
vector/src/main/res/layout/composer_layout_constraint_set_expanded.xml
vector/src/main/res/layout/item_bottom_sheet_message_preview.xml

Also add the image preview in the message detail bottomsheet
Fixes #2916

Picture preview when replying. 

---

CHANGES.md
vector/src/main/java/im/vector/app/features/login/LoginSplashFragment.kt
vector/src/main/res/layout/fragment_login_splash.xml

(Build number is only relevant if built by Buildkite)

Add version details on the login screen, in debug or developer mode

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/Membership.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomGuestAccessContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomHistoryVisibilityContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomJoinRules.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomJoinRulesContent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAPI.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/LoadRoomMembersTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/state/DefaultStateService.kt

Be more robust when parsing some enums

---

vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt

And display details about it in the bottom sheet
When there is an exception to build on item in the timeline, it's correctly handled, but it was not handled in the message detail bottom sheet.
Exception was due to bad translation in French, see below usage of `%2$s` instead of `%1$s`:
```xml
<plurals name="notice_room_canonical_alias_alternative_added_by_you">
<item quantity="one">Vous avez ajouté %2$s comme adresse alternative pour ce salon.</item>
<item quantity="other">Vous avez ajouté %2$s comme adresses alternatives pour ce salon.</item>
</plurals>
```
Sadly Lint do not detect that.
The translation is already fixed in Weblate, so it will be fixed for the next release 1.1.4.

Be robust to Exception.

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/SASTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/crypto/verification/VerificationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/DefaultVerificationService.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheetViewModel.kt

Convert VerificationService to suspend functions

---

matrix-sdk-android-rx/src/main/java/org/matrix/android/sdk/rx/RxSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/user/UserService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/user/DefaultUserService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheetViewModel.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileViewModel.kt
vector/src/main/java/im/vector/app/features/settings/ignored/IgnoredUsersViewModel.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeSharedViewModel.kt

Convert UserService to suspend functions

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/file/FileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt
vector/src/main/java/im/vector/app/core/glide/VectorGlideModelLoader.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/media/BaseAttachmentProvider.kt
vector/src/main/java/im/vector/app/features/media/DataAttachmentRoomProvider.kt
vector/src/main/java/im/vector/app/features/media/RoomEventsAttachmentProvider.kt
vector/src/main/java/im/vector/app/features/media/VideoContentRenderer.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt

Left a few TODO comments for another PR.

Convert FileService to suspend functions

---

matrix-sdk-android-rx/src/main/java/org/matrix/android/sdk/rx/RxSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/profile/ProfileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/DefaultProfileService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsGeneralFragment.kt
vector/src/main/java/im/vector/app/features/settings/threepids/ThreePidsSettingsViewModel.kt

Convert ProfileService to suspend functions

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/Request.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
vector/src/main/java/im/vector/app/core/utils/FirstThrottler.kt
vector/src/main/java/im/vector/app/features/MainActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsHelpAboutFragment.kt

Please review commit by commit

Various fixes before release 1.1.4

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/TestRoomDisplayNameFallbackProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/RoomDisplayNameFallbackProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/RoomDisplayNameResolver.kt
vector/src/main/java/im/vector/app/features/room/VectorRoomDisplayNameFallbackProvider.kt

Improve the interface and limit the size of the room name if it was a crowded room...

Empty room name small iteration

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/Availability.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/registration/RegistrationAvailability.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/registration/RegistrationWizard.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/AuthAPI.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/Availability.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/DefaultRegistrationWizard.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/RegisterAvailableTask.kt

Will be merged if CI is happy.

Small cleanup for #3084

---

CHANGES.md
fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/en-US/short_description.txt
fastlane/metadata/android/en-US/title.txt
matrix-sdk-android-rx/src/main/AndroidManifest.xml
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/CryptoDeviceInfo.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/model/MXDeviceInfo.kt
vector/src/debug/res/layout/item_sas_emoji.xml
vector/src/main/java/im/vector/app/core/resources/AppNameProvider.kt
vector/src/main/java/im/vector/app/features/call/dialpad/DialPadFragment.kt
vector/src/main/res/layout/dialog_export_e2e_keys.xml

Store description update

---

CHANGES.md
vector/src/main/res/layout/item_timeline_event_base.xml
vector/src/main/res/values/colors.xml

Fix send state image color on dark theme

---

CHANGES.md
vector/src/main/java/im/vector/app/features/configuration/VectorConfiguration.kt

Tested OK on the room list and in the timeline
Fixes #2738

Fix color issues when the system theme is changed (#2738)

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomSummary.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/RoomSummaryMapper.kt

Expose directUserId in RoomSummary to identify the user if the room is direct.

Expose directUserId in RoomSummary

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/file/FileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/util/MimeTypes.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt
vector/src/main/AndroidManifest.xml
vector/src/main/java/im/vector/app/core/utils/SystemUtils.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt

Fixes #3067 (and replace #3229): open file using external app from Element. I've done a lot of test using an Android 11 emulator, and I haven't found other issue using Intent (save key, etc.)
Also fixes #3186 and fixes #2381

Android 11 fixes an other fixes for attachement

---

CHANGES.md
build.gradle
vector/build.gradle

`master` branch has been renamed to `main`. To apply change to your dev environment, run:
```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote prune origin
```

`master` branch has been renamed to `main`

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/SessionLifecycleObserver.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/DatabaseCleaner.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmLiveEntityObserver.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionCoroutineScopeHolder.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionListeners.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/identity/DefaultIdentityService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/integrationmanager/IntegrationManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorCoroutine.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorThread.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/DefaultWidgetURLFormatter.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/widgets/WidgetManager.kt
vector/src/main/java/im/vector/app/core/glide/VectorGlideModelLoader.kt
vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/search/SearchActivity.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationBroadcastReceiver.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/RoomMemberProfileActivity.kt
vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileActivity.kt
vector/src/main/java/im/vector/app/features/session/SessionCoroutineScopes.kt
vector/src/main/java/im/vector/app/features/session/SessionListener.kt
vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestAccountSettings.kt

@Dominaezzz what do you think about the new sessionScope?

WIP - introduce sessionScope

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/UpdatableLivePageResult.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/app/features/navigation/Navigator.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceCreationActivity.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceSettingsMenuBottomSheet.kt
vector/src/main/java/im/vector/app/features/spaces/create/ChoosePrivateSpaceTypeFragment.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceEvents.kt
vector/src/main/java/im/vector/app/features/spaces/create/CreateSpaceViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/manage/AddRoomListController.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceAddRoomFragment.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceAddRoomsViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManageActivity.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManageSharedViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedAction.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManagedSharedViewEvents.kt
vector/src/main/res/layout/fragment_space_add_rooms.xml

Fixes #3214
Added Just me space support.
After creation the add room screen will be open automatically.
Also contains update on Add room screen to separate spaces and room as per design
Edit: Added action to create a new room

Just me spaces support

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/timeline/TimelineEvent.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt

Fixes https://github.com/vector-im/element-android/issues/3184

Fix missing sender information after edits

---

CHANGES.md
build.gradle
matrix-sdk-android/build.gradle
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/PreShareKeysTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/room/timeline/TimelineWithManyMembersTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
matrix-sdk-android/src/test/java/org/matrix/android/sdk/internal/util/GraphUtilsTest.kt

https://github.com/Piasy/BigImageViewer is now hosted on mavenCentral()

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomHistoryVisibility.kt

Fix tests (one has been commented it's not relevant anymore, will create other PR to remove unused API for hierarchy)
Important Fix on Room History Visibility

Fix space test + room history visibility bug

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceCreationTest.kt
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/session/space/SpaceHierarchyTest.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomSummaryQueryParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryDataSource.kt
vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt
vector/src/main/java/im/vector/app/features/home/UnreadMessagesSharedViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/list/SpaceRoomListSectionBuilder.kt
vector/src/main/java/im/vector/app/features/spaces/SpacesListViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceAddRoomsViewModel.kt

Fix unread badges and invite filtering

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/quality.yml
.github/workflows/tests.yml

ci: add initial github actions pipelines

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/profile/ProfileService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/profile/ProfileAPI.kt
vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt

Allow inviting users even if profile information cannot be retrieved

---

.travis.yml
CHANGES.md
tools/release/sign_apk.sh
tools/release/sign_apk_unsafe.sh

Sign APK with build tools 30.0.3

Sign APK with build tools 30.0.3

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/login/LoginWizard.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/registration/RegistrationWizard.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/Room.kt
vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt

Fixes #3303
@tladesignz what do you think? Is it more understandable to you with this documentation? I will appreciate your feedback :)

Add documentation on LoginWizard and RegistrationWizard (#3303)

---

CHANGES.md
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt

Fix a problem with database migration on nightly builds (#3335)

---

CHANGES.md
vector/src/androidTest/java/im/vector/app/features/html/SpanUtilsTest.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageTextItem.kt
vector/src/main/java/im/vector/app/features/html/SpanUtils.kt

Implement a workaround to render <del> and <u> in the timeline (#1817)

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/quality.yml
.github/workflows/tests.yml

Follow up what have been done on #3058

GitHub action

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGES.md
CONTRIBUTING.md
newsfragment/3293.misc
tools/towncrier/template.md
tools/travis/check_pr.sh
towncrier.toml

Let's see if it's useful or not.

Setup towncrier

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/SessionListeners.kt
newsfragment/3424.bugfix

Fix https://github.com/vector-im/element-android/issues/3424

Fix crash on signout

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageType.kt
newsfragment/3430.feature
vector/src/main/java/im/vector/app/features/command/Command.kt
vector/src/main/java/im/vector/app/features/command/CommandParser.kt
vector/src/main/java/im/vector/app/features/home/room/detail/ChatEffectManager.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt
vector/src/main/res/values/strings.xml

/snow -> /snowfall and update wording (iso Element Web) (#3430)

---

vector/build.gradle

use multidex from androidx and not android support

---

newsfragment/3467.misc
vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt

Handle https://github.com/vector-im/element-android/issues/3467

VoIP: Change hold direction to send-only

---

changelog.d/3535.feature
vector/src/main/java/im/vector/app/features/home/room/detail/composer/TextComposerView.kt

Fix a regression in 1.1.10 (Fixes #3535)

Send button does not show up half of the time (#3535)

---

changelog.d/3564.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/call/CallEventProcessor.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/call/CallSignalingHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/events/DefaultEventService.kt

Fixes https://github.com/vector-im/element-android/issues/3564

Fix call invite processed after call is ended because of fastlane mode.

---

library/ui-styles/src/main/res/values/dimens_font.xml
library/ui-styles/src/main/res/values/styles_buttons.xml

Fix issue on button styles

---

vector/build.gradle

Fixes #3527
Signed-off-by: Erik Huizinga <huizinga.erik@gmail.com>

Apply Google Services Gradle plugin more robustly

---

changelog.d/3583.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt

Fixes #3583
Flatten parents Ids of DM keep growing

Fix / dm flattenParents always growing

---

changelog.d/3542.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/TimelineEventController.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactoryParams.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/MessageInformationDataFactory.kt

This PR fixes https://github.com/vector-im/element-android/issues/3542 and also avoid adding sender info when not required.

Fix some issues with timeline cache invalidation and visibility.

---

vector/src/main/res/values-it/strings.xml
vector/src/main/res/values-pt-rBR/strings.xml

A bit weird, I did not figure out was was the original problem.
Editing the line, for instance adding any char fixes the issue, so I decided to put all on one line.

Fix compilation issue

---

vector/src/main/java/im/vector/app/features/home/room/filtered/FilteredRoomFooterItem.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFooterController.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListListener.kt
vector/src/main/java/im/vector/app/features/home/room/list/widget/NotifsFabMenuView.kt

Just a small rework, no visible change

Decorelate interfaces for code clarity

---

vector/src/main/res/xml/vector_settings_notifications.xml

Fix path in notification settings xml that causes crash

---

changelog.d/3778.bugfix

Adds missing towncrier for https://github.com/vector-im/element-android/issues/3778

Add missing towncrier for 3778

---

changelog.d/3841.bugfix
vector/proguard-rules.pro
vector/src/main/res/values-it/strings.xml

Fix https://github.com/vector-im/element-android/issues/3841

Fix Authenticated Jitsi not working in release #3841

---

changelog.d/3845.bugfix
vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt

Fix Dial pad lost entry when config changes #3845

---

changelog.d/3887.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/EventInsertLiveObserver.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/EventEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/EventInsertEntity.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/EventEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/LocalEchoRepository.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineEventDecryptor.kt

Fix message edition is not rendered in e2e rooms after pagination

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/RetrofitExtensions.kt

Minor code cleanup (which is more kotlin friendly) to simplify adding cases using `when` statement instead of old school Java `if` / `else`.

Use `when` statement instead of `if`/ `else`

---

CONTRIBUTING.md
vector/src/main/java/im/vector/app/features/rageshake/BugReporterMultipartBody.java

Improve documentation about string resource

---

.github/workflows/integration.yml

ci: disable fail-fast for integration tests

---

.github/ISSUE_TEMPLATE/bug.yml
changelog.d/3960.misc

Feedback received asking to merge templates so they take up less space
and are quicker for developers to fill.
Signed-off-by: Ekaterina Gerasimova <ekaterinag@element.io>
The template will look like this:
Instead of this:

Issue templates: merge expected and actual results

---

changelog.d/3990.bugfix
vector/src/main/java/im/vector/app/core/ui/views/JoinConferenceView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/res/layout/layout_join_conference_action.xml
vector/src/main/res/layout/view_join_conference.xml
vector/src/main/res/menu/menu_timeline.xml

Fix memory leak on RoomDetailFragment

---

.github/ISSUE_TEMPLATE/release.yml

Let's see if it does not break something in Element codebase

Add code necessary to release the SDK

---

vector/lint.xml
vector/src/main/java/im/vector/app/features/home/AvatarRenderer.kt
vector/src/main/java/im/vector/app/features/roomdirectory/picker/RoomDirectoryItem.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt

And consider that's errors from now, because generally it is so.

Fix annoying issue detected by lint (CheckResult)

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/sanity_test.yml
.github/workflows/tests.yml
gradle.properties

- Optimize build time for local builds
- Enhance CI/CD workflows (7GB Ram, 2CPU) by adding custom gradle arguments to properly run
- Add unit test UI comment representation plugin

Build Time Optimizations

---

changelog.d/4015.bugfix
vector/src/main/java/im/vector/app/features/call/dialpad/CallDialPadBottomSheet.kt

Fix DTMF not working #4015

---

attachment-viewer/build.gradle
build.gradle
dependencies.gradle
library/ui-styles/build.gradle
matrix-sdk-android-rx/build.gradle
matrix-sdk-android/build.gradle
multipicker/build.gradle
vector/build.gradle

- Fix minSdk version to be aligned to all modules
- Fix & upgrade markwon dependency
- Create a file dependencies.gradle that will contain all the shared & common dependencies between modules in order to avoid inconsistencies

Optimize dependencies handling

---

changelog.d/4014.misc
vector/src/main/java/im/vector/app/features/call/conference/ConferenceEvent.kt
vector/src/main/java/im/vector/app/features/call/conference/JitsiActiveConferenceHolder.kt
vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt

This is just a small wrapper around Jitsi BroadcastEvent to avoid using this directly Fragment/Activity so we can get rid of Jitsi dependencies more easily.

Jitsi: introduces ConferenceEvent 

---

changelog.d/4068.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt

Fix MessageActionsBottomSheet not being shown on local echos 

---

.github/ISSUE_TEMPLATE/release.yml

No need for the CI to wait to be happy

Small change in the recipe to release the SDK

---

changelog.d/4103.bugfix
vector/src/main/java/im/vector/app/features/settings/VectorSettingsAdvancedSettingsFragment.kt

Fixes #4103 
Signed-off-by: Alex Baker <alex@beeper.com>

Fix settings crash when accelerometer unavailable

---

.github/ISSUE_TEMPLATE/release.yml
changelog.d/4113.misc

https://github.com/vector-im/element-android/issues/4113
Signed-off-by: Ekaterina Gerasimova <ekaterinag@element.io>

Fix release label in release issue template

---

changelog.d/3933.bugfix
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailActivity.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt
vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceExploreActivity.kt
vector/src/main/java/im/vector/app/features/usercode/UserCodeActivity.kt

Fixes #3933 
The bottomsheet listener was using a weak reference. Based on the assumption that those listener would probably be activities. But it's not the case as the default navigator is instanciating one by default.
Also the listener way is not resistent to configuration change, moved it to fragment callback insted

App doesn't take you to a Space after choosing to Join it

---

changelog.d/3048.bugfix
vector/src/main/java/im/vector/app/features/home/room/filtered/FilteredRoomFooterItem.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFooterController.kt
vector/src/main/res/layout/item_room_filter_footer.xml

Change call to action in filter room when space selected

---

changelog.d/4109.bugfix
vector/src/main/java/im/vector/app/features/settings/troubleshoot/TestSystemSettings.kt

Troubleshoot notification: Fix button not clickable

---

changelog.d/4155.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
vector/src/main/res/values/strings.xml

Fixes #3869 , the wording part
Also take the opportunity to reorder items, to group all items regarding reactions together.

Wording update

---

CONTRIBUTING.md

Signed-off-by: Andy Balaam <andyb@element.io>

Fix typo in CONTRIBUTING.md: your->you're

---

vector/src/main/java/im/vector/app/features/home/room/detail/composer/VoiceMessageHelper.kt

Will help debugging issues like #3904
No changelog required for a such small change

Add a log to get info when an error occurred when recording / playing voice message

---

changelog.d/4380.bugfix
vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt

Fixes crash when launching the key request dev screen
| --- | --- |
|![before-key-request](https://user-images.githubusercontent.com/1848238/139672270-19fa9d57-6848-4290-b3f2-2b15fd02b120.gif)|![after-key-request](https://user-images.githubusercontent.com/1848238/139672268-ac820771-493d-4a48-8e5b-1550b5e33e8f.gif)

Key request screen crash on launch

---

changelog.d/4424.bugfix
vector/src/main/java/im/vector/app/features/notifications/NotificationFactory.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationRenderer.kt
vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt

Fixes #4417 (see that issue for screenshots)
Signed-off-by: David Teresi <dkteresi@gmail.com>

Fix incorrect cropping of conversation icons

---

changelog.d/4424.bugfix
vector/src/main/java/im/vector/app/features/notifications/NotificationFactory.kt
vector/src/main/java/im/vector/app/features/notifications/NotificationRenderer.kt
vector/src/main/java/im/vector/app/features/notifications/RoomGroupMessageCreator.kt
vector/src/test/java/im/vector/app/features/notifications/NotificationRendererTest.kt

Fix incorrect cropping of conversation icons 

---

.github/workflows/triage-move-labelled.yml

Signed-off-by: Ekaterina Gerasimova <ekaterinag@element.io>

Actions: fix up triage conditionals

---

.github/ISSUE_TEMPLATE/bug.yml
changelog.d/4452.misc

Signed-off-by: Ekaterina Gerasimova <ekaterinag@element.io>

Bring the bug issue template in line with web

---

.github/workflows/triage-priority-bugs.yml

Move P1 issues to app team and crypto boards

---

.github/workflows/triage-move-labelled.yml

Fixes #4461
Covered by changelog entry 4435.misc

Add issue workflow automation for Threads

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixUrls.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/DefaultContentUrlResolver.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/contentscanner/tasks/ScanMediaTask.kt

Small cleanup after content scanner code has been merged

---

README.md

Explain the process of releasing to the app stores

---

README.md

Signed-off-by: Andy Balaam <andyb@element.io>

Add a note about the release builds depending on Google services

---

.github/workflows/sync-from-external-sources.yml

Sync data jobs should not run in forked projects

Disable sync data jobs in forks

---

vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt
vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
vector/src/main/java/im/vector/app/core/platform/VectorBaseBottomSheetDialogFragment.kt
vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapBottomSheet.kt
vector/src/main/java/im/vector/app/features/crypto/verification/VerificationBottomSheet.kt
vector/src/main/java/im/vector/app/features/devtools/RoomDevToolActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/readreceipts/DisplayReadReceiptsBottomSheet.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/edithistory/ViewEditHistoryBottomSheet.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/reactions/ViewReactionsBottomSheet.kt
vector/src/main/java/im/vector/app/features/matrixto/MatrixToBottomSheet.kt
vector/src/main/java/im/vector/app/features/roommemberprofile/devices/DeviceListBottomSheet.kt
vector/src/main/java/im/vector/app/features/settings/devices/DeviceVerificationInfoBottomSheet.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceCreationActivity.kt
vector/src/main/java/im/vector/app/features/widgets/permissions/RoomWidgetPermissionBottomSheet.kt
vector/src/main/res/layout/fragment_bootstrap_enter_account_password.xml
vector/src/main/res/layout/fragment_bootstrap_enter_passphrase.xml
vector/src/main/res/layout/fragment_bootstrap_migrate_backup.xml
vector/src/main/res/layout/fragment_keys_backup_restore_from_passphrase.xml
vector/src/main/res/layout/fragment_keys_backup_setup_step2.xml
vector/src/main/res/layout/fragment_ssss_access_from_passphrase.xml

First commit fixes #4520
Next commits are just cleanup.
One commit to hide password and passphrase by default.
Still looking to fix UI issue in the title:

Some cleanup on Fragment argument

---

library/ui-styles/src/debug/res/layout/debug_social_login.xml
library/ui-styles/src/main/res/values/styles_social_login.xml
library/ui-styles/src/main/res/values/theme_dark.xml

Fixes #4285 
See screenshot in https://github.com/vector-im/element-android/issues/4285#issuecomment-970342749

Small fix in sso providers icons

---

.github/workflows/triage-move-labelled.yml
.github/workflows/triage-priority-bugs.yml
changelog.d/4617.misc

Improve issue automation workflows

---

tools/compressVideo.sh

Small script to compress videos.
Gif is not always smaller than the mp4, but we can try to iterate later.

Add script to compress video and convert to gif file

---

.github/workflows/triage-move-labelled.yml

CC @bmarty so you're aware that the Spaces issues won't be redirected to the Delight team for now.
Covered by 4617.misc changelog entry.

Issue workflow updates for Delight

---

.github/workflows/triage-move-labelled.yml
changelog.d/4666.misc

Add automation to move messages bubbles issues to the message bubbles board

---

.github/workflows/triage-move-labelled.yml
changelog.d/4671.misc

Fix graphql warning in issue automation workflow

---

vector/src/debug/AndroidManifest.xml
vector/src/debug/java/im/vector/app/features/debug/DebugMenuActivity.kt
vector/src/debug/java/im/vector/app/features/debug/di/FeaturesModule.kt
vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesSettingsActivity.kt
vector/src/debug/java/im/vector/app/features/debug/features/DebugFeaturesStateFactory.kt
vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
vector/src/debug/java/im/vector/app/features/debug/features/EnumFeatureItem.kt
vector/src/debug/java/im/vector/app/features/debug/features/FeaturesController.kt
vector/src/debug/res/layout/activity_debug_menu.xml
vector/src/debug/res/layout/item_feature.xml
vector/src/main/java/im/vector/app/core/di/SingletonModule.kt
vector/src/release/java/im/vector/app/core/di/FeaturesModule.kt

Depends on https://github.com/vector-im/element-android/pull/4627
- Adds a dedicated features page to the Debug settings
- Allows overriding the `VectorFeatures` at runtime
| DEBUG SETTINGS | FEATURES | OPTIONS |
| --- | --- | --- |
|![Screenshot_20211206_121136](https://user-images.githubusercontent.com/1848238/144843961-0f393c1e-6466-4335-9a0a-706d2b773043.png)|![Screenshot_20211206_121143](https://user-images.githubusercontent.com/1848238/144843960-d0a30df5-449a-40ac-81c0-bcc34469a107.png)|![Screenshot_20211206_121150](https://user-images.githubusercontent.com/1848238/144843957-07adf1ee-11ea-4d2e-8c23-ef057a869176.png)
TODO consider creating a new entry point for accessing during the onboarding flow

Debug features override

---

vector/src/main/java/im/vector/app/features/poll/create/CreatePollViewModel.kt

Quick fix to avoid creating poll with empty answers

Use only non empty option to create a poll

---

.github/workflows/triage-incoming.yml
.github/workflows/triage-move-labelled.yml
.github/workflows/triage-move-unlabelled.yml
.github/workflows/triage-priority-bugs.yml

These actions don't seem useful for forks which may have their own triage process

Skip issue triage GitHub actions in forks

---

vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptionItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/RoomCreateItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/TimelineItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/WidgetItemFactory.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/NoticeEventFormatter.kt

Quick cleaning of state event rendering in timeline.
Added some validation around state_key, also state events are not encrypted

cleaning rendering of state event in timeline

---

.github/workflows/triage-incoming.yml
.github/workflows/triage-move-labelled.yml
.github/workflows/triage-move-unlabelled.yml
.github/workflows/triage-priority-bugs.yml

Reverts vector-im/element-android#4755

Revert "Skip issue triage GitHub actions in forks"

---

vector/src/main/java/im/vector/app/core/services/CallService.kt

Remove dead code and do some cleanup in CallService

---

changelog.d/3444.bugfix
changelog.d/3444.feature
vector/src/main/java/im/vector/app/features/attachments/AttachmentTypeSelectorView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt
vector/src/main/res/layout/view_attachment_type_selector.xml
vector/src/main/res/values/strings.xml

Add tooltip to explain what are the actions behind the icons

---

.github/workflows/triage-incoming.yml
.github/workflows/triage-move-labelled.yml
.github/workflows/triage-move-unlabelled.yml
.github/workflows/triage-priority-bugs.yml

Successor of #4755 which has been reverted in #4839 
This PR reintroduce the skip of the action in forks, fixing previous PR review and breaking changes.

Skip Github issue triage actions in forks

---

README.md

(Inspired from https://github.com/vector-im/element-web#triaging-issues)

Add a paragraph about issue triaging

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/CryptoTestHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/CancelSendTracker.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt
vector/src/main/java/im/vector/app/features/roomdirectory/roompreview/RoomPreviewViewModel.kt
vector/src/main/java/im/vector/app/features/roomprofile/settings/joinrule/advanced/RoomJoinRuleChooseRestrictedViewModel.kt
vector/src/main/java/im/vector/app/features/spaces/SpaceSummaryController.kt

I read the change twice but please review carefully, I did not do any test.

Prefer usage of `any` or `none` rather `indexOfFirst` wherever it is possible

---

vector/src/main/res/values-fr-rCA/strings_no_weblate.xml
vector/src/main/res/values-ml/strings_no_weblate.xml
vector/src/main/res/values-pa/strings_no_weblate.xml

- French - Canadian
- Malayalam
- Punjabi
Can now be selected in the "Choose language" screen

Add some missing languages in the change language screen

---

CONTRIBUTING.md
vector/src/main/res/values-ar/strings.xml
vector/src/main/res/values-cs/strings.xml
vector/src/main/res/values-de/strings.xml
vector/src/main/res/values-eo/strings.xml
vector/src/main/res/values-es/strings.xml
vector/src/main/res/values-et/strings.xml
vector/src/main/res/values-fa/strings.xml
vector/src/main/res/values-fi/strings.xml
vector/src/main/res/values-fr-rCA/strings.xml
vector/src/main/res/values-fr/strings.xml
vector/src/main/res/values-fy/strings.xml
vector/src/main/res/values-hu/strings.xml
vector/src/main/res/values-in/strings.xml
vector/src/main/res/values-it/strings.xml
vector/src/main/res/values-nb-rNO/strings.xml
vector/src/main/res/values-pl/strings.xml
vector/src/main/res/values-pt-rBR/strings.xml
vector/src/main/res/values-ru/strings.xml
vector/src/main/res/values-sq/strings.xml
vector/src/main/res/values-sv/strings.xml
vector/src/main/res/values-uk/strings.xml
vector/src/main/res/values-vi/strings.xml
vector/src/main/res/values-zh-rCN/strings.xml
vector/src/main/res/values-zh-rTW/strings.xml
vector/src/main/res/values/strings.xml

Remove unused strings

---

.github/workflows/quality.yml

Reverts vector-im/element-android#4900

Revert "Bump actions/github-script from 3 to 5.1.0"

---

changelog.d/4948.bugfix
vector/src/main/java/im/vector/app/features/popup/PopupAlertManager.kt

Prevent Alerts to be displayed on the analytics opt-in screen

---

matrix-sdk-android/build.gradle

Reverts vector-im/element-android#4982

Revert "Bump realm-gradle-plugin from 10.9.0 to 10.10.0"

---

changelog.d/4584.feature
library/ui-styles/src/main/res/drawable/bg_carousel_page_dark.xml
vector/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
vector/src/main/java/im/vector/app/features/VectorFeatures.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashCarouselFragment.kt
vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashFragment.kt
vector/src/main/res/layout/fragment_ftue_auth_splash.xml
vector/src/main/res/layout/fragment_ftue_splash_carousel.xml
vector/src/main/res/values/donottranslate.xml
vector/src/main/res/values/strings.xml

Fixes #4584 
Enabling the FTUE splash carousel flag, will also include any product/design review changes in this PR as well 
- Updates dark mode background to use a solid colour
- Replaces a `GET STARTED` with `CREATE ACCOUNT`  when the `I already have an account` feature is enabled
| 1 | 2 | 3 | 4 |
| TINY DEVICE | N9 TABLET LANDSCAPE | N9 TABLET PORTRAIT |
| --- | --- | --- |
_I already have an account_ 
| ENABLED | DISABLED |
| --- | --- |
|![Screenshot_20220119_094008](https://user-images.githubusercontent.com/1848238/150105239-ceeac4f5-900b-4c35-9ecc-3d007513e7af.png)|![Screenshot_20220119_094713](https://user-images.githubusercontent.com/1848238/150106025-a46c5437-619e-4f8a-bdcd-93f15a13df22.png)

Enabling FTUE splash carousel

---

.github/workflows/triage-labelled.yml

With the new board, we can filter well enough that we can get issues
ready for a future Android developer!
Changelog entry 4949.misc

Enable Delight issue automation

---

.github/workflows/triage-labelled.yml

Fix conditional for Delight issue automation

---

README.md

Add minimum Android version in the Readme

---

.github/ISSUE_TEMPLATE/bug.yml

Quick update of the issue template.

Add case for local or non public homeserver.

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/statistics/StatisticEvent.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/statistics/StatisticsListener.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncThread.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/job/SyncWorker.kt
vector/src/main/java/im/vector/app/features/analytics/extensions/PerformanceTimerExt.kt
vector/src/main/java/im/vector/app/features/session/SessionListener.kt

Quick PR to add 3 events in the next release about sync perf.

Track performance

---

vector/src/main/java/im/vector/app/core/utils/ToolbarConfig.kt
vector/src/main/java/im/vector/app/features/spaces/manage/SpaceManageRoomsFragment.kt

Sometimes setting the title to the toolbar has no effect (race condition?).
This PR fixes this issue.
Another small i18 issue fixed as a bonus.

Fix toolbar title

---

changelog.d/5021.bugfix
vector/src/main/java/im/vector/app/AutoRageShaker.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
vector/src/main/res/values/config.xml

Quick fixes on auto rageshake lab feature:
-> Align name and format with web (snake case, use json)
-> Fix an issue with auto rageshake disabling itself on restart
-> Update the report server app name (so that it goes to a dedicated private repo)
Depends on https://github.com/matrix-org/matrix-ansible-private/pull/4247 (do not merge before)

Quick fixes on auto uisi RS

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageLocationContent.kt
vector/src/main/res/layout/item_timeline_event_location_stub.xml

`./tools/check/check_code_quality.sh` fixes
- Converting `androidx.cardview.widget.CardView`   `com.google.android.material.card.MaterialCardView` has no visual changes

build quality errors 

---

vector/src/main/res/values/strings.xml

I miss that during the previous string cleanup in #5059 
@ouchadam do you agree with this plan?

Instruction for the next weblate sync

---

changelog.d/5067.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/EventRelationsAggregationProcessor.kt

Allow ending polls if user created it

---

vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector/src/androidTest/java/im/vector/app/ui/robot/settings/SettingsLegalsRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/settings/SettingsRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/settings/SettingsSecurityRobot.kt

Fixes #4709.
No need for a changelog here I think.

Test screens in the settings

---

changelog.d/5081.bugfix
vector/src/main/java/im/vector/app/features/call/VectorCallActivity.kt
vector/src/main/java/im/vector/app/features/call/VectorCallViewActions.kt
vector/src/main/java/im/vector/app/features/call/VectorCallViewModel.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferActivity.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferViewEvents.kt
vector/src/main/java/im/vector/app/features/call/transfer/CallTransferViewModel.kt
vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/app/features/navigation/Navigator.kt

Fixes https://github.com/vector-im/element-android/issues/5081

Hold call for transfer selection

---

vector/src/main/res/values-tr/strings.xml

Fix some typos

---

changelog.d/5128.bugfix
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt

Fixing permalink navigation when threads are disabled. Closes #5128

Fix fallback permalink when threads are disabled

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/relation/RelationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/relation/DefaultRelationService.kt
vector/src/main/java/im/vector/app/AutoRageShaker.kt
vector/src/main/java/im/vector/app/VectorApplication.kt
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReportActivity.kt
vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
vector/src/main/java/im/vector/app/features/rageshake/VectorUncaughtExceptionHandler.kt

I have reverted the change on the crypto part as we are not sure about the side effect.
The rest seems OK, after a quick smoke test.

Remove some usage of MatrixCallback

---

.github/ISSUE_TEMPLATE/release.yml

Update the release recipe

---

.github/workflows/triage-labelled.yml
changelog.d/5173.misc

Fix WTF automation

---

vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt
vector/src/main/java/im/vector/app/features/analytics/plan/Identity.kt

Fix analytics not putting identity params.
Remove UI test search menu item.

Feature/fga/fix UI test

---

changelog.d/5178.bugfix
vector/src/main/java/im/vector/app/core/ui/list/GenericButtonItem.kt
vector/src/main/java/im/vector/app/features/poll/create/CreatePollController.kt

Remove redundant highlight on add poll option button

---

.github/PULL_REQUEST_TEMPLATE.md

This is a proposal update for the PR description template to be more consistent between PRs.

Updating PR template description

---

docs/ui-tests.md

Adds explanation and examples to the UI test documentation for the `UiAllScreensSanityTest` and usage of the `Robot` pattern.
To help provide references when talking about the UI tests https://github.com/vector-im/element-android/pull/5087#discussion_r794587083
N/A
N/A
N/A

Adding UI test docs section for contributing to the sanity tests

---

.github/workflows/integration_tests.yml
.github/workflows/sanity_test.yml
.github/workflows/sync-from-external-sources.yml

Use of explicit action/cache has been removed; action/setup-python already includes caching.
Remove use of venv as it doesn't assist in this situation
Remove installation of `synapse` package which is unrelated(!)
This will reduce complexity of workflows and should improve performance, slightly.
N/A
Not run yet - this PR itself should test much of the usecase.
GHA

Rely on setup python cache and tidy up python actions

---

.github/workflows/integration_tests.yml
tools/ci/render_test_output.py

Render integration test results inline (including timing information for each test), while preserving the formatting for the PR comment integration.

Render integration test results inline.

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/keysbackup/KeysBackupPasswordTest.kt

ignore KeysBackup tests

---

.github/workflows/tests.yml
tools/ci/render_test_output.py

Render unit test xml files into github action logs, using same as we use for integration / ui tests
Be clearer about results; also show unit test run times to identify slow tests.

Format unit test results

---

.github/workflows/nightly.yml
build.gradle
coverage.gradle
dependencies_groups.gradle

Add codecov calcuation and overall report.
Based on @ouchadam 's version at https://github.com/ouchadam/small-talk
Provides data we can upload using the sonarqube / codecov platforms for analysis over time.

Code coverage using jacoco (and xml report)

---

matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/verification/qrcode/VerificationTest.kt

See #5449 for reasoning.
Make the integration test build green.

Ignore flaky VerificationTest

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/SendingEventsDataSource.kt

Fix realm crash on v1.4.4

---

changelog.d/5346.misc
vector/src/main/res/drawable/bg_space_item.xml
vector/src/main/res/layout/item_space.xml

fixes #5346 
| Light theme  | Dark theme |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/66663241/157003042-ac59f169-e93e-4a89-8561-0d6f68d77c77.png) | ![image](https://user-images.githubusercontent.com/66663241/157003128-d6fa3791-b147-41aa-ae1e-fe0373fdd257.png) |

change selected space highlight

---

.github/workflows/nightly.yml
.github/workflows/tests.yml

Run the compilation steps for unit tests and integration tests on each PR, to avoid build tests breaking during nightly run on develop.
Also uses linux runners on the PR branches to speed up time to get a runner (we use macos on the nightly runs for performance running the tests)
Add a notification step that triggers if the build fails on develop or main, and sends a confetti-filled ball to the channel to announce with pleasure that the build has failed and someone should do something about it.

Compile tests on PR, to ensure we don't break the build when merging. Alert if we merge and the build fails.

---

CONTRIBUTING.md
docs/pull_request.md

Opened for comment!
[rendered](https://github.com/vector-im/element-android/blob/0dbd6797f7800776edf16cd455a13ee9ed66853d/docs/pull_request.md)

Create a documentation about PR

---

matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/helper/TimelineEventEntityHelper.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/query/TimelineEventEntityQueries.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/TimelineEventDataSource.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/UserAccountDataSyncHandler.kt

Fixes #5810 and do some cleanup.

Improve code in file TimelineEventEntityQueries.kt

---

.github/workflows/triage-move-review-requests.yml

We don't need the triage-move-review-requests in forks.
- Step 1
- Step 2
- Step ...

disable triage-move-review-requests for forks

---

.github/workflows/update-gradle-wrapper.yml

Disable CI script: update-gradle-wrapper for forks
- Step 1
- Step 2
- Step ...

Disable update-gradle-wrapper for forks

---

vector/src/androidTest/java/im/vector/app/espresso/tools/EspressoPreference.kt
vector/src/androidTest/java/im/vector/app/ui/robot/RoomDetailRobot.kt
vector/src/androidTest/java/im/vector/app/ui/robot/settings/SettingsSecurityRobot.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewState.kt

(does not deserve a changelog I think)
Room header with one room member:
Previously only the video call was displayed

Fix sanity test

---

docs/ui-tests.md

The most recent merge to develop changes how PRs are tested.
This PR does nothing (except a trivial markdown file change) but will validate that merges will do the right thing.

noop change to test build system

---

docs/ui-tests.md

noop change to trigger another PR

---

README.md

This no-op change actually fixes a spelling mistake i noticed. But it's acting as a no-op change to test post-pr GHA.

noop change to test Post PR merging

---

README.md

noop change to README to test post-pr merging

---

.github/ISSUE_TEMPLATE/release.yml

Cleaning up my local branches, tiny PR, the branch name is not relevant

Add small step at the beginning of the release flow

---

library/core-utils/src/main/java/im/vector/lib/core/utils/flow/TimingOperators.kt

Fix usage of System.currentTimeMillis().

---

CHANGES.md

Fix issue number in changes.md
- Step 1
- Step 2
- Step ...

Update issue number in changes.md

---

docs/notifications.md

This pull request fixes various small issues in the notification documentation, among them typos and not being able to navigate to "Foreground sync mode (Gplay & F-Droid)"

Docs: Fix various formatting and spelling issues in notifications.md

---

docs/add_threePids.md
docs/analytics.md
docs/color_migration_guide.md
docs/design.md
docs/identity_server.md
docs/integration_tests.md
docs/jitsi.md
docs/notifications.md
docs/pull_request.md
docs/signin.md
docs/signup.md
docs/ui-tests.md

Add TOC to our markdown files, using https://github.com/Kotlin/kotlinx-knit#table-of-contents.
- Just checking that some link are correct on the generated file, especially this one (https://github.com/vector-im/element-android/pull/6186/files#diff-d69a0ce38694428276be8c41b53530dc3120f65cbde7fbed15fab8a33588c1fbR17) which was just fixed in #6182. -> KO, broken again! I will update the title. -> fb884e29b5f619dc7a8e5edf0ff8c11b3e2154c3
- N/A

Generate toc in md files using knit

---

vector/src/main/res/values-ca/strings.xml
vector/src/main/res/values-cs/strings.xml
vector/src/main/res/values-de/strings.xml
vector/src/main/res/values-eo/strings.xml
vector/src/main/res/values-es/strings.xml
vector/src/main/res/values-et/strings.xml
vector/src/main/res/values-fa/strings.xml
vector/src/main/res/values-fi/strings.xml
vector/src/main/res/values-fr/strings.xml
vector/src/main/res/values-hu/strings.xml
vector/src/main/res/values-in/strings.xml
vector/src/main/res/values-is/strings.xml
vector/src/main/res/values-it/strings.xml
vector/src/main/res/values-iw/strings.xml
vector/src/main/res/values-ja/strings.xml
vector/src/main/res/values-lo/strings.xml
vector/src/main/res/values-nl/strings.xml
vector/src/main/res/values-pl/strings.xml
vector/src/main/res/values-pt-rBR/strings.xml
vector/src/main/res/values-ru/strings.xml
vector/src/main/res/values-sk/strings.xml
vector/src/main/res/values-sq/strings.xml
vector/src/main/res/values-sv/strings.xml
vector/src/main/res/values-uk/strings.xml
vector/src/main/res/values-vi/strings.xml
vector/src/main/res/values-zh-rCN/strings.xml
vector/src/main/res/values-zh-rTW/strings.xml
vector/src/main/res/values/strings.xml

Can be merged if CI is happy, Weblate is still locked.

Remove unused strings.

---

.github/workflows/triage-priority-bugs.yml

Issue triage automation got broken with the last update, fixing the issue.
- Step 1
- Step 2
- Step ...

Fix triage automation

---

.github/workflows/tests.yml
build.gradle
coverage.gradle
vector/src/androidTest/java/im/vector/app/RegistrationTest.kt
vector/src/androidTest/java/im/vector/app/SecurityBootstrapTest.kt
vector/src/androidTest/java/im/vector/app/VerifySessionInteractiveTest.kt
vector/src/androidTest/java/im/vector/app/VerifySessionPassphraseTest.kt
vector/src/androidTest/java/im/vector/app/core/utils/TemporaryStoreTest.kt
vector/src/androidTest/java/im/vector/app/features/html/SpanUtilsTest.kt

* Sonarqube plugin has been updated to latest
* Sonarqube now runs im.vector instrumented tests as part of coverage, excluding UI test
* Various ignores to ensure tests are stable when running
* Adjust timing on test to increase reliability in CI
This change increases the reported sonar coverage to be closer to actual test coverage.
- Step 1
- Step 2
- Step ...

Improve Sonar coverage, including im.vector tests

---

.github/workflows/build.yml
.github/workflows/quality.yml
docs/flipper.md
tools/dependencycheck/suppressions.xml
vector/src/androidTest/java/im/vector/app/core/utils/TemporaryStoreTest.kt
vector/src/main/java/im/vector/app/core/utils/TemporaryStore.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailPendingActionStore.kt
vector/src/main/java/im/vector/app/features/login/ReAuthHelper.kt

Also this PR will try to fix the CI issue.
Remaining Issue with `Buildkite` will be fixed by https://github.com/matrix-org/pipelines/pull/196

Add link to the Matrix room.

---

.github/workflows/build.yml
.github/workflows/post-pr.yml
.github/workflows/quality.yml
.github/workflows/tests.yml

Harmonize the parameter for the CI and prevent usage of the gradle deamon to fix unstability of this one.
CI builds can fails if the daemon crashes, for instance see: https://github.com/vector-im/element-android/runs/7090593743?check_suite_focus=true
- CI build

Try no daemon on CI

---

changelog.d/6429.misc
vector/src/main/AndroidManifest.xml

See details and screenshot in #2352 
Closes #2352

Add `android:hasFragileUserData="true"` in the manifest

---

vector/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt

Originally changed by @Florian14 , see https://github.com/vector-im/element-android/pull/6051#discussion_r912845065, but creating a dedicated PR to merge this quick fix faster to develop.

Fix copy paste issue

---

changelog.d/6463.bugfix
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/DefaultTimeline.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/LoadTimelineStrategy.kt

Fix crashes when opening Thread (#6463)

---

.github/workflows/triage-labelled.yml

The design team would like to see all of their issues on their board for triage now
- Step 1
- Step 2
- Step ...

Update issue automation for the design team

---

changelog.d/5115.bugfix
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/crypto/gossiping/WithHeldTests.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/EventType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/events/model/StableUnstableId.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/DefaultCryptoService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/IncomingKeyRequestManager.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/algorithms/megolm/MXMegolmEncryption.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/store/db/model/OutgoingKeyRequestEntity.kt

Fixes #5115
Stop using unstable names for withheld codes #2233 

stable name for withheld

---

changelog.d/6612.misc
vector/src/main/res/values/strings.xml

terns -> terms
I didn't test at all and assumed it will just work out :)
```
Signed-off-by: Andrew Morgan <andrewm@element.io>
```

Fix a typo during registration

---

.github/workflows/triage-labelled.yml

Same change than on https://github.com/vector-im/element-x-ios/commit/2f4fb81aa5bd659c6c2451d0cef8bf4afe68cc8c

Update issue triage workflow.

---

tools/danger/dangerfile.js

Tweak of the dangerfile.
Please see commit messages for more details.
No changelog required for this PR.

No signoff, no changelog for dependabot's PR

---

changelog.d/6739.misc
tools/danger/dangerfile.js

Add link to synapse docs on how to provide DCO (which are linked elsewhere in the project) to the dangerfile message.
Make it easier for third parties to contribute by making it more obvious how to sign off (and that it's not a lengthy Process).
This PR did not have a DCO signoff.
Signed-off-by: Michael Kaye <1917473+michaelkaye@users.noreply.github.com>

Make it easier to find developer sign-off instructions

---

dependencies.gradle

Reverts vector-im/element-android#6732

Revert "Bump dagger from 2.42 to 2.43.2"

---

build.gradle
changelog.d/6843.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/verification/VerificationTransportToDevice.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/SessionRealmConfigurationFactory.kt
tools/check/forbidden_strings_in_code.txt
vector/src/androidTest/java/im/vector/app/espresso/tools/ScreenshotFailureRule.kt
vector/src/main/java/im/vector/app/core/extensions/Fragment.kt
vector/src/main/java/im/vector/app/features/crypto/keysbackup/setup/KeysBackupSetupStep3Fragment.kt
vector/src/main/java/im/vector/app/features/rageshake/VectorFileLogger.kt

Ensure that there is no mistake in string template usage.
Fix existing issues and ignore false positive.
Especially hunt unexpected logs which could leak sensitive user data.
- Step 1
- Step 2
- Step ...

Fix some string template

---

vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt

Fixes avatar not showing on fresh login or sign up due to not being invalidated as the initial sync happens
Closes https://github.com/vector-im/element-android/issues/6605
N/A
Freshly login to an account or sign up to a new account. See that avatar on the top-left shows

App Layout - Fixes avatar not showing on fresh login

---

.github/workflows/triage-priority-bugs.yml

App team's column names have been updated
- Step 1
- Step 2
- Step ...

Update automation to match renamed coloumns

---

changelog.d/7054.bugfix
vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/NewHomeDetailFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
vector/src/main/java/im/vector/app/features/navigation/DefaultNavigator.kt
vector/src/main/java/im/vector/app/features/navigation/Navigator.kt
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt
vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsFragment.kt
vector/src/main/java/im/vector/app/features/roomprofile/members/RoomMemberListFragment.kt
vector/src/main/java/im/vector/app/features/settings/devices/VectorSettingsDevicesFragment.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt

Fixes #7053.
Also ensure other navigation fun are taking a FragmentActivity instead of a Context if a BottomSheet has to be displayed (other potential same issues).
Fix #7053.
Before: see #7053 
After:
- Step 1
- Step 2
- Step ...

Fix invite to room in space

---

vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
vector/src/main/java/im/vector/app/features/settings/VectorSettingsLabsFragment.kt

we should restart app when app layout flag is changed

restart HomeActivity when app layout flag is changed

---

vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt

room/dm create dialog is now closed after any option is chosen and we need to do corresponding changes to allScreens ui 
test
there is no issue for this task

fixed all screens test to follow latest changes

---

docs/unit_testing.md
vector/src/main/java/im/vector/app/features/notifications/CircularCache.kt
vector/src/test/java/im/vector/app/features/notifications/CircularCacheTest.kt

Providing context and examples around contributing unit tests to the project, describing the current conventions and best practices. 
[Rendered](https://github.com/vector-im/element-android/blob/1b3e099d7ce4d91cb6615bc65945fc6f8495507e/docs/unit_testing.md)
N/A
N/A
N/A

[docs] Unit testing documentation

---

.github/workflows/tests.yml
build.gradle
vector/src/test/java/im/vector/app/screenshot/PaparazziExampleScreenshotTest.kt
vector/src/test/snapshots/images/im.vector.app.screenshot_PaparazziExampleScreenshotTest_example paparazzi test.png

An example screenshot test to show the CI pipelines working and to use as a reference for future tests
N/A
N/A

Example screenshot test

---

build.gradle
tools/gradle/doctor.gradle

Gradle Doctor is a gradle plugin that can help to detect configuration issue or other problems, and give "prescription" to improve the codebase and/or developer's environment.
Let's see how the CI accept this change.
Locally it already fixes an issue with missing JAVA_HOME key in the environment, which allows to have faster build from AS and command line.
https://runningcode.github.io/gradle-doctor/
Add a tool to help developers.
NA
NA
NA

Set up Gradle doctor

---

vector/src/main/java/im/vector/app/features/home/room/list/home/HomeRoomListViewModel.kt

we have a problem back when room list is not updated after navigating back to home screen after leaving room
#7152

fixing bug when room list is not updated being on background

---

changelog.d/5712.misc
library/ui-styles/src/main/res/values/dimens.xml

* Decreases the size of rounded corners
* Increases the maximum width of message bubbles to help avoid unnecessary unused space on screen
* Increases font size for messages
These style tweaks help alleviate some of the issues seen in #5683.  If anything looks off or weird, it's likely because this is my first stab at any type of Android development. I don't expect this PR to be merged straightaway, but I figure it can spark some good conversation.
|Before|After|
|-|-|
| ![-CtQCyaYy5jOyC3WA7Ue](https://user-images.githubusercontent.com/3161330/162168013-c9426c86-0f37-4d43-95c0-c52879e6ab39.png) | ![2FP-RaeIhXZxXB0vm0IK](https://user-images.githubusercontent.com/3161330/162168092-a5e7f33e-8751-4fb1-8b9d-b7c44024ba92.png)|

Styling tweaks

---

changelog.d/7287.misc
library/ui-strings/src/main/res/values/strings.xml

Fixes #3677
Replace stale #5488

Use American English by default.

---

.github/ISSUE_TEMPLATE/enhancement.yml

Add a link to element-meta for feature requests

---

changelog.d/7358.sdk
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/LoginType.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/AuthModule.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/LoginParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/PasswordLoginParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/data/TokenLoginParams.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/login/QrLoginTokenTask.kt
vector/src/main/java/im/vector/app/features/signout/soft/SoftLogoutController.kt

- Step 1
- Step 2
- Step ...
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>

Support for login by m.login.token during QR code sign in

---

.github/workflows/triage-labelled.yml

Put only high priority issues in front of the design team, all of which the design team will aim to action to keep the queue at zero
- Step 1
- Step 2
- Step ...

Update issue automation for design

---

vector-app/src/androidTest/java/im/vector/app/espresso/tools/ViewActionsExt.kt
vector-app/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt
vector-app/src/androidTest/java/im/vector/app/ui/robot/ElementRobot.kt
vector-app/src/androidTest/java/im/vector/app/ui/robot/LayoutPreferencesRobot.kt
vector-app/src/androidTest/java/im/vector/app/ui/robot/RoomListRobot.kt

ui test for new app layout's screens 
closes #7304 
closes #6755

added UI tests for new App Layout's screens

---

tools/danger/dangerfile.js

Do not require kittykat's PR to include a sign-off

---

changelog.d/7396.feature
library/ui-strings/src/main/res/values/strings.xml
vector/src/main/java/im/vector/app/features/settings/devices/v2/DeviceFullInfo.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/VectorSettingsDevicesFragment.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionItem.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionsController.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/list/OtherSessionsView.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsAction.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsFragment.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsViewModel.kt
vector/src/main/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsViewState.kt
vector/src/main/res/drawable/bg_device_type.xml
vector/src/main/res/drawable/bg_other_session.xml
vector/src/main/res/layout/item_other_session.xml
vector/src/main/res/layout/view_other_sessions.xml
vector/src/main/res/menu/menu_other_sessions.xml
vector/src/test/java/im/vector/app/features/settings/devices/v2/othersessions/OtherSessionsViewModelTest.kt
vector/src/test/java/im/vector/app/test/fixtures/DeviceFullInfoFixture.kt

Adding multi selection capability in session list screen. For now, we can do nothing with the selected sessions.
Closes #7396 
- Enable the labs flag for the new Session manager
- Press the "View all" button in the other sessions section (need at least 6 other sessions)
- Open the overflow menu of the screen
- Press "Select session"
- Check you can select sessions in the list and that toolbar is correctly updated
- Press back
- Check the select mode is disabled
- Long press a session item
- Check the select mode is enabled and selection is empty
- Check you can select sessions in the list and that toolbar is correctly updated
- Open the overflow menu of the screen
- Press the "Select all" option
- Check all sessions in the list …

[Session manager] Multi selection in sessions list (PSG-852)

---

vector/src/main/java/im/vector/app/features/voicebroadcast/usecase/GetOngoingVoiceBroadcastsUseCase.kt

Clean useless logs added in #7450 

[Voice Broadcast] Minor cleanup in GetOngoingVoiceBroadcastsUseCase

---

.github/workflows/triage-labelled.yml

Send relevant issues to the correct PS team for followup
- Step 1
- Step 2
- Step ...

Add issue automation for PS feature teams

---

.github/workflows/triage-labelled.yml

Move VoIP issues to VoIP team board
- Step 1
- Step 2
- Step ...

Add issue automation for the VoIP team

---

.github/workflows/triage-move-review-requests.yml

Stop using deprecated ProjectNext API in favour of the new ProjectV2 one
- Step 1
- Step 2
- Step ...

Update PR automation

---

.github/workflows/post-pr.yml
.github/workflows/tests.yml

Sets a 90 minutes timeout to the test jobs in the CI.
Sometimes, the CI jobs can get stuck and run up to 6h (GH max timeout by default). This is a problem, because:
1. If you're just expecting the CI job to finish and merge a PR, you'll only notice it at the end of the day.
2. The stuck CI runners won't be available for other jobs.
3. We're wasting money.
- The tests should just work as before.

Set timeout for test CI jobs

---

.github/ISSUE_TEMPLATE/release.yml
tools/release/releaseScript.sh

This script will help to release the app faster, by doing step that was done manually before.
Read the script to see what it is doing!
There is room for improvements, will iterate in the future.
I have also draft a script for the SDK at https://github.com/matrix-org/matrix-android-sdk2/commit/52a546c2831665f535da07571ea119caddbbda4e
Release faster and avoid human mistake.
NA
- Do a release.
NA

First version of the release script.

---

.github/workflows/triage-labelled.yml
changelog.d/7477.misc

Add Z-Labs label for rich text editor and migrate to new label naming

Add Z-Labs label for rich text editor and migrate to new label naming

---

.github/workflows/triage-labelled.yml
.github/workflows/triage-move-review-requests.yml

"PN-" prefixed IDs are no longer working, update to new IDs
- Step 1
- Step 2
- Step ...

Update project board IDs for automation

---

library/ui-strings/src/main/res/values/strings.xml
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt

[Voice Broadcast] Prompt the user before ending a live broadcast

---

changelog.d/7746.feature
dependencies.gradle
library/ui-strings/src/main/res/values/strings.xml
vector/src/main/java/im/vector/app/core/di/MavericksViewModelModule.kt
vector/src/main/java/im/vector/app/core/platform/VectorBaseDialogFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerView.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/RichTextComposerLayout.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/link/SetLinkAction.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/link/SetLinkFragment.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/link/SetLinkSharedActionViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/link/SetLinkViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/link/SetLinkViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/detail/composer/link/SetLinkViewState.kt
vector/src/main/java/im/vector/app/features/themes/ThemeUtils.kt
vector/src/main/res/drawable/ic_composer_link.xml
vector/src/main/res/layout/fragment_set_link.xml
vector/src/test/java/im/vector/app/features/home/room/detail/composer/link/SetLinkViewModelTest.kt

Add the ability to create and edit links using the rich text editor.
- https://element-io.atlassian.net/browse/PSU-1023
- https://github.com/matrix-org/matrix-rich-text-editor/pull/381
[links.webm](https://user-images.githubusercontent.com/4940864/206470758-e922ae92-b345-401f-9c21-64265b83d8e2.webm)
- Enable the rich text editor via Labs
- Start typing a message
- Highlight/select some text in the editor
- Tap the new link icon
- Set and save the link
- Ensure no text is highlighted/selected
- Set text and and save the link
- Tap in a space
- Set text and and save the link
- Select some linked text
- Edit the link and save
- Select some linked text
- Remove the link

[Rich text editor] Add support for links in the rich text editor

---

changelog.d/7913.bugfix
library/ui-strings/src/main/res/values/strings.xml
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/threads/ThreadsService.kt
vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewActions.kt
vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewEvents.kt
vector/src/main/java/im/vector/app/features/home/room/threads/list/viewmodel/ThreadListViewModel.kt
vector/src/main/java/im/vector/app/features/home/room/threads/list/views/ThreadListFragment.kt

Handle network error on API `rooms/{roomId}/threads`
Fixes #7912 
- See #7912 

Thread list crashes

---

matrix-sdk-android/src/androidTest/AndroidManifest.xml

Remove package declaration from AndroidManifest.xml

---

.github/workflows/build.yml
.github/workflows/nightly.yml
.github/workflows/post-pr.yml
.github/workflows/tests.yml

Update cache to use gradle action rather than direct caching. Based on https://github.com/vector-im/element-android/pull/5629 but also using the override for when to treat the cache read only from @fedrunov in https://github.com/vector-im/element-android/pull/7238
We do not include the home directory cleanup task from that; as there's no benefit to doing it repeatedly.
This should improve caching and decrease build times.
N/A
This PR will build using the new cache, which will show it working. I haven't created the PR yet though. 
Signed-off-by: Michael Kaye <1917473+michaelkaye@users.noreply.github.com>

Use gradle build cache action rather than manual cache usage.

---

vector-config/src/main/res/values/config.xml

The old one has disappeared from Netlify. This replaces it with a ROSA deployment like our live EC which shouldn't randomly go away.
NB. This is to the PTT branch.
- Step 1
- Step 2
- Step ...

Update to new Element Call URL

---

changelog.d/7960.misc
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/extensions/MetricsExtensions.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/metrics/SyncDurationMetricPlugin.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncTask.kt
vector/src/main/java/im/vector/app/features/analytics/metrics/sentry/SentrySyncDurationMetrics.kt

Send Sentry analytics for sync response only for initial sync and sync after pause
Closes #7960
- Run the app and check that all sync are still working.

Slow down sentry

---

.gitignore

Ignore files generated by sonarlint.

Ignore sonarlint generated files in repo

---

.github/workflows/build.yml
changelog.d/8044.misc

When building APKs for pull requests, build from the unmerged source.
Note that test jobs continue to build from merged source in order to reduce the chance of breaking the CI after merging.
- When testers test unmerged features built from pull requests, they should expect to test the same code that developers are working on in their development branch.
- Repeated builds of the same PR branch should result in the same binary.
From the [build](https://github.com/vector-im/element-android/actions/runs/4054768119/jobs/6977008380) of [`9f10c49`](https://github.com/vector-im/element-android/pull/8044/commits/9f10c49bd8f6571fc470c2bae974f97aafb9717b)
```
Checking out the ref
/usr/bin/git checkout --progress --force 9f10c49bd8f6571fc470c2bae974f97aafb9717b
HEAD is now at 9f10c49 Build unmerged …
```

Build unmerged APKs on pull request

---

.github/workflows/tests.yml

If a PR is only touching files in the .github directory, there's no need to run tests on the app. This will speed up merging changes to templates and automation.
Not tested the patch, but followed docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
- Step 1
- Step 2
- Step ...

Don't run tests on changes to .github/*

---

CHANGES.md
changelog.d/8026.bugfix
changelog.d/8208.bugfix
changelog.d/8210.bugfix
changelog.d/8217.bugfix
changelog.d/8218.bugfix
changelog.d/8219.feature
changelog.d/8220.feature
changelog.d/8221.feature
changelog.d/8268.bugfix
changelog.d/8286.misc
fastlane/metadata/android/en-US/changelogs/40105300.txt

[Release] v1.5.30

---

changelog.d/8307.bugfix
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/internal/session/room/send/TestPermalinkService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/MatrixPatterns.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/PermalinkService.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/permalinks/DefaultPermalinkService.kt
vector/src/main/java/im/vector/app/features/home/room/detail/timeline/render/EventTextRenderer.kt
vector/src/main/java/im/vector/app/features/html/PillsPostProcessor.kt
vector/src/main/java/im/vector/app/features/permalink/PermalinkHandler.kt

#8307 
- Step 1
- Step 2
- Step ...

Add pills for permalink supported hosts

---

.github/workflows/triage-labelled.yml

Modernise actions: switch from graphql to use new actions.
Remove automation for Delight, WTF, FTUE, voice message and message bubble boards.
- Step 1
- Step 2
- Step ...

Update triage for labelled issues

---

.gitignore
library/rustCrypto/matrix-rust-sdk-crypto.aar

Remove file added with LFS
Should reduce our usage of git lfs on github.
This file is not necessary to build the project, so it can be removed from version system.
Reduce our usage of git lfs on github
NA
- NA

Remove crypto rust sdk binary

---

.github/dependabot.yml

Only upgrade our libraries to limit the number of open PRs by Dependabot

---

changelog.d/8554.misc
matrix-sdk-android/build.gradle

Bump rust sdk version to 0.3.10

---

.github/workflows/triage-incoming.yml

Issues should go to the V2 triage board
- Step 1
- Step 2
- Step ...

Send new issues to new triage board

---

changelog.d/3736.feature
matrix-sdk-android/src/androidTest/java/org/matrix/android/sdk/common/TestRoomDisplayNameFallbackProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/provider/RoomDisplayNameFallbackProvider.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomAvatarResolver.kt
matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/membership/RoomDisplayNameResolver.kt
vector-app/src/androidTest/java/im/vector/app/core/utils/TestMatrixHelper.kt
vector-app/src/androidTest/java/im/vector/app/core/utils/TestRoomDisplayNameFallbackProvider.kt
vector-config/src/main/java/im/vector/app/config/Config.kt
vector/src/main/java/im/vector/app/features/room/FunctionalMembersState.kt
vector/src/main/java/im/vector/app/features/room/VectorRoomDisplayNameFallbackProvider.kt

Support Functional members #3736

---

vector/src/main/java/im/vector/app/features/call/conference/VectorJitsiActivity.kt

Fix  jitsi-meet constants URL
I change  https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js to https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.ts
Signed-off-by: AmirMohammad Yazdanmanesh  [amir.yazdanmanesh@gmail.com](mailto:amir.yazdanmanesh@gmail.com)

Change jitsi-meet constants URL

---

SECURITY.md

Security reporting email address and link to the Security Disclosure Policy.
The current links point to the Matrix foundation.

Point to Element security@ address and policy

---

fastlane/metadata/android/en-US/changelogs/40106100.txt
tools/release/download_github_artifacts.py

Similar to https://github.com/element-hq/element-x-android/pull/2108.
Tested OK during release 1.6.10

Fix release script which download artifact

---

.github/workflows/tests.yml

Fix sonarqube CI error UnsupportedClassVersionError

---

changelog.d/8904.bugfix
vector/src/main/AndroidManifest.xml

This commit should fix the bug from issue https://github.com/element-hq/element-android/issues/8904
- On an Android device, follow the link: https://app.element.io/mobile_guide/
- Click the `Configure` button
- The link will open: https://mobile.element.io/?hs_url=https%3A%2F%2Fmatrix-client.matrix.org%2F&is_url=https%3A%2F%2Fvector.im%2F
- The link should be intercepted by the Element app.
Signed-off-by: Artem Sadovyi <arm121@i.ua>

Intercept mobile.element.io links with Element app

---

matrix-sdk-android/build.gradle

org.matrix.rustcomponents:crypto-android 0.11.0 is based on
matrix-sdk-crypto-0.11.0.
Just updating to the latest stable release. No breaking changes.
Built locally and sent/received some messages in encrypted rooms.

Bump `org.matrix.rustcomponents:crypto-android` to 0.11.0

---

matrix-sdk-android/build.gradle

deps (rust crypto sdk) : bump version to 0.11.1

---

vector/src/main/java/im/vector/app/core/utils/PermissionChecker.kt

Corrected check comparison
https://github.com/element-hq/element-android/issues/9074
N/A
- Built app and deployed to a fresh physical test device
- Started app and logged in to existing account suffering from #9074 
- Changed to a channel, pressed (+) tapped the location drop symbol
- Confirmed the world map appearing and after some time switching to my current location
- Shared location for 15 minutes, confirmed location updates to be posted
- OS version(s): 10

Fixes permission check for location
